### ISSUE TITLE
saved model not found error when I tried to convert .pb to .onnx

### ISSUE THREAD

**Issue by cheers00** [onnx/tensorflow-onnx#1010]
**Describe the bug**
Getting the following error when I tried to convert TF model.pb to onnx.
_OSError: SavedModel file does not exist_ 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Tensorflow Version: 2.2.0 (public)
- Python version: 3.6

**Screenshots**
```
**python -m tf2onnx.convert --saved-model model.pb --opset 10  --output wnd.onnx**
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/env/lib/python3.6/site-packages/tf2onnx/convert.py", line 169, in <module>
    main()
  File "/env/lib/python3.6/site-packages/tf2onnx/convert.py", line 130, in main
    args.saved_model, args.inputs, args.outputs, args.signature_def)
  File "/env/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 240, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names, signatures)
  File "/env/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 214, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path)  # pylint: disable=no-value-for-parameter
  File "/tf220/tfpub/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 578, in load
    return load_internal(export_dir, tags)
  File "/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 588, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/env/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/env/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: model.pb/{saved_model.pbtxt|saved_model.pb}
```

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by cheers00** [comment]
I've to use pass path to saved model, instead of model. Closing this...
