### ISSUE TITLE
failing to determine type of iterable attribute

### ISSUE THREAD

**Issue by robers97** [onnx/tensorflow-onnx#1014]
Conversion of TF model in 'savedmodel' format to ONNX is failing due to ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.

I am unable to find documentation saying if the TF model must first be preconditioned for input so I'm unclear how to proceed if it is a user error.

TF Graph and SavedModel build:

    x_idxs = tf.placeholder(tf.int64, shape=[None,2])
    x_vals = tf.placeholder(tf.float32, shape=[None])
    x = tf.SparseTensor(x_idxs, x_vals, [batch_size,feature_dim])
    y = tf.placeholder(tf.float32, shape=[None,n_classes])
...
    builder = tf.compat.v1.saved_model.builder.SavedModelBuilder('./models')
   tensor_info_input = tf.compat.v1.saved_model.utils.build_tensor_info(x)
    tensor_info_output = tf.compat.v1.saved_model.utils.build_tensor_info(y)
    a_signature = (
        tf.compat.v1.saved_model.signature_def_utils.build_signature_def(
             inputs={'feature_ids_values': tensor_info_input},
             outputs={'classification': tensor_info_output},
             method_name=tf.saved_model.CLASSIFY_METHOD_NAME))

    builder.add_meta_graph_and_variables(
        sess, [tf.saved_model.SERVING],
        signature_def_map={
             'slide_a':
             a_signature,
        })
    builder.save()

Failed innvocation to tf2onnx:

(tfonnx) [robers@cn01 python_examples]$ python -m tf2onnx.convert --opset 10 --saved-model ./model --output model.onnx
2020-07-21 11:59:11,688 - WARNING - From /fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-07-21 11:59:12,562 - INFO - Using tensorflow=1.15.3, onnx=1.7.0, tf2onnx=1.6.2/8d5253
2020-07-21 11:59:12,562 - INFO - Using opset <onnx, 10>
2020-07-21 11:59:12,569 - ERROR - pass1 convert failed for name: "RestoreV2"
op: "RestoreV2"
input: "file_prefix:0"
input: "RestoreV2/tensor_names:0"
input: "RestoreV2/shape_and_slices:0"
device: "/device:CPU:0"
attr {
  key: "dtypes"
  value {
    list {
      type: DT_STRING
    }
  }
}
, ex=You passed in an iterable attribute but I cannot figure out its applicable type.
Traceback (most recent call last):
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/convert.py", line 169, in <module>
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/convert.py", line 153, in main
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/tfonnx.py", line 382, in process_tf_graph
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/tf_loader.py", line 395, in resolve_functions
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/tf_utils.py", line 215, in tflist_to_onnx
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/onnx-1.7.0-py3.7-linux-ppc64le.egg/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/onnx-1.7.0-py3.7-linux-ppc64le.egg/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/onnx-1.7.0-py3.7-linux-ppc64le.egg/onnx/helper.py", line 268, in make_attribute
    "You passed in an iterable attribute but I cannot figure out "
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.

**Urgency**
I'm evaluating the state of the this workflow for a proposal to support it.  

**System information**
- OS Platform: RHEL8.2

**To Reproduce**
Will provide if this doesn't get immediately classified as newbie user error.

**Expected behavior**
Expected it to produce an ONNX model.

**Additional context**
This is not a Keras model.  Its a fairly simple TF graph with two layers and operators defined.
Though simple, its not clear to me that the savedmodel population is legitimate for ONNX representation.  But the again its simple, so any help clearing up my expectations is appreciated.

    W1 = tf.Variable(tf.truncated_normal([feature_dim,hidden_dim], stddev=2.0/math.sqrt(feature_dim+hidden_dim)))
    b1 = tf.Variable(tf.truncated_normal([hidden_dim], stddev=2.0/math.sqrt(feature_dim+hidden_dim)))
    layer_1 = tf.nn.relu(tf.sparse_tensor_dense_matmul(x,W1)+b1)
    W2 = tf.Variable(tf.truncated_normal([hidden_dim,n_classes], stddev=2.0/math.sqrt(hidden_dim+n_classes)))
    b2 = tf.Variable(tf.truncated_normal([n_classes], stddev=2.0/math.sqrt(n_classes+hidden_dim)))
    logits = tf.matmul(layer_1,W2)+b2
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
    train_step = tf.train.AdamOptimizer(lr).minimize(loss)

**Comment by guschmue** [comment]
We don't really support sparse tensors right now because we have no runtime that implements sparse.
But the error in RestoreV2 is puzzling - since we freeze the graph we should not be seeing the RestoreV2.
Was this using the python api or the command line ?

**Comment by robers97** [comment]
Thank you for the feedback on the runtime.  That was a next step that I'll now reconsider :+1: 

It was the command line: python -m tf2onnx.convert --opset 10 --saved-model ./model --output model.onnx

I did not explicitly freeze the graph (input above) before I saved to file.  So I would expect that the RestoreV2 object may indeed be in there unless you tf2convert freezes the graph after load.  Please do advise if freezing is a precursor to storing.

I have been working on the runtime API as well using tf2onnx.tfonnx.process_tf_graph, but I need to ensure I have the inputs and outputs correct as this means is currently giving me index errors which is likely mismatch type.  I have some code to freeze the graph so I can also try freezing before the API call.  If any of this this results in a work-around I'll post to this thread.

**Comment by guschmue** [comment]
--saved-model will freeze the graph for you and only keep the part of the graph needed for inference. The RestoreV2 should have been removed in that process. We sometime see that some Variables are left after freezing but we never saw the RestoreV2 left.
Maybe we can give your code above a try.

**Comment by robers97** [comment]
Here is the code (only ~165 lines with comments):

https://github.com/robers97/HashingDeepLearning/blob/master/python_examples/full_softmax_modelsave.py

Before you invest too much time, my versions are listed above: 
Using tensorflow=1.15.3, onnx=1.7.0, tf2onnx=1.6.2/8d5253

If any of these throws a wrench in things, I can work to upgrade.

**Comment by guschmue** [comment]
super, thanks. The version you used should be ok. We'll take a look at it.

**Comment by robers97** [comment]
note - I updated the config.py today so that it would finish in ~12 min and have that out in the repo now.  Sorry to miss that detail before.  Otherwise it runs for a long time before the model is saved.

**Comment by guschmue** [comment]
Seems to be ok to close. As soon there is support for Sparse we'd add the needed changes and test it as well.
