### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by DayDayupupupup** [onnx/tensorflow-onnx#1033]
I tried to convert a SavedModel model to onnx, and then I encountered the following problems. How should I solve them?
Using tensorflow=2.1.0, onnx=1.7.0, tf2onnx=1.7.0/cbffde

2020-08-01 12:05:42,816 - ERROR - Failed to convert node StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/FusedBatchNormV3
OP=BatchNormalization
Name=StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/FusedBatchNormV3
Inputs:
	StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/Reshape:0=Reshape, [1, -1, -1, 1], 1
	StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/Fill:0=Expand, [-1], 1
	StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/Fill_1:0=Expand, [-1], 1
	StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/Const_2:0=Const, [0], 1
	StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/Const_3:0=Const, [0], 1
Outpus:
	StatefulPartitionedCall/model/j_tags_avg/ln_j_tags_avg/FusedBatchNormV3:0=[1, -1, -1, 1], 1
Traceback (most recent call last):
  File "/code/lbb/wangzekai/tensorflow-onnx/tf2onnx/tfonnx.py", line 257, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/code/lbb/wangzekai/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 696, in version_9
    cls.version_6(ctx, node, **kwargs)
  File "/code/lbb/wangzekai/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 680, in version_6
    new_mean_value = np.array(np.resize(node.inputs[3].get_tensor_value(as_list=False), scale_shape),
  File "<__array_function__ internals>", line 6, in resize
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 1361, in resize
    return mu.zeros(new_shape, a.dtype)
ValueError: negative dimensions are not allowed

**Comment by azraelkuan** [comment]
@DayDayupupupup do u solve this problem?

**Comment by DayDayupupupup** [comment]
The problem has not been solved. I just want to convert the model to ONNX and use Netron to see the model structure。

**Comment by guschmue** [comment]
Not much info to go on, But based on the stack it looks there is a batchnorm without mean and scale has a shape [-1,H,W,C]. Is it possible to share the model?

**Comment by guschmue** [comment]
not enough info to debug this.
