### ISSUE TITLE
error converting BERT model trained in TF2: StridedSlice: attribute new_axis_mask not supported

### ISSUE THREAD

**Issue by Zhen-hao** [onnx/tensorflow-onnx#1034]
Hi, I don't know how to reproduce it. Hope the following stack print helps.

```
2020-08-01 14:13:53,910 - ERROR - Failed to convert node StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/bert/strided_slice_1
OP=StridedSlice
Name=StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/bert/strided_slice_1
Inputs:
        Func/StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/input/_208:0=Identity, [-1, 500], 6
        StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/bert/strided_slice_1/stack:0=Const, [4], 6
        StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/bert/strided_slice_1/stack_1:0=Const, [4], 6
        StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/bert/strided_slice_1/stack_2:0=Const, [4], 6
Outpus:
        StatefulPartitionedCall/tf_bert_for_multi_classification/StatefulPartitionedCall/bert/strided_slice_1:0=[-1, 1, 1, 500], 6
Traceback (most recent call last):
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 256, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/onnx_opset/tensor.py", line 650, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
Traceback (most recent call last):
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/convert.py", line 171, in <module>
    main()
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/convert.py", line 155, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 475, in process_tf_graph
    raise exceptions[0]
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 256, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/nix/store/mzl83pah9jyg8cvd8rn6c8vb77gxdj5a-python3.7-tf2onnx-1.6.3/lib/python3.7/site-packages/tf2onnx/onnx_opset/tensor.py", line 650, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
```

**Comment by Zhen-hao** [comment]
I found a workaround with `keras2onnx`.
closing because I don't have a good way to reproduce it.
