### ISSUE TITLE
Exception list index out of range

### ISSUE THREAD

**Issue by plin47** [onnx/tensorflow-onnx#1043]
**Describe the bug**
I got my trained model, a saved_model.pb, from AutoML Vision Object Detection 
Next, I used the following command to convert the .pb model to .onnx, then an error occurred

`python3 -m tf2onnx.convert --saved-model ./input --output ./model.onnx`

**System information**
OS: Ubuntu 18.04.4 LTS
Python: 3.6.9
Tensorflow: 1.15.2

**Error Message**
WARNING:tensorflow:From /home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-08-06 20:40:35,307 - WARNING - From /home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-08-06 20:40:35,329 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2020-08-06 20:40:36,873 - INFO - Using tensorflow=1.15.2, onnx=1.7.0, tf2onnx=1.6.3/d4abc8
2020-08-06 20:40:36,873 - INFO - Using opset <onnx, 8>
2020-08-06 20:40:36,874 - WARNING - Shapes of Merge map/while/decode_image/cond_jpeg/cond_png/cond_gif/Merge have different ranks: 3, 4
2020-08-06 20:40:39,555 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator/Cast
2020-08-06 20:40:39,560 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator/range
2020-08-06 20:40:39,564 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator/Cast_1
2020-08-06 20:40:39,569 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator/range_1
2020-08-06 20:40:39,574 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator/Cast_2
2020-08-06 20:40:39,579 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates/Cast
2020-08-06 20:40:39,584 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates/Cast_1
2020-08-06 20:40:39,590 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_1/Cast
2020-08-06 20:40:39,595 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_1/range
2020-08-06 20:40:39,600 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_1/Cast_1
2020-08-06 20:40:39,605 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_1/range_1
2020-08-06 20:40:39,611 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_1/Cast_2
2020-08-06 20:40:39,616 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_1/Cast
2020-08-06 20:40:39,621 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_1/Cast_1
2020-08-06 20:40:39,627 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_2/Cast
2020-08-06 20:40:39,632 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_2/range
2020-08-06 20:40:39,637 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_2/Cast_1
2020-08-06 20:40:39,641 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_2/range_1
2020-08-06 20:40:39,646 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_2/Cast_2
2020-08-06 20:40:39,652 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_2/Cast
2020-08-06 20:40:39,657 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_2/Cast_1
2020-08-06 20:40:39,662 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_3/Cast
2020-08-06 20:40:39,667 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_3/range
2020-08-06 20:40:39,672 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_3/Cast_1
2020-08-06 20:40:39,677 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_3/range_1
2020-08-06 20:40:39,682 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_3/Cast_2
2020-08-06 20:40:39,688 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_3/Cast
2020-08-06 20:40:39,693 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_3/Cast_1
2020-08-06 20:40:39,698 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_4/Cast
2020-08-06 20:40:39,702 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_4/range
2020-08-06 20:40:39,708 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_4/Cast_1
2020-08-06 20:40:39,713 - INFO - folding node type=Range, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_4/range_1
2020-08-06 20:40:39,717 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/GridAnchorGenerator_4/Cast_2
2020-08-06 20:40:39,723 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_4/Cast
2020-08-06 20:40:39,728 - INFO - folding node type=Cast, name=MultiscaleGridAnchorGenerator/ToNormalizedCoordinates_4/Cast_1
2020-08-06 20:40:39,733 - INFO - folding node type=Cast, name=Postprocessor/Cast_2
2020-08-06 20:40:39,739 - INFO - folding node type=Cast, name=Postprocessor/Cast_3
2020-08-06 20:40:39,744 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_padded/while/suppression_loop_body/range
2020-08-06 20:40:39,749 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_padded/while/suppression_loop_body/range_1
2020-08-06 20:40:39,754 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_padded/range_2
2020-08-06 20:40:39,759 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/range
2020-08-06 20:40:39,765 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_padded_1/while/suppression_loop_body/range
2020-08-06 20:40:39,770 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_padded_1/while/suppression_loop_body/range_1
2020-08-06 20:40:39,776 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_padded_1/range_2
2020-08-06 20:40:39,781 - INFO - folding node type=Range, name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/range_1
2020-08-06 20:40:42,161 - ERROR - rewriter <function rewrite_generic_loop at 0x7f1dd1dded08>: exception list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 171, in <module>
    main()
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 155, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 465, in process_tf_graph
    run_rewriters(g, rewriters, continue_on_error)
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 317, in run_rewriters
    raise ex
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 308, in run_rewriters
    ops = func(g, g.get_nodes())
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/rewriter/rnn.py", line 50, in rewrite_generic_loop
    return LoopRewriter(g).run()
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter.py", line 35, in run
    return self.run_internal()
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal
    self._check_in_read_only_mode(context)
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode
    self._parse_loop_variables(context)
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables
    loop_var = self._get_loop_var_from_switch(s)
  File "/home/atgcv/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 366, in _get_loop_var_from_switch
    enter_node = [n for n in merge_node.inputs if n.type == 'Enter'][0]
IndexError: list index out of range

**Additional context**
How can I fix it? Please help me

**Comment by bedapisl** [comment]
Exactly the same thing happened to me, also on Ubuntu 18.04, Python 3.6 and tensorflow 1.15. Here is a link to my model for debugging: https://drive.google.com/file/d/105xs9j1PjzKk45PkM5-hGNKxGTdElsCL/view?usp=sharing. The command line I used was:
```
python -m tf2onnx.convert --input tf_model.pb --inputs input_1:0 --outputs decoded_predictions/loop_over_batch/TensorArrayStack/TensorArrayGatherV3:0 --output from_tensorflow.onnx
```

**Comment by georgiaraj** [comment]
I've just seen this. It happens during the conversion of a custom layer we have implemented for object detection decoding. But weirdly I can run my conversion repeatedly and sometimes see this, and other times not and the conversion completes successfully, which makes me think this must be a bug.

**Comment by guschmue** [comment]
I think grappler is optimizing that enter away. Let me see if we can deal with this.

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one.
