### ISSUE TITLE
Tensorflow op [batch_join: QueueDequeueUpToV2] is not supported

### ISSUE THREAD

**Issue by robers97** [onnx/tensorflow-onnx#1044]
**Describe the bug**
2020-08-07 15:13:14,603 - ERROR - Tensorflow op [batch_join: QueueDequeueUpToV2] is not supported
2020-08-07 15:13:19,636 - ERROR - Unsupported ops: Counter({'QueueDequeueUpToV2': 1})

I apologize in advance if there is a support op list that I should have cross referenced ahead of this.  I did look, but I didn't find one.  I figure that might be more trouble than its worth, but then again...

**Urgency**
Low - evaluation phase
This model was chosen due to is structure which is similar to one I will attempt to move from C code directly to the ONNX API.
My alternative is to pull the mobile model from the model zoo.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 8.1
- Tensorflow Version: tensorflow=1.15.3, onnx=1.7.0, tf2onnx=1.6.2/8d5253
- Python version: 3.3.7

**To Reproduce**
Download the model from: https://drive.google.com/open?id=1R77HmFADxe87GmoLwzfgMu_HY0IhcyBz

python -m tf2onnx.convert --opset 12 --graphdef 20180408-102900.pb --fold_const --inputs input:0 --outputs embeddings:0
2020-08-07 15:19:10,587 - WARNING - From /fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Output_names from frozen session:
embeddings:0
Input_names from frozen session:
input:0
2020-08-07 15:19:17,712 - INFO - Using tensorflow=1.15.3, onnx=1.7.0, tf2onnx=1.6.2/8d5253
2020-08-07 15:19:17,712 - INFO - Using opset <onnx, 12>
2020-08-07 15:19:17,712 - WARNING - Shape of placeholder batch_size is unknown, treated it as a scalar
2020-08-07 15:19:17,712 - WARNING - Shape of placeholder phase_train is unknown, treated it as a scalar
2020-08-07 15:19:22,703 - WARNING - Cannot infer shape for batch_join: batch_join:0,batch_join:1
2020-08-07 15:19:22,703 - WARNING - Cannot infer shape for image_batch: image_batch:0
2020-08-07 15:19:22,703 - WARNING - Cannot infer shape for input: input:0
2020-08-07 15:19:47,659 - ERROR - Tensorflow op [batch_join: QueueDequeueUpToV2] is not supported
2020-08-07 15:19:52,683 - ERROR - Unsupported ops: Counter({'QueueDequeueUpToV2': 1})
Traceback (most recent call last):
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/convert.py", line 169, in <module>
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/convert.py", line 153, in main
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/tfonnx.py", line 487, in process_tf_graph
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/tfonnx.py", line 292, in topological_sort
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/graph.py", line 922, in topological_sort
  File "/fomshare/home/robers/anaconda3/envs/tfonnx/lib/python3.7/site-packages/tf2onnx-1.6.2-py3.7.egg/tf2onnx/utils.py", line 193, in make_sure
ValueError: make_sure failure: Cannot find node with output batch_join/fifo_queue:0

**Expected behavior**
The error reporting is fine, but it would be nice to have the converter finish successfully.

**Additional context**
Note that I could not pull this up in Tensorboard, but through code review of https://github.com/davidsandberg/facenet I found the inputs and outputs.

**Comment by TomWildenhain-Microsoft** [comment]
Since ONNX doesn't have a queue datatype, our current solution for QueueDequeue ops is to remove them and make graph inputs that wire to their outputs.  I've added a similar solution in #1047

**Comment by robers97** [comment]
I wondered what would be the best option without queues on the onnx operator list.
As part of my poking around the web, I found this discussion on the topic which seems to validate your approach.

https://groups.google.com/a/tensorflow.org/forum/#!topic/tfjs/jNZ2Uv6NQBc

**Comment by robers97** [comment]
Tom,

I download your commit and found it did not work due to a slight issue with syntax.
I'm really rusty with commits and may not have access to commit to the project, but here's a diff.  Notice the brackets.

diff --git a/tf2onnx/onnx_opset/generator.py b/tf2onnx/onnx_opset/generator.py
index f30cfa7..b81d6fb 100644
--- a/tf2onnx/onnx_opset/generator.py
+++ b/tf2onnx/onnx_opset/generator.py
@@ -196,7 +196,7 @@ class IteratorGetNext:
         ctx.add_graph_input(output_names[1], type_1, shape_1)
 
 
-@tf_op("QueueDequeueManyV2")
+@tf_op(["QueueDequeueManyV2", "QueueDequeueUpToV2"])
 class QueueDequeueManyV2:
     @classmethod
     def version_8(cls, ctx, node, **kwargs):

**Comment by TomWildenhain-Microsoft** [comment]
Shoot.  You're right.  I'll fix it.  Thanks!

**Comment by TomWildenhain-Microsoft** [comment]
Fixed by #1050
