### ISSUE TITLE
Issues while installing tf2onnx

### ISSUE THREAD

**Issue by sparsh-b** [onnx/tensorflow-onnx#1067]
I issued this command `pip install -U tf2onnx`
And, the below was the output:

Collecting tf2onnx
  Downloading tf2onnx-1.6.3-py3-none-any.whl (185 kB)
     |████████████████████████████████| 185 kB 727 kB/s
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from tf2onnx) (1.11.0)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from tf2onnx) (2.18.4)
Collecting onnx>=1.4.1
  Using cached onnx-1.7.0.tar.gz (5.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/venv/bin/python3 /home/xxxxxx/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyrahvkfv
         cwd: /tmp/pip-install-yjimbqnr/onnx
    Complete output (43 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running dist_info
    creating /tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info
    writing /tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/entry_points.txt
    writing requirements to /tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/requires.txt
    writing top-level names to /tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/tmp/pip-modern-metadata-6fkefpjh/onnx.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-6fkefpjh/onnx.dist-info'
    Traceback (most recent call last):
      File "/home/xxxxxx/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/xxxxxx/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/xxxxxx/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 267, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 340, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/dist_info.py", line 36, in run
        bdist_wheel.egg2dist(egg_info.egg_info, dist_info_dir)
      File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 443, in egg2dist
        shutil.copy(license, os.path.join(self.distinfo_dir, license_filename))
      File "/usr/lib/python3.6/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/xxxxxx/venv/bin/python3 /home/xxxxxx/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyrahvkfv Check the logs for full command output.

Please help me with this issue.
Thanks!

**Comment by sparsh-b** [comment]
The problem was with onnx.
I was in a venv.
I came out of venv & installe onnx with `pip install onnx --user`

& it got resolved.
