### ISSUE TITLE
Transpose Optimization error when working less than 4 dims

### ISSUE THREAD

**Issue by NikolasMarkou** [onnx/tensorflow-onnx#1072]
**Describe the bug**
At many points in the transpose optimization it is assumed that the shape is of size 4. 

**Urgency**
This is a non blocker, if the optimization fails it just continues with the next optimization

**System information**
- Linux Mint 18.04
- Tensorflow Version: 1.15
- Python version: 3.6.9

**To Reproduce**
Add a Transpose optimization with input shape less than 4
```
2020-08-21 13:44:13,975 - WARNING - Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/__init__.py", line 52, in optimize_graph
    graph = opt.optimize(current) or graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 135, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 148, in _optimize_at_current_graph_level
    if self._handle_nhwc_tranpose(n):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 281, in _handle_nhwc_tranpose
    return op_handler(trans, p)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 660, in _slice_handler
    return self._switch_transpose_and_node(node, trans)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 262, in _switch_transpose_and_node
    new_shape = [shape[i] for i in NHWC_TO_NCHW]
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 262, in <listcomp>
    new_shape = [shape[i] for i in NHWC_TO_NCHW]
IndexError: list index out of range
```

**Expected behavior**
We need to handle occurrences of different sizes of transpose

**Additional context**
Failing on specific cases of strided slice in tensorflow

**Comment by TomWildenhain-Microsoft** [comment]
Sorry I should have taken a closer look at this when you opened the PR.  The index out of range is coming from `_switch_transpose_and_node` but that is called from `_handle_nhwc_tranpose` which calls `is_nhwc_transpose` on the node in question.  `is_nhwc_transpose` makes sure the 'perm' property of the node has length 4.  So it seems the real problem here is somehow a transpose node has perm of length 4 but shape of length less than 4.  This needs more investigation.  Can you share the model or tf code causing the conversion error?

**Comment by NikolasMarkou** [comment]
Hi @TomWildenhain-Microsoft , it's a client's model so i can't share it out of the organization.

**Comment by TomWildenhain-Microsoft** [comment]
No problem.  I still think the problem is a mismatch between the length of perm and shape, which suggests an invalid model.  Do you agree?

**Comment by NikolasMarkou** [comment]
I'm not sure on that, i will need to test further. Because this is a valid
tf model. If something is going wrong then there may be a deeper reason.

**Comment by guschmue** [comment]
assume this has been resolved.
