### ISSUE TITLE
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bidirectional_3/while/add/y}}

### ISSUE THREAD

**Issue by SBarzz** [onnx/tensorflow-onnx#1085]
**Describe the bug**
Can't convert frozen pb file to ONNX

When trying to:
`python -m tf2onnx.convert --graphdef frozen_model.pb --output model.onnx --inputs x1:0,x2:0  --outputs dense_3/BiasAdd:0,dense_4/BiasAd`

I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shir/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 171, in <module>
    main()
  File "/home/shir/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 125, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/shir/.local/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 148, in from_graphdef
    tf.import_graph_def(graph_def, name='')
  File "/home/shir/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/shir/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/shir/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))

ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bidirectional_3/while/add/y}}

```

**System information**
- Ubuntu 18.04
- Tensorflow Version: 2.3.0
- Python version: 3.6.9

**To Reproduce**
Describe steps/code to reproduce the behavior:

1. Freeze model using:
```
def freeze_graph(graph, session, output, save_pb_dir='.', save_pb_name='frozen_model.pb', save_pb_as_text=False):
    import keras.backend as K
    K.set_learning_phase(0)
    with graph.as_default():
        graphdef_inf = tf.graph_util.remove_training_nodes(graph.as_graph_def())
        graphdef_frozen = tf.graph_util.convert_variables_to_constants(session, graphdef_inf, output)
        graph_io.write_graph(graphdef_frozen, save_pb_dir, save_pb_name, as_text=save_pb_as_text)
        return graphdef_frozen
```
2. Get the input and outputs with:

```
model = load_model(model_fname)
session = tf.keras.backend.get_session()
input_names = [t.op.name for t in model.inputs]
output_names = [t.op.name for t in model.outputs]
print(input_names, output_names)
```

The output is:
`([u'x1', u'x2'], [u'dense_3/BiasAdd', u'dense_4/BiasAdd'])`

Did I write the outputs in the right way in the command?

**Expected behavior**
Onnx file to be used in tensorRT.

**Additional context**
I have tried also using:
1. --fold_const flag
2. --opset 10/11/12
3. Tried to change the bidirectional layer in my network to lstm and still getiing this error:
`ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node lstm_3/while/add/y}}`

Any suggestions?

Thanks

**Comment by guschmue** [comment]
Your outputs are missing the ```:0``` at the end. If you have the keras model as saved-model you can use the our command line as well - it should be able to deal with keras models.
