### ISSUE TITLE
Converting TF2 model with StatefulPartitionedCall

### ISSUE THREAD

**Issue by bedapisl** [onnx/tensorflow-onnx#1093]
**Describe the bug**
Converting tf2 model ([Google drive link](https://drive.google.com/file/d/1Ep6HGWZIE86Pwc90t7oKIzlGLl1STskQ/view?usp=sharing)) which contains StatefulPartitionedCall produces error:
```
...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pislb/packages/tensorflow-onnx/tf2onnx/convert.py", line 171, in <module>
    main()
  File "/home/pislb/packages/tensorflow-onnx/tf2onnx/convert.py", line 155, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/pislb/packages/tensorflow-onnx/tf2onnx/tfonnx.py", line 380, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes, _ = tensorflow_to_onnx(tf_graph, shape_override)
  File "/home/pislb/packages/tensorflow-onnx/tf2onnx/tf_utils.py", line 224, in tensorflow_to_onnx
    return tflist_to_onnx(graph, shape_override)
  File "/home/pislb/packages/tensorflow-onnx/tf2onnx/tf_utils.py", line 211, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/home/pislb/.local/lib/python3.6/site-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/home/pislb/.local/lib/python3.6/site-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/home/pislb/.local/lib/python3.6/site-packages/onnx/helper.py", line 272, in make_attribute
    'value "{}" is not valid attribute data type.'.format(value))
TypeError: value "name: "__inference_pruned_18886"
" is not valid attribute data type.
```

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- Tensorflow Version: 2.2
- Python version: 3.6.9

**To Reproduce**
1. Download the model ([Google drive link](https://drive.google.com/file/d/1Ep6HGWZIE86Pwc90t7oKIzlGLl1STskQ/view?usp=sharing))
2. Add line `import tensorflow_text` to imports 
3. Run `python -m tf2onnx.convert --saved-model tf_save_dir --output converted.onnx --opset=12 --fold_const --verbose` 

**Expected behavior**
Model is converted.

**Additional context**
Similar bug was already reported, but not fixed: https://github.com/onnx/tensorflow-onnx/issues/755

Full error output: [full_error.txt](https://github.com/onnx/tensorflow-onnx/files/5188077/full_error.txt)

**Comment by TomWildenhain-Microsoft** [comment]
I'll take a look.

**Comment by nezbyy** [comment]
Dne út 8. 9. 2020 18:47 uživatel TomWildenhain-Microsoft <
notifications@github.com> napsal:

**Comment by TomWildenhain-Microsoft** [comment]
Can you please try again with the latest version of the converter from the master branch?

**Comment by rajeevsrao** [comment]
@TomWildenhain-Microsoft with the tf2onnx build from source (master), export completes, but the ONNX model includes the op "StatefulPartitionedCall" which is not valid ONNX.

```
2020-10-08 21:25:14,661 - INFO - Using tensorflow=2.2.0, onnx=1.7.0, tf2onnx=1.7.0/b53f1b
2020-10-08 21:25:14,661 - INFO - Using opset <onnx, 12>
2020-10-08 21:25:14,666 - WARNING - Cannot infer shape for StatefulPartitionedCall: StatefulPartitionedCall:0,StatefulPartitionedCall:1,StatefulPartitionedCall:2,StatefulPartitionedCall:3,StatefulPartitionedCall:4,StatefulPartitionedCall:5
2020-10-08 21:25:14,666 - WARNING - Cannot infer shape for Identity: Identity:0
2020-10-08 21:25:14,667 - WARNING - Cannot infer shape for Identity_1: Identity_1:0
2020-10-08 21:25:14,667 - WARNING - Cannot infer shape for Identity_2: Identity_2:0
2020-10-08 21:25:14,667 - WARNING - Cannot infer shape for Identity_3: Identity_3:0
2020-10-08 21:25:14,667 - WARNING - Cannot infer shape for Identity_4: Identity_4:0
2020-10-08 21:25:14,667 - WARNING - Cannot infer shape for Identity_5: Identity_5:0
2020-10-08 21:25:14,669 - INFO - Computed 0 values for constant folding
2020-10-08 21:25:14,763 - ERROR - Tensorflow op [StatefulPartitionedCall: StatefulPartitionedCall] is not supported
2020-10-08 21:25:14,764 - ERROR - Unsupported ops: Counter({'StatefulPartitionedCall': 1})
2020-10-08 21:25:14,769 - INFO - Optimizing ONNX model
2020-10-08 21:25:14,993 - INFO - After optimization: Identity -12 (12->0)
2020-10-08 21:25:15,003 - WARNING - missing output shape for Identity:0
2020-10-08 21:25:15,003 - WARNING - missing output shape for Identity_1:0
2020-10-08 21:25:15,003 - WARNING - missing output shape for Identity_2:0
2020-10-08 21:25:15,003 - WARNING - missing output shape for Identity_3:0
2020-10-08 21:25:15,003 - WARNING - missing output shape for Identity_4:0
2020-10-08 21:25:15,003 - WARNING - missing output shape for Identity_5:0
2020-10-08 21:25:15,004 - INFO -
2020-10-08 21:25:15,004 - INFO - Successfully converted TensorFlow model ./checkpoints/triton_models/electra/1/model.savedmodel to ONNX
2020-10-08 21:25:15,005 - INFO - ONNX model is saved at model.onnx
```

**Comment by buddhapuneeth** [comment]
> StatefulPartitionedCall is an op that does a simple function call in TF. Our converter doesn't normally have to deal with it since the optimizer we run before conversion automatically inlines most function calls. If it shows up in the optimized graph there is usually some reason that will prevent conversion from working. In this case, there is a SentencepieceOp in the function preventing it from being inlined. We can't convert SentencepieceOp yet since there is no analogous onnx op. However SentencepieceOp is usually just for preprocessing, so if you can remove it from the graph you can use onnx to convert the rest.

@TomWildenhain-Microsoft I am also facing similar issue with my model. In the above case, how you are able to narrow down the issue to SentencepieceOp? I tried to open the attached model and searched for it in Netron, but there is no match.
 I am trying to find the op which is causing the issue in my case using the similar approach you employed.

**Comment by TomWildenhain-Microsoft** [comment]
@buddhapuneeth I opened it in Netron and looked through the subgraphs.  There are quite a few ops that can cause this problem so it might not be a SentencepieceOp.  You can also get a count of the op types programmatically and look through that.  If you post the model I can take a look.  We might want to consider making tf2onnx convert StatefulPartitionedCall or at least do a preprocessing pass to find ops it can't support...

**Comment by guschmue** [comment]
I might have some improvement for the StatefulPartitionedCall by forceing tensorflow to do more aggressive inline - at least in my case it helped. I'm going to send a PR for that in the next few days.

**Comment by buddhapuneeth** [comment]
> I might have some improvement for the StatefulPartitionedCall by forceing tensorflow to do more aggressive inline - at least in my case it helped. I'm going to send a PR for that in the next few days.

@guschmue is the change you are making on the TF side? Can you provide some patch if possible for a tentative fix?

**Comment by TomWildenhain-Microsoft** [comment]
@buddhapuneeth Tensorflow saved models have a bunch of graphs for loading/saving the model that don't have the real computation.  To find the real computation graph look through the subgraphs in Netron (click the lines in the top-left, then select a subgraph from the panel).  You can get a much easier to read graph through freezing the saved model.

**Comment by guschmue** [comment]
My changes passes some additional flags to a tensorflow api. Its a 1 line change but I still need to write it to the command line.

**Comment by TomWildenhain-Microsoft** [comment]
Aggressive inlining PR has merged.  Try conversion again with the latest master and see if it helps. #1148

**Comment by guschmue** [comment]
Maybe we should add a command line option to save the frozen graph so it becomes easier for people to look at things.

**Comment by TomWildenhain-Microsoft** [comment]
Agreed.

**Comment by buddhapuneeth** [comment]
Thanks for the fix. It worked in my case.
Looks like I have one disconnected node in the graph. I am guessing that might have caused issue earlier. With fix, we are making aggressive_inlining=True and as per [TF documentation](https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/python/framework/convert_to_constants.py#L437), it will disable safety checks in the [Gappler optimizations](https://www.tensorflow.org/guide/graph_optimization). May be prior that disconnected node messed up the graph during the optimizations in my case. I would like to know your thoughts.

**Comment by guschmue** [comment]
sometimes you see disconnected nodes if it is referenced from a subgraph (netron doesn't know about the subgraph). Possible that it is such a case ?
tf2onnx should remove disconnected nodes if things work according to plan.

**Comment by guschmue** [comment]
I think this one is fixed. If you need a sentencepiceop - its not defined in onnx but for onnxruntime you can find it here:
https://github.com/microsoft/ort-customops

**Comment by lifang-zhang** [comment]
Above discussion shows that the problem has been solved? But why when I am trying to convert [movinet](https://github.com/tensorflow/models/tree/master/official/projects/movinet), I got this error
 ```
2023-01-02 20:44:22,599 - ERROR - Tensorflow op [StatefulPartitionedCall/movinet_classifier/classifier_head/classifier/conv3d/StatefulPartitionedCall: StatefulPartitionedCall] is not supported
2023-01-02 20:44:22,600 - ERROR - Unsupported ops: Counter({'StatefulPartitionedCall': 83})
2023-01-02 20:44:22,651 - INFO - Optimizing ONNX model
2023-01-02 20:44:28,389 - INFO - After optimization: Cast -64 (112->48), Const -446 (799->353), Gather +32 (0->32), Identity -2 (2->0), Reshape +16 (0->16), Shape -32 (64->32), Transpose -9 (110->101)
2023-01-02 20:44:28,470 - INFO - 
2023-01-02 20:44:28,471 - INFO - Successfully converted TensorFlow model ./test to ONNX
2023-01-02 20:44:28,471 - INFO - Model inputs: ['image']
2023-01-02 20:44:28,471 - INFO - Model outputs: ['classifier_head']
2023-01-02 20:44:28,471 - INFO - ONNX model is saved at model.onnx
```
The model was converted successfully though. I used tensorflow 2.11.0 and tf2onnx 1.13.0.

**Comment by li-zihang** [comment]
Same issue for me. I tried to convert this model, which is also movinet published by `tensorflow/models`. It shows same `StatefulPartitionedCall` error:
```
[StatefulPartitionedCall/movinet_classifier/movinet/head/project/conv3d/StatefulPartitionedCall: StatefulPartitionedCall] is not supported

ERROR - Unsupported ops: Counter({'StatefulPartitionedCall': 304})
```

**Comment by FransHk** [comment]
@li-zihang @lifang-zhang hi, I am in the same boat trying to export MoviNet to TRT. Did you find a solution for this problem?
