### ISSUE TITLE
Could not install on Windows

### ISSUE THREAD

**Issue by achernigin1987** [onnx/tensorflow-onnx#11]
I've successfully install onnx 1.1.1 via Anaconda but could not install tf2oonx via command
`python setup.py install`. 
The following error observed:
```
(base) D:\tools\windows\sources>cd tensorflow-onnx

(base) D:\tools\windows\sources\tensorflow-onnx>python setup.py install
running install
running bdist_egg
running egg_info
creating tf2onnx.egg-info
writing tf2onnx.egg-info\PKG-INFO
writing dependency_links to tf2onnx.egg-info\dependency_links.txt
writing requirements to tf2onnx.egg-info\requires.txt
writing top-level names to tf2onnx.egg-info\top_level.txt
writing manifest file 'tf2onnx.egg-info\SOURCES.txt'
reading manifest file 'tf2onnx.egg-info\SOURCES.txt'
writing manifest file 'tf2onnx.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running create_version
creating build
creating build\lib
creating build\lib\tf2onnx
copying tf2onnx\convert.py -> build\lib\tf2onnx
copying tf2onnx\graph.py -> build\lib\tf2onnx
copying tf2onnx\graph_matcher.py -> build\lib\tf2onnx
copying tf2onnx\tfonnx.py -> build\lib\tf2onnx
copying tf2onnx\utils.py -> build\lib\tf2onnx
copying tf2onnx\version.py -> build\lib\tf2onnx
copying tf2onnx\__init__.py -> build\lib\tf2onnx
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\convert.py -> build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\graph.py -> build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\graph_matcher.py -> build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\tfonnx.py -> build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\utils.py -> build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\version.py -> build\bdist.win-amd64\egg\tf2onnx
copying build\lib\tf2onnx\__init__.py -> build\bdist.win-amd64\egg\tf2onnx
byte-compiling build\bdist.win-amd64\egg\tf2onnx\convert.py to convert.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tf2onnx\graph.py to graph.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tf2onnx\graph_matcher.py to graph_matcher.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tf2onnx\tfonnx.py to tfonnx.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tf2onnx\utils.py to utils.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tf2onnx\version.py to version.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tf2onnx\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying tf2onnx.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying tf2onnx.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tf2onnx.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tf2onnx.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tf2onnx.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\tf2onnx-0.0.0.1-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing tf2onnx-0.0.0.1-py3.6.egg
Removing d:\program files\anaconda3\lib\site-packages\tf2onnx-0.0.0.1-py3.6.egg
Copying tf2onnx-0.0.0.1-py3.6.egg to d:\program files\anaconda3\lib\site-packages
Removing tf2onnx 0.0.0.1 from easy-install.pth file
Adding tf2onnx 0.0.0.1 to easy-install.pth file

Installed d:\program files\anaconda3\lib\site-packages\tf2onnx-0.0.0.1-py3.6.egg
Processing dependencies for tf2onnx==0.0.0.1
Searching for pytest-cov==2.5.1
Best match: pytest-cov 2.5.1
Processing pytest_cov-2.5.1-py3.6.egg
pytest-cov 2.5.1 is already the active version in easy-install.pth

Using d:\program files\anaconda3\lib\site-packages\pytest_cov-2.5.1-py3.6.egg
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file

Using d:\program files\anaconda3\lib\site-packages
Searching for graphviz==0.8.2
Best match: graphviz 0.8.2
Processing graphviz-0.8.2-py3.6.egg
graphviz 0.8.2 is already the active version in easy-install.pth

Using d:\program files\anaconda3\lib\site-packages\graphviz-0.8.2-py3.6.egg
Searching for coverage==4.5.1
Best match: coverage 4.5.1
Processing coverage-4.5.1-py3.6-win-amd64.egg
coverage 4.5.1 is already the active version in easy-install.pth
Installing coverage-3.6-script.py script to D:\Program Files\anaconda3\Scripts
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    install_requires=['graphviz', 'pyyaml', 'pytest-cov']
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "D:\Program Files\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Program Files\anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Program Files\anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 701, in install_item
    self.process_distribution(spec, dist, deps)
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 756, in process_distribution
    self.easy_install(dist.as_requirement())
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 704, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 726, in process_distribution
    self.install_egg_scripts(dist)
  File "D:\Program Files\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 600, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "D:\Program Files\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1405, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

**Comment by guschmue** [comment]
no totally sure why this is failing, something  wrong with the graphviz I assume.
On a clean anaconda 3.6 install I tried:
python setup.py install and bdist_wheel - it is happy. 
I had changed setup.py to only install ['pytest', 'pytest-cov', 'psutil', 'graphviz'] for tests since we only need them for tests. If you try on the master you should be fine.
If I do a 'python setup.py test ' I see that graphviz-0.8.3 gets installed which is newer than the one on your system ...
closing, assuming that works now, please re-open if you still see problems.
