### ISSUE TITLE
--large-model for TF 1.X: ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.

### ISSUE THREAD

**Issue by OpUs-Nebula** [onnx/tensorflow-onnx#1131]
**Describe the bug**
Using the --large-model option with the CLI tool causes `ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.` when compiling PEGASUS, a BERT derivative, for TF 1.X.

**Urgency**
none.

**System information**
[g4dn.8xlarge](https://www.amazonaws.cn/en/ec2/instance-types/) EC2 instance:
- [DLAMI](https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-AWS-Deep-Learning-AMI-Ubuntu-1/B07Y43P7X5), Linux Ubuntu 18.04, version 34.0
- 1.15.2:
- 3.6.10:

**To Reproduce**
1. Download [exported model](https://public-sources-bucket.s3.amazonaws.com/model.tar.gz)
2. Unpack tar
3. Run  python -m tf2onnx.convert --saved-model cnn_dailymail/1601652430 --output model.onnx

**Expected behavior**
Not sure. First time running ONNX. 

**Screenshots**

**Additional context**
saved_model of [this](https://github.com/google-research/pegasus)

**Comment by TomWildenhain-Microsoft** [comment]
Did you try using TF 2.3?  Is there a reason you want to use TF 1.x?

**Comment by OpUs-Nebula** [comment]
The model is built using TF 1.X. I've tried running the upgrade script, but the report gave me ~26 files worth of manual changes necessary, some impacting the accuracy of the computations involved. I'm unsure how it may impact the performance of the model, as I am not it's author, so would prefer to try this before digging into that.

**Comment by TomWildenhain-Microsoft** [comment]
Makes sense. Can you include the entire stdout from conversion?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by OpUs-Nebula** [comment]
`(aws_neuron_tensorflow_p36) ubuntu@ip-172-31-66-139:~/project$ python -m tf2onnx.convert --large_model  --saved-model cnn_dailymail/1601652430 --output model.onnx
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-10-14 17:35:34,088 - WARNING - From /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-10-14 17:35:34,114 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2020-10-14 17:35:38,009 - INFO - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2020-10-14 17:35:38,009 - INFO - NumExpr defaulting to 8 threads.
2020-10-14 17:35:47,108 - INFO - Using tensorflow=1.15.3, onnx=1.7.0, tf2onnx=1.7.1/796841
2020-10-14 17:35:47,108 - INFO - Using opset <onnx, 8>
2020-10-14 17:35:54,469 - INFO - Computed 526 values for constant folding
2020-10-14 17:35:54,585 - ERROR - pass1 convert failed for name: "ParseExample/ParseExample"
op: "ParseExample"
input: "input_example_tensor"
input: "ParseExample/ParseExample/names"
input: "ParseExample/ParseExample/dense_keys_0"
input: "ParseExample/Const"
attr {
  key: "Ndense"
  value {
    i: 1
  }
}
attr {
  key: "Nsparse"
  value {
    i: 0
  }
}
attr {
  key: "Tdense"
  value {
    list {
      type: DT_INT64
    }
  }
}
attr {
  key: "dense_shapes"
  value {
    list {
      shape {
        dim {
          size: 1024
        }
      }
    }
  }
}
attr {
  key: "sparse_types"
  value {
    list {
    }
  }
}
, ex=You passed in an iterable attribute but I cannot figure out its applicable type.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/convert.py", line 185, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/convert.py", line 163, in main
    const_node_values=const_node_values)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 414, in process_tf_graph
    tensorflow_to_onnx(tf_graph, shape_override, const_node_values)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/tf_utils.py", line 326, in tensorflow_to_onnx
    return tflist_to_onnx(graph, shape_override, const_node_values)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tf2onnx/tf_utils.py", line 313, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/onnx/helper.py", line 268, in make_attribute
    "You passed in an iterable attribute but I cannot figure out "
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.`

**Comment by TomWildenhain-Microsoft** [comment]
Thanks.  Oh and including a link to the tar is totally fine.

**Comment by OpUs-Nebula** [comment]
I tried this for the same model compiled for tf2.x by @TheRockXu, mentioned at https://github.com/google-research/pegasus/issues/65, and recieved the same error.

**Comment by TomWildenhain-Microsoft** [comment]
It looks like this model contains a ParseExample op which has no analogous onnx op and cannot be converted.  

https://www.tensorflow.org/api_docs/python/tf/io/parse_example

Is it possible to remove this op from the model?

**Comment by OpUs-Nebula** [comment]
I think it should be doable, something i will need to look into though. Is that the only problematic operator or is there a chance that more will come up along the way?

**Comment by TomWildenhain-Microsoft** [comment]
Normally the converter just skips ops it can't convert but in this case it crashed while parsing the op so it didn't give that information.  After fixing the parsing of ParseExample the model converts with only 2 unsupported ops:
`Unsupported ops: Counter({'ParseExample': 1, 'TensorScatterUpdate': 1})`
I can easily add support for TensorScatterUpdate

**Comment by TomWildenhain-Microsoft** [comment]
Parsing fixed with #1140

**Comment by TomWildenhain-Microsoft** [comment]
TensorScatterNdUpdate #1142
