### ISSUE TITLE
TypeError: value "<dtype: 'int32'>" is not valid attribute data type.

### ISSUE THREAD

**Issue by oswen** [onnx/tensorflow-onnx#1181]
When I use tf2onnx, I have the following error, which seems to prompt the error of the op while/roll. Since my model needs to use beam search, so I need to use tf.while_ loop, is it because tf2onnx is not compatible with while_ loop?

**2020-11-16 10:38:04,980 - INFO - Using tensorflow=1.13.1, onnx=1.7.0, tf2onnx=1.7.1/796841
2020-11-16 10:38:04,980 - INFO - Using opset <onnx, 10>
2020-11-16 10:38:06,538 - INFO - Computed 65 values for constant folding
2020-11-16 10:38:08,325 - ERROR - pass1 convert failed for name: "while/Roll"
op: "Roll"
input: "while/Greater_8"
input: "while/Roll/shift"
input: "while/Roll/axis"
attr {
  key: "T"
  value {
    type: DT_BOOL
  }
}
attr {
  key: "Taxis"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tshift"
  value {
    type: DT_INT32
  }
}
, ex=value "<dtype: 'int32'>" is not valid attribute data type.
Traceback (most recent call last):
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\tf2onnx\convert.py", line 185, in <module>
    main()
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\tf2onnx\convert.py", line 163, in main
    const_node_values=const_node_values)
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\tf2onnx\tfonnx.py", line 414, in process_tf_graph
    tensorflow_to_onnx(tf_graph, shape_override, const_node_values)
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\tf2onnx\tf_utils.py", line 326, in tensorflow_to_onnx
    return tflist_to_onnx(graph, shape_override, const_node_values)
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\tf2onnx\tf_utils.py", line 313, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\onnx\helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\onnx\helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "C:\Users\w00444710\AppData\Local\Continuum\anaconda3\lib\site-packages\onnx\helper.py", line 272, in make_attribute
    'value "{}" is not valid attribute data type.'.format(value))
TypeError: value "<dtype: 'int32'>" is not valid attribute data type.**

**Comment by TomWildenhain-Microsoft** [comment]
We do support the While loop, but not the Roll op yet.  I'll look into adding support now.
