### ISSUE TITLE
.onnx -file is not created after convert ends/finishes

### ISSUE THREAD

**Issue by frankhaugen** [onnx/tensorflow-onnx#1186]
**Describe the bug**
There are no onnx file generated. Seemingly the process just stops without an exception or log-message

**Urgency**
This is blocking our work on the 2020 ml.net hackathon

**System information**
- Windows 10
- Tensorflow Version: 2.3.1
- Python version: 3.8
- Onnx version: 1.8.0

**To Reproduce**
run this: `python -m tf2onnx.convert --saved-model exported-models\saved_model --output model.onnx --verbose`  
(This is from the readme.md in this repo)

**Expected behavior**
There is a model.onnx file saved somewhere

**Screenshots**
Where the process ends:
![126027992_745713316299746_6441435703123173094_n](https://user-images.githubusercontent.com/13543585/99372702-d9edbc00-28c0-11eb-810e-4fa75cdbd0a5.png)

**Additional context**
The .pb file is 7.8MB in size, the process takes about twenty minutes

**Comment by guschmue** [comment]
I wonder if the process crashed.

Early on tf2onnx logs some versions, like:
 INFO - Using tensorflow=2.3.1, onnx=1.8.0, tf2onnx=1.8.0/5c0e1a
Can you send us this line?

We recently had some crashes with onnx-1.8 on windows but those should have been fixed before onnx-1.8 released.
If you see onnx-1.8, could you do a 
```pip install onnx==1.7```
 and see if that fixes it to confirm?

**Comment by frankhaugen** [comment]
Thank you @guschmue for a quick reply!

> I wonder if the process crashed.  

You were correct and now we actually get an error message after downgrading, which is kind of cryptic and has an exception in the exception handling ironically enough.

I'm no expert, but I'm guessing the issue is in the training and not in the tf2onnx. Can you confirm my hypothesis:
````
2020-11-17 18:07:18.224818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-11-17 18:07:18.227750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-17 18:07:18.231487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-11-17 18:07:18.234796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-11-17 18:07:18.237171: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6228 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-11-17 18:07:18.253423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 with Max-Q Design computeCapability: 7.5
coreClock: 1.185GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 357.69GiB/s
2020-11-17 18:07:18.261488: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-11-17 18:07:18.266301: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-11-17 18:07:18.270433: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-11-17 18:07:18.274151: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-11-17 18:07:18.278648: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-11-17 18:07:18.285089: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-11-17 18:07:18.288710: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-11-17 18:07:18.292424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-11-17 18:07:18.295863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-17 18:07:18.299996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-11-17 18:07:18.302707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-11-17 18:07:18.305555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6228 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-11-17 18:07:18,353 - INFO - tf2onnx.tf_utils: Computed 2 values for constant folding
2020-11-17 18:14:19,917 - INFO - tf2onnx.tfonnx: folding node using tf type=Select, name=StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/Select_1
2020-11-17 18:14:19,917 - INFO - tf2onnx.tfonnx: folding node using tf type=Select, name=StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/Select_8
2020-11-17 18:14:20,222 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2020-11-17 18:14:20,985 - ERROR - tf2onnx.tfonnx: Tensorflow op [StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/non_max_suppression_with_scores/NonMaxSuppressionV5: NonMaxSuppressionV5] is not supported
2020-11-17 18:14:22,023 - ERROR - tf2onnx.tfonnx: Failed to convert node 'StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/TopKV2' (fct=<bound method TopKV2.version_1 of <class 'tf2onnx.onnx_opset.tensor.TopKV2'>>)
'OP=TopK\nName=StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/TopKV2\nInputs:\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Concatenate/concat_1/concat:0=Identity, [100], 1\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/strided_slice__534:0=Cast, [], 6\nOutpus:\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/TopKV2:0=[-1], 1\nOutpus:\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/TopKV2:1=[-1], 6'
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\tfonnx.py", line 287, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 1000, in version_1
    k = node.inputs[1].get_tensor_value()
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\graph.py", line 318, in get_tensor_value
    raise ValueError("get tensor value: '{}' must be Const".format(self.name))
ValueError: get tensor value: 'StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/strided_slice__534' must be Const
2020-11-17 18:14:22,032 - ERROR - tf2onnx.tfonnx: Tensorflow op [StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/ClipToWindow/Where: Where] is not supported
2020-11-17 18:14:23,191 - ERROR - tf2onnx.tfonnx: Failed to convert node 'StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/TopKV2' (fct=<bound method TopKV2.version_1 of <class 'tf2onnx.onnx_opset.tensor.TopKV2'>>)
'OP=TopK\nName=StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/TopKV2\nInputs:\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Select_1:0=Identity, [-1], 1\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/strided_slice__562:0=Cast, [], 6\nOutpus:\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/TopKV2:0=[-1], 1\nOutpus:\n\tStatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/TopKV2:1=[-1], 6'
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\tfonnx.py", line 287, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 1000, in version_1
    k = node.inputs[1].get_tensor_value()
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\graph.py", line 318, in get_tensor_value
    raise ValueError("get tensor value: '{}' must be Const".format(self.name))
ValueError: get tensor value: 'StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/strided_slice__562' must be Const
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\tfonnx.py", line 287, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 341, in version_1
    _ = GraphBuilder(ctx).make_slice(kwargs, name=node.name)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\graph_builder.py", line 41, in make_slice
    ends = self.convert_to_attribute(kwargs.pop("ends"))
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\graph_builder.py", line 106, in convert_to_attribute
    res = const_node.get_tensor_value(as_list=True)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\graph.py", line 318, in get_tensor_value
    raise ValueError("get tensor value: '{}' must be Const".format(self.name))
ValueError: get tensor value: 'Add__648' must be Const

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\convert.py", line 188, in <module>
    main()
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\convert.py", line 156, in main
    g = process_tf_graph(tf_graph,
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\tfonnx.py", line 525, in process_tf_graph
    mapped_op, unmapped_op, exceptions = tensorflow_onnx_mapping(g, ops_mapping)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\tfonnx.py", line 291, in tensorflow_onnx_mapping
    node.name, func, node.summary, exc_info=1)
  File "C:\Users\marie\Anaconda3\envs\pythonProject1\lib\site-packages\tf2onnx\graph.py", line 233, in summary
    node = g.get_node_by_output(name)
AttributeError: 'NoneType' object has no attribute 'get_node_by_output'
```

**Comment by TomWildenhain-Microsoft** [comment]
Can you try again with the `--opset 12` flag?

**Comment by frankhaugen** [comment]
> Can you try again with the `--opset 12` flag?

Turns out that it was the model being FUBAR, but your suggestion was also used and nothing went wrong! :-)

**Comment by guschmue** [comment]
cool. I think we need to take a look at onnx-1.8.

**Comment by askhade** [comment]
@frankhaugen can you list the version of pybind11 and protobuf you have installed. Also I am assuming you installed onnx from pypi ... can you try onnx 1.8 from conda and see if you still see crashes. Thanks!
