### ISSUE TITLE
Tensorflow 2.0 checkpoints conversion to Onnx fails

### ISSUE THREAD

**Issue by baymak** [onnx/tensorflow-onnx#1197]
I get error to use the below command in order to convert checkpoints to Onnx. I guess it is designed for TF1.0 checkpoints. Could you please help how can I convert TF2.x checkpoints to Onnx?
here is my comment line:
!python -m tf2onnx.convert --checkpoint  './Onnx_Trials/ckptGen/StarGAN_v2_GAN_HairS_gan-gp/'  --output mymodel.onnx --inputs input_1:0[1,256,256,3],input_2:0[1,64] --outputs Identity:0[1,256,256,3]

and I get the error code below. It complains that I provide the folder as checkpoint. There are 3 files produced as checkpoints in TF2, checkpoint, .index and the data file. 

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 188, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 132, in main
    graph_def, inputs, outputs = tf_loader.from_checkpoint(args.checkpoint, args.inputs, args.outputs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_loader.py", line 203, in from_checkpoint
    saver = tf_import_meta_graph(model_path, clear_devices=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1462, in import_meta_graph
    **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1476, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/meta_graph.py", line 627, in read_meta_graph_file
    file_content = file_io.FileIO(filename, "rb").read()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 121, in read
    return self._prepare_value(self._read_buf.read(length))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Onnx_Trials/ckptGen/StarGAN_v2_GAN_HairS_gan-gp; Is a directory

**Comment by guschmue** [comment]
the ```--checkpoint``` argument needs to be the .meta file in the checkpoint directory.

**Comment by nikhildurgam95** [comment]
There's no .meta file in tf 2.0 checkpoints. There's only index and data files. How do we get around that?

**Comment by guschmue** [comment]
There are graphdefs, checkpoints and saved-models. tf-2.x prefers the later. 
Its a directory with a saved_model.pb in it.
Use ```--saved-model the_directory``` in the command line.
