### ISSUE TITLE
Failed to convert with node LookupTableFindV2

### ISSUE THREAD

**Issue by wangqiaoshi** [onnx/tensorflow-onnx#1219]
**Describe the bug**
When trying to convert a tensorflow model containing op LookupTableFindV2 , the conversion to onnx fails.   table_node.get_attr_value("shared_name") is None, details
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 287, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 24, in version_8
    file_path = table_node.get_attr_value("shared_name")[11:-6]
TypeError: 'NoneType' object is not subscriptable
2020-12-08 03:01:51,234 - ERROR - Unsupported ops: Counter({'LookupTableSizeV2': 1, 'StringToHashBucketFast': 1})
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/convert.py", line 156, in main
    g = process_tf_graph(tf_graph,
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 529, in process_tf_graph
    raise exceptions[0]
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 287, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 24, in version_8
    file_path = table_node.get_attr_value("shared_name")[11:-6]
TypeError: 'NoneType' object is not subscriptable
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  18.04
- Tensorflow Version:   2.3.1
- Python version: 3.8

**To Reproduce**
Describe steps/code to reproduce the behavior:
```
import tensorflow as tf
import os
def make_data_file(path, lines):
    with open(path, "w") as data:
        for line in lines:
            data.write("%s\n" % line)
    return path
source_vocabulary = make_data_file(
    os.path.join("", "src_vocab.txt"),
    ["<blank>", "<s>", "</s>", "a", "b", "c", "d"])



class MyModel(tf.keras.layers.Layer):
    def __init__(self):
        super(MyModel, self).__init__()
        vocabulary_path="src_vocab.txt"
        tokens_to_ids_initializer = tf.lookup.TextFileInitializer(
        vocabulary_path,
        tf.string,
        tf.lookup.TextFileIndex.WHOLE_LINE,
        tf.int64,
        tf.lookup.TextFileIndex.LINE_NUMBER,
        vocab_size=7)
        self.tokens_to_ids = tf.lookup.StaticVocabularyTable(tokens_to_ids_initializer, 1)
    def build(self,input_shape):
        # self.v = self.add_weight(name="v", shape=(3, 3),dtype=tf.float32)
        # tf.print(type(self.v))
        self.w = self.add_weight(name="w", shape=(5),dtype=tf.int64)
#         self.b = self.add_weight(name="b",shape=(2,4,4),dtype=tf.float32)
#         self.c = self.add_weight(name="b", shape=(5,3), dtype=tf.float32)

    @tf.function(input_signature=[tf.TensorSpec.from_spec(tf.TensorSpec([5,], tf.string))])
    def call(self, tokens):
        ids = self.tokens_to_ids.lookup(tokens)
        out = ids+self.w
        return out

input_tensor = tf.constant(["emerson", "lake", "palmer", "king", "crimnson"])
myModel = MyModel()
myModel(input_tensor)
tf.saved_model.save(myModel, "save1", signatures=myModel.call)
```
python -m tf2onnx.convert --saved-model save1  --opset 10 --output model.onnx

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
We've recently made some changes to improve conversion of this op.  Can you try with the latest version of tf2onnx from GitHub?
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by wangqiaoshi** [comment]
> We've recently made some changes to improve conversion of this op. Can you try with the latest version of tf2onnx from GitHub?
> `pip uninstall tf2onnx`
> `pip install git+https://github.com/onnx/tensorflow-onnx`

@TomWildenhain-Microsoft  thanks for the reply. I don't know if it is the problem of tensorflow itself, or the problem of using tensorflow, or other problems. Now there are other problems
```
2020-12-09 01:59:22,517 - ERROR - Failed to convert node 'StatefulPartitionedCall/None_Lookup/None_Size/LookupTableSizeV2' (fct=<bound method LookupTableSize.version_1 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableSize'>>)
'OP=LookupTableSizeV2\nName=StatefulPartitionedCall/None_Lookup/None_Size/LookupTableSizeV2\nInputs:\n\tFunc/StatefulPartitionedCall/input/_1:0=Identity, [], 7\nOutpus:\n\tStatefulPartitionedCall/None_Lookup/None_Size/LookupTableSizeV2:0=[], 7'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 289, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 86, in version_1
    utils.make_sure(shared_name is not None, "Could not determine table shared name for node %s", node.name)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/utils.py", line 214, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Could not determine table shared name for node StatefulPartitionedCall/None_Lookup/None_Size/LookupTableSizeV2
2020-12-09 01:59:22,518 - ERROR - Tensorflow op [StatefulPartitionedCall/None_Lookup/hash_bucket: StringToHashBucketFast] is not supported
2020-12-09 01:59:22,518 - ERROR - Failed to convert node 'StatefulPartitionedCall/None_Lookup/None_Lookup/LookupTableFindV2' (fct=<bound method LookupTableFind.version_8 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableFind'>>)
'OP=LookupTableFindV2\nName=StatefulPartitionedCall/None_Lookup/None_Lookup/LookupTableFindV2\nInputs:\n\tFunc/StatefulPartitionedCall/input/_1:0=Identity, [], 7\n\tFunc/StatefulPartitionedCall/input/_0:0=Identity, [5], 8\n\tFunc/StatefulPartitionedCall/input/_2:0=Identity, [], 7\nOutpus:\n\tStatefulPartitionedCall/None_Lookup/None_Lookup/LookupTableFindV2:0=[5], 7'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 289, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 34, in version_8
    utils.make_sure(shared_name is not None, "Could not determine table shared name for node %s", node.name)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/utils.py", line 214, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Could not determine table shared name for node StatefulPartitionedCall/None_Lookup/None_Lookup/LookupTableFindV2
2020-12-09 01:59:22,520 - ERROR - Unsupported ops: Counter({'StringToHashBucketFast': 1})
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/convert.py", line 157, in main
    g = process_tf_graph(tf_graph,
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 533, in process_tf_graph
    raise exceptions[0]
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 289, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 86, in version_1
    utils.make_sure(shared_name is not None, "Could not determine table shared name for node %s", node.name)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/utils.py", line 214, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Could not determine table shared name for node StatefulPartitionedCall/None_Lookup/None_Size/LookupTableSizeV2
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x7f003c3a7b80>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py", line 202, in __del__
    self._destroy_resource()
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 237, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 74, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 105, in _call_flat
    return super(_WrapperFunction, self)._call_flat(args, captured_inputs,
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1938, in _call_flat
    flat_outputs = forward_function.call(ctx, args_with_tangents)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 573, in call
    outputs = functional_ops.partitioned_call(
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/functional_ops.py", line 1192, in partitioned_call
    f.add_to_graph(graph)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 495, in add_to_graph
    g._add_function(self)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3344, in _add_function
    pywrap_tf_session.TF_GraphCopyFunction(self._c_graph, function._c_func.func,
```

**Comment by TomWildenhain-Microsoft** [comment]
Two things: It looks like there was a bug in reading hash table initializers which I'm fixing with #1223.  Also this model contains some ops with no ONNX equivalents (StringToHashBucketFast).  Fortunately, these ops do have implementations in our soon-to-be-announced custom ops framework here: https://github.com/microsoft/ort-customops

To enable these conversions, follow this tutorial: https://github.com/microsoft/ort-customops/blob/tom/AddTutorial/tutorials/custom_ops_tutorial.ipynb

**Comment by wangqiaoshi** [comment]
> Two things: It looks like there was a bug in reading hash table initializers which I'm fixing with #1223. Also this model contains some ops with no ONNX equivalents (StringToHashBucketFast). Fortunately, these ops do have implementations in our soon-to-be-announced custom ops framework here: https://github.com/microsoft/ort-customops
> 
> To enable these conversions, follow this tutorial: https://github.com/microsoft/ort-customops/blob/tom/AddTutorial/tutorials/custom_ops_tutorial.ipynb

I have a question, I don't know if ort-customops is suitable for tensorrt.

**Comment by wangqiaoshi** [comment]
> Two things: It looks like there was a bug in reading hash table initializers which I'm fixing with #1223. Also this model contains some ops with no ONNX equivalents (StringToHashBucketFast). Fortunately, these ops do have implementations in our soon-to-be-announced custom ops framework here: https://github.com/microsoft/ort-customops
> 
> To enable these conversions, follow this tutorial: https://github.com/microsoft/ort-customops/blob/tom/AddTutorial/tutorials/custom_ops_tutorial.ipynb

@TomWildenhain-Microsoft 
thanks！ This bug fix has played a big role, but encountered a problem

`
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 289, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 39, in version_8
    utils.make_sure(default_node.is_const(), "Default value of table lookup must be const.")
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/utils.py", line 214, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Default value of table lookup must be const.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/pdb.py", line 1703, in main
    pdb._runscript(mainpyfile)
  File "/opt/conda/lib/python3.8/pdb.py", line 1572, in _runscript
    self.run(statement)
  File "/opt/conda/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/jovyan/data/glusterfs_sharing_04_v3/11112968/OpenNMT-tf/scripts/wmt/test.py", line 2, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/convert.py", line 157, in main
    g = process_tf_graph(tf_graph,
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 533, in process_tf_graph
    raise exceptions[0]
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 289, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 39, in version_8
    utils.make_sure(default_node.is_const(), "Default value of table lookup must be const.")
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/utils.py", line 214, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Default value of table lookup must be const.
`

**Comment by wangqiaoshi** [comment]
I look at the tensorflow code, default_value=-1
[code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/lookup_ops.py#L1237)

**Comment by TomWildenhain-Microsoft** [comment]
Interesting, it is working for me.  Can you upload the zipped saved model?  Maybe your tf version is saving it differently.

No, the customops will not work with TensorRT, but you may want to consider using onnxruntime instead which uses TensorRT as an execution provider.  Ops with TensorRT support will be routed to TensorRT.  Other ops will use the c++ onnxruntime implementation.  https://github.com/microsoft/onnxruntime

`pip install onnxruntime`

**Comment by wangqiaoshi** [comment]
[save1.zip](https://github.com/onnx/tensorflow-onnx/files/5676591/save1.zip)
@TomWildenhain-Microsoft

**Comment by wangqiaoshi** [comment]
sorry,It’s my mistake, now the export is OK, but there are also errors
···
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x7fd9e58ecb80>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py", line 202, in __del__
    self._destroy_resource()
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 237, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 74, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 105, in _call_flat
    return super(_WrapperFunction, self)._call_flat(args, captured_inputs,
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1938, in _call_flat
    flat_outputs = forward_function.call(ctx, args_with_tangents)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 573, in call
    outputs = functional_ops.partitioned_call(
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/functional_ops.py", line 1192, in partitioned_call
    f.add_to_graph(graph)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 495, in add_to_graph
    g._add_function(self)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3344, in _add_function
    pywrap_tf_session.TF_GraphCopyFunction(self._c_graph, function._c_func.func,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null
WARNING:tensorflow:Unresolved object in checkpoint: (root).tokens_to_ids._initializer
2020-12-11 03:30:00,586 - WARNING - Unresolved object in checkpoint: (root).tokens_to_ids._initializer
WARNING:tensorflow:Unresolved object in checkpoint: (root).tokens_to_ids._initializer._filename
2020-12-11 03:30:00,586 - WARNING - Unresolved object in checkpoint: (root).tokens_to_ids._initializer._filename
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
2020-12-11 03:30:00,586 - WARNING - A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
···

**Comment by TomWildenhain-Microsoft** [comment]
Those exceptions look like they can be safely ignored.  Was an onnx file generated?

**Comment by wangqiaoshi** [comment]
> Those exceptions look like they can be safely ignored. Was an onnx file generated?
thank you , file generated.

**Comment by wangqiaoshi** [comment]
It works normally in a simple network, but will cause problems in a complex network.
if op HashTableV2 






`
 for r in imported.__dict__.values():
        if isinstance(r, TfRestoredResourceType) and hasattr(r, '_create_resource') and hasattr(r, 'resource_handle'):
            # Add tables from saved_model table initializers
            # pylint: disable=protected-access
            initializer = r._create_resource.concrete_functions[0].function_def
            new_names, new_k_dtypes, new_v_dtypes = get_hash_table_info(initializer.node_def)
            table_names.extend(new_names)
            key_dtypes.extend(new_k_dtypes)
            value_dtypes.extend(new_v_dtypes)
            table_handle = id(r.resource_handle)
            if table_handle in removed_resource_to_placeholder and len(new_names) == 1:
                table_info = (new_names[0], new_k_dtypes[0], new_v_dtypes[0])
                placeholder_to_table_info[removed_resource_to_placeholder[table_handle]] = table_info
`

**Comment by wangqiaoshi** [comment]
For this, I wrote an implementation example

```
from tensorflow.python.training.tracking.tracking import AutoTrackable

try:
    from tensorflow.python.saved_model.load import _RestoredResource as TfRestoredResourceType
except ImportError:
    TfRestoredResourceType = None


def get_hash_table_info_from_trackable(trackable, table_names, key_dtypes, value_dtypes,
                                       removed_resource_to_placeholder, placeholder_to_table_info):
    for r in trackable.__dict__.values():
        if isinstance(r, TfRestoredResourceType) and hasattr(r, '_create_resource') and hasattr(r, 'resource_handle'):
            initializer = r._create_resource.concrete_functions[0].function_def
            new_names, new_k_dtypes, new_v_dtypes = get_hash_table_info(initializer.node_def)
            table_names.extend(new_names)
            key_dtypes.extend(new_k_dtypes)
            value_dtypes.extend(new_v_dtypes)
            table_handle = id(r.resource_handle)
            if table_handle in removed_resource_to_placeholder and len(new_names) == 1:
                table_info = (new_names[0], new_k_dtypes[0], new_v_dtypes[0])
                placeholder_to_table_info[removed_resource_to_placeholder[table_handle]] = table_info


def fetch_all_hash_table_info(trackable, table_names, key_dtypes, value_dtypes, removed_resource_to_placeholder,
                            placeholder_to_table_info):
    if not isinstance(trackable, AutoTrackable):
        return
    get_hash_table_info_from_trackable(trackable, table_names, key_dtypes, value_dtypes,
                                       removed_resource_to_placeholder,
                                       placeholder_to_table_info)
    if isinstance(trackable, AutoTrackable):
        for r in trackable.__dict__.values():
            fetch_all_hash_table_info(r,table_names, key_dtypes, value_dtypes, removed_resource_to_placeholder,
                            placeholder_to_table_info)
```

**Comment by TomWildenhain-Microsoft** [comment]
Thanks @wangqiaoshi, can you also upload the keras code to create such a nested model?  Then I can add it as a test case and incorporate your changes.  Thanks so much!

**Comment by TomWildenhain-Microsoft** [comment]
Never mind, a different GitHub issue provided such a model.  #1228

**Comment by wangqiaoshi** [comment]
ok

**Comment by TomWildenhain-Microsoft** [comment]
Has the PR solved your issue?  If so, I'll close this.

**Comment by wangqiaoshi** [comment]
Solved it, close it
