### ISSUE TITLE
if concrete_func.graph.captures contain dtype= string ,can throw exception

### ISSUE THREAD

**Issue by wangqiaoshi** [onnx/tensorflow-onnx#1227]
**Describe the bug**
- convert a transformer model
- training code https://github.com/OpenNMT/OpenNMT-tf
-  if concrete_func.graph.captures contain dtype= string ,can throw exception

```
Traceback (most recent call last):
  File "test2.py", line 2, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/convert.py", line 136, in main
    graph_def, inputs, outputs, initialized_tables = tf_loader.from_saved_model(
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 409, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names, tag, signatures, concrete_function, large_model)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 362, in _from_saved_model_v2
    frozen_graph = from_function(concrete_func, inputs, outputs, large_model)
  File "/opt/conda/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 134, in from_function
    frozen_func = convert_variables_to_constants_v2(func, lower_control_flow=False, aggressive_inlining=True)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1066, in convert_variables_to_constants_v2
    converter_data = _FunctionConverterData(
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 804, in __init__
    self._build_tensor_data()
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 826, in _build_tensor_data
    dtype=dtypes.as_dtype(data.dtype).as_datatype_enum,
AttributeError: 'bytes' object has no attribute 'dtype'
```

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Tensorflow Version:  2.3.1
- Python version: 3.8

**To Reproduce**
Describe steps/code to reproduce the behavior:

wget https://s3.amazonaws.com/opennmt-models/averaged-ende-export500k-v2.tar.gz
tar xf averaged-ende-export500k-v2.tar.gz
python test2.py -m tf2onnx.convert  --saved-model averaged-ende-export500k-v2 --extra_opset   ai.onnx.contrib:1 --opset 10 --output model.onnx

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by wangqiaoshi** [comment]
I don't know if it is right, I think the variables and resources of dtype=string should also be removed before freezing the graph

**Comment by TomWildenhain-Microsoft** [comment]
This is caused by a bug in TF's convert_variables_to_constants_v2 function.
https://github.com/tensorflow/tensorflow/pull/45610/files

**Comment by TomWildenhain-Microsoft** [comment]
There are some other issues causing this model not to convert.  I'm taking a look now.
