### ISSUE TITLE
RuntimeError: Shape inference error(s): (op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/mul): [ShapeInferenceError] Incompatible dimensions

### ISSUE THREAD

**Issue by ben-omji** [onnx/tensorflow-onnx#1251]
**Describe the bug**
Hi, I'm trying to convert [attention ocr model](https://github.com/tensorflow/models/tree/master/research/attention_ocr) to onnx.

Train model, export to saved model format and use tf2onnx for converting from saved model to onnx model.
`python -m tf2onnx.convert --saved-model aocr_indexout/1/ --opset 12 --output model.onnx`

I checked that the tf saved model brings a valid output. Then load and use the converted onnx model in python script.
```
import onnx
  
model = onnx.load("model.onnx")

onnx.checker.check_model(model)
onnx.helper.printable_graph(model.graph)

import caffe2.python.onnx.backend as backend
import numpy as np
import PIL.Image

rep = backend.prepare(model, device="GPU")

outputs = rep.run([np.asarray(PIL.Image.open('IDiHafX2zNrl.jpg')).tolist()])
print(outputs[0])
```
And I face the error, 

**RuntimeError: Shape inference error(s): (op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/mul): [ShapeInferenceError] Incompatible dimensions**

I'm very new to onnx, so totally can not guess what's wrong.. Opset 9~12 throw the same RuntimeError.

**Urgency**
None, but plz give me the solution or any recommended model format for run tensorflow model on nvidia jetson nano.

**System information**
- Test on Linux Ubuntu 18.04 with RTX 2080Ti & NVIDIA Jetson nano
- Tensorflow Version: 1.15
- Python version: 3.6.8

**To Reproduce**
Describe on the top with bug.

**Expected behavior**
Same output with the tensorflow saved model's

**Screenshots**
Full error message:
```
Traceback (most recent call last):
  File "infer_onnx.py", line 12, in <module>
    rep = backend.prepare(model, device="CPU")
  File "/usr/local/lib/python3.6/dist-packages/caffe2/python/onnx/backend.py", line 707, in prepare
    model = onnx.shape_inference.infer_shapes(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_1/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_2/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_3/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_4/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_5/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_7/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/mul): [ShapeInferenceError] Incompatible dimensions
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/Sum): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Softmax, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/Softmax): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/Reshape_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/mul_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:ReduceSum, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/Sum_1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: AttentionOcr_v1/sequence_logit_fn/SQLR/LSTM/attention_decoder/Attention_0_8/Reshape_2): [TypeInferenceError] Input 0 expected to have type but instead is null
```

**Additional context**
If you need the saved model dir, tensorflow model export script or any other information of this problem, feel free to say it.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @ben-omji , yes could please upload the saved model directory?

**Comment by ben-omji** [comment]
@TomWildenhain-Microsoft 

This is the Savedmodel dir. Thank you.
[aocr_indexout.zip](https://github.com/onnx/tensorflow-onnx/files/5753115/aocr_indexout.zip)

**Comment by TomWildenhain-Microsoft** [comment]
The problem is caused by a bug in the transpose optimizer.  I'm working on a fix.
