### ISSUE TITLE
Tensorflow Recommenders model fails to convert

### ISSUE THREAD

**Issue by marshallpierce** [onnx/tensorflow-onnx#1279]
**Describe the bug**
When using `tf2onnx.convert` on a model produced by tensorflow recommenders, conversion fails with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mbp/.virtualenvs/tfrs-onnx-repro-oWWnfm9c/lib/python3.8/site-packages/tf2onnx/convert.py", line 198, in <module>
    main()
  File "/home/mbp/.virtualenvs/tfrs-onnx-repro-oWWnfm9c/lib/python3.8/site-packages/tf2onnx/convert.py", line 165, in main
    g = process_tf_graph(tf_graph,
  File "/home/mbp/.virtualenvs/tfrs-onnx-repro-oWWnfm9c/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 491, in process_tf_graph
    fold_constants_using_tf(g, outputs_to_values, outputs_to_dtypes)
  File "/home/mbp/.virtualenvs/tfrs-onnx-repro-oWWnfm9c/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 52, in fold_constants_using_tf
    ops[idx] = g.make_const(new_node_name, val)
  File "/home/mbp/.virtualenvs/tfrs-onnx-repro-oWWnfm9c/lib/python3.8/site-packages/tf2onnx/graph.py", line 562, in make_const
    onnx_tensor = numpy_helper.from_array(np_val, name)
  File "/home/mbp/.virtualenvs/tfrs-onnx-repro-oWWnfm9c/lib/python3.8/site-packages/onnx/numpy_helper.py", line 112, in from_array
    raise NotImplementedError(
NotImplementedError: ('Unrecognized object in the object array, expect a string, or array of bytes: ', "<class 'bytes'>")
```

I don't have much context for this code but perhaps https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py#L111 needs to handle `bytes` in addition to `str`?

**Urgency**
We're exploring using onnxruntime to run tensorflow models, and this is currently blocking tfrs-based models, so it will significantly increase our chances of using onnx & onnxruntime if this problem is solved. :)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Gentoo x64 Linux, macOS
- Tensorflow Version: 2.4.0
- Python version: 3.8.6

**To Reproduce**
Run the code in https://github.com/marshallpierce/tfrs-onnx-repro as per the README.

**Expected behavior**
`tf2onnx` should produce an onnx artifact instead of crashing.

**Screenshots**
n/a

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Yes, this is a bug in numpy_helper but we should be able to work around it.  #1282 should fix your issue.

**Comment by marshallpierce** [comment]
Great, thanks! I'll keep an eye out for the next release.

**Comment by TomWildenhain-Microsoft** [comment]
You can also install from the master branch
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by marshallpierce** [comment]
Ah right, so I can, and that works successfully! Thanks for the quick fix. :heart:
