### ISSUE TITLE
Unsupported operations for TensorFlow word embeddings demo model

### ISSUE THREAD

**Issue by marshallpierce** [onnx/tensorflow-onnx#1328]
**Describe the bug**
The simple TensorFlow [word embeddings demo](https://www.tensorflow.org/tutorials/text/word_embeddings) produces a model that tf2onnx can't convert.

**Urgency**
We are prototyping using onnx (via onnxruntime), so the more of our models we can convert the more likely we are to be able to move forward with onnx. :)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.7
- Tensorflow Version: 2.4.1
- Python version: 3.8.7

**To Reproduce**
Follow the TensorFlow word embeddings demo notebook at https://www.tensorflow.org/tutorials/text/word_embeddings, and add a cell to save the model with `model.save('file name here')`.

Converting the model via `python -m tf2onnx.convert --saved-model saved --output word-embeddings.onnx --opset 13` produces:

```
ERROR - Unsupported ops: Counter({'StaticRegexReplace': 2, 'StringLower': 1, 'StringSplitV2': 1, 'RaggedTensorToTensor': 1})
```

**Expected behavior**
The model should convert without error.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @marshallpierce, this model contains string ops that ONNX has no analogous ops for.  Fortunately, we have many of these ops implemented in our custom ops repo:
https://github.com/microsoft/ort-customops

Try following the tutorial here: https://github.com/microsoft/ort-customops/blob/main/tutorials/tf2onnx_custom_ops_tutorial.ipynb

There are some ops (StringLower, RaggedTensorToTensor) that don't have conversions yet but should by the end of the week.

**Comment by marshallpierce** [comment]
That's great news, thanks. I'll give that a try, and keep my eye out for the new ops.

**Comment by TomWildenhain-Microsoft** [comment]
I think all the ops you need are now implemented.

**Comment by marshallpierce** [comment]
Using tf2onnx 1.8.2, it still crashes using `--extra_opset ai.onnx.contrib:1`:

```
2021-02-16 12:50:40,479 - ERROR - Failed to convert node 'StatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace' (fct=<bound method StaticRegexReplace.version_1 of <class 'tf2onnx.custom_opsets.string_ops.StaticRegexReplace'>>)
'OP=StringRegexReplace\nName=StatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace\nInputs:\n\tStatefulPartitionedCall/sequential/text_vectorization/StringLower:0=StringLower, [-1, 1], 8\nOutpus:\n\tStatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace:0=[-1, 1], 8'
Traceback (most recent call last):
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 294, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/custom_opsets/string_ops.py", line 63, in version_1
    pattern_node = ctx.make_const(utils.make_name("pattern"), np.array([pattern], np.object))
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/graph.py", line 567, in make_const
    onnx_tensor = helper.make_tensor(name, utils.map_numpy_to_onnx_dtype(np_val.dtype),
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/onnx/helper.py", line 251, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: '<br />' has type str, but expected one of: bytes
2021-02-16 12:50:40,480 - ERROR - Failed to convert node 'StatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace_1' (fct=<bound method StaticRegexReplace.version_1 of <class 'tf2onnx.custom_opsets.string_ops.StaticRegexReplace'>>)
'OP=StringRegexReplace\nName=StatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace_1\nInputs:\n\tStatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace:0=StringRegexReplace, [-1, 1], 8\nOutpus:\n\tStatefulPartitionedCall/sequential/text_vectorization/StaticRegexReplace_1:0=[-1, 1], 8'
Traceback (most recent call last):
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 294, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/custom_opsets/string_ops.py", line 63, in version_1
    pattern_node = ctx.make_const(utils.make_name("pattern"), np.array([pattern], np.object))
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/graph.py", line 567, in make_const
    onnx_tensor = helper.make_tensor(name, utils.map_numpy_to_onnx_dtype(np_val.dtype),
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/onnx/helper.py", line 251, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: '[!"\\#\\$%\\&\'\\(\\)\\*\\+,\\-\\./:;<=>\\?@\\[\\\\\\]\\^_`\\{\\|\\}\\~]' has type str, but expected one of: bytes
2021-02-16 12:50:40,509 - ERROR - Tensorflow op [StatefulPartitionedCall/sequential/text_vectorization/RaggedToTensor/RaggedTensorToTensor: RaggedTensorToTensor] is not supported
2021-02-16 12:50:40,515 - ERROR - Unsupported ops: Counter({'StringLower': 1, 'RaggedTensorToTensor': 1})
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/convert.py", line 221, in <module>
    main()
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/convert.py", line 185, in main
    g = process_tf_graph(tf_graph,
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 487, in process_tf_graph
    g = process_parsed_graph(g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter, target,
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 584, in process_parsed_graph
    raise exceptions[0]
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 294, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables)
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/custom_opsets/string_ops.py", line 63, in version_1
    pattern_node = ctx.make_const(utils.make_name("pattern"), np.array([pattern], np.object))
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/tf2onnx/graph.py", line 567, in make_const
    onnx_tensor = helper.make_tensor(name, utils.map_numpy_to_onnx_dtype(np_val.dtype),
  File "/Users/marshallpierce/.virtualenvs/tf-word-embeddings-cRgOsfbv/lib/python3.8/site-packages/onnx/helper.py", line 251, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: '<br />' has type str, but expected one of: bytes
```

**Comment by TomWildenhain-Microsoft** [comment]
Please use the latest tf2onnx from git.
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by marshallpierce** [comment]
Aha, that resolved the exceptions. Still one unsupported op thought:

```
Unsupported ops: Counter({'StringLower': 1})
```

**Comment by TomWildenhain-Microsoft** [comment]
Almost done: https://github.com/onnx/tensorflow-onnx/pull/1343

**Comment by marshallpierce** [comment]
Your responsiveness on this project is amazing :)

**Comment by marshallpierce** [comment]
Works
