### ISSUE TITLE
What is the correct format to mention node in --outputs argument

### ISSUE THREAD

**Issue by parth1595** [onnx/tensorflow-onnx#137]
I have run this command and it seems that the converter expects different format style to write output node in argument:

python -m tf2onnx.convert --input temp.pb --inputs data:0[1,28,28,3] --outputs Mean:0[1,4,1,1] --output model.onnx

Following is the **error** which I got:

File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/parthr/project/tools/tensorflow-onnx/tf2onnx/convert.py", line 112, in <module>
    main()
  File "/home/parthr/project/tools/tensorflow-onnx/tf2onnx/convert.py", line 85, in main
    graph_def = tf_optimize(None, args.inputs, args.outputs, graph_def, args.optimize_transpose)
  File "tf2onnx/tfonnx.py", line 1571, in tf_optimize
    graph_def = graph_util.extract_sub_graph(graph_def, needed_names)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_util_impl.py", line 174, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_util_impl.py", line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: 4 is not in graph

**Comment by pengwa** [comment]
"--outputs Mean:0[1,4,1,1]" should be "--outputs Mean:0"

The "[1,28,28,3]" is also optional, if without your conversion is successful.

**Comment by parth1595** [comment]
python -m tf2onnx.convert --input temp.pb --inputs data:0 --outputs Mean:0 --output model.onnx

I have already tried that but it also throws some **error**:

 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/parthr/project/lattice-tools/tensorflow-onnx/tf2onnx/convert.py", line 112, in <module>
    main()
  File "/home/parthr/project/lattice-tools/tensorflow-onnx/tf2onnx/convert.py", line 96, in main
    shape_override=args.shape_override)
  File "tf2onnx/tfonnx.py", line 1606, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "tf2onnx/tfonnx.py", line 104, in tensorflow_to_onnx
    onnx_tensor = utils.tf_to_onnx_tensor(node.get_attr(a), name=node.name + ":0")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2349, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)

I don't know what's wrong here

**Comment by pengwa** [comment]
is temp.pb a frozen tensorflow graph?

**Comment by parth1595** [comment]
Yes it is frozen tensorflow graph

**Comment by parth1595** [comment]
@pengwa Actually I am converting this tensorflow to onnx model using python 2.7 maybe that can be the issue. I have found this in forum that tensorflow->onnx is only tested in python. And the error which I get is maybe due to that version issue but not sure of it.

**Error:**
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/parthr/project/lattice-tools/tensorflow-onnx/tf2onnx/convert.py", line 112, in <module>
    main()
  File "/home/parthr/project/lattice-tools/tensorflow-onnx/tf2onnx/convert.py", line 96, in main
    shape_override=args.shape_override)
  File "tf2onnx/tfonnx.py", line 1606, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "tf2onnx/tfonnx.py", line 104, in tensorflow_to_onnx
    onnx_tensor = utils.tf_to_onnx_tensor(node.get_attr(a), name=node.name + ":0")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2349, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
TypeError: in method 'TF_OperationGetAttrValueProto', argument 2 of type 'char const *'

**Comment by pengwa** [comment]
the error happens when we called TF api to get attribute, my guess is that we passed the attribute name, that is not parsed correctly by python2. I filed an issue before https://github.com/onnx/tensorflow-onnx/issues/60. 

I think using python3 would help get what you want.

**Comment by parth1595** [comment]
@pengwa Done. It was the error of python2
