### ISSUE TITLE
convert.from_keras fails with default parameters

### ISSUE THREAD

**Issue by HalfVoxel** [onnx/tensorflow-onnx#1377]
**Describe the bug**
Calling `tf2onnx.convert.from_keras(model)` throws an exception

```
Traceback (most recent call last):
  File "/home/arong/projects/embark/cog/hive-ml/hive/entry_points/model_runner.py", line 32, in main
    executor.run()
  File "/home/arong/projects/embark/cog/hive-ml/hive/model_executor.py", line 293, in run
    self._experiment.run(shutdown_signal=Signal(self._should_stop))
  File "/home/arong/projects/embark/cog/polytopia/polytopia/engine/hive/experiment_wrapper.py", line 203, in run
    return self._run(shutdown_signal=shutdown_signal)
  File "/home/arong/projects/embark/cog/polytopia/polytopia/protocols/hive/nstep_protocol.py", line 142, in fit_proxy
    fit(handler, data_loader, [], total_epochs, shutdown_signal)
  File "/home/arong/projects/embark/cog/embarkrl/embarkrl/train.py", line 69, in fit
    raise ex
  File "/home/arong/projects/embark/cog/embarkrl/embarkrl/train.py", line 40, in fit
    cb_handler.on_waiting_for_data()
  File "/home/arong/projects/embark/cog/embarkrl/embarkrl/tensorflow/handler.py", line 50, in on_waiting_for_data
    self.exported_model_storage.process_pending_exports()
  File "/home/arong/projects/embark/cog/embarkrl/embarkrl/checkpoints/checkpoint_manager.py", line 61, in process_pending_exports
    a = tf2onnx.convert.from_keras(self.model)
  File "/home/arong/miniconda3/envs/cog/lib/python3.7/site-packages/tf2onnx/convert.py", line 310, in from_keras
    concrete_func = function.get_concrete_function(*input_signature)
TypeError: get_concrete_function() argument after * must be an iterable, not NoneType
```

The default value for the `input_signature` parameter to `from_keras` is None, but that will cause the method to throw an exception because it tries to effectively expand `*None`.

**Urgency**
None. It would be nice to be able to use the new api though.

**System information**
- Linux Ubuntu 20.04
- Tensorflow Version: 2.3.1
- Python version: 2.7

**To Reproduce**
Call

```python
tf2onnx.convert.from_keras(model)
```

with a valid keras model.

**Expected behavior**
There is no exception thrown

**Comment by guschmue** [comment]
fair, I can add a check.

**Comment by guschmue** [comment]
Initially I thought we could run without input signature but than we'd need to allow you to pass a signature number which is hard to pick for in-memory models so we ended up enforceing that input signature is passed in.

**Comment by benquan** [comment]
This is now working (at least in my case)
`tf2onnx.convert.from_keras(model)`
