### ISSUE TITLE
value "name: "tf_data_structured_function_wrapper_PhyAMdDq5iE" " is not valid attribute data type.

### ISSUE THREAD

**Issue by ZhangZhiHao233** [onnx/tensorflow-onnx#1395]
2021-03-15 07:43:33,925 - INFO - Using tensorflow=1.12.0, onnx=1.8.1, tf2onnx=1.8.3/0fbdb5
2021-03-15 07:43:33,925 - INFO - Using opset <onnx, 13>
2021-03-15 07:43:33,963 - INFO - Computed 0 values for constant folding
2021-03-15 07:43:34,147 - ERROR - pass1 convert failed for name: "GeneratorDataset"
op: "GeneratorDataset"
input: "arg0:0"
attr {
  key: "Tfinalize_func_args"
  value {
    list {
    }
  }
}
attr {
  key: "Tinit_func_args"
  value {
    list {
      type: DT_INT32
    }
  }
}
attr {
  key: "Tnext_func_args"
  value {
    list {
    }
  }
}
attr {
  key: "finalize_func"
  value {
    func {
      name: "tf_data_structured_function_wrapper_PhyAMdDq5iE"
    }
  }
}
attr {
  key: "init_func"
  value {
    func {
      name: "tf_data_structured_function_wrapper_Qqhv6y79aq8"
    }
  }
}
attr {
  key: "next_func"
  value {
    func {
      name: "tf_data_structured_function_wrapper_AGvjOa56HCs"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_INT32
      type: DT_INT32
      type: DT_STRING
    }
  }
}
, ex=value "name: "tf_data_structured_function_wrapper_PhyAMdDq5iE"
" is not valid attribute data type.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 233, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 211, in main
    dequantize=args.dequantize)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 458, in process_tf_graph
    ordered_func = resolve_functions(tf_graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_loader.py", line 596, in resolve_functions
    _, _, _, _, _, tfunctions = tflist_to_onnx(func, {})
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_utils.py", line 412, in tflist_to_onnx
    onnx_node = helper.make_node(node_type, input_names, output_names, name=node.name, **attr)
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 111, in make_node
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 111, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 395, in make_attribute
    'value "{}" is not valid attribute data type.'.format(value))
TypeError: value "name: "tf_data_structured_function_wrapper_PhyAMdDq5iE"
" is not valid attribute data type.

**Comment by TomWildenhain-Microsoft** [comment]
This model contains the GeneratorDataset op, which we cannot yet convert.  Is it possible to remove this op from the model?  Seems like a strange op to include in an inference graph.

**Comment by guschmue** [comment]
I assume this is resolved.
