### ISSUE TITLE
Test script for validating the pre-trained TensorFlow models fails on onnxruntime

### ISSUE THREAD

**Issue by calvinmccarter-at-lightmatter** [onnx/tensorflow-onnx#1407]
**Describe the bug**
After being installed from source, it fails to validate the pre-trained TensorFlow models using `tests/run_pretrained_models.py`. While running all the models in TF succeeds, they all fail on the ONNX runtime (`RESULT: 21 failed of 21, backend=onnxruntime`). All models have the following error in to_onnx: 

```TypeError: process_tf_graph() got an unexpected keyword argument 'tensors_to_rename'```

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020
- Tensorflow Version: 2.4.1
- Python version: Python 3.6.12 :: Anaconda, Inc.

**To Reproduce**
After cloning, I installed and tried to validate the pre-trained TensorFlow models.
$ python setup.py test
$ python tests/run_pretrained_models.py

**Screenshots**
2021-03-17 09:46:22,938 - INFO - Running benchtf-fc
2021-03-17 09:46:22,938 - INFO - Load model from /home/calvin/sandbox/tensorflow-onnx/tests/models/fc-layers/frozen.pb
2021-03-17 09:46:23,014 - INFO - Running TF
2021-03-17 09:46:23,028 - INFO - TensorFlow OK
2021-03-17 09:46:23,028 - ERROR - To_ONNX FAIL
Traceback (most recent call last):
  File "tests/run_pretrained_models.py", line 514, in run_test
    tensors_to_rename=to_rename)
  File "tests/run_pretrained_models.py", line 313, in to_onnx
    tensors_to_rename=tensors_to_rename)
TypeError: process_tf_graph() got an unexpected keyword argument 'tensors_to_rename'

**Comment by calvinmccarter-at-lightmatter** [comment]
Indeed! Uninstalling from pip and then reinstalling with setup.py worked -- thanks!
