### ISSUE TITLE
Memory and timing issue related to operation  tf.math.unsorted_segment_sum

### ISSUE THREAD

**Issue by charlinergr** [onnx/tensorflow-onnx#1455]
Hi!

Describe the bug
I'm using a Graph Neural Network model from the deepmind's Graph-Nets library, based on Sonnet. I success to convert the model in <.onnx>. Then, I load it to make some inference with python on a CPU (which is the host of my GPU). What I can see is:

same performances on the inference than expected (which is great)
Quite long (25-30 minutes) to deals with one graph
costing in CPU ressources : ~1 TiB of memory is taken
System information

ONNX Runtime installed from (source or binary): pip
ONNX Runtime version: 1.7.0
Python version: 3.6
GPU model and memory: RTX 8000 but run on its host (~1 TiB)
Expected behavior
I expect the inference time to be at most around 10 minutes. I'm more concerned about memory consumption (which I was expected to be around 10 GB at most).

Additional context
I try the : "enable_cpu_mem_arena" and "enable_mem_pattern" which did not works.
I profile the session and I can see that an operation "OneHot" is most likely the cause of the problem. I did not understand where this operation happen in my model (Interaction Network of https://github.com/deepmind/graph_nets/blob/master/graph_nets/modules.py).
In the model, we need the operation tf.math.unsorted_segment_sum on num_segments>100 000. If I remove this operation then the memory as well as the timing issue disappear.

Is a solution to be able to use  tf.math.unsorted_segment_sum exist ? This operation is really important is the model used here.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @charlinergr, the unsorted segment sum op doesn't exist in the ONNX spec so I had to hack it together by composing some ops (including OneHot).  As you mentioned, the implementation is not memory efficient at all (especially when the number of segments is large).  It should be possible to make a more efficient implementation, provided that most of the segments have similar sizes.  Can you upload a .npy file for the segment id tensor?  Based on its value distribution, I'll see if I can make a more efficient implementation.

**Comment by charlinergr** [comment]
Hi @TomWildenhain-Microsoft ! Thanks for the reply !

I create an example of our use of  tf.math.unsorted_segment_sum.

It take 3 arguments:
*The data are the embeddings of each edges of a graph. The number of edges depends of the input data. For now it it less than 2 millions edges (1.1 millions edges on average)
* num_segments are the ids of the source node of the edges
* num_segments is the number of node (less than 200k, 100k on average)

I attached a file (.npz) containing this 3 informations (it is huge so I put it in a tar file ). The file is available here : https://gitlab.com/Chrougier/reduce_file

The code using the TF function can be seen at https://github.com/deepmind/graph_nets/blob/64771dff0d74ca8e77b1f1dcd5a7d26634356d61/graph_nets/blocks.py#L250

 Thanks

**Comment by TomWildenhain-Microsoft** [comment]
I made a new implementation that should be better: #1463 
Try it out and let me know if it meets your needs.

**Comment by charlinergr** [comment]
Hi @TomWildenhain-Microsoft ! 

Thank you for the new implementation. It indeed help a lot the situation: now the memory need is around 20 GB and the timing around 110 s (CPU single core).
To be more specific, half of the time is spend on the unsorted segment operation. I provide the profiling file in json format (change to .txt to be able to upload it).
[onnxruntime_profile__2021-04-21_11-12-11.txt](https://github.com/onnx/tensorflow-onnx/files/6350447/onnxruntime_profile__2021-04-21_11-12-11.txt)

Moreover, I don't know if it is linked to the situation here or to our complex model (or even because I used the master version), but there is a bug during graph optimisation:
`Failed to apply merge_duplication
Traceback (most recent call last):
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/__init__.py", line 59, in optimize_graph
    graph = opt.optimize(current) or graph
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 29, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 34, in _optimize_at_current_graph_level
    self._merge_duplicated_nodes(graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 47, in _merge_duplicated_nodes
    self._del_nodes_if_duplicated(nodes_group, graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 75, in _del_nodes_if_duplicated
    self._merge_nodes_that_are_duplicated(nodes_to_process, graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 106, in _merge_nodes_that_are_duplicated
    graph.remove_node(node_to_delete.name)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/graph.py", line 694, in remove_node
    del self._output_to_node_name[op_output]
KeyError: ''
Failed to apply merge_duplication
Traceback (most recent call last):
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/__init__.py", line 59, in optimize_graph
    graph = opt.optimize(current) or graph
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 29, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 34, in _optimize_at_current_graph_level
    self._merge_duplicated_nodes(graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 47, in _merge_duplicated_nodes
    self._del_nodes_if_duplicated(nodes_group, graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 75, in _del_nodes_if_duplicated
    self._merge_nodes_that_are_duplicated(nodes_to_process, graph)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/optimizer/merge_duplicated_nodes_optimizer.py", line 106, in _merge_nodes_that_are_duplicated
    graph.remove_node(node_to_delete.name)
  File "/sps/l2it/crougier/conda/envs/inference_TF2.4/lib/python3.7/site-packages/tf2onnx/graph.py", line 694, in remove_node
    del self._output_to_node_name[op_output]
KeyError: ''
`

I dumped the model using `tf2onnx.convert.from_function`.

**Comment by TomWildenhain-Microsoft** [comment]
#1467 should fix the bug you mentioned.  How does the overall runtime compare to TF now?  It looks like 50% of the time is in the ReduceSum which should be significantly faster in the next ORT release (they are making some optimizations).  I might be able to do 1 more quick fix to make it better on the converter side.

**Comment by charlinergr** [comment]
Hi @TomWildenhain-Microsoft !

Thank you for the fix. It doesn't change the overall runtime.
[onnxruntime_profile__2021-04-22_11-31-12.txt](https://github.com/onnx/tensorflow-onnx/files/6357219/onnxruntime_profile__2021-04-22_11-31-12.txt)

Yes 50% of the time is in the ReduceSum.

**Comment by TomWildenhain-Microsoft** [comment]
You said the ONNX runtime is 110 secs.  What is the TF runtime?

**Comment by charlinergr** [comment]
Oh sorry.

TF runtime is ~35 secondes.

**Comment by TomWildenhain-Microsoft** [comment]
Just to make sure, can you try the ort-nightly build and see if it is faster?
`pip uninstall onnxruntime`
`pip install -i https://test.pypi.org/simple/ ort-nightly`

It might not be yet, but when we merge the ReduceSum improvements it should be.  Unfortunately those got delayed.  What latency would be acceptable for you?  If we are lucky I think we can get down to 60 seconds, but anything less than that will probably require implementing SegmentSum as a custom op or adding it to the onnx spec:

https://github.com/microsoft/ort-customops

The problem is onnx only deals with dense tensors.  One other thing you could try, the implementation I did has running time proportional to number of segments * max segment size.  Your data has a max segment size of about 200 and an average segment size of about 10.  We should be able to get it 10 times faster or so by evening out that distribution.  Split the segment sum it two: one for segments with >= 20 elements (twice the average) and one for the rest.  It will require a lot of ops but might actually be much faster in ORT.

![image](https://user-images.githubusercontent.com/67606533/115780711-78f27480-a387-11eb-9e9d-e55981b4ba00.png)

**Comment by guschmue** [comment]
assume this is resolved.
