### ISSUE TITLE
Convert LookupTableFindV2 error

### ISSUE THREAD

**Issue by sneaxiy** [onnx/tensorflow-onnx#1485]
I tried to convert a TensorFlow SavedModel to ONNX format, but converting `LookupTableFindV2` failed.

```
$ python -m tf2onnx.convert --saved-model . --output model.onnx --opset 14 --custom-ops StringSplitV2:ai.onnx.contrib
/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-04-28 16:01:00,521 - WARNING - From /Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-04-28 16:01:00,535 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-04-28 16:01:02,787 - INFO - Using tensorflow=1.15.0, onnx=1.9.0, tf2onnx=1.8.4/cd55bf
2021-04-28 16:01:02,787 - INFO - Using opset <onnx, 14>
2021-04-28 16:01:03,628 - INFO - Computed 77 values for constant folding
2021-04-28 16:01:06,327 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/embeddings/word_embeddings/read
2021-04-28 16:01:06,476 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/embeddings/token_type_embeddings/read
2021-04-28 16:01:06,476 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/embeddings/position_embeddings/read
2021-04-28 16:01:06,477 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/embeddings/LayerNorm/beta/read
2021-04-28 16:01:06,478 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/embeddings/LayerNorm/gamma/read
2021-04-28 16:01:06,478 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/self/query/kernel/read
2021-04-28 16:01:06,479 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/self/query/bias/read
2021-04-28 16:01:06,479 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/self/key/kernel/read
2021-04-28 16:01:06,481 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/self/key/bias/read
2021-04-28 16:01:06,481 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/self/value/kernel/read
2021-04-28 16:01:06,482 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/self/value/bias/read
2021-04-28 16:01:06,482 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/output/dense/kernel/read
2021-04-28 16:01:06,484 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/output/dense/bias/read
2021-04-28 16:01:06,484 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/output/LayerNorm/beta/read
2021-04-28 16:01:06,484 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/attention/output/LayerNorm/gamma/read
2021-04-28 16:01:06,484 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/intermediate/dense/kernel/read
2021-04-28 16:01:06,499 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/intermediate/dense/bias/read
2021-04-28 16:01:06,500 - INFO - folding node using tf type=Sqrt, name=input_embed_bert/bert/encoder/layer_0/intermediate/dense/Sqrt
2021-04-28 16:01:06,500 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/output/dense/kernel/read
2021-04-28 16:01:06,515 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/output/dense/bias/read
2021-04-28 16:01:06,515 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/output/LayerNorm/beta/read
2021-04-28 16:01:06,515 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_0/output/LayerNorm/gamma/read
2021-04-28 16:01:06,516 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/self/query/kernel/read
2021-04-28 16:01:06,517 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/self/query/bias/read
2021-04-28 16:01:06,517 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/self/key/kernel/read
2021-04-28 16:01:06,520 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/self/key/bias/read
2021-04-28 16:01:06,520 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/self/value/kernel/read
2021-04-28 16:01:06,523 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/self/value/bias/read
2021-04-28 16:01:06,523 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/output/dense/kernel/read
2021-04-28 16:01:06,525 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/output/dense/bias/read
2021-04-28 16:01:06,526 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/output/LayerNorm/beta/read
2021-04-28 16:01:06,526 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/attention/output/LayerNorm/gamma/read
2021-04-28 16:01:06,526 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/intermediate/dense/kernel/read
2021-04-28 16:01:06,539 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/intermediate/dense/bias/read
2021-04-28 16:01:06,539 - INFO - folding node using tf type=Sqrt, name=input_embed_bert/bert/encoder/layer_1/intermediate/dense/Sqrt
2021-04-28 16:01:06,539 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/output/dense/kernel/read
2021-04-28 16:01:06,552 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/output/dense/bias/read
2021-04-28 16:01:06,552 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/output/LayerNorm/beta/read
2021-04-28 16:01:06,553 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_1/output/LayerNorm/gamma/read
2021-04-28 16:01:06,553 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/self/query/kernel/read
2021-04-28 16:01:06,555 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/self/query/bias/read
2021-04-28 16:01:06,555 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/self/key/kernel/read
2021-04-28 16:01:06,558 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/self/key/bias/read
2021-04-28 16:01:06,558 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/self/value/kernel/read
2021-04-28 16:01:06,561 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/self/value/bias/read
2021-04-28 16:01:06,561 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/output/dense/kernel/read
2021-04-28 16:01:06,563 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/output/dense/bias/read
2021-04-28 16:01:06,564 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/output/LayerNorm/beta/read
2021-04-28 16:01:06,564 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/attention/output/LayerNorm/gamma/read
2021-04-28 16:01:06,564 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/intermediate/dense/kernel/read
2021-04-28 16:01:06,576 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/intermediate/dense/bias/read
2021-04-28 16:01:06,576 - INFO - folding node using tf type=Sqrt, name=input_embed_bert/bert/encoder/layer_2/intermediate/dense/Sqrt
2021-04-28 16:01:06,577 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/output/dense/kernel/read
2021-04-28 16:01:06,589 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/output/dense/bias/read
2021-04-28 16:01:06,590 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/output/LayerNorm/beta/read
2021-04-28 16:01:06,590 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_2/output/LayerNorm/gamma/read
2021-04-28 16:01:06,590 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/self/query/kernel/read
2021-04-28 16:01:06,592 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/self/query/bias/read
2021-04-28 16:01:06,593 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/self/key/kernel/read
2021-04-28 16:01:06,595 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/self/key/bias/read
2021-04-28 16:01:06,595 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/self/value/kernel/read
2021-04-28 16:01:06,598 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/self/value/bias/read
2021-04-28 16:01:06,598 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/output/dense/kernel/read
2021-04-28 16:01:06,601 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/output/dense/bias/read
2021-04-28 16:01:06,601 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/output/LayerNorm/beta/read
2021-04-28 16:01:06,601 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/attention/output/LayerNorm/gamma/read
2021-04-28 16:01:06,601 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/intermediate/dense/kernel/read
2021-04-28 16:01:06,614 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/intermediate/dense/bias/read
2021-04-28 16:01:06,614 - INFO - folding node using tf type=Sqrt, name=input_embed_bert/bert/encoder/layer_3/intermediate/dense/Sqrt
2021-04-28 16:01:06,614 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/output/dense/kernel/read
2021-04-28 16:01:06,627 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/output/dense/bias/read
2021-04-28 16:01:06,627 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/output/LayerNorm/beta/read
2021-04-28 16:01:06,627 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/encoder/layer_3/output/LayerNorm/gamma/read
2021-04-28 16:01:06,627 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/pooler/dense/kernel/read
2021-04-28 16:01:06,630 - INFO - folding node using tf type=Identity, name=input_embed_bert/bert/pooler/dense/bias/read
2021-04-28 16:01:06,630 - INFO - folding node using tf type=Identity, name=output_weights/read
2021-04-28 16:01:06,630 - INFO - folding node using tf type=Identity, name=output_bias/read
2021-04-28 16:01:06,781 - ERROR - Failed to convert node 'hash_table_Lookup' (fct=<bound method LookupTableFind.version_8 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableFind'>>)
'OP=LookupTableFindV2\nName=hash_table_Lookup\nInputs:\n\thash_table:0=HashTableV2, [], 7\n\tSparseToDense:0=ScatterND, [-1, -1], 8\n\tConst:0=Const, [], 6\nOutpus:\n\thash_table_Lookup:0=[-1, -1], 6'
Traceback (most recent call last):
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 294, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 36, in version_8
    shared_name, node.name)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/utils.py", line 220, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Initialized table b'' for node hash_table_Lookup not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/convert.py", line 467, in <module>
    main()
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/convert.py", line 256, in main
    output_path=args.output)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/convert.py", line 153, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 535, in process_tf_graph
    output_names, initialized_tables, outputs_to_values, outputs_to_dtypes, op_cnt, attr_cnt)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 637, in process_parsed_graph
    raise exceptions[0]
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 294, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 36, in version_8
    shared_name, node.name)
  File "/Users/zengjinle/Desktop/TEST/.test_env/lib/python3.7/site-packages/tf2onnx/utils.py", line 220, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Initialized table b'' for node hash_table_Lookup not found.
```

Could you please help me to solve this problem?

Another question: `StringSplitV2` is not supported in the default domain of ONNX, so I used the domain `ai.onnx.contrib` to convert this op to ONNX format. My question is that is this `StringSplitV2` op would be supported by TensorRT when loading ONNX model?

P.S.: I am pretty sure that my SavedModel file is valid for TensorFlow, because I have verified that it can be loaded by TensorFlow API for prediction.

**Comment by TomWildenhain-Microsoft** [comment]
It seems like the shared_name for this table is empty string, which is a little strange.  Can you upload the model?  To use StringSplitV2, you need to use onnxruntime extensions here: https://github.com/microsoft/onnxruntime-extensions

TensorRT can't run the StringSplitV2 op as far as I know, but onnxruntime does have a tensorflow execution provider.  If you use it along with onnxruntime-extensions, you should theoretically get similar performance to TensorRT.  The string ops will happen on CPU, but the other tensor ops will be forwarded to TensorRT.

If you really want to use TensorRT, one option is to "cut" the model to only include the tensor ops, not the string ops.  To cut the model, use the `--inputs` flag and specify the inputs you want the model to have.

**Comment by guschmue** [comment]
I assume this is resolved.

**Comment by Agoniii** [comment]
Hi @TomWildenhain-Microsoft I met the same error. Could you give me some suggestion?
Here is my code.
```
import tensorflow as tf
import tf2onnx

with tf.Session() as sess:
    #init = tf.compat.v1.lookup.KeyValueTensorInitializer(['a', 'b'], [1, 2])
    keys_tensor = tf.constant([1, 2], name="input_keys")
    vals_tensor = tf.constant(["a", "b"], name="input_vals")
    init = tf.contrib.lookup.KeyValueTensorInitializer(keys_tensor, vals_tensor)
    table = tf.contrib.lookup.HashTable(init, default_value="z", name="TempHashTable")
    result = table.lookup(tf.constant([1, 5]))
    table.init.run()
    result = tf.identity(result, name="output")

    print(sess.run(result))

    # write pb model
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
       sess,
       sess.graph_def,
       ["output"])
    sess.close()
    tf.train.write_graph(frozen_graph_def, '', "model.pb", as_text=False)

    # write onnx model
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, input_names=["input_keys:0", "input_vals:0"], output_names=["output:0"], opset=13)
    model_proto = onnx_graph.make_model("test")
    with open("model.onnx", "wb") as f:
        f.write(model_proto.SerializeToString())
```
The error is
```
Failed to convert node 'TempHashTable_Lookup/LookupTableFindV2' (fct=<bound method LookupTableFind.version_8 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableFind'>>)
'OP=LookupTableFindV2\nName=TempHashTable_Lookup/LookupTableFindV2\nInputs:\n\tTempHashTable:0=HashTableV2, [], 7\n\tConst_1:0=Const, [2], 6\n\tConst:0=Const, [], 8\nOutpus:\n\tTempHashTable_Lookup/LookupTableFindV2:0=[2], 8'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/custom_opsets/onnx_ml.py", line 35, in version_8
    utils.make_sure(shared_name in initialized_tables, "Initialized table %s for node %s not found.",
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Initialized table b'' for node TempHashTable_Lookup/LookupTableFindV2 not found.
Traceback (most recent call last):
  File "hashtable_test.py", line 26, in <module>
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, input_names=["input_keys:0", "input_vals:0"], output_names=["output:0"], opset=13)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 438, in process_tf_graph
    g = process_graphs(main_g, subgraphs, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 490, in process_graphs
    g = process_parsed_graph(main_g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 600, in process_parsed_graph
    raise exceptions[0]
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/custom_opsets/onnx_ml.py", line 35, in version_8
    utils.make_sure(shared_name in initialized_tables, "Initialized table %s for node %s not found.",
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Initialized table b'' for node TempHashTable_Lookup/LookupTableFindV2 not found.
```
