### ISSUE TITLE
Can not convert TF model that uses feature_column API

### ISSUE THREAD

**Issue by bappy043** [onnx/tensorflow-onnx#1500]
While trying to convert a TF model that uses `feature_column` API, I am getting the following error
```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-16-ec390fb69aa3> in <module>()
      3 output_path = model.name + ".onnx"
      4 
----> 5 model_proto, _ = tf2onnx.convert.from_keras(model, input_signature=spec, opset=13, output_path=output_path)
      6 output_names = [n.name for n in model_proto.graph.output]

7 frames
/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py in from_keras(model, input_signature, opset, custom_ops, custom_op_handlers, custom_rewriter, inputs_as_nchw, extra_opset, shape_override, target, large_model, output_path)
    346 
    347     with tf.device("/cpu:0"):
--> 348         frozen_graph = tf_loader.from_function(concrete_func, input_names, output_names, large_model=large_model)
    349         model_proto, external_tensor_storage = _convert_common(
    350             frozen_graph,

/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py in from_function(func, input_names, output_names, large_model)
    161             frozen_func = convert_variables_to_constants_v2(func, lower_control_flow=False)
    162         else:
--> 163             frozen_func = convert_variables_to_constants_v2(func, lower_control_flow=False, aggressive_inlining=True)
    164     except ValueError as e:
    165         if "incompatible with expected resource" in str(e):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/convert_to_constants.py in convert_variables_to_constants_v2(func, lower_control_flow, aggressive_inlining)
   1069       func=func,
   1070       lower_control_flow=lower_control_flow,
-> 1071       aggressive_inlining=aggressive_inlining)
   1072 
   1073   output_graph_def, converted_input_indices = _replace_variables_by_constants(

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/convert_to_constants.py in __init__(self, func, lower_control_flow, aggressive_inlining, variable_names_allowlist, variable_names_denylist)
    804         variable_names_allowlist=variable_names_allowlist,
    805         variable_names_denylist=variable_names_denylist)
--> 806     self._build_tensor_data()
    807 
    808   def _build_tensor_data(self):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/convert_to_constants.py in _build_tensor_data(self)
    823         data = map_index_to_variable[idx].numpy()
    824       else:
--> 825         data = val_tensor.numpy()
    826       self._tensor_data[tensor_name] = _TensorData(
    827           numpy=data,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in numpy(self)
   1069     """
   1070     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1071     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1072     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1073 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1037       return self._numpy_internal()
   1038     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1039       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1040 
   1041   @property

/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**To Reproduce**
TF saved model: [model.zip](https://github.com/onnx/tensorflow-onnx/files/6425057/model.zip)
Colab link: https://colab.research.google.com/drive/19LmJyL8PpJKbmMZVQJOmc_1-Rdl2cEVo?usp=sharing

```
import tensorflow as tf
import tf2onnx

def parseElem(elemDict):
    label = elemDict.pop("class")
    return (elemDict, label)

ds_train = tf.data.Dataset.from_tensor_slices({"conf": [[1.0], [0.9], [0.2], [0.4]],
                                               "type": [["a"], ["b"], ["c"], ["d"]],
                                               "class": [[0], [1], [2], [3]]}
  ).map(lambda elem: parseElem(elem)
  ).batch(2)

featCols = [tf.feature_column.numeric_column("conf", dtype=tf.float32),
            tf.feature_column.indicator_column(
                tf.feature_column.categorical_column_with_vocabulary_list("type", vocabulary_list=["a", "b", "c"], num_oov_buckets=1)
            )]
featureLayer = tf.keras.layers.DenseFeatures(featCols)

inputDict = {}
inputDict["conf"] = tf.keras.Input(name="conf", shape=(1,), dtype=tf.float32)
inputDict["type"] = tf.keras.Input(name="type", shape=(1,), dtype=tf.string)

inputs = [input for input in inputDict.values()]
standardFeatures = featureLayer(inputDict)
hidden1 = tf.keras.layers.Dense(512, activation='relu')(standardFeatures)
output = tf.keras.layers.Dense(10, activation='softmax')(hidden1)
model = tf.keras.Model(inputs=inputs, outputs=output)

model.compile(optimizer='adam',
              loss=tf.keras.losses.mean_squared_error,
              metrics=[tf.keras.metrics.sparse_categorical_crossentropy])

model.fit(ds_train)

spec = (tf.TensorSpec((None, 1), dtype=tf.float32, name="conf"),
        tf.TensorSpec((None, 1), tf.string, name="type"))
output_path = model.name + ".onnx"

model_proto, _ = tf2onnx.convert.from_keras(model, input_signature=spec, opset=13, output_path=output_path)
```

**Additional context**
I also tried to convert using the command line option but got the following error
```
!python -m tf2onnx.convert --opset 13 \
    --saved-model {outputDirTF} \
    --output {output_path}
```
```
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-05-05 02:05:04,337 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-05-05 02:05:04,627 - INFO - Signatures found in model: [serving_default].
2021-05-05 02:05:04,627 - WARNING - '--signature_def' not specified, using first signature: serving_default
2021-05-05 02:05:04,627 - INFO - Output names: ['dense_3']
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py:603: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-05-05 02:05:04,710 - WARNING - From /usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py:603: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-05-05 02:05:04,743 - INFO - Using tensorflow=2.4.1, onnx=1.9.0, tf2onnx=1.9.0/9c7b56
2021-05-05 02:05:04,743 - INFO - Using opset <onnx, 13>
2021-05-05 02:05:04,744 - WARNING - Cannot infer shape for StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/None_Lookup/LookupTableFindV2: StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/None_Lookup/LookupTableFindV2:0
2021-05-05 02:05:04,744 - WARNING - Cannot infer shape for StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/NotEqual: StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/NotEqual:0
2021-05-05 02:05:04,744 - WARNING - Cannot infer shape for StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/SelectV2: StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/SelectV2:0
2021-05-05 02:05:04,749 - INFO - Computed 0 values for constant folding
2021-05-05 02:05:04,800 - ERROR - Tensorflow op [StatefulPartitionedCall/model_1/dense_features_1/type_indicator/None_Lookup/hash_bucket: StringToHashBucketFast] is not supported
2021-05-05 02:05:04,809 - ERROR - Unsupported ops: Counter({'StringToHashBucketFast': 1})
2021-05-05 02:05:04,813 - INFO - Optimizing ONNX model
2021-05-05 02:05:05,012 - INFO - After optimization: Cast -5 (7->2), Concat -2 (4->2), Const -23 (36->13), HashTableV2 -1 (1->0), Identity -7 (7->0), Shape -2 (3->1), Slice -2 (2->0), Squeeze -2 (2->0), Unsqueeze -7 (7->0)
2021-05-05 02:05:05,015 - INFO - 
2021-05-05 02:05:05,015 - INFO - Successfully converted TensorFlow model functional_savedModel to ONNX
2021-05-05 02:05:05,015 - INFO - Model inputs: ['conf:0', 'type:0']
2021-05-05 02:05:05,015 - INFO - Model outputs: ['dense_3']
2021-05-05 02:05:05,015 - INFO - ONNX model is saved at model_12.onnx
```

I found this issue is also mentioned here: https://github.com/onnx/tensorflow-onnx/issues/1158. However,  could not figure out the fix.

**Comment by TomWildenhain-Microsoft** [comment]
StringToHashBucketFast requires the custom op framework (onnx-extensions) since ONNX doesn't have those ops:
https://github.com/microsoft/onnxruntime-extensions
Add this flag during conversion: `--extra_opset ai.onnx.contrib:1`

Then follow this tutorial: https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/tf2onnx_custom_ops_tutorial.ipynb

Let me know if that works.

**Comment by bappy043** [comment]
Thanks, @TomWildenhain-Microsoft for the suggestion. I tried to install onnx-extensions using `pip install -i https://test.pypi.org/simple/ onnxruntime-customops` but it didn't succeed. Do I need to clone the repo and install manually?

**Comment by TomWildenhain-Microsoft** [comment]
Yes, unfortunately we don't have a test release for Linux yet.  You can use Windows/Mac or build from source.  Instructions here: https://github.com/microsoft/onnxruntime-extensions#build-and-development

**Comment by bappy043** [comment]
@TomWildenhain-Microsoft thanks, I tried to build from source in google colab but got some error, however, in my Mac it completed successfully. Now I can download the onnx model from google colab run on my Mac using Python ONNX Runtime. 

I am now planning to run the model in Java ONNX Runtime. Is it possible to run an onnx model with custom ops in JAVA. I think I need to have the `onnxruntime_customops` library in java also.

**Comment by TomWildenhain-Microsoft** [comment]
It should be possible.  I think you'll just need to get the .dll location and pass its location into session options in the Java ORT.

**Comment by bappy043** [comment]
After running the `bash ./build.sh` command, I see the following files/folders generated under the directory `out/`
```
$ ls -l out/
total 0
Darwin

$ ls -l out/Darwin/
total 32128
CMakeCache.txt
CMakeFiles
CPackConfig.cmake
CPackSourceConfig.cmake
Makefile
_deps
cmake_install.cmake
libortcustomops.dylib
libortcustomops_static.a

$ ls -lR out/Darwin/ | grep dll
hha.dll
itcc.dll
itircl.dll
itss.dll
```
Do you know what are the .dll files I need to use. 

Also, I have found a tutorial for Java ORT here: https://www.onnxruntime.ai/docs/tutorials/mnist_java.html. Is there any guide on how to pass .dll locations into session options.

**Comment by TomWildenhain-Microsoft** [comment]
You are not on Windows so you should look for a .so file, not a .dll.  I believe it is "ortcustomops.so".

Then register it here: https://javadoc.io/static/com.microsoft.onnxruntime/onnxruntime/1.7.0/ai/onnxruntime/OrtSession.SessionOptions.html#registerCustomOpLibrary(java.lang.String)

**Comment by TomWildenhain-Microsoft** [comment]
Awesome.  For extra opsets, use:

```python
from onnx import helper

model_proto, _ = tf2onnx.convert.from_keras(model, 
                                            input_signature=spec, 
                                            opset=13, 
                                            extra_opset=helper.make_opsetid("ai.onnx.contrib", 1),
                                            output_path=output_path)
```

**Comment by bappy043** [comment]
providing list didn't help, getting the same error `InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.`

**Comment by guschmue** [comment]
Stack trace ... the error comes from convert_variables_to_constants_v2()
```
    model_proto, _ = tf2onnx.convert.from_keras(model, input_signature=spec, opset=13, output_path=output_path)
  File "/home/gs/tensorflow-onnx/tf2onnx/convert.py", line 348, in from_keras
    frozen_graph = tf_loader.from_function(concrete_func, input_names, output_names, large_model=large_model)
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 163, in from_function
    frozen_func = convert_variables_to_constants_v2(func, lower_control_flow=False, aggressive_inlining=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1071, in convert_variables_to_constants_v2
    aggressive_inlining=aggressive_inlining)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 806, in __init__
    self._build_tensor_data()
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 825, in _build_tensor_data
    data = val_tensor.numpy()
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1071, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1039, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**Comment by TomWildenhain-Microsoft** [comment]
Ah I see.  The error has nothing to do with the extra_opset flag.  It is crashing before it even gets there.  I'll investigate.  @bappy043  the model converted from the command line works, right?

**Comment by bappy043** [comment]
Yes, it works for command line

**Comment by TomWildenhain-Microsoft** [comment]
Our saved_model loader has some special code for dealing with lookup tables.  convert.keras doesn't have it.  I'm working on finding where keras stores the lookup table info.

**Comment by TomWildenhain-Microsoft** [comment]
Try again with the latest tf2onnx from github.  #1512 should fix your issue.

**Comment by bappy043** [comment]
Thanks @TomWildenhain-Microsoft for fixing this. It is working with python now.
