### ISSUE TITLE
TF saved_model -> .onnx = ONNXRuntimeError

### ISSUE THREAD

**Issue by ulrichMarco** [onnx/tensorflow-onnx#1505]
**Describe the bug**
Cornvering a Tensorflow Saved Model to .onnx works fine but running it with returns a ONNXRuntimeError

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04 LTS
- Tensorflow Version: 2.4.1
- Python version: 3.8

**To Reproduce**
Trained a custom model and saved it in Tensorflow Saved Model Format.
Converting it with 
`python3 -m tf2onnx.convert --saved-model saved_model --output tfmodel.onnx --opset 13`
works fine but running it with onnx runtime results in 
```
Traceback (most recent call last):
  File "run_onnx_runtime.py", line 228, in <module>
    detections = sess.run([output_name], {input_name: image_data})[0]
  File "/home/marco/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(uint8))
```
Saved model and converted model available at 
https://drive.google.com/drive/folders/1GBb458uQojlS4ODLlfmgqA6stIp8LRKy?usp=sharing

**Comment by guschmue** [comment]
just tried your model and it seems fine.
If you look at the tensorflow model with ```saved_model_cli show``` - the input to the model is uint8 here and it is the same for the onnx model. If you pass in float32, onnxruntime is correctly throwing the error.
```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_tensor'] tensor_info:
        dtype: DT_UINT8
        shape: (1, -1, -1, 3)
        name: serving_default_input_tensor:0
```

**Comment by guschmue** [comment]
should add: if you use tensorflow directly it should complain the same way as onnxruntime does. If you use keras - possible it does a autocast for you so you'd not notice if your input is float32.
