### ISSUE TITLE
Support for dynamic RNNs

### ISSUE THREAD

**Issue by ryotatomioka** [onnx/tensorflow-onnx#153]
TensorFlow's dynamic RNN which is a syntactic sugar for `tf.while_loop` does seem to be supported. I tried the following:
```python
i = tf.constant(0, name="i")
c = lambda i: tf.less(i, 10)
b = lambda i: tf.add(i, 1)
while_loop = tf.while_loop(c, b, [i], name="while_loop")
with tf.Session() as sess:
    tf.global_variables_initializer().run(session=sess)
    result = sess.run(while_loop)
    print(result)
    meta_graph_def = tf.train.export_meta_graph(filename='while_loop.meta')
    with open("while_loop.pb", "wb") as f:
        f.write(meta_graph_def.graph_def.SerializeToString())
```
and
```bash
python -m tf2onnx.convert --input while_loop.pb --inputs "" --outputs while_loop/Exit:0
```
but got the following error
```
using tensorflow=1.9.0, onnx=1.3.0, opset=7
2018-10-09 11:53:46.670848: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying fold_batch_norms
2018-10-09 11:53:46.672001: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying fold_old_batch_norms
2018-10-09 11:53:46.693706: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ryotat/python3/lib/python3.5/site-packages/tf2onnx-0.0.3.0-py3.5.egg/tf2onnx/convert.py", line 110, in <module>
  File "/home/ryotat/python3/lib/python3.5/site-packages/tf2onnx-0.0.3.0-py3.5.egg/tf2onnx/convert.py", line 95, in main
  File "/home/ryotat/python3/lib/python3.5/site-packages/tf2onnx-0.0.3.0-py3.5.egg/tf2onnx/tfonnx.py", line 1627, in process_tf_graph
  File "/home/ryotat/python3/lib/python3.5/site-packages/tf2onnx-0.0.3.0-py3.5.egg/tf2onnx/tfonnx.py", line 1599, in topological_sort
  File "/home/ryotat/python3/lib/python3.5/site-packages/tf2onnx-0.0.3.0-py3.5.egg/tf2onnx/graph.py", line 430, in topological_sort
  File "/home/ryotat/python3/lib/python3.5/site-packages/tf2onnx-0.0.3.0-py3.5.egg/tf2onnx/graph.py", line 395, in _push_stack
ValueError: Graph has cycles.
```

Maybe it makes sense to support dynamic RNN with LSTM or GRU cell as special cases?

**Comment by pengwa** [comment]
current only LSTM + dynamic_rnn is supported, see https://github.com/onnx/tensorflow-onnx/blob/master/tests/test_lstm.py for supported examples.
dynamic_rnn return 2 values, specify the one of the value node instead of while_loop/Exit:0. 

and add "--fold_const" in the command.

**Comment by guschmue** [comment]
Ah, you want generic control flow support. 
onnx opset 8 should support this but we not added that support yet since we don't have a runtime that fully supports control flow to test with (yet). Its maybe a month before we can start adding support.

**Comment by ryotatomioka** [comment]
Thank you! I confirmed that basic LSTM and BiLSTM are supported. Probably the model I am trying to import contains something else in the while loop. I need to investigate a bit more
