### ISSUE TITLE
Cannot convert model with conv2d_transpose using channels_first format

### ISSUE THREAD

**Issue by csantosbh** [onnx/tensorflow-onnx#1539]
**Description**
The tool currently crashes when I try to convert a model that has a `conv2d_transpose` using the format `channels_first`:

**Tip:** This issue was introduced by 620b9528 (found via git bisect).

**Urgency**
Medium urgency, as the workaround is to convert the models to use `channels_first` format.

**System information**
- OS Platform and Distribution: Ubuntu 20.04.02 LTS
- Tensorflow Version: 2.4.1
- Python version: 3.7.10
- tf2onnx: Latest from github (2f9078e77c280dfbb5721ededeac760f6256bc7c). The issue does not happen in 1.8.5.

**Reproducing**
Using this code:
```py
import tensorflow as tf
import tensorflow.keras as keras

x=keras.layers.Input((1,4,4))
y=x
y=keras.layers.Conv2DTranspose(1,1,data_format='channels_first')(y)
model = keras.Model(x,y)
model.summary()
model.save('my_model')
```
Then:
```bash
python test.py && python -m tf2onnx.convert --saved-model my_model --output model.onnx
```

The problem does **not** happen when using the default `channels_last` format:
```py
import tensorflow as tf
import tensorflow.keras as keras

x=keras.layers.Input((4,4,1))
y=x
y=keras.layers.Conv2DTranspose(1,1,data_format='channels_last')(y)
model = keras.Model(x,y)
model.summary()
model.save('my_model')
```

**Error Message**
```
> python test.py && python -m tf2onnx.convert --saved-model my_model --output model.onnx
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 1, 4, 4)]         0
_________________________________________________________________
conv2d_transpose (Conv2DTran (None, 1, 4, 4)           2
=================================================================
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
/home/cfernandes/anaconda3/envs/ml-lab/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-05-28 11:40:37,719 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-05-28 11:40:37,774 - INFO - Signatures found in model: [serving_default].
2021-05-28 11:40:37,774 - WARNING - '--signature_def' not specified, using first signature: serving_default
2021-05-28 11:40:37,774 - INFO - Output names: ['conv2d_transpose']
WARNING:tensorflow:From /home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/tf_loader.py:628: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-05-28 11:40:37,801 - WARNING - From /home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/tf_loader.py:628: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-05-28 11:40:37,813 - INFO - Using tensorflow=2.4.1, onnx=1.9.0, tf2onnx=1.9.0/2f9078
2021-05-28 11:40:37,813 - INFO - Using opset <onnx, 9>
2021-05-28 11:40:37,814 - INFO - Computed 0 values for constant folding
2021-05-28 11:40:37,825 - ERROR - Failed to convert node 'StatefulPartitionedCall/model/conv2d_transpose/conv2d_transpose' (fct=<bound method ConvTranspose.version_1 of <class 'tf2onnx.onnx_opset.nn.ConvTranspose'>>)
'OP=ConvTranspose\nName=StatefulPartitionedCall/model/conv2d_transpose/conv2d_transpose\nInputs:\n\tStatefulPartitionedCall/model/conv2d_transpose/stack_Concat__13:0=Concat, [4], 6\n\tStatefulPartitionedCall/model/conv2d_transpose/conv2d_transpose/ReadVariableOp:0=Const, [1, 1, 1, 1], 1\n\tFunc/StatefulPartitionedCall/input/_0:0=Identity, [-1, 1, 4, 4], 1\nOutpus:\n\tStatefulPartitionedCall/model/conv2d_transpose/conv2d_transpose:0=[-1, 1, 4, 4], 1'
Traceback (most recent call last):
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/tfonnx.py", line 290, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 472, in version_1
    - new_output_shape[i])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/cfernandes/anaconda3/envs/ml-lab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cfernandes/anaconda3/envs/ml-lab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/convert.py", line 530, in <module>
    main()
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/convert.py", line 261, in main
    output_path=args.output)
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/convert.py", line 154, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/tfonnx.py", line 530, in process_tf_graph
    output_names, initialized_tables, outputs_to_values, outputs_to_dtypes, op_cnt, attr_cnt)
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/tfonnx.py", line 635, in process_parsed_graph
    raise exceptions[0]
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/tfonnx.py", line 290, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/cfernandes/workspace/foss/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 472, in version_1
    - new_output_shape[i])
IndexError: list index out of range
```

**Comment by TomWildenhain-Microsoft** [comment]
#1542 should fix the issue.

**Comment by csantosbh** [comment]
Hi Tom, I can confirm that the issue has been solved, both in the small test case and in my production code.

I can also see that the name suffixes (":0") have been dropped in the latest version, which is something I was also doing (after the model was exported). Nice!

Thanks for the quick fix, this issue can be closed.
