### ISSUE TITLE
No Op registered for Identity

### ISSUE THREAD

**Issue by marton-avrios** [onnx/tensorflow-onnx#1573]
I ran...
```
python -m tf2onnx.convert --saved-model my_model --output model.onnx --opset 13 --tag serve --signature_def serving_default
```
...and it says...
```
Successfully converted TensorFlow model my_model to ONNX
```
...but I also get messages from `onnxruntime` like...
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:OPT_to_onnx_id_0_140148320973824 : No Op registered for Identity with domain_version of 13
```
...and...
```
WARNING - Failed to apply einsum_optimizer
```
When I try to load it in Python with `onnxruntime` I get...
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:strided_slice_16 : No Op registered for Slice with domain_version of 13
```

So was the conversion succesful? Here is the full output (model dir is actually called 512, not my_model):

```
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:22,763 - WARNING - Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:22,763 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:22,763 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:22,763 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:22,763 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,311 - WARNING - Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,311 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,311 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,311 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,311 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,870 - WARNING - Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,870 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,870 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,870 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:23,870 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:28,351 - WARNING - Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:28,351 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:28,351 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:28,351 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:28,351 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:28,572 - INFO - Signatures found in model: [serving_default].
2021-06-16 12:54:28,572 - INFO - Output names: ['inputs', 'inputs_encoded', 'outputs', 'scores']
WARNING:tensorflow:Issue encountered when serializing global_step.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
2021-06-16 12:54:28,722 - WARNING - Issue encountered when serializing global_step.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
2021-06-16 12:54:28,731 - WARNING - Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:29,158 - WARNING - Unable to create a python object for variable <tf.Variable 'shared/embedding:0' shape=(32128, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:29,158 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/layer_norm/scale:0' shape=(512,) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:29,158 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/q:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:29,158 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/k:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2021-06-16 12:54:29,158 - WARNING - Unable to create a python object for variable <tf.Variable 'encoder/block_000/layer_000/SelfAttention/v:0' shape=(512, 512) dtype=bfloat16_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:From /home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/tf_loader.py:649: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-06-16 12:54:40,255 - WARNING - From /home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/tf_loader.py:649: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-06-16 12:54:46,957 - INFO - Using tensorflow=2.3.0, onnx=1.9.0, tf2onnx=1.9.0/de80f5
2021-06-16 12:54:46,957 - INFO - Using opset <onnx, 13>
2021-06-16 12:55:06,446 - INFO - Computed 6 values for constant folding
2021-06-16 12:55:42,608 - INFO - folding node using tf type=ExpandDims, name=while_loop/while/encoder/block_000/layer_000/SelfAttention/add_44/parallel_0_1/ExpandDims
2021-06-16 12:55:42,614 - INFO - folding node using tf type=ExpandDims, name=while_loop/while/encoder/block_001/layer_000/SelfAttention/add_44/parallel_0_1/ExpandDims
2021-06-16 12:55:42,619 - INFO - folding node using tf type=ExpandDims, name=while_loop/while/encoder/block_002/layer_000/SelfAttention/add_44/parallel_0_1/ExpandDims
2021-06-16 12:55:42,624 - INFO - folding node using tf type=ExpandDims, name=while_loop/while/encoder/block_003/layer_000/SelfAttention/add_44/parallel_0_1/ExpandDims
2021-06-16 12:55:42,629 - INFO - folding node using tf type=ExpandDims, name=while_loop/while/encoder/block_004/layer_000/SelfAttention/add_44/parallel_0_1/ExpandDims
2021-06-16 12:55:42,635 - INFO - folding node using tf type=ExpandDims, name=while_loop/while/encoder/block_005/layer_000/SelfAttention/add_44/parallel_0_1/ExpandDims
2021-06-16 12:55:48,455 - INFO - Optimizing ONNX model
2021-06-16 12:56:08,525 - WARNING - Failed to apply einsum_optimizer
Traceback (most recent call last):
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/__init__.py", line 62, in optimize_graph
    graph = opt.optimize(current, iteration) or graph
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1862, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1870, in _optimize_at_current_graph_level
    if op.type == "Einsum" and self._optimize_einsum(op, graph):
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1888, in _optimize_einsum
    equation, decompose=self._decompose, dtype=np.float32, opset=graph.opset)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1832, in optimize_einsum
    dtype, decompose=decompose, key=key)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1806, in build_einsum
    inst.build()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1718, in build
    inst.build()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1736, in build
    self.build_runtime()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1784, in build_runtime
    self.sess_ = InferenceSession(self.onnx_.SerializeToString())
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:OPT_to_onnx_id_0_140147939881312 : No Op registered for Identity with domain_version of 13
2021-06-16 12:56:20,373 - WARNING - Failed to apply einsum_optimizer
Traceback (most recent call last):
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/__init__.py", line 62, in optimize_graph
    graph = opt.optimize(current, iteration) or graph
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1862, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1870, in _optimize_at_current_graph_level
    if op.type == "Einsum" and self._optimize_einsum(op, graph):
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1888, in _optimize_einsum
    equation, decompose=self._decompose, dtype=np.float32, opset=graph.opset)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1832, in optimize_einsum
    dtype, decompose=decompose, key=key)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1806, in build_einsum
    inst.build()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1718, in build
    inst.build()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1736, in build
    self.build_runtime()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1784, in build_runtime
    self.sess_ = InferenceSession(self.onnx_.SerializeToString())
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:OPT_to_onnx_id_0_140148321595520 : No Op registered for Identity with domain_version of 13
2021-06-16 12:56:32,134 - WARNING - Failed to apply einsum_optimizer
Traceback (most recent call last):
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/__init__.py", line 62, in optimize_graph
    graph = opt.optimize(current, iteration) or graph
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1862, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1870, in _optimize_at_current_graph_level
    if op.type == "Einsum" and self._optimize_einsum(op, graph):
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1888, in _optimize_einsum
    equation, decompose=self._decompose, dtype=np.float32, opset=graph.opset)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1832, in optimize_einsum
    dtype, decompose=decompose, key=key)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1806, in build_einsum
    inst.build()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1718, in build
    inst.build()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1736, in build
    self.build_runtime()
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/tf2onnx/optimizer/einsum_optimizer.py", line 1784, in build_runtime
    self.sess_ = InferenceSession(self.onnx_.SerializeToString())
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/home/martongyorgy/myenv/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:OPT_to_onnx_id_0_140148320973824 : No Op registered for Identity with domain_version of 13
2021-06-16 12:56:32,175 - INFO - After optimization: Add -1 (566->565), Cast -762 (1308->546), Concat -79 (89->10), Const -1638 (2633->995), Equal -8 (51->43), GlobalMaxPool +1 (0->1), Identity -690 (690->0), Mul -4 (617->613), Neg -1 (200->199), Not -5 (110->105), ReduceMax -1 (31->30), ReduceSum -2 (113->111), Reshape -363 (522->159), Squeeze +1 (9->10), Transpose -93 (194->101), Unsqueeze -257 (663->406)
2021-06-16 12:56:33,861 - INFO - 
2021-06-16 12:56:33,861 - INFO - Successfully converted TensorFlow model 512 to ONNX
2021-06-16 12:56:33,862 - INFO - Model inputs: ['Placeholder:0', 'Placeholder_4:0', 'Placeholder_6:0', 'Placeholder_1:0', 'Placeholder_2:0', 'Placeholder_8:0', 'Placeholder_3:0', 'Placeholder_7:0', 'Placeholder_5:0']
2021-06-16 12:56:33,862 - INFO - Model outputs: ['inputs', 'inputs_encoded', 'outputs', 'scores']
2021-06-16 12:56:33,862 - INFO - ONNX model is saved at model.onnx
````

**Comment by guschmue** [comment]
So this error is a problem because we call onnxruntime during conversion which we should not.
I assume the onnxruntime you have installed does not support opset-13.
This happens in our optimizer pipeline and if one of the steps in the pipleline fails we can continue correctly, aka the conversion is ok, only the einsum optimizer fails.

@xadupre - can we find a way of not calling onnxruntime during conversion?

**Comment by xadupre** [comment]
onnxruntime is used to find the fastest letter permutation. We can replace onnxruntime by numpy.einsum, the optimized permutation may be 2,3 times slower than the one found with onnxruntime. Is that ok with you?

**Comment by guschmue** [comment]
let discuss. 
If we call onnxruntime it would need to be a soft call.
For sure we can not call it with opset-13 and would need to honor the opset from the command line.
And if onnxruntime is not installed we should maybe print a warning that we are skipping einsum optimization instead of the stack trace.

**Comment by TomWildenhain-Microsoft** [comment]
@marton-avrios as a sanity check, please do install the latest onnxruntime with opset 13 support and try again
`pip install --upgrade onnxruntime`

**Comment by marton-avrios** [comment]
Runs fine with upgraded onnxruntime but wit warnings like:
```
WARNING - Reshape__3808:0's shape is unknown, which may interfere further optimization
```.
However when trying to load it in python like this:
```
session = onnxruntime.InferenceSession(model_file)
```
I get:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Pad) Op (Pad) [ShapeInferenceError] Pads has incorrect number of values
```
If I remove padding code in savedmodel serving_input_fn when exporting to savedmodel I get messages saying that a OneHot operation could not be placed on any execution provider.

**Comment by TomWildenhain-Microsoft** [comment]
Can you please upload a copy of the zipped saved model?  Leave in the padding code.

**Comment by guschmue** [comment]
I assume this is no longer an issue. We have changed the handling of the einsum optimizer so that should no longer log the warning messages.
