### ISSUE TITLE
Conversion of TensorFlow Decision Forest (Protobuf) to ONNX Model

### ISSUE THREAD

**Issue by JulianHBuecher** [onnx/tensorflow-onnx#1593]
**Describe the bug**
Now I am trying for a while to convert my [TensorFlow Decision Forest](https://github.com/tensorflow/decision-forests) model saved as protobuf and I didn't got it done... Every time I get an error, some handler is not running in binary on my system (see log message below).
During the process I used keras2onnx as an alternative, too. But it still does not work. Is this type of model not supported or is it a mistake made by myself?
I did not find any other issue describing my problem. Hopefully you could help me here.

**System information**
- OS Platform and Distribution: WSL Linux Ubuntu 18.04 and Pop OS 21.04
- Tensorflow Version: 2.5.0
- Python version: 3.9

**To Reproduce**
For reproduction: I tried it in a Python virtual environment on Pop Os on my laptop and WSL 2 Ubuntu on my desktop pc.
Here is the link to the model I am trying to convert:
https://github.com/JulianHBuecher/Bachelor-Thesis/tree/main/ML.Proxy.Python.ModelTrainer/Data/Models/goldeneye_model

**Screenshots**
```bash
python -m tf2onnx.convert --saved-model Data/Models/goldeneye_model --opset 13 --output Data/ONNX_Models/goldeneye_model.onnx
2021-07-02 11:44:58.306038: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic libra
ry 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-02 11:44:58.306080: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do n
ot have a GPU set up on your machine.
/usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx
', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-07-02 11:44:59.010339: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic libra
ry 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-07-02 11:44:59.010376: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (
303)
2021-07-02 11:44:59.010392: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to
be running on this host (WS000252): /proc/driver/nvidia/version does not exist
2021-07-02 11:44:59.010571: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized wit
h oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:
 AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-02 11:44:59,013 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/framework/ops.py"
, line 3958, in _get_op_def
    return self._op_def_cache[type]
KeyError: 'SimpleMLLoadModelFromPathWithHandle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/saved_model/load.
py", line 905, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/saved_model/load.
py", line 133, in __init__
    function_deserialization.load_function_def_library(
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/saved_model/funct
ion_deserialization.py", line 358, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/framework/functio
n_def_to_graph.py", line 63, in function_def_to_graph
    graph_def, nested_to_flat_tensor_name = function_def_to_graph_def(
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/framework/functio
n_def_to_graph.py", line 228, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/framework/ops.py"
, line 3962, in _get_op_def
    pywrap_tf_session.TF_GraphGetOpDef(self._c_graph, compat.as_bytes(type),
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SimpleMLLoadModelFromPathWithHandle' in b
inary running on WS000252. Make sure the Op and Kernel are registered in the binary running in this process. Note that i
f you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done b
efore importing the graph, as contrib ops are lazily registered when the module is first accessed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tf2onnx/convert.py", line 488, in <
module>
    main()
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tf2onnx/convert.py", line 211, in m
ain
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tf2onnx/tf_loader.py", line 511, in
from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tf2onnx/tf_loader.py", line 418, in
_from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/saved_model/load.
py", line 869, in load
    return load_internal(export_dir, tags, options)["root"]
  File "/home/julianbuecher/ML.Proxy.Python.ModelTrainer/lib/python3.9/site-packages/tensorflow/python/saved_model/load.
py", line 908, in load_internal
    raise FileNotFoundError(
FileNotFoundError: Op type not registered 'SimpleMLLoadModelFromPathWithHandle' in binary running on WS000252. Make sure
the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph whic
h used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contri
b ops are lazily registered when the module is first accessed.
If trying to load on a different device from the computational device, consider using setting the `experimental_io_devi
ce` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.
```

**Comment by TomWildenhain-Microsoft** [comment]
Hi @JulianHBuecher, it seems like the random forest algorithms within the model are entirely outside the ONNX opset (https://github.com/onnx/onnx/blob/master/docs/Operators.md).  You could try to implement them as custom ops and use onnx for the rest of the model, but given that the model seems to entirely consist of unsupported ops from my quick glance at it, I don't see much point.

![image](https://user-images.githubusercontent.com/67606533/124371718-50191600-dc39-11eb-80a9-55b4b72b14c8.png)

What is your motivation for converting to ONNX?  Are you trying to accelerate inference?

**Comment by JulianHBuecher** [comment]
Hello @TomWildenhain-Microsoft, thank you for your reply. I am new to ML and the different models and formats converting them. My intention is/was to convert the protobuf to ONNX because of compatibility.
In my current project I am using ML.NET and the ONNX models seems to be the best model format to interchange in the .NET world and its cross-platform apps.
So I thought I give it a try and found your libraries for conversion. Due to the fact this type of model is a relatively new implementation, I suspect the used operations in it could be the reason for incompatibility. 
Thank you for your help 👍 As far as I know there is a NuGet-package which supports protobuf models too.
