### ISSUE TITLE
 failed:Fatal error: StringSplit is not a registered function/op

### ISSUE THREAD

**Issue by sreehasa** [onnx/tensorflow-onnx#1609]
**I followed the tutorial on text  classification  in tf.** 
https://www.tensorflow.org/hub/tutorials/tf2_text_classification

**To convert the model,** 
`python -m tf2onnx.convert --saved-model content/saved_model/my_model --output /content/saved_model/model_export1.onnx --opset 13 --extra_opset ai.onnx.contrib:1`

**it gives the following while converting to ONNX model**

tensorflow-onnx % python -m tf2onnx.convert --saved-model content/saved_model/my_model  --output /content/saved_model/model_export1.onnx  --opset 13 --extra_opset ai.onnx.contrib:1
/.pyenv/versions/3.7.10/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-07-10 20:21:24,449 - WARNING - tensorflow_text not installed. Model will fail to load if tensorflow_text ops are used.
2021-07-10 20:21:24,451 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-07-10 20:21:25,586 - INFO - Signatures found in model: [serving_default].
2021-07-10 20:21:25,586 - WARNING - '--signature_def' not specified, using first signature: serving_default
2021-07-10 20:21:25,586 - INFO - Output names: ['dense_3']
WARNING:tensorflow:From /tensorflow-onnx/tf2onnx/tf_loader.py:662: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-07-10 20:21:33,498 - WARNING - /tensorflow-onnx/tf2onnx/tf_loader.py:662: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-07-10 20:21:42,846 - INFO - Using tensorflow=2.5.0, onnx=1.9.0, tf2onnx=1.10.0/b65b05
2021-07-10 20:21:42,846 - INFO - Using opset <onnx, 13>
2021-07-10 20:21:55,432 - WARNING - Cannot infer shape for StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup/None_Lookup/LookupTableFindV2: StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup/None_Lookup/LookupTableFindV2:0
2021-07-10 20:21:55,433 - WARNING - Cannot infer shape for StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup/NotEqual: StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup/NotEqual:0
2021-07-10 20:21:55,433 - WARNING - Cannot infer shape for StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/None_Lookup/LookupTableFindV2: StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/None_Lookup/LookupTableFindV2:0
2021-07-10 20:21:55,433 - WARNING - Cannot infer shape for StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup/SelectV2: StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup/SelectV2:0
2021-07-10 20:21:55,433 - WARNING - Cannot infer shape for StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/NotEqual: StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/NotEqual:0
2021-07-10 20:21:55,433 - WARNING - Cannot infer shape for StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/SelectV2: StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/SelectV2:0
2021-07-10 20:22:03,103 - INFO - Computed 1 values for constant folding
2021-07-10 20:22:15,601 - INFO - folding node using tf type=StringToHashBucketFast, name=StatefulPartitionedCall/sequential_1/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/None_Lookup_1/hash_bucket
2021-07-10 20:22:17,992 - INFO - Optimizing ONNX model
2021-07-10 20:22:42,269 - INFO - After optimization: Const -28 (50->22), HashTableV2 -1 (1->0), Identity -24 (24->0), Unsqueeze -1 (7->6)
2021-07-10 20:22:43,361 - INFO - 
2021-07-10 20:22:43,361 - INFO - Successfully converted TensorFlow model /content/saved_model/my_model to ONNX
2021-07-10 20:22:43,361 - INFO - Model inputs: ['keras_layer_1_input']
2021-07-10 20:22:43,361 - INFO - Model outputs: ['dense_3']
2021-07-10 20:22:43,361 - INFO - ONNX model is saved at /content/saved_model/model_export1.onnx

**when I try to infer using onnxruntime  i get the following error**

`import onnxruntime as rt`
`sess = rt.InferenceSession("/content/saved_model/model_export1.onnx", providers=["CPUExecutionProvider"])`
`input_name = sess.get_inputs()[0].name`
`output_name = sess.get_outputs()[0].name`

File "onnx_runtime_test.py", line 2, in <module>
    sess = rt.InferenceSession("content/saved_model/model_export1.onnx", providers=["CPUExecutionProvider"])
  File "pyonnxr/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "pyonnxr/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /content/saved_model/model_export1.onnx failed:Fatal error: StringSplit is not a registered function/op

**Code:**
`import numpy as np

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

import matplotlib.pyplot as plt

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.list_physical_devices('GPU') else "NOT AVAILABLE")

train_data, test_data = tfds.load(name="imdb_reviews", split=["train", "test"], 
                                  batch_size=-1, as_supervised=True)

train_examples, train_labels = tfds.as_numpy(train_data)
test_examples, test_labels = tfds.as_numpy(test_data)

print("Training entries: {}, test entries: {}".format(len(train_examples), len(test_examples)))

print("Training entries: {}, test entries: {}".format(len(train_examples), len(test_examples)))

print(train_examples[:10])

print(train_labels[:10])

model = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(model, input_shape=[], dtype=tf.string, trainable=True)
hub_layer(train_examples[:3])

model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

model.compile(optimizer='adam',
              loss=tf.losses.BinaryCrossentropy(from_logits=True),
              metrics=[tf.metrics.BinaryAccuracy(threshold=0.0, name='accuracy')])

x_val = train_examples[:10000]
partial_x_train = train_examples[10000:]

y_val = train_labels[:10000]
partial_y_train = train_labels[10000:]

history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=1,
                    batch_size=512,
                    validation_data=(x_val, y_val),
                    verbose=1)

results = model.evaluate(test_data, test_labels)

print(results)

history_dict = history.history
history_dict.keys()

`

To save the tf model 
`!mkdir -p saved_model`
`model.save('saved_model/my_model')`

How will I be able to infer using onnxruntime

**Comment by TomWildenhain-Microsoft** [comment]
Hi @sreehasa, the `--extra_opset ai.onnx.contrib:1` tells to converter to include non-onnx ops from (among other sources) `onnxruntime-extensions`.  
https://github.com/microsoft/onnxruntime-extensions

You need to install that and import it before inference will work.
`pip install onnxruntime-extensions`

```python
import onnxruntime as rt
from onnxruntime_extensions import get_library_path

so = rt.SessionOptions()
so.register_custom_ops_library(get_library_path())
sess = rt.InferenceSession(path/to/model, so)
```

**Comment by sreehasa** [comment]
@TomWildenhain-Microsoft my bad! 
got it thanks.
However, I was working on the tutorial given in https://www.tensorflow.org/text/tutorials/classify_text_with_bert.
when I try to convert the model to onnx, it gives the following error

**ERROR - Unsupported ops: Counter({'CaseFoldUTF8': 1, 'NormalizeUTF8': 1})**

FULL ERROR LOG

2021-08-02 02:56:07,570 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-08-02 02:56:14,351 - INFO - Signatures found in model: [serving_default].
2021-08-02 02:56:14,351 - WARNING - '--signature_def' not specified, using first signature: serving_default
2021-08-02 02:56:14,352 - INFO - Output names: ['classifier']
WARNING:tensorflow:From /pyenv/lib/python3.7/site-packages/tf2onnx/tf_loader.py:662: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-08-02 02:56:19,061 - WARNING - From /pyenv/lib/python3.7/site-packages/tf2onnx/tf_loader.py:662: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-08-02 02:56:25,421 - INFO - Using tensorflow=2.5.0, onnx=1.9.0, tf2onnx=1.9.1/8e8c23
2021-08-02 02:56:25,421 - INFO - Using opset <onnx, 13>
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/None_Lookup/LookupTableFindV2: StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/None_Lookup/LookupTableFindV2:0
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/Cast_2: StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/Cast_2:0
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/Identity: StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/Identity:0
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for Func/StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/output/_355: Func/StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/output/_355:0
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for Func/StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/input/_360: Func/StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/input/_360:0
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/BroadcastTo: StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/BroadcastTo:0
2021-08-02 02:56:25,431 - WARNING - Cannot infer shape for StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/map/RaggedFromVariant/RaggedTensorFromVariant: StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/map/RaggedFromVariant/RaggedTensorFromVariant:1
2021-08-02 02:56:29,817 - INFO - Computed 7 values for constant folding
2021-08-02 02:56:43,995 - INFO - Computed 0 values for constant folding
2021-08-02 02:56:44,013 - INFO - Computed 0 values for constant folding
2021-08-02 02:56:44,072 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/RaggedConcat/RaggedFromTensor/strided_slice_2
2021-08-02 02:56:44,072 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/RaggedConcat/RaggedFromTensor_1/strided_slice_2
2021-08-02 02:56:44,073 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/RaggedConcat_1/RaggedFromTensor/strided_slice_2
2021-08-02 02:56:44,073 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/RaggedConcat_1/RaggedFromTensor_1/strided_slice_2
2021-08-02 02:56:44,073 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/self_attention_mask/strided_slice_2
2021-08-02 02:56:44,073 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/position_embedding/strided_slice_1
2021-08-02 02:56:44,074 - INFO - folding node using tf type=StridedSlice, name=StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/self_attention_mask/strided_slice_1
2021-08-02 02:56:44,317 - ERROR - Tensorflow op [StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/CaseFoldUTF8/CaseFoldUTF8: CaseFoldUTF8] is not supported
2021-08-02 02:56:44,317 - ERROR - Tensorflow op [StatefulPartitionedCall/model/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/NormalizeUTF8/NormalizeUTF8: NormalizeUTF8] is not supported
2021-08-02 02:56:44,904 - ERROR - Unsupported ops: Counter({'CaseFoldUTF8': 1, 'NormalizeUTF8': 1})
2021-08-02 02:56:45,033 - INFO - Optimizing ONNX model
2021-08-02 02:56:52,135 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_3/self_attention/einsum/Einsum' by its decomposed version, name of the last node 'Identity__725'.
2021-08-02 02:56:52,144 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_1/self_attention/einsum/Einsum' by its decomposed version, name of the last node 'Identity__773'.
2021-08-02 02:56:52,461 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_3/self_attention/einsum_1/Einsum' by its decomposed version, name of the last node 'Identity__819'.
2021-08-02 02:56:52,471 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_0/self_attention/einsum_1/Einsum' by its decomposed version, name of the last node 'Identity__865'.
2021-08-02 02:56:52,480 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_1/self_attention/einsum_1/Einsum' by its decomposed version, name of the last node 'Identity__911'.
2021-08-02 02:56:52,489 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_2/self_attention/einsum/Einsum' by its decomposed version, name of the last node 'Identity__959'.
2021-08-02 02:56:52,499 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_2/self_attention/einsum_1/Einsum' by its decomposed version, name of the last node 'Identity__1005'.
2021-08-02 02:56:52,510 - INFO - replacing einsum node 'StatefulPartitionedCall/model/BERT_encoder/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_encoder/StatefulPartitionedCall/transformer/layer_0/self_attention/einsum/Einsum' by its decomposed version, name of the last node 'Identity__1053'.
2021-08-02 02:56:52,776 - WARNING - Reshape__1001:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,778 - WARNING - Reshape__955:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,784 - WARNING - Reshape__907:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,789 - WARNING - Reshape__721:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,794 - WARNING - Reshape__769:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,801 - WARNING - Reshape__1049:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,809 - WARNING - Reshape__861:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:52,815 - WARNING - Reshape__815:0's shape is unknown, which may interfere further optimization
2021-08-02 02:56:59,601 - INFO - After optimization: Add -1 (81->80), Cast -31 (60->29), Compress -3 (18->15), Concat +17 (29->46), Const -434 (565->131), ConstantOfShape -1 (5->4), CumSum -1 (8->7), Div -1 (3->2), Einsum -8 (24->16), Expand -1 (9->8), Gather +59 (15->74), GlobalAveragePool +18 (0->18), Greater -1 (5->4), HashTableV2 -1 (1->0), Identity -126 (126->0), Less -4 (10->6), MatMul +8 (11->19), Max +8 (1->9), Mod -1 (3->2), Mul -9 (73->64), RaggedTensorToVariant -1 (1->0), Range -1 (6->5), ReduceMax -1 (4->3), ReduceMean -18 (18->0), ReduceMin -1 (3->2), ReduceProd +16 (0->16), Reshape +12 (27->39), Shape +12 (22->34), Slice -14 (52->38), Sub -6 (40->34), Transpose +29 (2->31), Unsqueeze -5 (37->32), Where -1 (3->2)
2021-08-02 02:56:59,971 - INFO - 
2021-08-02 02:56:59,972 - INFO - Successfully converted TensorFlow model /tf_pp_bt_cl/imdb_bert to ONNX
2021-08-02 02:56:59,972 - INFO - Model inputs: ['text']
2021-08-02 02:56:59,972 - INFO - Model outputs: ['classifier']
2021-08-02 02:56:59,972 - INFO - ONNX model is saved at /model_export1.onnx

**Comment by TomWildenhain-Microsoft** [comment]
Unfortunately we don't have an implementation for CaseFoldUTF8 or NormalizeUTF8 in onnxruntime-extensions.  These ops probably come from the preprocessing model you used.  I believe we can convert some of the preprocessing models (specifically https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/3).  Which preprocessing model did you use?

**Comment by sreehasa** [comment]
@TomWildenhain-Microsoft used this for preprocessing https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3

**Comment by sreehasa** [comment]
@TomWildenhain-Microsoft I tried to convert tfhub model (https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1) to onnx.
`python -m tf2onnx.convert --saved-model /models/bert/bert_uncased_L-12_H-768_A-12_1 --output /content/saved_model/model_export1.onnx --opset 13 --extra_opset ai.onnx.contrib:1`

I get the following error:
**RuntimeError: MetaGraphDef associated with tags 'serve' could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [{'train'}, set()]**

Full Error Log
.pyenv/versions/3.7.10/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-08-03 14:19:56,125 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File ".pyenv/versions/3.7.10/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".pyenv/versions/3.7.10/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lib/python3.7/site-packages/tf2onnx/convert.py", line 605, in <module>
    main()
  File "lib/python3.7/site-packages/tf2onnx/convert.py", line 222, in main
    use_graph_names=args.use_graph_names)
  File "lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 571, in from_saved_model
    tag, signatures, concrete_function, large_model, use_graph_names)
  File "lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 508, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 869, in load
    return load_internal(export_dir, tags, options)["root"]
  File "lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 925, in load_internal
    root = load_v1_in_v2.load(export_dir, tags)
  File "lib/python3.7/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 281, in load
    return loader.load(tags=tags)
  File "lib/python3.7/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 207, in load
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "lib/python3.7/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 87, in get_meta_graph_def_from_tags
    tags)
  File "lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 360, in get_meta_graph_def_from_tags
    "\navailable_tags: " + str(available_tags))
RuntimeError: MetaGraphDef associated with tags 'serve' could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [{'train'}, set()]

**Comment by TomWildenhain-Microsoft** [comment]
Try again with the `--tag ""` flag

**Comment by fatcat-z** [comment]
No response from user yet, close it.
