### ISSUE TITLE
TypeError: must be type, not classobj

### ISSUE THREAD

**Issue by rogerou** [onnx/tensorflow-onnx#163]
```cmd
using tensorflow=1.5.0, onnx=1.3.0, opset=8
2018-10-17 16:16:19.052982: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2018-10-17 16:16:19.068366: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/tf2onnx/convert.py", line 113, in <module>
  File "build/bdist.linux-x86_64/egg/tf2onnx/convert.py", line 98, in main
  File "build/bdist.linux-x86_64/egg/tf2onnx/tfonnx.py", line 1647, in process_tf_graph
  File "build/bdist.linux-x86_64/egg/tf2onnx/rewriter/rnn.py", line 19, in rewrite_single_direction_lstm
  File "build/bdist.linux-x86_64/egg/tf2onnx/rewriter/lstm_rewriter.py", line 19, in __init__
TypeError: must be type, not classobj
```

**Comment by rogerou** [comment]
@guschmue  Thanks, it's not difficult for me to use python3

**Comment by guschmue** [comment]
We won't be supporting python 2.7 because numpy 1.17 will drop support for python 2.7 ... no future.
