### ISSUE TITLE
tensorflow inceptionv4 convert error

### ISSUE THREAD

**Issue by TUT-jiayou** [onnx/tensorflow-onnx#1633]
HI, all
@guschmue  @vuzelac-cadence  @zhijxu-MS @lucienwang1009 
#  I also try to convert the  https://storage.googleapis.com/download.tensorflow.org/models/inception_v4_2016_09_09_frozen.pb.tar.gz to onnx, I got the error
```
/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-07-30 16:41:47,830 - WARNING - From /home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/convert.py", line 605, in <module>
    main()
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/convert.py", line 213, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 315, in from_graphdef
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 262, in freeze_session
    graph_def = convert_variables_to_constants(sess, graph_def, output_node_names)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 277, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 197, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 152, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: graph/InceptionV4/Logits/Predictions is not in graph
```
#  used command
```
python -m tf2onnx.convert \
    --input $MODEL_DIR/inception_v4_2016_09_09_frozen.pb  \
    --inputs graph/input:0 \
    --outputs"graph/InceptionV4/Logits/Predictions:0" \
    --fold_const
```
# Env 
* Ubuntu18.04
* python 3.7.10
* tensorflow-estimator 1.15.1
* tensorflow-gpu 1.15.5
* onnx 1.6.0
* onnxruntime 1.3.0
* tf2onnx 1.9.1
* tensorrt 7.1.3
Thanks for your time.

_Originally posted by @TUT-jiayou in https://github.com/onnx/tensorflow-onnx/issues/490#issuecomment-889765249_

**Comment by zhijxu-MS** [comment]
![image](https://user-images.githubusercontent.com/43435212/127635176-ccbedeab-6090-4e28-96db-ded5be15182d.png)

the input/output name of model are not prefixed with "graph"?

**Comment by TUT-jiayou** [comment]
yes, thanks 

But i can not understand the difference between netron result  and  the scripts and tensorboard?

**Comment by zhijxu-MS** [comment]
when the tf loaded pb file, it will add a default namespace if i remember correctly. you could check the diff between your tf load and tf2onnx's way.

**Comment by guschmue** [comment]
```
python -m tf2onnx.convert --input /tmp/pre-trained/inception_v4_2016_09_09_frozen.pb/inception_v4_2016_09_09_frozen.pb --inputs input:0 --outputs InceptionV4/Logits/Predictions:0 --output /tmp/inception_v4_2016_09_09.onnx --opset 13
```

does work for me.

**Comment by TUT-jiayou** [comment]
HI, @zhijxu-MS  @guschmue

Thanks for your time.
