### ISSUE TITLE
convert fasterrcnn failed

### ISSUE THREAD

**Issue by chwjshlwel** [onnx/tensorflow-onnx#1639]
**Describe the bug**
I want to convert the Tensorflow API Object Detection model Faster_RCNN using this link http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz.
I got the error like:
2021-08-03 08:07:35,850 - WARNING - Cannot infer shape for BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros: BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros:0
2021-08-03 08:07:35,850 - WARNING - Cannot infer shape for SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros:0
2021-08-03 08:07:36,911 - INFO - Computed 1 values for constant folding
2021-08-03 08:07:43,192 - INFO - folding node using tf type=StridedSlice, name=Preprocessor/map/while/ResizeToRange/strided_slice_2
2021-08-03 08:07:49,772 - WARNING - ONNX Failed to infer shapes and dtypes for [CropAndResize, type: Loop]
Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 154, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto, strict_mode=True)
TypeError: infer_shapes() got an unexpected keyword argument 'strict_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 157, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto)
  File "C:\Users\twim\anaconda3\envs\onnx_new\lib\site-packages\onnx\shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Slice, node name: Slice_c): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: Reshape__1669): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice__1675): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice__1672): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice_a): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Add, node name: Add__1659): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice_b): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Transpose, node name: Transpose__1663): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Resize, node name: Resize__1684): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Transpose, node name: Transpose__1685): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Squeeze, node name: Squeeze__1687): [TypeInferenceError] Input 0 expected to have type but instead is null

2021-08-03 08:07:49,773 - WARNING - ONNX Failed to infer shapes and dtypes for [Reshape__1697, type: Reshape]
Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 154, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto, strict_mode=True)
TypeError: infer_shapes() got an unexpected keyword argument 'strict_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 157, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto)
  File "C:\Users\twim\anaconda3\envs\onnx_new\lib\site-packages\onnx\shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Reshape, node name: Reshape__1697): [TypeInferenceError] Element type of input 0 unknown

2021-08-03 08:07:49,773 - WARNING - ONNX Failed to infer shapes and dtypes for [MaxPool2D/MaxPool__1698, type: Transpose]
Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 154, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto, strict_mode=True)
TypeError: infer_shapes() got an unexpected keyword argument 'strict_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 157, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto)
  File "C:\Users\twim\anaconda3\envs\onnx_new\lib\site-packages\onnx\shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Transpose, node name: MaxPool2D/MaxPool__1698): [TypeInferenceError] Element type of input 0 unknown

2021-08-03 08:07:52,861 - INFO - Optimizing ONNX model
2021-08-03 08:10:03,299 - INFO - After optimization: Add -3 (339->336), Cast -334 (1162->828), Concat -3 (408->405), Const -4764 (10100->5336), Gather +6 (571->577), GlobalAveragePool +1 (0->1), Identity -71 (74->3), Mul -10 (692->682), ReduceMean -1 (1->0), Reshape -13 (318->305), Shape -8 (134->126), Slice -6 (1065->1059), Squeeze -379 (1537->1158), Transpose -221 (415->194), Unsqueeze -493 (815->322)
2021-08-03 08:10:06,203 - INFO - 
2021-08-03 08:10:06,203 - INFO - Successfully converted TensorFlow model work/faster_rcnn_resnet101_coco_2018_01_28/frozen_inference_graph.pb to ONNX
2021-08-03 08:10:06,203 - INFO - Model inputs: ['image_tensor:0']
2021-08-03 08:10:06,203 - INFO - Model outputs: ['num_detections:0', 'detection_boxes:0', 'detection_scores:0', 'detection_classes:0']
2021-08-03 08:10:06,203 - INFO - ONNX model is saved at work/faster_rcnn_resnet101_coco_2018_01_28/frozen1.onnx

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Tensorflow Version:2.4.1
- Python version:3.7
- tf2onnx: 1.9.1
- onnx:1.8.0
- onnxruntime:1.8.1 

**To Reproduce**
The link of the model is http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_coco_2018_01_28.tar.gz.
I use the commend
!python -m tf2onnx.convert --graphdef work/faster_rcnn_resnet101_coco_2018_01_28/frozen_inference_graph.pb --output work/faster_rcnn_resnet101_coco_2018_01_28/frozen1.onnx \
    --opset 13 \
    --inputs image_tensor:0 \
    --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0

**Comment by chwjshlwel** [comment]
I try another model for tensorflow 2.4 the link is http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8.tar.gz, and I got another error like:
Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 154, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto, strict_mode=True)
TypeError: infer_shapes() got an unexpected keyword argument 'strict_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 157, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto)
  File "C:\Users\twim\anaconda3\envs\onnx_new\lib\site-packages\onnx\shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Slice, node name: Slice_c): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Reshape, node name: Reshape__1753): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice__1759): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice__1756): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice_a): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Add, node name: Add__1744): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Slice, node name: Slice_b): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Transpose, node name: Transpose__1747): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Resize, node name: Resize__1768): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Transpose, node name: Transpose__1769): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Squeeze, node name: Squeeze__1771): [TypeInferenceError] Input 0 expected to have type but instead is null

2021-08-03 08:51:30,310 - WARNING - ONNX Failed to infer shapes and dtypes for [Reshape__1780, type: Reshape]
Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 154, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto, strict_mode=True)
TypeError: infer_shapes() got an unexpected keyword argument 'strict_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\twim\AppData\Roaming\Python\Python37\site-packages\tf2onnx\schemas.py", line 157, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto)
  File "C:\Users\twim\anaconda3\envs\onnx_new\lib\site-packages\onnx\shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Reshape, node name: Reshape__1780): [TypeInferenceError] Element type of input 0 unknown

2021-08-03 08:51:31,997 - INFO - Optimizing ONNX model
2021-08-03 08:52:00,533 - INFO - After optimization: Add -91 (438->347), BatchNormalization -104 (104->0), Cast -707 (1903->1196), Concat -98 (323->225), Const -5273 (5780->507), Equal -90 (100->10), Gather +2 (395->397), GlobalAveragePool +1 (0->1), Identity -51 (52->1), Mul -94 (532->438), ReduceMean -2 (2->0), ReduceSum -91 (93->2), Reshape -125 (428->303), Shape -95 (302->207), Slice -13 (431->418), Split -2 (34->32), Squeeze -24 (462->438), Sub -95 (221->126), Transpose -425 (448->23), Unsqueeze -224 (469->245)
2021-08-03 08:52:02,337 - INFO - 
2021-08-03 08:52:02,337 - INFO - Successfully converted TensorFlow model work/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8/saved_model to ONNX
2021-08-03 08:52:02,337 - INFO - Model inputs: ['input_tensor']
2021-08-03 08:52:02,337 - INFO - Model outputs: ['detection_anchor_indices', 'detection_boxes', 'detection_classes', 'detection_multiclass_scores', 'detection_scores', 'num_detections', 'raw_detection_boxes', 'raw_detection_scores']
2021-08-03 08:52:02,337 - INFO - ONNX model is saved at work/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8/model.onnx

I use the commend:
!python -m tf2onnx.convert --saved-model work/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8/saved_model --output work/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8/model.onnx \
    --opset 13

**Comment by chwjshlwel** [comment]
I have successed in converting the model. Thanks

**Comment by FrankZTH** [comment]
> I have successed in converting the model. Thanks

Hello, chwjshlwel could you provide your faster_rcnn converted from tf2onnx?
I stuck in same error, but i can't fix it.
Thank you very much.
