### ISSUE TITLE
OSError: SavedModel file does not exist 

### ISSUE THREAD

**Issue by ken20065** [onnx/tensorflow-onnx#1677]
Hello,
I am getting the OSError, when trying to access the saved model.

commands used:

runfile('C:/Users/Administrator/Desktop/Project Cnn/Emotion_Detection_CNN-main (1)/Emotion_Detection_CNN-main/main.py', wdir='C:/Users/Administrator/Desktop/Project Cnn/Emotion_Detection_CNN-main (1)/Emotion_Detection_CNN-main')
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\Project Cnn\Emotion_Detection_CNN-main (1)\Emotion_Detection_CNN-main\main.py", line 9, in <module>
    classifier =load_model(r'C:\Users\Administrator\Desktop\Project Cnn\Emotion_Detection_CNN-main (1)\Emotion_Detection_CNN-main\model_1')

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\saving\save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\saving\saved_model\load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 118, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s%s{%s|%s}" %

OSError: SavedModel file does not exist at: C:\Users\Administrator\Desktop\Project Cnn\Emotion_Detection_CNN-main (1)\Emotion_Detection_CNN-main\model_1\{saved_model.pbtxt|saved_model.pb}

 please help me resolve this issue.

Thanks.

checked this issue, no proper explanation found :#1348

**Comment by guschmue** [comment]
there is no indication that this has anything to with tf2onnx.
