### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 59: invalid start byte

### ISSUE THREAD

**Issue by xinsuinizhuan** [onnx/tensorflow-onnx#1682]
C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
C:\ProgramData\Anaconda3\envs\base37\lib\runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\comm_Item\Item_doing\tensorrt_item\tensorflow-onnx-master\tf2onnx\convert.py", line 617, in <module>
    main()
  File "E:\comm_Item\Item_doing\tensorrt_item\tensorflow-onnx-master\tf2onnx\convert.py", line 222, in main
    graph_def, inputs, outputs = tf_loader.from_checkpoint(args.checkpoint, args.inputs, args.outputs)
  File "E:\comm_Item\Item_doing\tensorrt_item\tensorflow-onnx-master\tf2onnx\tf_loader.py", line 376, in from_checkpoint
    saver = tf_import_meta_graph(model_path, clear_devices=True)
  File "C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\tensorflow\python\training\saver.py", line 1467, in import_meta_graph
    **kwargs)[0]
  File "C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\tensorflow\python\training\saver.py", line 1481, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 634, in read_meta_graph_file
    file_content = f.read()
  File "C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "C:\ProgramData\Anaconda3\envs\base37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 59: invalid start byte

**Comment by zuoyuwei** [comment]
我也有这个问题+1

**Comment by TomWildenhain-Microsoft** [comment]
This looks like a unicode decoding error while trying to open a tensorflow saved model.  That would be a problem with TensorFlow or the model, not tf2onnx.  Try this:

```python
import tensorflow as tf
tf.saved_model.load("path/to/model")
```

If that also fails, it is a tf/model issue.  You may be able to work around the issue by removing non-ascii characters from file paths/names.

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
