### ISSUE TITLE
Frozen Graph outputs not readable during conversion to ONNX

### ISSUE THREAD

**Issue by pra-dan** [onnx/tensorflow-onnx#1693]
I am using latest ONNX and tf 1.15+keras 2.1.6

Model/frozen graph: [LINK](https://www.dropbox.com/s/05b7bv4jmvai8ut/resnet101/resnet101-epoch1-patched-batch1.pb)

I checked the model inputs and outputs using netron.app and when I try to convert the model using 
```console
python -m tf2onnx.convert --input '/content/resnet101-epoch1-patched-batch1.pb' --inputs input_image:0[1,3,1024,1024] --outputs mrcnn_mask/convolution:0 --output resnet101-epoch1-patched-batch1.onnx --opset 12
```

I get 
```console
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-08-31 10:09:06,805 - WARNING - From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py:347: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  graph_def.ParseFromString(content)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 617, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 219, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py", line 358, in from_graphdef
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py", line 305, in freeze_session
    graph_def = convert_variables_to_constants(sess, graph_def, output_node_names)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/graph_util_impl.py", line 277, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/graph_util_impl.py", line 197, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/graph_util_impl.py", line 152, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: mrcnn_mask/convolution is not in graph
```

Although i can clearly see the layer `AssertionError: mrcnn_mask/convolution` in my graph. Another weird thing is, that the graph seems to be unreadable. I try reading its nodes/ops as follows:
```python3
import tensorflow as tf
def printTensors(pbFile):
  with tf.gfile.GFile(pbFile, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
  
  # import graph_def
  with tf.Graph().as_default() as graph:
    tf.import_graph_def(graph_def)
  
  nodes = [n.name+' => '+n.op for n in graph_def.node]
  for n in nodes:
    print(n)

  # print ops
  for op in graph.get_operations():
    print(op.name)
printTensors('/content/resnet101-epoch1-patched-batch1.pb')
```

To which I get
```console
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  """
```

Any idea on this ? Thanks.

**Comment by pra-dan** [comment]
SOrry for the wrong link. [Here](https://www.dropbox.com/s/9vnevoqaslgdr6j/res101-ep1-patched-batch1.pb) is the frozen graph. I have checked it using netron and find everything well over there.

**Comment by pra-dan** [comment]
Ok. so the model was corrupted before I tried converting it into ONNX, nothing wrong. Thanks for your time
