### ISSUE TITLE
ValueError: variable already exists as state variable.

### ISSUE THREAD

**Issue by pallavimohansaab** [onnx/tensorflow-onnx#1696]
**Issue**
Hi, I get the following error while trying to convert a SavedModel to onnx:
ValueError: make_sure failure: variable mrcnn_detection/map/while/Enter already exists as state variable.

History:
I generated a custom MaskRCNN model and converted it to SavedModel using [this Github code](https://github.com/moganesyan/tensorflow_model_deployment).

I used `python -m tf2onnx.convert --saved-model exported_models\coco_mrcnn\3 --opset 15 --output "model.onnx"` to export it to ONNX and I get the following error: 
```
2021-09-01 12:15:43.529971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]
2021-09-01 12:15:43,531 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-09-01 12:15:43,531 - WARNING - '--signature_def' not provided. Using all signatures.
2021-09-01 12:15:46,994 - INFO - Using tensorflow=1.15.5, onnx=1.10.1, tf2onnx=1.9.2/0f28b7
2021-09-01 12:15:46,994 - INFO - Using opset <onnx, 15>
2021-09-01 12:15:50,231 - INFO - Computed 0 values for constant folding
2021-09-01 12:15:52,045 - ERROR - rewriter <function rewrite_single_direction_lstm at 0x00000202CC84B400>: exception make_sure failure: variable mrcnn_detection/map/while/Enter already exists as state variable.
Traceback (most recent call last):
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\convert.py", line 617, in <module>
    main()
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\convert.py", line 277, in main
    output_path=args.output)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\convert.py", line 155, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\tfonnx.py", line 439, in process_tf_graph
    initialized_tables, tensors_to_rename, is_tflite, dequantize)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\tfonnx.py", line 492, in process_graphs
    dequantize)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\tfonnx.py", line 588, in process_parsed_graph
    run_rewriters(g, rewriters, continue_on_error)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\tfonnx.py", line 361, in run_rewriters
    raise ex
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\tfonnx.py", line 352, in run_rewriters
    ops = func(g, g.get_nodes())
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\rnn.py", line 25, in rewrite_single_direction_lstm
    return r.run()
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\lstm_rewriter.py", line 31, in run
    return super(LSTMRewriter, self).run()
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\unit_rnn_rewriter_base.py", line 61, in run
    return self.run_internal()
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\loop_rewriter_base.py", line 220, in run_internal
    self._check_in_read_only_mode(context)  # parses loop variables
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\loop_rewriter_base.py", line 247, in _check_in_read_only_mode
    self._parse_loop_variables(context)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\loop_rewriter_base.py", line 262, in _parse_loop_variables
    context.loop_properties.add_variable(loop_var)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\rewriter\loop_rewriter_base.py", line 58, in add_variable
    "variable %s already exists as state variable.", var.enter_name)
  File "C:\Users\pallavi.mohan\Anaconda3\envs\tfserving\lib\site-packages\tf2onnx\utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: variable mrcnn_detection/map/while/Enter already exists as state variable.
```
This occurs even when I change the opset to 15.
I have tried converting my model through all ways: Frozen graph with .pb throws:
    ```   
    assert d in name_to_node, "%s is not in graph" % d
    AssertionError: output0 is not in graph
    ```
This is after I have mentioned the input and output nodes.

**Urgency**
Need the converted ONNX by tomorrow to inference with Unity Barracuda due to an urgent paper deadline.

**System information**
- OS: Windows 10, Conda environment
- Tensorflow Version: 1.15.5 (the model was generated with TF 1.15 also)
- Python version: 3.6.13

**To Reproduce**
Convert the attached SavedModel to tf2onnx using: `python -m tf2onnx.convert --saved-model exported_models\coco_mrcnn\3 --opset 15 --output "model.onnx"`

**Additional context**
The model was trained on a custom dataset from [Matterport's MaskRCNN implementation](https://github.com/matterport/Mask_RCNN).
Link to .h5 and savedmodel files: https://drive.google.com/drive/folders/1RA6v0et64UCnt1pNaOR3UM6YZ7YIOe0A?usp=sharing

**Comment by TomWildenhain-Microsoft** [comment]
Hi @pallavimohansaab 
Thanks for the bug report.  #1697 should fix the issue.  Here's a copy of the converted model with opset 14:
https://microsoft-my.sharepoint-df.com/:u:/p/tomwi/EYbaETGSqXFDhtk4aNNAykEBqM1WgS4GJnv_4MDhhxmlnA?e=XTCBXb
