### ISSUE TITLE
Beta input to batch norm has bad shape: [64]

### ISSUE THREAD

**Issue by nistarlwc** [onnx/tensorflow-onnx#1700]
tensorflow 1.13.1
ubuntu18
model: resnetv2-50

python -m tf2onnx.convert \
    --input ckpt-ResNet50-20210903/model.pb \
    --inputs Placeholder:0 \
    --outputs logits/Sigmoid:0 \
    --output ckpt-ResNet50-20210903/model.onnx \
    --verbose

But there is a error: Beta input to batch norm has bad shape: [64]

Traceback (most recent call last):
  File "/home/lwc/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lwc/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lwc/anaconda3/lib/python3.6/site-packages/tf2onnx/convert.py", line 617, in <module>
    main()
  File "/home/lwc/anaconda3/lib/python3.6/site-packages/tf2onnx/convert.py", line 219, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/lwc/anaconda3/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 364, in from_graphdef
    frozen_graph = tf_optimize(input_names, output_names, frozen_graph)
  File "/home/lwc/anaconda3/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 717, in tf_optimize
    graph_def = TransformGraph(graph_def, input_names, output_names, transforms)
  File "/home/lwc/anaconda3/lib/python3.6/site-packages/tensorflow/tools/graph_transforms/__init__.py", line 51, in TransformGraph
    transforms_string, status)
  File "/home/lwc/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Beta input to batch norm has bad shape: [64]

**Comment by TomWildenhain-Microsoft** [comment]
It looks like tf thinks the graph is invalid after freezing it.  Can you upload your model to One Drive/Google Drive/Dropbox and post a link?

**Comment by nistarlwc** [comment]
@TomWildenhain-Microsoft   

model:  
https://drive.google.com/file/d/1edSM-JSMgKpdRmexIyWWSQxVhwxHJQs0/view?usp=sharing

Thanks a lot

**Comment by nistarlwc** [comment]
this model can run in tensorflow

**Comment by TomWildenhain-Microsoft** [comment]
I requested access.

**Comment by fatcat-z** [comment]
No response from user yet, close it.
