### ISSUE TITLE
None-zero status code returned issue(running Scan node, running GreaterOrEqual node)

### ISSUE THREAD

**Issue by harrymort** [onnx/tensorflow-onnx#1705]
**Describe the bug**
- I made onnx model using deepspeech model. It was not problem. However, onnxruntime error is happend. Could you check the issue?

converting onnx model log :
$ python -m tf2onnx.convert --graphdef /home/taejuhwang/workspace/2021_digital_human/data/deepspeech/pretrained_model/output_graph.pb --opset 14 --output opset14_model.onnx --inputs input_node:0,input_lengths:0 --outputs logits:0
/home/taejuhwang/anaconda3/envs/digital_demo/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /home/taejuhwang/workspace/2021_digital_human/source/onnx/tensorflow-onnx/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-09-09 13:23:21,155 - WARNING - From /home/taejuhwang/workspace/2021_digital_human/source/onnx/tensorflow-onnx/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-09-09 13:23:38,991 - INFO - Using tensorflow=1.15.2, onnx=1.10.1, tf2onnx=1.8.0/240803
2021-09-09 13:23:38,991 - INFO - Using opset <onnx, 14>
2021-09-09 13:24:38,002 - INFO - Computed 0 values for constant folding
2021-09-09 13:25:07,511 - INFO - Optimizing ONNX model
2021-09-09 13:25:12,434 - INFO - After optimization: Cast -15 (36->21), Concat -4 (11->7), Const -86 (120->34), Expand -4 (6->2), Identity -13 (13->0), Reshape -6 (16->10), Shape -2 (5->3), Slice -3 (6->3), Squeeze -6 (6->0), Unsqueeze -12 (12->0)
2021-09-09 13:25:13,146 - INFO - 
2021-09-09 13:25:13,146 - INFO - Successfully converted TensorFlow model /home/taejuhwang/workspace/2021_digital_human/data/deepspeech/pretrained_model/output_graph.pb to ONNX
2021-09-09 13:25:13,146 - INFO - Model inputs: ['input_node:0', 'input_lengths:0']
2021-09-09 13:25:13,146 - INFO - Model outputs: ['logits:0']
2021-09-09 13:25:13,146 - INFO - ONNX model is saved at opset14_model.onnx

Runtime error log :
$ python inference_onnx.py 
2021-09-09 13:42:18.264664198 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running GreaterOrEqual node. Name:'bidirectional_rnn/bw/bw/while/GreaterEqual_2' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: bidirectional_rnn/bw/ToInt32:0

2021-09-09 13:42:18.264698885 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Scan node. Name:'custom_rnn_scan_Scan__15' Status Message: Non-zero status code returned while running GreaterOrEqual node. Name:'bidirectional_rnn/bw/bw/while/GreaterEqual_2' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: bidirectional_rnn/bw/ToInt32:0

Traceback (most recent call last):
  File "inference_onnx.py", line 21, in <module>
    test.inference()
  File "inference_onnx.py", line 15, in inference
    'input_lengths:0': [ input_vector.shape[0] ]
  File "/home/taejuhwang/anaconda3/envs/digital_demo/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Scan node. Name:'custom_rnn_scan_Scan__15' Status Message: Non-zero status code returned while running GreaterOrEqual node. Name:'bidirectional_rnn/bw/bw/while/GreaterEqual_2' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: bidirectional_rnn/bw/ToInt32:0

Exception ignored in: <function OnnxInference.__del__ at 0x7f92d92f9cb0>
Traceback (most recent call last):
  File "inference_onnx.py", line 9, in __del__

**Urgency**
2021-09-17

**System information**
- Linux Ubuntu 18.04
- Tensorflow Version: 1.15.2
- Python version: 3.7

**To Reproduce**
tensorflow model:
https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0
deepspeech-0.1.0-models.tar.gz, 1.31 GB

onnx model:
- download above deepspeech-0.1.0 model 
- you can make onnx model using (output_graph.pb)
-  command line : python -m tf2onnx.convert --graphdef /home/taejuhwang/workspace/2021_digital_human/data/deepspeech/pretrained_model/output_graph.pb --opset 14 --output opset14_model.onnx --inputs input_node:0,input_lengths:0 --outputs logits:0

code :

import numpy as np
import onnxruntime as ort

class OnnxInference():
    def __init__(self):
        self.sess_ort = ort.InferenceSession("./opset14_model.onnx")

    def __del__(self):
        self.sess_ort.close()

    def inference(self):
        np.random.seed(0)
        input_vector =np.random.uniform(low=-1.0, high=13.0, size=(1, 494)).astype(np.float32)
        network_output = self.sess_ort.run(output_names=['logits:0'], input_feed={'input_node:0': input_vector[np.newaxis, ...],
                                                                                    'input_lengths:0': [ input_vector.shape[0] ]
                                                                                    })
        print("ONNXRruntime {} shape {}".format(network_output, network_output.shape))

if __name__ == '__main__':
    test = OnnxInference()
    test.inference()

**Screenshots**
- none

**Additional context**
-none

**Comment by ulucsahin** [comment]
Did you solve the issue?

**Comment by harrymort** [comment]
> 



> Did you solve the issue?

**Comment by ulucsahin** [comment]
Disabling inference optimizations solves this issue.

```
options = onnxruntime.SessionOptions()
options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL
```

**Comment by brooks0519** [comment]
> > Did you solve the issue?
> > No, not yet.

hello @harrymort, have you finally solved this issue? I have the issue same to you, and I have try @ulucsahin method, but it dosn't work. Hope to get your reply. tks!

**Comment by longcw** [comment]
Does anyone have a solution here?
