### ISSUE TITLE
Cannot convert saved keras model to ONNX

### ISSUE THREAD

**Issue by pacospace** [onnx/tensorflow-onnx#1715]
**Describe the bug**
Cannot convert saved keras model to ONNX

**Urgency**
https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/297

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 33
- Tensorflow Version: tf 2.6.0
- Python version: 3.8

**To Reproduce**
1. clone https://github.com/AICoE/elyra-aidevsecops-tutorial
2. pip install tf2onnx
3. Run python3 -m tf2onnx.convert --saved-model ./models/210124112759-d97fd1f46b13ee40 --output mnist_model.onnx

**Screenshots**
```
python3 -m tf2onnx.convert --saved-model ../../models/210124112759-d97fd1f46b13ee40 --output mnist_model.onnx
2021-09-14 13:17:32.748488: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-14 13:17:32.748515: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/lib64/python3.8/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-09-14 13:17:33.815313: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-09-14 13:17:33.815335: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-09-14 13:17:33.815352: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (pc-7): /proc/driver/nvidia/version does not exist
2021-09-14 13:17:33.815584: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-14 13:17:33,816 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib/python3.8/site-packages/tf2onnx/convert.py", line 633, in <module>
    main()
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib/python3.8/site-packages/tf2onnx/convert.py", line 233, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 614, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 552, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 902, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 162, in __init__
    self._load_all()
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 259, in _load_all
    self._load_nodes()
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
It seems like tensorflow is failing to load the original model.  Can you try running `tf.saved_model.load(model_path)` yourself and see if it fails?  That would be a tensorflow error, but you may be able to work around it by using `tf2onnnx.convert.from_keras` instead (and skip saving the tf model to disk entirely)

**Comment by pacospace** [comment]
> It seems like tensorflow is failing to load the original model. Can you try running `tf.saved_model.load(model_path)` yourself and see if it fails? That would be a tensorflow error, but you may be able to work around it by using `tf2onnnx.convert.from_keras` instead (and skip saving the tf model to disk entirely)

Yes `tf.saved_model.load(model_path)` actually fails with same error. I can open an issue in TensorFlow then, thanks!

I will try the other solution!

**Comment by TomWildenhain-Microsoft** [comment]
Awesome.  I'm going to close this issue for now, but if from_keras fails with a different error feel free to open a new one.  Out of interest, what are you using the ONNX model for?

**Comment by pacospace** [comment]
Thanks @TomWildenhain-Microsoft, it works normally using the workaround you suggested.

I'm using it with neuralmagic, you can check the example here: https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/297

**Comment by pacospace** [comment]
From tensorflow they suggested to use https://github.com/tensorflow/tensorflow/issues/52013#issuecomment-920206995, so this might be the fix in this repo.

**Comment by TomWildenhain-Microsoft** [comment]
Can you try using the `--keras` flag instead of `--saved_model`?

**Comment by pacospace** [comment]
> Can you try using the `--keras` flag instead of `--saved_model`?

unfortunately same error :/

**Comment by TomWildenhain-Microsoft** [comment]
Interesting. We should be using keras.models.load_model in that case.

https://github.com/onnx/tensorflow-onnx/blob/496b65d7d33c621b3e2e53844af0dd64240fcf69/tf2onnx/tf_loader.py#L648

You will still need to put the full path of the .h5 model as suggested here:
https://github.com/tensorflow/tensorflow/issues/52013#issuecomment-920694023

Also is there a reason you need the CLI instead of `from_keras`, or just convenience?

**Comment by fatcat-z** [comment]
This issue could not be reproed in tensofrflow 2.7.0 + tf2onnx 1.10.0 + python 3.8.5 + onnx 1.8.0 + Ubuntu 20.04.1 LTS. Both previous "210124112759-d97fd1f46b13ee40" model and "tf-210915165333-7b04047d1220f5cd" model could be exported to ONNX successfully without any issues.

Close this and if any further problem, please feel free to open a new issue to trace it.

**Comment by pacospace** [comment]
> This issue could not be reproed in tensofrflow 2.7.0 + tf2onnx 1.10.0 + python 3.8.5 + onnx 1.8.0 + Ubuntu 20.04.1 LTS. Both previous "210124112759-d97fd1f46b13ee40" model and "tf-210915165333-7b04047d1220f5cd" model could be exported to ONNX successfully without any issues.
> 
> Close this and if any further problem, please feel free to open a new issue to trace it.

Thanks @fatcat-z !!
