### ISSUE TITLE
TF1-Keras Dilated Conv ONNX Exported Incorrectly.

### ISSUE THREAD

**Issue by leimao** [onnx/tensorflow-onnx#1728]
**Describe the bug**
TF2ONNX does not export the dilated convolution correctly.

**Urgency**
Ideally, I wish it could be fixed by 10/1/2021.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04.2 LTS
- Tensorflow Version: 1.15.5
- Python version: 3.8.10

**To Reproduce**
Describe steps/code to reproduce the behavior. Please upload/link the model you are trying to convert if possible.

In NVIDIA TensorFlow-1 Docker Container:

```bash
docker run -it --rm --gpus all -v $(pwd):/mnt nvcr.io/nvidia/tensorflow:21.08-tf1-py3
```

Install TF2ONNX (tried both the master branch and the latest release 1.9.2)
```
pip install git+https://github.com/onnx/tensorflow-onnx
```

Run the following script to generate ONNX file for dilated conv.

```python
import onnx
import tf2onnx
import tensorflow as tf

inputs = tf.keras.Input(shape=(64, 256, 256))
outputs = tf.keras.layers.Conv2D(
    filters=128,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_first',
    dilation_rate=(2, 2),
    name='conv_1',
    use_bias=False,
)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)


onnx_model, _ = tf2onnx.convert.from_keras(
    model=model,
    opset=13,
    large_model=False,
)

onnx.save_model(onnx_model, "dilated_conv.onnx")


inputs = tf.keras.Input(shape=(64, 256, 256))
outputs = tf.keras.layers.Conv2D(
    filters=128,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_first',
    dilation_rate=(1, 1),
    name='conv_1',
    use_bias=False,
)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)


onnx_model, _ = tf2onnx.convert.from_keras(
    model=model,
    opset=13,
    large_model=False,
)

onnx.save_model(onnx_model, "conv.onnx")
```

**Screenshots**
Conv is normal, but dilated conv is a mess.

![image](https://user-images.githubusercontent.com/17606112/134722984-bf304922-2c69-4c9a-8db2-f85a9d4f04f5.png)

**Additional context**
N/A

**Comment by TomWildenhain-Microsoft** [comment]
Keras is not using the dilations property of Conv in TF and is surrounding the Conv with SpaceToBatchND and BatchToSpaceND ops.
![image](https://user-images.githubusercontent.com/67606533/134970470-f2f8c0cb-3d6f-4b39-9de3-f094b231bda5.png)

tf2onnx doesn't recognize this pattern and converts the ops individually causing a complicated model.  The solution is to add a rewriter for this pattern.  I'm not devoting a lot of time to tf2onnx currently, but if you contribute a PR adding a rewriter I will help review it.

Here is an example to work from:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/rewriter/conv2d_with_add_rewriter.py

**Comment by leimao** [comment]
Thanks very much @TomWildenhain-Microsoft. I will try to see if I got time for this. I am less experienced with TF-Keras model protobuf. 
BTW, does Microsoft own and actively maintain this repository? Thank you,

**Comment by garymm** [comment]
@leimao It is actively maintained by Microsoft, but I'd say it's owned by the ONNX community, which is part of the LF AI & Data Foundation.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft I am looking into the problem now. Could you please inform me of how to generate the figure in your comments? Thank you.

**Comment by TomWildenhain-Microsoft** [comment]
The image is a screenshot from netron, a neural network visualizer. Very useful for debugging.
https://github.com/lutzroeder/Netron

I extracted the frozen graph during conversion at this line:
https://github.com/onnx/tensorflow-onnx/blob/446494eea2fb80b4beca13914811678399c91e11/tf2onnx/convert.py#L159

Netron can view .onnx and .pb files, as well as a lot of other neural network formats.

**Comment by leimao** [comment]
> The image is a screenshot from netron, a neural network visualizer. Very useful for debugging. https://github.com/lutzroeder/Netron
> 
> I extracted the frozen graph during conversion at this line:
> 
> https://github.com/onnx/tensorflow-onnx/blob/446494eea2fb80b4beca13914811678399c91e11/tf2onnx/convert.py#L159
> 
> Netron can view .onnx and .pb files, as well as a lot of other neural network formats.

I see. I was using Netron to visualize the ONNX and the HDF5 model but neither of them produce the visualization that you got. Good to know it is the frozen graph. I had been using Python to print out the layers and ops for debugging.

**Comment by leimao** [comment]
Hello @TomWildenhain-Microsoft, why would the unit test ever fail even if I did not modify the repo?
```
============================================================= short test summary info =============================================================
FAILED tests/test_backend.py::BackendTests::test_conv2d_explicit_padding - AssertionError:
FAILED tests/test_einsum_ml.py::TestEinsumMl::test_onnx_micro_runtime_unsqueeze - TypeError: '>' not supported between instances of 'tuple' and ...
======================================= 2 failed, 512 passed, 379 skipped, 24 warnings in 90.42s (0:01:30) ========================================
```

**Comment by TomWildenhain-Microsoft** [comment]
@leimao Are you running it locally?  Run it again but just the two failing tests and post the full error messages.  Also make sure onnxruntime and onnx are up-to-date.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft, I don't know how to run single tests using `python setup.py test`. Could you please give me some hints?

**Comment by leimao** [comment]
@TomWildenhain-Microsoft All the dependencies should be up-to-date.

**Comment by TomWildenhain-Microsoft** [comment]
Sure.  First install the test dependencies listed here:
https://github.com/onnx/tensorflow-onnx/blob/446494eea2fb80b4beca13914811678399c91e11/setup.py#L77

`pip install graphviz parameterized pytest pytest-cov pyyaml`

Next set the environment variables that determine the opset to use and add tests to your PYTHONPATH. Commands for cmd on Windows:
```
set PYTHONPATH=%PYTHONPATH%;.\tests;.
set TF2ONNX_TEST_OPSET=14
```

Then run a specific test:
`python -m unittest test_backend.BackendTests.test_conv2d_explicit_padding`
`python -m unittest test_einsum_ml.TestEinsumMl.test_onnx_micro_runtime_unsqueeze`

**Comment by leimao** [comment]
@TomWildenhain-Microsoft 
```
# python -m unittest test_einsum_ml.TestEinsumMl.test_onnx_micro_runtime_unsqueeze
2021-09-28 22:57:57.652041: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
WARNING:tensorflow:From /mnt/tests/backend_test_base.py:38: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /mnt/tests/backend_test_base.py:39: The name tf.tables_initializer is deprecated. Please use tf.compat.v1.tables_initializer instead.

E
======================================================================
ERROR: test_onnx_micro_runtime_unsqueeze (test_einsum_ml.TestEinsumMl)
test OnnxMicroRuntime
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/tests/test_einsum_ml.py", line 129, in test_onnx_micro_runtime_unsqueeze
    out = rt.run({'X': x, 'I': i})
  File "/mnt/tf2onnx/optimizer/einsum_optimizer.py", line 68, in run
    out = getattr(self, meth_name)(*inp, **kwargs)
  File "/mnt/tf2onnx/optimizer/einsum_optimizer.py", line 221, in _op_unsqueeze
    return (np.expand_dims(x, axis=tuple(axes)),)
  File "<__array_function__ internals>", line 5, in expand_dims
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/shape_base.py", line 577, in expand_dims
    if axis > a.ndim or axis < -a.ndim - 1:
TypeError: '>' not supported between instances of 'tuple' and 'int'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

**Comment by leimao** [comment]
```
____________________________________________________ BackendTests.test_conv2d_explicit_padding ____________________________________________________

self = <test_backend.BackendTests testMethod=test_conv2d_explicit_padding>

    @check_tf_min_version("1.14", "tf 1.14 needed for explicit padding")
    def test_conv2d_explicit_padding(self):
        x_shape = [1, 35, 35, 288]
        kernel_shape = [3, 3, 288, 384]
        pads = [[0, 0], [1, 2], [3, 4], [0, 0]]
        strides = [1, 1, 1, 1]
        x_val = np.arange(1, 1 + np.prod(x_shape)).astype("float32").reshape(x_shape)
        kernel_val = np.arange(1, 1 + np.prod(kernel_shape)).astype("float32").reshape(kernel_shape)
>       self._conv_test(x_val, kernel_val, strides=strides, padding=pads, rtol=1.1e-05)

tests/test_backend.py:445:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_backend.py:392: in _conv_test
    self._run_test_case(func, [_OUTPUT], {_INPUT: x_val}, rtol=rtol)
tests/test_backend.py:178: in _run_test_case
    return self.run_test_case(func, feed_dict, [], output_names_with_port, **kwargs)
tests/backend_test_base.py:396: in run_test_case
    self.assert_results_equal(expected, actual, rtol, atol, mtol, check_value, check_shape, check_dtype)
tests/backend_test_base.py:128: in assert_results_equal
    self.assertAllClose(expected_val, actual_val, rtol=rtol, atol=atol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

expected = array([[[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+0...0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]]],
      dtype=float32)
actual = array([[[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+0...0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]]],
      dtype=float32)
kwargs = {'atol': 1e-05, 'rtol': 1.1e-05}

    @staticmethod
    def assertAllClose(expected, actual, **kwargs):
>       np.testing.assert_allclose(expected, actual, **kwargs)
E       AssertionError:
E       Not equal to tolerance rtol=1.1e-05, atol=1e-05
E
E       Mismatch: 0.00543%
E       Max absolute difference: 8.388608e+08
E       Max relative difference: 1.6960472e-05
E        x: array([[[[0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
E                 0.000000e+00, 0.000000e+00],
E                [2.794342e+12, 2.794345e+12, 2.794348e+12, ..., 2.795479e+12,...
E        y: array([[[[0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
E                 0.000000e+00, 0.000000e+00],
E                [2.794342e+12, 2.794345e+12, 2.794348e+12, ..., 2.795480e+12,...

tests/backend_test_base.py:62: AssertionError
-------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------
2021-09-28 23:00:02.500974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:15:00.0
2021-09-28 23:00:02.501898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 1 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:2d:00.0
2021-09-28 23:00:02.501927: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 23:00:02.501947: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-09-28 23:00:02.501956: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-09-28 23:00:02.501966: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-09-28 23:00:02.501975: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-09-28 23:00:02.501984: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-09-28 23:00:02.501993: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-09-28 23:00:02.504223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0, 1
2021-09-28 23:00:02.504263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-28 23:00:02.504271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0 1
2021-09-28 23:00:02.504278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N Y
2021-09-28 23:00:02.504283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 1:   Y N
2021-09-28 23:00:02.505741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 31006 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:15:00.0, compute capability: 7.0)
2021-09-28 23:00:02.506589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30905 MB memory) -> physical GPU (device: 1, name: Quadro GV100, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2021-09-28 23:00:02.555978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:15:00.0
2021-09-28 23:00:02.557171: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 1 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:2d:00.0
2021-09-28 23:00:02.557206: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 23:00:02.557231: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-09-28 23:00:02.557245: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-09-28 23:00:02.557256: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-09-28 23:00:02.557269: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-09-28 23:00:02.557281: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-09-28 23:00:02.557293: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-09-28 23:00:02.560132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0, 1
2021-09-28 23:00:02.560175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-28 23:00:02.560196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0 1
2021-09-28 23:00:02.560205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N Y
2021-09-28 23:00:02.560213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 1:   Y N
2021-09-28 23:00:02.562175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 31006 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:15:00.0, compute capability: 7.0)
2021-09-28 23:00:02.566464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30905 MB memory) -> physical GPU (device: 1, name: Quadro GV100, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2021-09-28 23:00:02.572411: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 2
2021-09-28 23:00:02.572556: I tensorflow/core/grappler/clusters/single_machine.cc:360] Starting new session
2021-09-28 23:00:02.573291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:15:00.0
2021-09-28 23:00:02.574372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 1 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:2d:00.0
2021-09-28 23:00:02.574407: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 23:00:02.574436: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-09-28 23:00:02.574452: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-09-28 23:00:02.574466: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-09-28 23:00:02.574481: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-09-28 23:00:02.574495: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-09-28 23:00:02.574510: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-09-28 23:00:02.577255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0, 1
2021-09-28 23:00:02.577297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-28 23:00:02.577307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0 1
2021-09-28 23:00:02.577315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N Y
2021-09-28 23:00:02.577323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 1:   Y N
2021-09-28 23:00:02.579093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 31006 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:15:00.0, compute capability: 7.0)
2021-09-28 23:00:02.580094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30905 MB memory) -> physical GPU (device: 1, name: Quadro GV100, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2021-09-28 23:00:02.586807: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:821] Optimization results for grappler item: graph_to_optimize
2021-09-28 23:00:02.586848: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:823]   constant_folding: Graph size after: 4 nodes (0), 3 edges (0), time = 0.901ms.
2021-09-28 23:00:02.586854: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:823]   function_optimizer: function_optimizer did nothing. time = 0.007ms.
2021-09-28 23:00:02.586868: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:823]   constant_folding: Graph size after: 4 nodes (0), 3 edges (0), time = 1.806ms.
2021-09-28 23:00:02.586874: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:823]   function_optimizer: function_optimizer did nothing. time = 0.005ms.
2021-09-28 23:00:02.594266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:15:00.0
2021-09-28 23:00:02.595157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 1 with properties:
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:2d:00.0
2021-09-28 23:00:02.595190: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-09-28 23:00:02.595217: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-09-28 23:00:02.595228: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-09-28 23:00:02.595240: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-09-28 23:00:02.595252: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-09-28 23:00:02.595263: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-09-28 23:00:02.595274: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-09-28 23:00:02.597424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0, 1
2021-09-28 23:00:02.597465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-28 23:00:02.597473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0 1
2021-09-28 23:00:02.597479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N Y
2021-09-28 23:00:02.597485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 1:   Y N
2021-09-28 23:00:02.598896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 31006 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:15:00.0, compute capability: 7.0)
2021-09-28 23:00:02.599727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30905 MB memory) -> physical GPU (device: 1, name: Quadro GV100, pci bus id: 0000:2d:00.0, compute capability: 7.0)
```

**Comment by leimao** [comment]
@TomWildenhain-Microsoft I think the second one is relatively harmless. You would probably need to adjust the output values so that they are not that large.

**Comment by leimao** [comment]
@TomWildenhain-Microsoft I think I have been able to fix this issue. The merge request will be submitted later as I need to check with manager if a SWIPT from NVIDIA is necessary or not.

**Comment by TomWildenhain-Microsoft** [comment]
@leimao awesome, thanks!  The int/tuple comparison might be a numpy version issue.  On numpy 1.19.5 it is working for me.  Also please add a unit test to your rewriter to test_backend.py.  Add a graph validator arg like:

```python
graph_validator=lambda g: check_op_count(g, "Reshape", 0, disabled=False))
```

Using an op that you expect to not appear if the pattern matches.

**Comment by leimao** [comment]
> @leimao awesome, thanks! The int/tuple comparison might be a numpy version issue. On numpy 1.19.5 it is working for me. Also please add a unit test to your rewriter to test_backend.py. Add a graph validator arg like:
> 
> ```python
> graph_validator=lambda g: check_op_count(g, "Reshape", 0, disabled=False))
> ```
> 
> Using an op that you expect to not appear if the pattern matches.

Thanks. These just look like negative tests right?

**Comment by TomWildenhain-Microsoft** [comment]
> Thanks. These just look like negative tests right?

By "negative tests" do you mean tests that handle a failure case?  I would consider this a positive test where you provide a TF model that you expect to match the pattern and make sure it 1) converts, 2) produces correct results and 3) matched the pattern instead of converting the constituent ops individually.  The arg above goes to the test and will provide 3.  1 and 2 happen automatically with our tests.

**Comment by leimao** [comment]
> > Thanks. These just look like negative tests right?
> 
> By "negative tests" do you mean tests that handle a failure case? I would consider this a positive test where you provide a TF model that you expect to match the pattern and make sure it 1) converts, 2) produces correct results and 3) matched the pattern instead of converting the constituent ops individually. The arg above goes to the test and will provide 3. 1 and 2 happen automatically with our tests.

Thanks. I think the unit test above assumes that if the rewriter does not work there will be some Reshape ops in the ONNX graph. If the rewriter works, then there will be no Reshape ops. Thinking twice, it is a positive test. However, if the assumption no longer hold, this unit test is essentially testing nothing.

**Comment by TomWildenhain-Microsoft** [comment]
Yes, Reshape might not be the best choice and was just an example. An expensive op like Concat/Slice, etc. might be better, or you could even check the number of ops (validator can be an arbitrary function).

The test will also affirm that the pattern replaced by the rewriter is in fact correct.  The op count assertion is in addition to the normal assertions included in all our unit tests.

**Comment by hwangdeyu** [comment]
PR fixed this issue. Close it.
