### ISSUE TITLE
Failed to apply optimize_transpose but model still exports

### ISSUE THREAD

**Issue by cchan-lm** [onnx/tensorflow-onnx#1729]
**Bug description**
While trying out various architectures with `tf2onnx`, I ran into an `optimize_transpose` failure when trying to export [3D U-Net from NVIDIA](https://ngc.nvidia.com/catalog/resources/nvidia:unet3d_medical_for_tensorflow/quickStartGuide). For now, we're just testing untrained models so that purely architecture can be tested. Although the message appears in the log, the model still exports and is viewable in Netron.

**Urgency**
We have a deliverable in October and part of that deliverable is providing guidance on exporting TF models to ONNX. We would like to know if this log we're seeing is a non-issue or something must be done. Thanks!

**System information**
- OS Platform and Distribution): Ubuntu 18.04.5 (MacOS Big Sur 11.5.1 as well)
- Tensorflow Version: 2.6.0 (CPU)
- Python version: 3.9.0
- tf2onnx version: latest (used `pip install git+https://github.com/onnx/tensorflow-onnx`)

**To Reproduce**
1. Use the script below (`python unet3d.py`), which is NVIDIA's 3D-UNet without `tf.contrib` code.
2. Run latest tf2onnx on the model using `python -m tf2onnx.convert --saved-model unet3d_nvidia --output unet3d_nvidia.onnx --opset 13 --verbose`

**Logs**
Below is the log.  Mac OS has the same log as well:
```
/home/cchan/.pyenv/versions/3.9.0/lib/python3.9/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-09-27 08:48:50,260 - WARNING - tf2onnx.tf_loader: '--tag' not specified for saved_model. Using --tag serve
2021-09-27 08:48:53,090 - INFO - tf2onnx.tf_loader: Signatures found in model: [serving_default].
2021-09-27 08:48:53,091 - WARNING - tf2onnx.tf_loader: '--signature_def' not specified, using first signature: serving_default
2021-09-27 08:48:53,091 - INFO - tf2onnx.tf_loader: Output names: ['tf.nn.softmax']
WARNING:tensorflow:From /home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/tf_loader.py:706: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-09-27 08:48:55,182 - WARNING - tensorflow: From /home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/tf_loader.py:706: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2021-09-27 08:48:55,937 - INFO - tf2onnx: inputs: ['input_1:0']
2021-09-27 08:48:55,967 - INFO - tf2onnx: outputs: ['Identity:0']
2021-09-27 08:48:56,210 - INFO - tf2onnx.tfonnx: Using tensorflow=2.6.0, onnx=1.10.1, tf2onnx=1.10.0/446494
2021-09-27 08:48:56,210 - INFO - tf2onnx.tfonnx: Using opset <onnx, 13>
2021-09-27 08:49:06,090 - INFO - tf2onnx.tf_utils: Computed 15 values for constant folding
2021-09-27 08:49:11,602 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose/mul
2021-09-27 08:49:11,602 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose/mul_1
2021-09-27 08:49:11,602 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose/mul_2
2021-09-27 08:49:11,602 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_1/mul
2021-09-27 08:49:11,602 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_1/mul_1
2021-09-27 08:49:11,602 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_1/mul_2
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_2/mul
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_2/mul_1
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_2/mul_2
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_3/mul
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_3/mul_1
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_3/mul_2
2021-09-27 08:49:11,603 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_4/mul
2021-09-27 08:49:11,604 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_4/mul_1
2021-09-27 08:49:11,604 - INFO - tf2onnx.tfonnx: folding node using tf type=Mul, name=StatefulPartitionedCall/model/conv3d_transpose_4/mul_2
2021-09-27 08:49:11,681 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2021-09-27 08:49:11,990 - VERBOSE - tf2onnx.tfonnx: Summay Stats:
	tensorflow ops: Counter({'Const': 244, 'Identity': 33, 'Conv3D': 23, 'FusedBatchNormV3': 22, 'LeakyRelu': 22, 'StridedSlice': 20, 'Shape': 5, 'Pack': 5, 'Conv3DBackpropInputV2': 5, 'ConcatV2': 5, 'NoOp': 3, 'Placeholder': 1, 'Softmax': 1})
	tensorflow attr: Counter({'value': 244, 'dtype': 230, 'data_format': 50, 'dilations': 28, 'padding': 28, 'strides': 28, 'epsilon': 22, 'exponential_avg_factor': 22, 'is_training': 22, 'alpha': 22, 'begin_mask': 20, 'ellipsis_mask': 20, 'end_mask': 20, 'new_axis_mask': 20, 'shrink_axis_mask': 20, 'N': 10, 'out_type': 5, 'axis': 5, 'Tidx': 5, '_acd_function_control_output': 2, 'shape': 1})
	onnx mapped: Counter({'Const': 156, 'Identity': 32, 'Conv3D': 23, 'FusedBatchNormV3': 22, 'LeakyRelu': 22, 'Shape': 5, 'StridedSlice': 5, 'Pack': 5, 'Conv3DBackpropInputV2': 5, 'ConcatV2': 5, 'Placeholder': 1, 'Softmax': 1})
	onnx unmapped: Counter()
2021-09-27 08:49:11,990 - INFO - tf2onnx.optimizer: Optimizing ONNX model
2021-09-27 08:49:11,991 - VERBOSE - tf2onnx.optimizer: Apply optimize_transpose
2021-09-27 08:49:12,091 - WARNING - tf2onnx.optimizer: Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/__init__.py", line 62, in optimize_graph
    graph = opt.optimize(current, iteration) or graph
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 157, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 191, in _optimize_at_current_graph_level
    self.post_optimize_action()
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 123, in post_optimize_action
    new_shape = _calculate_new_shape(self._g, op)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 98, in _calculate_new_shape
    perm_shape = [tagged_shape[p] for p in perm]
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 98, in <listcomp>
    perm_shape = [tagged_shape[p] for p in perm]
IndexError: list index out of range
2021-09-27 08:49:12,092 - VERBOSE - tf2onnx.optimizer: Apply remove_redundant_upsample
2021-09-27 08:49:12,125 - VERBOSE - tf2onnx.optimizer.UpsampleOptimizer: Cast -5 (5->0), Concat -5 (10->5), Const -85 (201->116), Shape -5 (5->0), Slice -5 (5->0), Squeeze -5 (5->0), Unsqueeze -25 (25->0)
2021-09-27 08:49:12,125 - VERBOSE - tf2onnx.optimizer: Apply fold_constants
2021-09-27 08:49:12,150 - VERBOSE - tf2onnx.optimizer.ConstFoldOptimizer: no change
2021-09-27 08:49:12,150 - VERBOSE - tf2onnx.optimizer: Apply const_dequantize_optimizer
2021-09-27 08:49:12,175 - VERBOSE - tf2onnx.optimizer.ConstDequantizeOptimizer: no change
2021-09-27 08:49:12,175 - VERBOSE - tf2onnx.optimizer: Apply loop_optimizer
2021-09-27 08:49:12,198 - VERBOSE - tf2onnx.optimizer.LoopOptimizer: no change
2021-09-27 08:49:12,198 - VERBOSE - tf2onnx.optimizer: Apply merge_duplication
2021-09-27 08:49:12,363 - VERBOSE - tf2onnx.optimizer.MergeDuplicatedNodesOptimizer: Const -78 (116->38)
2021-09-27 08:49:12,363 - VERBOSE - tf2onnx.optimizer: Apply reshape_optimizer
2021-09-27 08:49:12,382 - VERBOSE - tf2onnx.optimizer.ReshapeOptimizer: no change
2021-09-27 08:49:12,382 - VERBOSE - tf2onnx.optimizer: Apply global_pool_optimizer
2021-09-27 08:49:12,401 - VERBOSE - tf2onnx.optimizer.GlobalPoolOptimizer: no change
2021-09-27 08:49:12,401 - VERBOSE - tf2onnx.optimizer: Apply q_dq_optimizer
2021-09-27 08:49:12,420 - VERBOSE - tf2onnx.optimizer.QDQOptimizer: no change
2021-09-27 08:49:12,420 - VERBOSE - tf2onnx.optimizer: Apply remove_identity
2021-09-27 08:49:12,450 - VERBOSE - tf2onnx.optimizer.IdentityOptimizer: Identity -33 (33->0)
2021-09-27 08:49:12,450 - VERBOSE - tf2onnx.optimizer: Apply remove_back_to_back
2021-09-27 08:49:12,468 - VERBOSE - tf2onnx.optimizer.BackToBackOptimizer: Transpose -22 (100->78)
2021-09-27 08:49:12,468 - VERBOSE - tf2onnx.optimizer: Apply einsum_optimizer
2021-09-27 08:49:12,483 - VERBOSE - tf2onnx.optimizer.EinsumOptimizer: no change
2021-09-27 08:49:12,483 - VERBOSE - tf2onnx.optimizer: Apply optimize_transpose
2021-09-27 08:49:12,514 - WARNING - tf2onnx.optimizer: Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/__init__.py", line 62, in optimize_graph
    graph = opt.optimize(current, iteration) or graph
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 157, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 191, in _optimize_at_current_graph_level
    self.post_optimize_action()
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 123, in post_optimize_action
    new_shape = _calculate_new_shape(self._g, op)
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 98, in _calculate_new_shape
    perm_shape = [tagged_shape[p] for p in perm]
  File "/home/cchan/.pyenv/versions/tf-cpu/lib/python3.9/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 98, in <listcomp>
    perm_shape = [tagged_shape[p] for p in perm]
IndexError: list index out of range
2021-09-27 08:49:12,514 - VERBOSE - tf2onnx.optimizer: Apply remove_redundant_upsample
2021-09-27 08:49:12,529 - VERBOSE - tf2onnx.optimizer.UpsampleOptimizer: no change
2021-09-27 08:49:12,529 - VERBOSE - tf2onnx.optimizer: Apply fold_constants
2021-09-27 08:49:12,545 - VERBOSE - tf2onnx.optimizer.ConstFoldOptimizer: no change
2021-09-27 08:49:12,545 - VERBOSE - tf2onnx.optimizer: Apply const_dequantize_optimizer
2021-09-27 08:49:12,560 - VERBOSE - tf2onnx.optimizer.ConstDequantizeOptimizer: no change
2021-09-27 08:49:12,560 - VERBOSE - tf2onnx.optimizer: Apply loop_optimizer
2021-09-27 08:49:12,578 - VERBOSE - tf2onnx.optimizer.LoopOptimizer: no change
2021-09-27 08:49:12,579 - VERBOSE - tf2onnx.optimizer: Apply merge_duplication
2021-09-27 08:49:12,660 - VERBOSE - tf2onnx.optimizer.MergeDuplicatedNodesOptimizer: no change
2021-09-27 08:49:12,660 - VERBOSE - tf2onnx.optimizer: Apply reshape_optimizer
2021-09-27 08:49:12,676 - VERBOSE - tf2onnx.optimizer.ReshapeOptimizer: no change
2021-09-27 08:49:12,676 - VERBOSE - tf2onnx.optimizer: Apply global_pool_optimizer
2021-09-27 08:49:12,690 - VERBOSE - tf2onnx.optimizer.GlobalPoolOptimizer: no change
2021-09-27 08:49:12,691 - VERBOSE - tf2onnx.optimizer: Apply q_dq_optimizer
2021-09-27 08:49:12,705 - VERBOSE - tf2onnx.optimizer.QDQOptimizer: no change
2021-09-27 08:49:12,705 - VERBOSE - tf2onnx.optimizer: Apply remove_identity
2021-09-27 08:49:12,720 - VERBOSE - tf2onnx.optimizer.IdentityOptimizer: no change
2021-09-27 08:49:12,721 - VERBOSE - tf2onnx.optimizer: Apply remove_back_to_back
2021-09-27 08:49:12,738 - VERBOSE - tf2onnx.optimizer.BackToBackOptimizer: no change
2021-09-27 08:49:12,738 - VERBOSE - tf2onnx.optimizer: Apply einsum_optimizer
2021-09-27 08:49:12,753 - VERBOSE - tf2onnx.optimizer.EinsumOptimizer: no change
2021-09-27 08:49:12,756 - INFO - tf2onnx.optimizer: After optimization: Cast -5 (5->0), Concat -5 (10->5), Const -163 (201->38), Identity -33 (33->0), Shape -5 (5->0), Slice -5 (5->0), Squeeze -5 (5->0), Transpose -22 (100->78), Unsqueeze -25 (25->0)
2021-09-27 08:49:13,154 - INFO - tf2onnx: 
2021-09-27 08:49:13,155 - INFO - tf2onnx: Successfully converted TensorFlow model unet3d_nvidia to ONNX
2021-09-27 08:49:13,155 - INFO - tf2onnx: Model inputs: ['input_1']
2021-09-27 08:49:13,155 - INFO - tf2onnx: Model outputs: ['tf.nn.softmax']
2021-09-27 08:49:13,155 - INFO - tf2onnx: ONNX model is saved at unet3d_nvidia.onnx
```

**Additional context**
unet3d.py:
```
import os
import tensorflow as tf

def _normalization(inputs, name, mode):
    training = mode == tf.estimator.ModeKeys.TRAIN

    # tf.contrib is not in base TF2 and paper uses batch norm

    # if name == 'instancenorm':
    #     gamma_initializer = tf.constant_initializer(1.0)
    #     return tf.contrib.layers.instance_norm(
    #         inputs,
    #         center=True,
    #         scale=True,
    #         epsilon=1e-6,
    #         param_initializers={'gamma': gamma_initializer},
    #         reuse=None,
    #         variables_collections=None,
    #         outputs_collections=None,
    #         trainable=True,
    #         data_format='NHWC',
    #         scope=None)

    # if name == 'groupnorm':
    #     return tf.contrib.layers.group_norm(inputs=inputs,
    #                                         groups=16,
    #                                         channels_axis=-1,
    #                                         reduction_axes=(-4, -3, -2),
    #                                         activation_fn=None,
    #                                         trainable=True)

    if name == 'batchnorm':
        return tf.keras.layers.BatchNormalization(axis=-1,
                                                  trainable=True,
                                                  virtual_batch_size=None)(inputs, training=training)
    elif name == 'none':
        return inputs
    else:
        raise ValueError('Invalid normalization layer')


def _activation(x, activation):
    if activation == 'relu':
        return tf.nn.relu(x)
    elif activation == 'leaky_relu':
        return tf.nn.leaky_relu(x, alpha=0.01)
    elif activation == 'sigmoid':
        return tf.nn.sigmoid(x)
    elif activation == 'softmax':
        return tf.nn.softmax(x, axis=-1)
    elif activation == 'none':
        return x
    else:
        raise ValueError("Unknown activation {}".format(activation))


def convolution(x,
                out_channels,
                kernel_size=3,
                stride=1,
                mode=tf.estimator.ModeKeys.TRAIN,
                normalization='batchnorm',
                activation='leaky_relu',
                transpose=False):

    if transpose:
        conv = tf.keras.layers.Conv3DTranspose
    else:
        conv = tf.keras.layers.Conv3D
    regularizer = None#tf.keras.regularizers.l2(1e-5)

    x = conv(filters=out_channels,
             kernel_size=kernel_size,
             strides=stride,
             activation=None,
             padding='same',
             data_format='channels_last',
             kernel_initializer=tf.keras.initializers.GlorotUniform(),  #tf.glorot_uniform_initializer(),
             kernel_regularizer=regularizer,
             bias_initializer=tf.keras.initializers.Zeros(),  #tf.zeros_initializer(),
             bias_regularizer=regularizer)(x)

    x = _normalization(x, normalization, mode)

    return _activation(x, activation)


def upsample_block(x, skip_connection, out_channels, normalization, mode):
    x = convolution(x, kernel_size=2, out_channels=out_channels, stride=2,
                    normalization='none', activation='none', transpose=True)
    x = tf.keras.layers.Concatenate(axis=-1)([x, skip_connection])

    x = convolution(x, out_channels=out_channels, normalization=normalization, mode=mode)
    x = convolution(x, out_channels=out_channels, normalization=normalization, mode=mode)
    return x


def input_block(x, out_channels, normalization, mode):
    x = convolution(x, out_channels=out_channels, normalization=normalization, mode=mode)
    x = convolution(x, out_channels=out_channels, normalization=normalization, mode=mode)
    return x


def downsample_block(x, out_channels, normalization, mode):
    x = convolution(x, out_channels=out_channels, normalization=normalization, mode=mode, stride=2)
    return convolution(x, out_channels=out_channels, normalization=normalization, mode=mode)


def linear_block(x, out_channels, mode, activation='leaky_relu', normalization='none'):
    x = convolution(x, out_channels=out_channels, normalization=normalization, mode=mode)
    return convolution(x, out_channels=out_channels, activation=activation, mode=mode, normalization=normalization)


def output_layer(x, out_channels, activation):
    x = tf.keras.layers.Conv3D(out_channels,
                               kernel_size=3,
                               activation=None,
                               padding='same',
                               kernel_regularizer=None,
                               kernel_initializer=tf.keras.initializers.GlorotUniform(),  #tf.glorot_uniform_initializer(),
                               bias_initializer=tf.keras.initializers.Zeros(),  #tf.zeros_initializer(),
                               bias_regularizer=None)(x)
    return _activation(x, activation)


class Builder:
    def __init__(self, n_classes, mode, normalization='none'):
        self._n_classes = n_classes
        self._mode = mode
        self._normalization = normalization

    def __call__(self, features):
        skip_128 = input_block(x=features,
                               out_channels=32,
                               normalization=self._normalization,
                               mode=self._mode)

        skip_64 = downsample_block(x=skip_128,
                                   out_channels=64,
                                   normalization=self._normalization,
                                   mode=self._mode)

        skip_32 = downsample_block(x=skip_64,
                                   out_channels=128,
                                   normalization=self._normalization,
                                   mode=self._mode)

        skip_16 = downsample_block(x=skip_32,
                                   out_channels=256,
                                   normalization=self._normalization,
                                   mode=self._mode)

        skip_8 = downsample_block(x=skip_16,
                                  out_channels=320,
                                  normalization=self._normalization,
                                  mode=self._mode)

        x = downsample_block(x=skip_8,
                             out_channels=320,
                             normalization=self._normalization,
                             mode=self._mode)

        x = upsample_block(x, skip_8,
                           out_channels=320,
                           normalization=self._normalization,
                           mode=self._mode)

        x = upsample_block(x, skip_16,
                           out_channels=256,
                           normalization=self._normalization,
                           mode=self._mode)

        x = upsample_block(x, skip_32,
                           out_channels=128,
                           normalization=self._normalization,
                           mode=self._mode)

        x = upsample_block(x, skip_64,
                           out_channels=64,
                           normalization=self._normalization,
                           mode=self._mode)

        x = upsample_block(x, skip_128,
                           out_channels=32,
                           normalization=self._normalization,
                           mode=self._mode)

        return output_layer(x=x,
                            out_channels=self._n_classes,
                            activation='softmax')


def get_unet3d_model(input_shape, n_classes, mode="evaluate", normalization="batchnorm"):
    input_layer = tf.keras.Input(input_shape)
    output_layer = Builder(n_classes, mode, normalization)(input_layer)

    return tf.keras.Model(input_layer, output_layer)


if __name__ == "__main__":
    model_dir = os.path.join(os.path.dirname(__file__), "unet3d_nvidia")
    model = get_unet3d_model(input_shape=(128, 128, 128, 3), n_classes=3)
    model.save(model_dir)
```

**Comment by TomWildenhain-Microsoft** [comment]
Hi @cchan-lm, thanks for reporting this issue.  tf2onnx will attempt to recover when an optimizer crashes (reverting to the graph before that optimizer), but crashes indicate a bug and should be fixed.  The transpose optimizer is pretty important, so if it crashes you won't get any of its benefits and the model might be slower.

The crash is happening in this function:
https://github.com/onnx/tensorflow-onnx/blob/446494eea2fb80b4beca13914811678399c91e11/tf2onnx/optimizer/transpose_optimizer.py#L92

The function replaces Transpose ops with Reshape ops when possible (the order of non-1 axes doesn't change).  I don't see any issue with the logic, but the most likely cause is an incorrect shape exists in the graph.  I unfortunately don't have a lot of time to work on tf2onnx right now, but if you can find the bug and submit a PR to fix it, I will review it.  Try attaching the python debugger and see if the shape there is correct.  If not, try to find where the incorrect shape is introduced.

**Comment by cchan-lm** [comment]
Thank you for your response, @TomWildenhain-Microsoft! If an incorrect shape is the likely cause, then it could be due to the input layer I added. My bandwidth is pretty limited as well, but I'll try looking into it.

**Comment by fatcat-z** [comment]
@cchan-lm 

I've tried your scripts with environment settings below, seems like this issue has gone and optimize_transpose could work well.

tensorflow=2.8.0-dev20211208(pip install tf-nightly)
onnx=1.10.2
tf2onnx=1.10.0/72d646(nightly job)

Could you please double check this in your machine? Thanks.

**Comment by cchan-lm** [comment]
@fatcat-z Thank you for testing this! I've tried again with the onnx and tf2onnx versions you specified, but kept tensorflow at 2.6.0 to keep things consistent. The optimize_transpose error is gone on my end as well!

Curious, what resolved this?

**Comment by fatcat-z** [comment]
> 



> @fatcat-z Thank you for testing this! I've tried again with the onnx and tf2onnx versions you specified, but kept tensorflow at 2.6.0 to keep things consistent. The optimize_transpose error is gone on my end as well!
> 
> Curious, what resolved this? And when can we expect tf2onnx 1.10.0 to be officially released?


Didn't take a deep look on possible root cause yet so no idea at this moment.
