### ISSUE TITLE
Op type not registered 'BucketizeWithInputBoundaries'

### ISSUE THREAD

**Issue by MatthewDGlynn** [onnx/tensorflow-onnx#1745]
**Describe the bug**
New to Tensorflow and trying to get these existing models within my team converted into ONNX to see if we can use the tool for better model inference. Currently just trying to convert a simple saved_model.pb into an onnx file. When I run tf2onnx.convert I am getting an error around 'BucketizeWithInputBoundaries' which is located within the model file, not sure if I need to create some kind of customized way of handling that when converting to onnx. Our models are created with TF 1.14 I believe. 

**Stacktrace**
**Command ->** tensorflow-onnx % python -m tf2onnx.convert --saved-model ../1 --output model.onnx

/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /Users/workspace/tensorflow-onnx/tf2onnx/verbose_logging.py:81: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-10-18 17:04:07,959 - WARNING - From /Users/workspace/tensorflow-onnx/tf2onnx/verbose_logging.py:81: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-10-18 17:04:07,982 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2021-10-18 17:04:07,982 - WARNING - '--signature_def' not provided. Using all signatures.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/workspace/tensorflow-onnx/tf2onnx/convert.py", line 640, in <module>
    main()
  File "/Users/workspace/tensorflow-onnx/tf2onnx/convert.py", line 243, in main
    use_graph_names=args.use_graph_names)
  File "/Users/workspace/tensorflow-onnx/tf2onnx/tf_loader.py", line 630, in from_saved_model
    _from_saved_model_v1(sess, model_path, input_names, output_names, tag, signatures, use_graph_names)
  File "/Users/workspace/tensorflow-onnx/tf2onnx/tf_loader.py", line 418, in _from_saved_model_v1
    imported = tf.saved_model.loader.load(sess, tag, model_path)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/Users/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'BucketizeWithInputBoundaries' in binary running on C02F7532MD6N. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Urgency**
Would like to try and get ONNX working with Tensorflow models, ASAP, but not urgent. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): System Version: macOS 11.6 (20G165)
- Tensorflow Version: 1.15.0
- Python version: Python 3.7.12

**To Reproduce**
Unable to provide model file, however, this model file does contain this 'BucketizeWithInputBoundaries' that I'm unable to find a reference to in our model generation code and very little information on Google. 

Example of the BucketizeWithInputBoundaries within the model file:
`<transform/transform/bucketize_2/apply_buckets/assign_bucketsBucketizeWithInputBoundariestransform/transform/Select_584transform/transform/bucketize_2/quantiles/ExpandDims*
T0*#
_output_shapes`

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Looks like the converter is failing before it even gets to the converter part. TF can't load the model because the op isn't in the TF binary. This StackOverflow post looks relevant:

https://stackoverflow.com/questions/55362917/tf-lite-converter-with-tensorflow-extended-pipeline-chicago-taxi-pipeline-examp

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
