### ISSUE TITLE
[BUG] converting tf2 models to onnx throwing error.

### ISSUE THREAD

**Issue by posEdgeOfLife** [onnx/tensorflow-onnx#1767]
**Describe the bug**
When converting the axial-deeplab model from google tf2 repo to onnx, an error occured and the model is not able to convert from tf2 to onnx.

Command I ran:
python -m tf2onnx.convert --saved-model C:\develop\max_deeplab_l_backbone_os16_axial_deeplab_cityscapes_trainfine_saved_model --opset 13 --output model.onnx

Error:
ValueError: Node 'StatefulPartitionedCall/DeepLab/max_deeplab_l_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique

**Urgency**
None

**System information**
Windows 11
tf2onnx 1.7.1
python version 3.6.12

**To Reproduce**

Model comes from official google deeplab git repo.
Downloaded from their demo scripts:
https://github.com/google-research/deeplab2/blob/main/DeepLab_Demo.ipynb
or here
https://storage.googleapis.com/gresearch/tf-deeplab/saved_model/max_deeplab_s_backbone_os16_axial_deeplab_cityscapes_trainfine_saved_model.tar.gz

run the command with this saved model would trigger the error.

**Could someone kindly tell what is the error and how to resolve it? Thanks in advance.**

**Comment by guschmue** [comment]
This comes from tensorflow itself when we call convert_variables_to_constants_v2()
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gs/tensorflow-onnx/tf2onnx/convert.py", line 633, in <module>
    main()
  File "/home/gs/tensorflow-onnx/tf2onnx/convert.py", line 236, in main
    use_graph_names=args.use_graph_names)
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 615, in from_saved_model
    tag, signatures, concrete_function, large_model, use_graph_names)
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 598, in _from_saved_model_v2
    frozen_graph, initialized_tables = from_trackable(imported, concrete_func, inputs, outputs, large_model)
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 225, in from_trackable
    raise e
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 221, in from_trackable
    frozen_graph = from_function(concrete_func, inputs, outputs, large_model)
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 280, in from_function
    raise e
  File "/home/gs/tensorflow-onnx/tf2onnx/tf_loader.py", line 273, in from_function
    frozen_func = convert_variables_to_constants_v2(func, lower_control_flow=False, aggressive_inlining=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1156, in convert_variables_to_constants_v2
    converted_input_indices)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1082, in _construct_concrete_function
    new_output_names)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 660, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 631, in wrap_function
    collections={}),
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1143, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 654, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 552, in new_func
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 412, in import_graph_def
    producer_op_list=producer_op_list)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 508, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'StatefulPartitionedCall/DeepLab/max_deeplab_s_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique
```

**Comment by posEdgeOfLife** [comment]
@guschmue thank you very much for responding. Could you provide some details to reproduce this in tensorflow environment, will it happen when I load this model using tensorflow?  If so, I will reproduce it and take it to the tensorflow community.  Thanks a lot!

**Comment by guschmue** [comment]
We load the saved-model and eventually call tensorflow/convert_variables_to_constants_v2() to make variables constants and the error under there. Need to look a little at the deeplab2 source to see if we can work around it. 
In the deeplab2 source I also see some custom ops - that might become an issue too.

**Comment by posEdgeOfLife** [comment]
> We load the saved-model and eventually call tensorflow/convert_variables_to_constants_v2() to make variables constants and the error under there. Need to look a little at the deeplab2 source to see if we can work around it. In the deeplab2 source I also see some custom ops - that might become an issue too.

Ok, thanks. So looks like the model loads fine but only when tensorflow/convert_variables_to_constants_v2 is causing an issue, which is used in tf2onnx. Per my very shallow understanding, I can't say if this is a tensorflow issue or not or how they should fix it.. for the network i was looking at, axial-deeplab, i think all ops are defined in onnx, IMO. I looked at the source code and didn't find anything beyond the onnx ops.

**Comment by guschmue** [comment]
yes, that is all correct. They do have custom ops but it depends how the model was exported - there is a switch here:
https://github.com/google-research/deeplab2/blob/main/export_model.py#L48
that decides if they use the custom ops or not.

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
