### ISSUE TITLE
converting openNMT tf1 models to onnx throwing error

### ISSUE THREAD

**Issue by HelloShirleyHello** [onnx/tensorflow-onnx#1770]
**Describe the bug**
Can't convert the decoder part of openNMT model to onnx format. I debug the problem and find the bug is related to "while loop" operator. With this bug, I can't convert openNMT tensorflow model to onnx format.

**Urgency**
none

**System information**
- Linux Ubuntu 20.04:
- Tensorflow Version: 1.15
- Python version: 3.8.10

**To Reproduce**
https://www.dropbox.com/sh/l6udrmjt6w8rryt/AACKP_I10pmS2UWMXk2lh6Iva?dl=0
There are two folder , "correct one" and "with debug".
in "correct one" folder, there is a saved model and a onnx file. The onnx file is generated by the saved model using command 
python -m tf2onnx.convert --saved-model saved_model/ --output onnx_model/nmt_decoder.onnx  --opset=13
in "with debug" folder. I made small change to the saved model and the convert failed with error (the screenshot of the error in "with debug" folder):

2021-11-12 03:45:37,407 - ERROR - rewriter <function rewrite_cond at 0x7f89314d2280>: exception make_sure failure: Cannot find node with output 'transformer/decoder_1/while/Identity_30:0' in graph 'tf2onnx__3'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 489, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 237, in main
    model_proto, _ = _convert_common(
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 154, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 533, in process_tf_graph
    g = process_parsed_graph(g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter, target,
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 628, in process_parsed_graph
    run_rewriters(g, rewriters, continue_on_error)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 363, in run_rewriters
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 354, in run_rewriters
    ops = func(g, g.get_nodes())
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/rewriter/cond_rewriter.py", line 320, in rewrite_cond
    return CondRewriter(g).rewrite()
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/rewriter/cond_rewriter.py", line 56, in rewrite
    return self.run()
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/rewriter/cond_rewriter.py", line 63, in run
    self.g.topological_sort(self.g.get_nodes())
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/graph.py", line 1030, in topological_sort
    utils.make_sure(j is not None, "Cannot find node with output %r in graph %r", inp, self.graph_name)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/utils.py", line 234, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Cannot find node with output 'transformer/decoder_1/while/Identity_30:0' in graph 'tf2onnx__3'

**Comment by fatcat-z** [comment]
@HelloShirleyHello ,

Is it possible you can share us the change you made to the model?

**Comment by fatcat-z** [comment]
It's been over 6 months, so closing this. Feel free to open a new one if the issue still exists.
