### ISSUE TITLE
SavedModel file does not exist error (when the file exists)

### ISSUE THREAD

**Issue by laumecha** [onnx/tensorflow-onnx#1775]
**Describe the bug**
I am trying to convert a TensorFlow model to ONNX model using:
```
> python -m tf2onnx.convert --saved-model /workspace/tensorflow-onnx/tests/models/conv-layers --output model.onnx 
```
But I am getting the following error:
```
Vitis-AI /workspace/downloaded_models/tensoflow/tf_yolov3_voc_416_416_65.63G_1.4/float > python -m tf2onnx.convert --saved-model /workspace/tensorflow-onnx/tests/models/conv-layers --output model.onnx 
/opt/vitis_ai/conda/lib/python3.9/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2021-11-17 08:49:43.603189: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-17 08:49:43,612 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/vitis_ai/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tf2onnx/convert.py", line 633, in <module>
    main()
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tf2onnx/convert.py", line 233, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tf2onnx/tf_loader.py", line 614, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tf2onnx/tf_loader.py", line 552, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 878, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 60, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/home/vitis-ai-user/.local/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /workspace/tensorflow-onnx/tests/models/conv-layers/{saved_model.pbtxt|saved_model.pb}

```

Clearly I have the source model in the specified folder:
```
> ls /workspace/tensorflow-onnx/tests/models/conv-layers 
frozen.pb  SavedModel.pb
```

I have also tried:
```
 > python -m tf2onnx.convert --saved-model /workspace/tensorflow-onnx/tests/models/conv-layers/SavedModel.pb --output model.onnx 
 > python -m tf2onnx.convert --saved-model ./SavedModel.pb --output model.onnx 
 > python -m tf2onnx.convert --saved-model . --output model.onnx 
```
But this does not work either.

**Urgency**
none

**System information**
- tensorflow              2.6.0
- Python version       3.9.5
- tf2onnx                 1.10.0

**Comment by laumecha** [comment]
Solved by:

change the name to "saved_model.pb" and then 
```
python -m tf2onnx.convert --saved-model /workspace/tensorflow-onnx/tests/models/conv-layers --output model.onnx
```
