### ISSUE TITLE
ValueError: Graph has cycles.

### ISSUE THREAD

**Issue by zcc720** [onnx/tensorflow-onnx#182]
when i convert my Object Detection Models(ssd_mobilenet_v2) to onnx, I encountered this mistake.
How should I solve this problem?

python -m tf2onnx.convert --input   ./ssd_mobilenet_feature_extractor2.pb --inputs image_tensor:0 --outputs detection_boxes:0,detection_scores:0,detection_classes:0,num_detections:0 --output=./mobilenet.onnx

**Comment by guschmue** [comment]
graph has cycles normally hints there is a control flow (like a while loop) in the graph which ssd would do.
Support for this is in onnx since opset 8 (ie. scan) and we'll add this pretty soon to the converter.

**Comment by sangwook236** [comment]
While I convert a YOLOv3 TensorFlow model, I also encountered the same error "Graph has cycles".
Do you have any plan to resolve this issue?
Please let me know ...
Thank you in advance.

**Comment by pengwa** [comment]
not yet, havn't get time for them. basic while loop was supported, but I assumed there was advanced usage , need further validation.

**Comment by dima85** [comment]
Same problem with RetinaNet implementation

**Comment by NylaWorker** [comment]
Same here, has this been fixed?

**Comment by nbcsm** [comment]
the circle issue is resolved.
but yolov3 and ssd_mobilenet_v2 also requires onnx opset 10 (e.g. NMS, TopK), which is coming soon with onnx 1.5 release.
please stay tuned.

**Comment by mkawahito** [comment]
I tried May 9th build, but I got the same error. Has the fix already integrated in the current build?

**Comment by nbcsm** [comment]
yolov3 and ssd_mobilenet should be supported now, please install onnx 1.5 and latest tf2onnx master branch.
```--opset 10``` is required.
please let us know if there is any other issue.

**Comment by mkawahito** [comment]
I tried to convert another model. Here is the log. Can you find if the fix should have already solved this problem?

```
$ python3 -m tf2onnx.convert --opset 10 --input kagglelstm1.pb --output kagglelstm1.onnx --inputs lstm_1_input:0 --outputs dense_1/Sigmoid:0 --continue_on_error

2019-05-10 05:31:46,509 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.0/348b4d
2019-05-10 05:31:46,510 - INFO - Using opset <onnx, 10>
2019-05-10 05:31:46,686 - ERROR - rewriter <function rewrite_single_direction_lstm at 0x7f4fe2b891e0>: exception list index out of range
2019-05-10 05:31:46,688 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 29, in rewrite_single_direction_lstm\n    return r.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/unit_rnn_rewriter_base.py", line 63, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,696 - ERROR - rewriter <function rewrite_single_direction_gru at 0x7f4fe2b997b8>: exception list index out of range
2019-05-10 05:31:46,696 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 38, in rewrite_single_direction_gru\n    return r.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/unit_rnn_rewriter_base.py", line 63, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,704 - ERROR - rewriter <function rewrite_custom_rnn_cell at 0x7f4fe2b99e18>: exception list index out of range
2019-05-10 05:31:46,704 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 46, in rewrite_custom_rnn_cell\n    return  CustomRnnRewriter(g).run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/custom_rnn_rewriter.py", line 43, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,710 - ERROR - rewriter <function rewrite_generic_loop at 0x7f4fe2b99ea0>: exception list index out of range
2019-05-10 05:31:46,710 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 50, in rewrite_generic_loop\n    return LoopRewriter(g).run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter.py", line 35, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,713 - ERROR - rewriter <function rewrite_cond at 0x7f4fe2b67488>: exception Graph has cycles.
2019-05-10 05:31:46,714 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/cond_rewriter.py", line 321, in rewrite_cond\n    return CondRewriter(g).rewrite()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/cond_rewriter.py", line 56, in rewrite\n    return self.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/cond_rewriter.py", line 63, in run\n    self.g.topological_sort(self.g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 775, in topological_sort\n    _push_stack(stack, node, in_stack)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 732, in _push_stack\n    raise ValueError(\'Graph has cycles.\')\n', 'ValueError: Graph has cycles.\n']
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/convert.py", line 145, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/convert.py", line 129, in main
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 867, in make_model
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 794, in make_graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 775, in topological_sort
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 732, in _push_stack
ValueError: Graph has cycles.
```

**Comment by nbcsm** [comment]
could you share the model please?
it is hard to tell what is the issue from the log...

**Comment by mkawahito** [comment]
Could you try [kagglelstm1.pb.zip](https://github.com/onnx/tensorflow-onnx/files/3165160/kagglelstm1.pb.zip) ?

**Comment by zcc720** [comment]
@nbcsm ，As you said, I succeeded. Thank you.
`2019-05-13 15:43:35,788 - INFO - Using tensorflow=1.12.0, onnx=1.5.0, tf2onnx=1.5.0/73ac94
2019-05-13 15:43:35,788 - INFO - Using opset <onnx, 10>
2019-05-13 15:44:12,889 - INFO - 
2019-05-13 15:44:13,967 - INFO - Optimizing ONNX model
2019-05-13 15:44:57,129 - INFO - After optimization: Gather +6 (553->559), Const +5 (2132->2137), Reshape -1 (314->313), Shape -1 (112->111), Cast -2 (1301->1299), Unsqueeze -7 (436->429), Identity -77 (79->2), Add -89 (379->290), Transpose -191 (389->198)
2019-05-13 15:44:58,852 - INFO - 
2019-05-13 15:44:58,853 - INFO - Successfully converted TensorFlow model ./ssd_inception_v2_coco_2017_11_17/frozen_inference_graph.pb to ONNX
2019-05-13 15:44:59,009 - INFO - ONNX model is saved at ./ssd_inception_v2_coco_2017_11_17/ssd_inception_v2_coco.onnx`
