### ISSUE TITLE
Failed to load Library - OnnxRuntime Yolov5 GPU Support C# 

### ISSUE THREAD

**Issue by MagnusGabell** [onnx/tensorflow-onnx#1826]
**Describe the bug**
I have made a program that can use the Yolo5 model as onnx format for CPU. When chaning the library to GPU I get

Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:Fail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
   at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithCudaProvider(Int32 deviceId)
   at Yolov5Net.App.Program.Main(String[] args) in C:\Development\YoloV5\yolov5-net\src\Yolov5Net.App\Program.cs:line 23

How can I get the program to utilize the GPU instead of CPU?
I have installed : cuda and cuDNN according to instructions.
Tested latest and version 10.1.
Graphic card is Quadro M1200.

**System information**
- OS: Windows 10
- Model: Yolo5l

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

**To Reproduce**
Write a code for CPU then change to GPU by adding a 
`
var opts = new SessionOptions();
opts.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE;
var so = SessionOptions.MakeSessionOptionWithCudaProvider(1);
`
It crash on MakeSessionOptionWithCudaProvider(1). I dont want to use 0 cause its built in GFX.

**Screenshots**
![image](https://user-images.githubusercontent.com/8070347/150152348-74f560f0-0216-4f99-b399-9177d0b07328.png)

**Additional context**
Please help. I dont know how to get this final step to work. The libraries are all copied in to bin. They exists everywhere.
Is this related to the Windows 10 pipeline issue for onnx?

**Comment by MagnusGabell** [comment]
Move issue to Microsoft/onnxruntime. Not really a tensorflow onnx issue..

**Comment by MagnusGabell** [comment]
See above statement
