### ISSUE TITLE
Complex operations not supported

### ISSUE THREAD

**Issue by lminer** [onnx/tensorflow-onnx#1830]
I'm trying to get onnx to work with my model that has a few complex operations, but am getting an error. From the release history, it appears complex ops are now supported. Not sure what's going on.

I'm using:
TF 2.7.0
tf2onnx=1.10.0/5cd3b5
opset=15

Here's the error. 

```python
.../lib/python3.8/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-01-20 13:55:38,514 - INFO - Signatures found in model: [serving_default].
2022-01-20 13:55:38,516 - INFO - Output names: ['output_0']
WARNING:tensorflow:From .../lib/python3.8/site-packages/tf2onnx/tf_loader.py:706: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2022-01-20 13:55:43,649 - WARNING - From .../lib/python3.8/site-packages/tf2onnx/tf_loader.py:706: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2022-01-20 13:55:45,274 - INFO - Using tensorflow=2.7.0, onnx=1.10.2, tf2onnx=1.10.0/5cd3b5
2022-01-20 13:55:45,274 - INFO - Using opset <onnx, 15>
2022-01-20 13:55:46,891 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,892 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,893 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,897 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,967 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,968 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,969 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,971 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,972 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,973 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,974 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,975 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:46,977 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:47,035 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:47,559 - WARNING - Cannot infer shape for StatefulPartitionedCall/ParseTensor: StatefulPartitionedCall/ParseTensor:0
2022-01-20 13:55:47,958 - INFO - Computed 0 values for constant folding
2022-01-20 13:55:51,306 - ERROR - Tensorflow op [while/StatefulPartitionedCall/StatefulPartitionedCall/stft2complexformat/Real: Real] is not supported
2022-01-20 13:55:51,306 - ERROR - Tensorflow op [while/StatefulPartitionedCall/StatefulPartitionedCall/stft2complexformat/Imag: Imag] is not supported
2022-01-20 13:55:51,444 - ERROR - Tensorflow op [while/StatefulPartitionedCall/StatefulPartitionedCall/complexformat2stft/Complex: Complex] is not supported
2022-01-20 13:55:51,444 - ERROR - Tensorflow op [while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Real: Real] is not supported
2022-01-20 13:55:51,444 - ERROR - Tensorflow op [while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Imag: Imag] is not supported
2022-01-20 13:55:51,444 - ERROR - Failed to convert node 'while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs_2' (fct=<bound method ComplexAbsOp.version_13 of <class 'tf2onnx.onnx_opset.signal.ComplexAbsOp'>>)
'OP=ComplexAbs\nName=while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs_2\nInputs:\n\twhile/StatefulPartitionedCall/StatefulPartitionedCall/complexformat2stft/Complex:0=Complex, [-1, 128, 2048, 2], 14\nOutpus:\n\twhile/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs_2:0=[-1, 128, 2048, 2], 1'
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 981, in version_13
    cls.any_version(13, ctx, node, **kwargs)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 939, in any_version
    utils.make_sure(
  File ".../lib/python3.8/site-packages/tf2onnx/utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: ComplexAbs expected the first dimension to be 2 but shape is [-1, 128, 2048, 2]
2022-01-20 13:55:51,445 - ERROR - Failed to convert node 'while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs_1' (fct=<bound method ComplexAbsOp.version_13 of <class 'tf2onnx.onnx_opset.signal.ComplexAbsOp'>>)
'OP=ComplexAbs\nName=while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs_1\nInputs:\n\twhile/StatefulPartitionedCall/StatefulPartitionedCall/complexformat2stft/Complex:0=Complex, [-1, 128, 2048, 2], 14\nOutpus:\n\twhile/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs_1:0=[-1, 128, 2048, 2], 1'
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 981, in version_13
    cls.any_version(13, ctx, node, **kwargs)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 939, in any_version
    utils.make_sure(
  File ".../lib/python3.8/site-packages/tf2onnx/utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: ComplexAbs expected the first dimension to be 2 but shape is [-1, 128, 2048, 2]
2022-01-20 13:55:51,445 - ERROR - Failed to convert node 'while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs' (fct=<bound method ComplexAbsOp.version_13 of <class 'tf2onnx.onnx_opset.signal.ComplexAbsOp'>>)
'OP=ComplexAbs\nName=while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs\nInputs:\n\twhile/StatefulPartitionedCall/StatefulPartitionedCall/complexformat2stft/Complex:0=Complex, [-1, 128, 2048, 2], 14\nOutpus:\n\twhile/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Abs:0=[-1, 128, 2048, 2], 1'
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 981, in version_13
    cls.any_version(13, ctx, node, **kwargs)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 939, in any_version
    utils.make_sure(
  File ".../lib/python3.8/site-packages/tf2onnx/utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: ComplexAbs expected the first dimension to be 2 but shape is [-1, 128, 2048, 2]
2022-01-20 13:55:51,446 - ERROR - Tensorflow op [while/StatefulPartitionedCall/StatefulPartitionedCall/MASK/Complex: Complex] is not supported
2022-01-20 13:55:51,446 - ERROR - Unsupported ops: Counter({'Real': 2, 'Imag': 2, 'Complex': 2})
Traceback (most recent call last):
  File ".../lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../lib/python3.8/site-packages/tf2onnx/convert.py", line 633, in <module>
    main()
  File ".../lib/python3.8/site-packages/tf2onnx/convert.py", line 264, in main
    model_proto, _ = _convert_common(
  File ".../lib/python3.8/site-packages/tf2onnx/convert.py", line 162, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 438, in process_tf_graph
    g = process_graphs(main_g, subgraphs, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 487, in process_graphs
    fg = process_parsed_graph(g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 600, in process_parsed_graph
    raise exceptions[0]
  File ".../lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 981, in version_13
    cls.any_version(13, ctx, node, **kwargs)
  File ".../lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 939, in any_version
    utils.make_sure(
  File ".../lib/python3.8/site-packages/tf2onnx/utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: ComplexAbs expected the first dimension to be 2 but shape is [-1, 128, 2048, 2]
```

**Comment by garlicdevs** [comment]
I have another problems with ComplexAbs

ERROR - Failed to convert node 'StatefulPartitionedCall/model/lambda/FFT' (fct=<bound method FFTOp.version_13 of <class 'tf2onnx.onnx_opset.signal.FFTOp'>>)
'OP=FFT\nName=StatefulPartitionedCall/model/lambda/FFT\nInputs:\n\tStatefulPartitionedCall/model/lambda/mul:0=Mul, [-1, -1, 256], 14\nOutpus:\n\tStatefulPartitionedCall/model/lambda/FFT:0=[-1, -1, 256], 14'
Traceback (most recent call last):
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 372, in version_13
    return cls.any_version(False, 13, ctx, node, **kwargs)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 170, in any_version
    utils.make_sure(
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Current implementation of FFT or RFFT assumes the input is real or complex produced by a node Cast just before this one.
2022-01-25 08:29:29,218 - ERROR - Failed to convert node 'StatefulPartitionedCall/model/lambda/Abs' (fct=<bound method ComplexAbsOp.version_13 of <class 'tf2onnx.onnx_opset.signal.ComplexAbsOp'>>)
'OP=ComplexAbs\nName=StatefulPartitionedCall/model/lambda/Abs\nInputs:\n\tStatefulPartitionedCall/model/lambda/FFT:0=FFT, [-1, -1, 256], 14\nOutpus:\n\tStatefulPartitionedCall/model/lambda/Abs:0=[-1, -1, 256], 1'
Traceback (most recent call last):
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 981, in version_13
    cls.any_version(13, ctx, node, **kwargs)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 939, in any_version
    utils.make_sure(
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: ComplexAbs expected the first dimension to be 2 but shape is [-1, -1, 256]
Traceback (most recent call last):
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/convert.py", line 636, in <module>
    main()
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/convert.py", line 264, in main
    model_proto, _ = _convert_common(
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/convert.py", line 162, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 438, in process_tf_graph
    g = process_graphs(main_g, subgraphs, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 490, in process_graphs
    g = process_parsed_graph(main_g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 600, in process_parsed_graph
    raise exceptions[0]
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 372, in version_13
    return cls.any_version(False, 13, ctx, node, **kwargs)
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/onnx_opset/signal.py", line 170, in any_version
    utils.make_sure(
  File "/home/garlicdevs/anaconda3/envs/vectalabs/lib/python3.8/site-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Current implementation of FFT or RFFT assumes the input is real or complex produced by a node Cast just before this one.

**Comment by fatcat-z** [comment]
For now, op Complex is still not supported by tf2onnx yet, but ComplexAbs is supported.

**Comment by Yaodada12** [comment]
@lminer How did you solved this problem，what is this‘’specifying the batch size‘’ meaning？please help me！！Thank‘s
