### ISSUE TITLE
ValueError: Input 2 of node StatefulPartitionedCall was passed float from stem_conv/kernel:0 incompatible with expected resource.

### ISSUE THREAD

**Issue by satpalsr** [onnx/tensorflow-onnx#1850]
Hey, I am trying to convert the model from [EfficientPose repo](https://github.com/ybkscht/EfficientPose) into onnx.
Here is the error I am receiving
```
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2022-02-15 14:48:26,386 - WARNING - From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2022-02-15 14:48:26,647 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2022-02-15 14:48:26,647 - WARNING - '--signature_def' not provided. Using all signatures.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 2 of node StatefulPartitionedCall was passed float from stem_conv/kernel:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 633, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 285, in main
    output_path=args.output)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 161, in _convert_common
    tf.import_graph_def(frozen_graph, name='')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 2 of node StatefulPartitionedCall was passed float from stem_conv/kernel:0 incompatible with expected resource.
```

Steps I followed:
```
# Following steps are already done & are not present in this colab.
# !git clone https://github.com/ybkscht/EfficientPose.git
# !pip install tensorflow-gpu==1.15.0
# !pip install -r requirements.txt
# !python setup.py build_ext --inplace
# !gdown --id 1dQ8zZXxQL1u2mn6VtwDKEuQWF3nit8G7 # Download Dataset
# !gdown --id 1i8qqChNBYCiKomBjhuvC3PYIZF5ln9x4 # Download weights
# Write "tf.keras.models.save_model(prediction_model, './keras_model_latest', save_format='tf')" at line 123 in evaulate.py
  # (https://github.com/ybkscht/EfficientPose/blob/64b71190df7ecbdfaa8f34a24c1ed6c4c67693ef/evaluate.py#L123)

# Execute evaluate.py to save model
```
**To Reproduce**
[Directly use this Colab](https://colab.research.google.com/drive/1QqHfcBciqMJLSH1_xet68ulyqGlVSKAV?usp=sharing)
or
Follow above steps &
1. `!pip install tf2onnx`
2. `!python3 -m tf2onnx.convert --saved-model ./phi_0_linemod_best_ADD/ --output "model.onnx" --opset 14`

**Comment by Kaladin-Syl-WR** [comment]
Hi @satpalsr 

I got the same error when trying to convert EfficientPose to an Onnx model. I tried upgrading the TensorFlow version and opset value, but it's not working for me. Can you please tell me exactly the steps you took to get the conversion working?

Thanks in advance.

**Comment by romygt** [comment]
hello @Kaladin-Syl-WR 
I am using EfficientPose and I want to convert it to ONNX format to use it in Unity. Unfortunately, I am getting the same error as you. Can you please help me with this? I am really under pressure.
