### ISSUE TITLE
ValueError: Unknown layer: BatchNormalization. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

### ISSUE THREAD

**Issue by OpDaSo** [onnx/tensorflow-onnx#1872]
**Describe the bug**
I want to convert the keras model  "resnet50.h5" to an onnx model "resnet50.onnx"
I get the keras model by:

import tensorflow as tf
model = tf.keras.applications.ResNet50()
model.save("resnet50.h5")

Now, I want to convert it with tf2onnx.convert:
python -m tf2onnx.convert --keras resnet50.h5 --inputs input_layer:0[-1,224,224,3] --output resnet50_.onnx

This command gets:

D:\Programme_DL\conda\envs\tf_gpu\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\Programme_DL\conda\envs\tf_gpu\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
D:\Programme_DL\conda\envs\tf_gpu\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\backend.py:437: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass
 a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
Traceback (most recent call last):
  File "D:\Programme_DL\conda\envs\tf_gpu\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programme_DL\conda\envs\tf_gpu\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programme_DL\conda\envs\tf_gpu\lib\site-packages\tf2onnx\convert.py", line 188, in <module>
    main()
  File "D:\Programme_DL\conda\envs\tf_gpu\lib\site-packages\tf2onnx\convert.py", line 140, in main
    graph_def, inputs, outputs = tf_loader.from_keras(
  File "D:\Programme_DL\conda\envs\tf_gpu\lib\site-packages\tf2onnx\tf_loader.py", line 357, in from_keras
    keras_model = _keras.models.load_model(model_path, custom_objects)
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\save.py", line 201, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\layers\serialization.py", line 123, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\functional.py", line 667, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\functional.py", line 1278, in reconstruct_from_config
    process_layer(layer_data)
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\functional.py", line 1260, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\layers\serialization.py", line 123, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 659, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 556, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown layer: BatchNormalization. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow Version: 2.6.0
- Python version: 3.8.11

**To Reproduce**
Describe steps/code to reproduce the behavior. Please upload/link the model you are trying to convert if possible.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by OpDaSo** [comment]
I tried:

python -m tf2onnx.convert --keras resnet50.h5 --inputs input_layer:0[-1,224,224,3] --output resnet50_.onnx --custom-ops BatchNormalization

But  I received the same error message.

**Comment by xellDart** [comment]
same error

**Comment by fatcat-z** [comment]
@OpDaSo ,

Please update your script which saved the model in your local machine as below:

import os
import tensorflow as tf

model = tf.keras.applications.ResNet50()
model.save(os.path.join("/tmp", model.name))

After this, you should have a new folder /tmp/resnet50, then execute below command could help you to export it to onnx file:

python -m tf2onnx.convert --keras /tmp/resnet50 --output resnet50_.onnx
