### ISSUE TITLE
Cannot run tools/example.sh

### ISSUE THREAD

**Issue by cjluo-nuro** [onnx/tensorflow-onnx#190]
Hi,

I cannot run the new script tools/example.sh checked into the releaser r0.3 commit (@guschmue ):

using tensorflow=1.9.0, onnx=1.2.2, opset=7, tfonnx=0.0.4.0/149990
2018-11-12 14:18:51.126424: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying fold_batch_norms
2018-11-12 14:18:51.127287: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying fold_old_batch_norms
2018-11-12 14:18:51.139556: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cjluo/Workspace/tensorflow-onnx/tf2onnx/convert.py", line 120, in <module>
    main()
  File "/home/cjluo/Workspace/tensorflow-onnx/tf2onnx/convert.py", line 105, in main
    shape_override=args.shape_override)
  File "tf2onnx/tfonnx.py", line 1845, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "tf2onnx/tfonnx.py", line 134, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "tf2onnx/tfonnx.py", line 106, in tflist_to_onnx
    onnx_tensor = utils.tf_to_onnx_tensor(node.get_attr(a), name=port_name(node.name))
  File "/home/cjluo/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2349, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
TypeError: in method 'TF_OperationGetAttrValueProto', argument 2 of type 'char const *

May I know if I'm missing anything?

**Comment by guschmue** [comment]
we currently don't support python2.7. Bunch of folk ran into this already, let me see if we find some time to make it work on 2.7.

**Comment by cjluo-nuro** [comment]
Gotcha, Thanks

**Comment by guschmue** [comment]
We won't be supporting python 2.7 since numpy 1.17 will drop 2.7 support ... no future.
