### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by Meimin-Wang** [onnx/tensorflow-onnx#1913]
```bash
python -m tf2onnx.convert --input ./output_graph_v2.pb --output metro_help.onnx --inputs DecodeJpeg:0 --outputs final_result:0
```
The output as follows:
```bash
Traceback (most recent call last):
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 56, in tf_to_onnx_tensor
    np_data = np_data.astype(np.str)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ms/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/ms/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/convert.py", line 633, in <module>
    main()
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/convert.py", line 285, in main
    output_path=args.output)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/convert.py", line 163, in _convert_common
    custom_op_handlers=custom_op_handlers, **kwargs)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 434, in process_tf_graph
    ignore_default, use_default)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 448, in graphs_from_tf
    ordered_func = resolve_functions(tf_graph)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 759, in resolve_functions
    _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 439, in tflist_to_onnx
    onnx_tensor = tf_to_onnx_tensor(value, name=port_name(node.name))
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 60, in tf_to_onnx_tensor
    np_data = decode(np_data).astype(np.object)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2163, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2241, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2201, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 59, in <lambda>
    decode = np.vectorize(lambda x: x.decode('UTF-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
Besides, 
```python
import tf2onnx
import tensorflow as tf


def load_graph(model_file: str) -> tf.Graph:
    """加载Tensorflow 1.x pb模型
    :param model_file: 模型地址，必须以.pb结尾的模型地址路径
    :return: 返回计算图对象
    """
    assert str.endswith(model_file, '.pb'), '模型文件必须是以.pb为结尾的Tensorflow 1.x预训练模型'
    graph = tf.Graph()
    graph_def = tf.GraphDef()
    with open(model_file, 'rb') as f:
        graph_def.ParseFromString(f.read())
    return graph_def



model_proto, external_tensor_storage = tf2onnx.convert.from_graph_def(
    load_graph('/tmp/output_graph_v2.pb'),
    name='output',
    input_names=['DecodeJpeg:0'],
    output_names=['final_result:0'],
    opset=None,
    custom_ops=None,
    custom_op_handlers=None,
    custom_rewriter=None,
    inputs_as_nchw=None,
    extra_opset=None,
    shape_override=None,
    target=None, large_model=False,
    output_path=None)
```
Perform fail and the error info as follows:

WARNING:tensorflow:From /tmp/tianmao/mindconverter_examples/test.py:13: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From /opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /opt/conda/envs/ms/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Traceback (most recent call last):
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 56, in tf_to_onnx_tensor
    np_data = np_data.astype(np.str)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:
```bash
Traceback (most recent call last):
  File "/tmp/tianmao/mindconverter_examples/test.py", line 33, in <module>
    output_path=None)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/convert.py", line 627, in from_graph_def
    output_path=output_path)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/convert.py", line 163, in _convert_common
    custom_op_handlers=custom_op_handlers, **kwargs)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 434, in process_tf_graph
    ignore_default, use_default)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 448, in graphs_from_tf
    ordered_func = resolve_functions(tf_graph)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 759, in resolve_functions
    _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 439, in tflist_to_onnx
    onnx_tensor = tf_to_onnx_tensor(value, name=port_name(node.name))
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 60, in tf_to_onnx_tensor
    np_data = decode(np_data).astype(np.object)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2163, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2241, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2201, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/opt/conda/envs/ms/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 59, in <lambda>
    decode = np.vectorize(lambda x: x.decode('UTF-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by fatcat-z** [comment]
Could you please try to make an update like below in your code to read the file?

with open(model_file, 'rb') as f:

=>

with open(model_file, encoding="utf8", errors='ignore') as f:

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.

**Comment by Etty-Cohen** [comment]
Hi, I have exactly the same problem @fatcat-z  @Meimin-Wang 
Can you help please?

**Comment by Etty-Cohen** [comment]
> Could you please try to make an update like below in your code to read the file?
> 
> with open(model_file, 'rb') as f:
> 
> =>
> 
> with open(model_file, encoding="utf8", errors='ignore') as f:

Hi, I tried it - changed in the file "utils.py" line 387 but still get that error:
`Traceback (most recent call last):
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 59, in tf_to_onnx_tensor
    np_data = np_data.astype(np.str).astype(object)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 706, in <module>
    main()
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 269, in main
    model_proto, _ = _convert_common(
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 164, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 459, in process_tf_graph
    main_g, subgraphs = graphs_from_tf(tf_graph, input_names, output_names, shape_override, const_node_values,
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 474, in graphs_from_tf
    ordered_func = resolve_functions(tf_graph)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 764, in resolve_functions
    _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 442, in tflist_to_onnx
    onnx_tensor = tf_to_onnx_tensor(value, name=port_name(node.name))
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 62, in tf_to_onnx_tensor
    np_data = decode(np_data).astype(object)
  File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2304, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2382, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2342, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 61, in <lambda>
    decode = np.vectorize(lambda x: x.decode('UTF-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
`

**Comment by fatcat-z** [comment]
> > Could you please try to make an update like below in your code to read the file?
> > with open(model_file, 'rb') as f:
> > =>
> > with open(model_file, encoding="utf8", errors='ignore') as f:
> 
> Hi, I tried it - changed in the file "utils.py" line 387 but still get that error:
> 
> ```
> `Traceback (most recent call last):
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 59, in tf_to_onnx_tensor
>     np_data = np_data.astype(np.str).astype(object)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 706, in <module>
>     main()
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 269, in main
>     model_proto, _ = _convert_common(
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 164, in _convert_common
>     g = process_tf_graph(tf_graph, const_node_values=const_node_values,
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 459, in process_tf_graph
>     main_g, subgraphs = graphs_from_tf(tf_graph, input_names, output_names, shape_override, const_node_values,
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 474, in graphs_from_tf
>     ordered_func = resolve_functions(tf_graph)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 764, in resolve_functions
>     _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 442, in tflist_to_onnx
>     onnx_tensor = tf_to_onnx_tensor(value, name=port_name(node.name))
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 62, in tf_to_onnx_tensor
>     np_data = decode(np_data).astype(object)
>   File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2304, in __call__
>     return self._vectorize_call(func=func, args=vargs)
>   File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2382, in _vectorize_call
>     ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
>   File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2342, in _get_ufunc_and_otypes
>     outputs = func(*inputs)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 61, in <lambda>
>     decode = np.vectorize(lambda x: x.decode('UTF-8'))
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
> `
> ```

Is it possible to share your model file so we can take a look?

**Comment by Etty-Cohen** [comment]
> > > Could you please try to make an update like below in your code to read the file?
> > > with open(model_file, 'rb') as f:
> > > =>
> > > with open(model_file, encoding="utf8", errors='ignore') as f:
> > 
> > 
> > Hi, I tried it - changed in the file "utils.py" line 387 but still get that error:
> > ```
> > `Traceback (most recent call last):
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 59, in tf_to_onnx_tensor
> >     np_data = np_data.astype(np.str).astype(object)
> > UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 706, in <module>
> >     main()
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 269, in main
> >     model_proto, _ = _convert_common(
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 164, in _convert_common
> >     g = process_tf_graph(tf_graph, const_node_values=const_node_values,
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 459, in process_tf_graph
> >     main_g, subgraphs = graphs_from_tf(tf_graph, input_names, output_names, shape_override, const_node_values,
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 474, in graphs_from_tf
> >     ordered_func = resolve_functions(tf_graph)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 764, in resolve_functions
> >     _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 442, in tflist_to_onnx
> >     onnx_tensor = tf_to_onnx_tensor(value, name=port_name(node.name))
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 62, in tf_to_onnx_tensor
> >     np_data = decode(np_data).astype(object)
> >   File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2304, in __call__
> >     return self._vectorize_call(func=func, args=vargs)
> >   File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2382, in _vectorize_call
> >     ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
> >   File "/home/etty/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2342, in _get_ufunc_and_otypes
> >     outputs = func(*inputs)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_utils.py", line 61, in <lambda>
> >     decode = np.vectorize(lambda x: x.decode('UTF-8'))
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
> > `
> > ```
> 
> Is it possible to share your model file so we can take a look?

Hi its not **my** model, but oidv2-resnet_v1_101.ckpt model for google.
I later I saw this answer:
[https://github.com/onnx/tensorflow-onnx/issues/920](url)
 and updated the tf2onnx code but it still does not work.
