### ISSUE TITLE
Converting AutoML saved model (.pb) to ONNX: LookupTableImportV2 doesn't exist in graph

### ISSUE THREAD

**Issue by vilmara** [onnx/tensorflow-onnx#1928]
Hi, I am trying to optimize a TF saved_model (.pb) that was trained with Google AutoML (TF 2.7), and got the error: `LookupTableImportV2 doesn’t exist in graph`, see below

`saved_model_cli convert --dir test/saved_model --output_dir test/trt_model --tag_set serve tensorrt`

Error:

```
INFO:tensorflow:Linked TensorRT version: (8, 2, 1)
INFO:tensorflow:Loaded TensorRT version: (8, 2, 3)
INFO:tensorflow:Loaded TensorRT 8.2.3 and linked TensorFlow against TensorRT 8.2.1. This is supported because TensorRT minor/patctible.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
2022-05-04 03:55:21.547729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 0, name: NVIDIA A30, pci bus id: 0000:3b:00.0, compute capability: 8.0
2022-05-04 03:55:21.548657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:5e:00.0, compute capability: 7.5
2022-05-04 03:55:21.549390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5
2022-05-04 03:55:21.550035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 3, name: NVIDIA A2, pci bus id: 0000:18:00.0, compute capability: 8.6
2022-05-04 03:55:24.008178: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capabilit
2022-05-04 03:55:24.008360: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-05-04 03:55:24.015561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 0, name: NVIDIA A30, pci bus id: 0000:3b:00.0, compute capability: 8.0
2022-05-04 03:55:24.016051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:5e:00.0, compute capability: 7.5
2022-05-04 03:55:24.016489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5
2022-05-04 03:55:24.016933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task memory:  -> device: 3, name: NVIDIA A2, pci bus id: 0000:18:00.0, compute capability: 8.6
2022-05-04 03:55:24.078820: E tensorflow/core/grappler/grappler_item_builder.cc:670] Init node index_to_string/table_init/LookupT graph
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 807, in convert_with_tensorrt
    converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1218, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1147, in convert_variab
    converter_data = _FunctionConverterDataInEager(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 810, in __init__
    graph_def = _run_inline_graph_optimization(func, lower_control_flow,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1045, in _run_inline_gr
    return tf_optimizer.OptimizeGraph(config, meta_graph)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/grappler/tf_optimizer.py", line 69, in OptimizeGraph
    out_graph = tf_opt.TF_OptimizeGraph(cluster.tf_cluster,
ValueError: Failed to import metagraph, check error log for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 1211, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 809, in convert_with_tensorrt
    raise RuntimeError(
RuntimeError: Failed to import metagraph, check error log for more info.. Try passing "--convert_tf1_model=True".
```

**Comment by vilmara** [comment]
Update:
Solved using the tflite version of the model (.tflite) instead of the saved model (.pb)

# Install the latest version of tf2onnx and TF

$ /usr/bin/python3 -m pip uninstall tf2onnx
$ /usr/bin/python3 -m pip install git+https://github.com/onnx/tensorflow-onnx
$ pip install tf-nightly-gpu
# Run the conversion with tflite version of the model
$ python -m tf2onnx.convert --opset 13 --tflite "path/to/model.tflite" --output "converted.onnx"

**Comment by hwangdeyu** [comment]
Hi @vilmara , you can close this issue if it was solved.
