### ISSUE TITLE
TFSegFormer model is being failed at inference

### ISSUE THREAD

**Issue by sayakpaul** [onnx/tensorflow-onnx#2008]
I am on TensorFlow 2.9.1. After converting the [TFSegFormer segmentation model](https://huggingface.co/docs/transformers/main/en/model_doc/segformer#transformers.TFSegformerForSemanticSegmentation) to ONNX I am facing the following error during performing inference: 

```py
Traceback (most recent call last):
  File "benchmark_onnx.py", line 69, in <module>
    main()
  File "benchmark_onnx.py", line 55, in main
    sess = ort.InferenceSession(onnx_model_path)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from segformer-b5-finetuned-ade-640-640.onnx failed:This is an invalid model. In Node, ("tf_segformer_for_semantic_segmentation/segformer/encoder/block.0.0/mlp/dwconv/dwconv/StatefulPartitionedCall", StatefulPartitionedCall, "", -1) : ("tf_segformer_for_semantic_segmentation/segformer/encoder/block.0.0/mlp/dwconv/Reshape:0": tensor(float),"tf_segformer_for_semantic_segmentation/segformer/encoder/block.0.0/mlp/dwconv/dwconv/26687:0": tensor(float),) -> ("tf_segformer_for_semantic_segmentation/segformer/encoder/block.0.0/mlp/dwconv/dwconv/StatefulPartitionedCall:0",) , Error No Op registered for StatefulPartitionedCall with domain_version of 15
```

I used the latest stable versions of `tf2onnx` and `onnxruntime`. 

Here's the full code to reproduce the problem:

```py
import time

import numpy as np
import onnx
import onnxruntime as ort
import tensorflow as tf
import tf2onnx
from PIL import Image
from transformers import SegformerFeatureExtractor, TFSegformerForSemanticSegmentation


def main():
    print("Loading original model...")
    model_ckpt = "nvidia/segformer-b5-finetuned-ade-640-640"

    feature_extractor = SegformerFeatureExtractor.from_pretrained(model_ckpt)
    model = TFSegformerForSemanticSegmentation.from_pretrained(model_ckpt)

    print("Exporting ONNX model...")
    input_size = feature_extractor.size
    input_signature = [
        tf.TensorSpec(
            [None, 3, input_size, input_size], tf.float32, name="pixel_values"
        )
    ]
    onnx_model, _ = tf2onnx.convert.from_keras(model, input_signature, opset=15)
    onnx_model_path = model_ckpt.split("/")[-1] + ".onnx"
    onnx.save(onnx_model, onnx_model_path)

    dummy_inputs = tf.random.normal((32, 3, input_size, input_size))
    dummy_inputs_numpy = dummy_inputs.numpy()

    # Warmup
    print("Benchmarking TF model...")
    for _ in range(2):
        _ = model(dummy_inputs, training=False)

    # Timing
    tf_outputs = []
    start_time = time.time()
    for _ in range(5):
        tf_outputs.append(model(dummy_inputs, training=False))
    end_time = time.time()
    print(f"Inference completed within {(end_time - start_time):.2f} seconds.")

    print("Benchmarking ONNX model...")
    sess = ort.InferenceSession(onnx_model_path)
    for _ in range(2):
        _ = sess.run(None, {"pixel_values": dummy_inputs_numpy})

    # Timing
    ort_outputs = []
    start_time = time.time()
    for _ in range(5):
        ort_outputs.append(sess.run(None, {"pixel_values": dummy_inputs_numpy}))
    end_time = time.time()
    print(f"Inference completed within {(end_time - start_time):.2f} seconds.")


if __name__ == "__main__":
    main()
```

Note that you'd need to install `transformers` from source to import the SegFormer model in TF:

```shell
pip install git+https://github.com/huggingface/transformers
```

**Comment by fatcat-z** [comment]
StatefulPartitionedCall op is not supported yet and tf2onnx just keeps those unsupported ops in the final generated ONNX file. It is not recognized by ORT so the error is expected.

**Comment by sayakpaul** [comment]
Is there a way to mitigate it on the model end?

**Comment by fatcat-z** [comment]
> Is there a way to mitigate it on the model end?

No, these ops are not supported meaning tf2onnx has no idea about how to convert them to ONNX ops so there is not mitigation plan for such case at this moment.
