### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by dan9thsense** [onnx/tensorflow-onnx#2031]
Using Ubuntu 18.04, trying both direct pip install and also from github, it fails with these messages.  I'm wondering if it is a protobuf issue.

$ pip install git+https://github.com/onnx/tensorflow-onnx
Collecting git+https://github.com/onnx/tensorflow-onnx
  Cloning https://github.com/onnx/tensorflow-onnx to /tmp/pip-req-build-5megenkh
  Running command git clone -q https://github.com/onnx/tensorflow-onnx /tmp/pip-req-build-5megenkh
Requirement already satisfied: numpy>=1.14.1 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from tf2onnx==1.12.0) (1.19.5)
Collecting onnx>=1.4.1
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
Requirement already satisfied: requests in ./.virtualenvs/tf2/lib/python3.6/site-packages (from tf2onnx==1.12.0) (2.25.1)
Requirement already satisfied: six in ./.virtualenvs/tf2/lib/python3.6/site-packages (from tf2onnx==1.12.0) (1.15.0)
Requirement already satisfied: flatbuffers~=1.12 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from tf2onnx==1.12.0) (1.12)
Requirement already satisfied: protobuf<=3.20.1,>=3.12.2 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from onnx>=1.4.1->tf2onnx==1.12.0) (3.15.6)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from onnx>=1.4.1->tf2onnx==1.12.0) (3.7.4.3)
Requirement already satisfied: idna<3,>=2.5 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from requests->tf2onnx==1.12.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from requests->tf2onnx==1.12.0) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from requests->tf2onnx==1.12.0) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in ./.virtualenvs/tf2/lib/python3.6/site-packages (from requests->tf2onnx==1.12.0) (4.0.0)
Building wheels for collected packages: tf2onnx, onnx
  Building wheel for tf2onnx (setup.py) ... done
  Created wheel for tf2onnx: filename=tf2onnx-1.12.0-py3-none-any.whl size=442112 sha256=75569810aec5449caabd0a051a6e075062029523b1ff7cdf7f88afa76ab457c3
  Stored in directory: /tmp/pip-ephem-wheel-cache-jf6qide1/wheels/5d/56/13/61f4f78a7d446d4cd9dd12d64ebcb908f41bbc1922bab6aea4
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dbarry/.virtualenvs/tf2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ck6_ef8a/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ck6_ef8a/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n43y4win
       cwd: /tmp/pip-install-ck6_ef8a/onnx/
  Complete output (213 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['/home/dbarry/cmake-3.12.2-Linux-x86_64/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/home/dbarry/.virtualenvs/tf2/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-ck6_ef8a/onnx']
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/dbarry/.virtualenvs/tf2/bin/python (found version "3.6.9")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "3.0.0")
  Generated: /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Generated: /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  -- Could NOT find pybind11 (missing: pybind11_DIR)
  -- pybind11 v2.9.1
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  --
  -- ******** Summary ********
  --   CMake version             : 3.12.2
  --   CMake command             : /home/dbarry/cmake-3.12.2-Linux-x86_64/bin/cmake
  --   System                    : Linux
  --   C++ compiler              : /usr/bin/c++
  --   C++ compiler version      : 7.5.0
  --   CXX flags                 :  -Wnon-virtual-dtor
  --   Build type                : Release
  --   Compile definitions       : __STDC_FORMAT_MACROS
  --   CMAKE_PREFIX_PATH         :
  --   CMAKE_INSTALL_PREFIX      : /usr/local
  --   CMAKE_MODULE_PATH         :
  --
  --   ONNX version              : 1.12.0
  --   ONNX NAMESPACE            : onnx
  --   ONNX_USE_LITE_PROTO       : OFF
  --   USE_PROTOBUF_SHARED_LIBS  : OFF
  --   Protobuf_USE_STATIC_LIBS  : ON
  --   ONNX_DISABLE_EXCEPTIONS   : OFF
  --   ONNX_WERROR               : OFF
  --   ONNX_BUILD_TESTS          : OFF
  --   ONNX_BUILD_BENCHMARKS     : OFF
  --   ONNXIFI_DUMMY_BACKEND     : OFF
  --   ONNXIFI_ENABLE_EXT        : OFF
  --
  --   Protobuf compiler         : /usr/bin/protoc
  --   Protobuf includes         : /usr/include
  --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
  --   BUILD_ONNX_PYTHON         : ON
  --     Python version        :
  --     Python executable     : /home/dbarry/.virtualenvs/tf2/bin/python
  --     Python includes       : /usr/include/python3.6m
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build
  Scanning dependencies of target gen_onnx_proto
  Scanning dependencies of target onnxifi_dummy
  Scanning dependencies of target onnxifi_loader
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  [  2%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  [  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  [  5%] Linking C static library libonnxifi_loader.a
  [  5%] Built target onnxifi_loader
  Processing /tmp/pip-install-ck6_ef8a/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  Scanning dependencies of target onnxifi_wrapper
  [  7%] Linking C shared library libonnxifi_dummy.so
  [  8%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
  [  9%] Running C++ protocol buffer compiler on /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  [  9%] Built target onnxifi_dummy
  Writing mypy to onnx/onnx_ml_pb2.pyi
  [  9%] Built target gen_onnx_proto
  Scanning dependencies of target gen_onnx_operators_proto
  Scanning dependencies of target gen_onnx_data_proto
  [ 11%] Running gen_proto.py on onnx/onnx-data.in.proto
  [ 12%] Running gen_proto.py on onnx/onnx-operators.in.proto
  [ 14%] Linking C shared module libonnxifi.so
  [ 14%] Built target onnxifi_wrapper
  Processing /tmp/pip-install-ck6_ef8a/onnx/onnx/onnx-data.in.proto
  Writing /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-data.proto3
  generating /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx_data_pb.py
  Processing /tmp/pip-install-ck6_ef8a/onnx/onnx/onnx-operators.in.proto
  Writing /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
  generating /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  [ 15%] Running C++ protocol buffer compiler on /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  [ 16%] Running C++ protocol buffer compiler on /tmp/pip-install-ck6_ef8a/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing mypy to onnx/onnx_operators_ml_pb2.pyi
  Writing mypy to onnx/onnx_data_pb2.pyi
  [ 16%] Built target gen_onnx_operators_proto
  [ 16%] Built target gen_onnx_data_proto
  Scanning dependencies of target onnx_proto
  [ 18%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
  [ 21%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
  [ 21%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
  [ 22%] Linking CXX static library libonnx_proto.a
  [ 30%] Built target onnx_proto
  Scanning dependencies of target onnx
  [ 33%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
  [ 33%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
  [ 35%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
  [ 36%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
  [ 39%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
  [ 39%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
  [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
  [ 42%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
  [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
  [ 45%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
  [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
  [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
  [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
  [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
  [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
  [ 53%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
  [ 54%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
  [ 56%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
  [ 57%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
  [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
  [ 60%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
  [ 61%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
  [ 63%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/defs.cc.o
  [ 64%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/parser.cc.o
  [ 66%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/printer.cc.o
  [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
  [ 69%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/old.cc.o
  [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
  [ 71%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
  [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
  [ 74%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
  [ 76%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
  [ 77%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
  [ 78%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o
  [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
  [ 81%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
  [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
  [ 84%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
  /tmp/pip-install-ck6_ef8a/onnx/onnx/defs/sequence/defs.cc: In function ‘bool onnx::BuildSequenceMapBodyFunc(const onnx::FunctionBodyBuildContext&, const onnx::OpSchema&, onnx::FunctionProto&)’:
  /tmp/pip-install-ck6_ef8a/onnx/onnx/defs/sequence/defs.cc:675:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
           seq_at_node.add_output(g_inputs[inputIndex].name());
                                          ^
  /tmp/pip-install-ck6_ef8a/onnx/onnx/defs/sequence/defs.cc:683:37: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
           identity.add_output(g_inputs[inputIndex].name());
                                       ^
  /tmp/pip-install-ck6_ef8a/onnx/onnx/defs/sequence/defs.cc:741:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
       int64_t dtype = g_outputs[outputIndex].type().tensor_type().elem_type();
                                ^
  CMakeFiles/onnx.dir/build.make:478: recipe for target 'CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o' failed
  make[2]: *** [CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/Makefile2:242: recipe for target 'CMakeFiles/onnx.dir/all' failed
  make[1]: *** [CMakeFiles/onnx.dir/all] Error 2
  Makefile:129: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ck6_ef8a/onnx/setup.py", line 354, in <module>
      "backend-test-tools = onnx.backend.test.cmd_tools:main",
    File "/home/dbarry/.virtualenvs/tf2/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dbarry/.virtualenvs/tf2/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-ck6_ef8a/onnx/setup.py", line 223, in run
      self.run_command("cmake_build")
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-ck6_ef8a/onnx/setup.py", line 217, in run
      subprocess.check_call(build_args)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['~/cmake-3.12.2-Linux-x86_64/bin/cmake', '--build', '.', '--', '-j', '12']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx

**Comment by dan9thsense** [comment]
Decided this was not worth the time needed to debug on Ubuntu 18.04.  Installed successfully in a docker container and worked from there.
