### ISSUE TITLE
[tflite] Error loading model into tflite interpreter: Didn't find op for builtin opcode 'CONV_2D' version '6'.

### ISSUE THREAD

**Issue by josephrocca** [onnx/tensorflow-onnx#2052]
### Describe the feature request
Support for `CONV_2D` version 6 for tflite conversion. I'm guessing that this entails updating the tflite interpreter used in this package.

### Describe scenario use case
I'd like to convert the [newly-open-sourced Lyra V2](https://opensource.googleblog.com/2022/09/lyra-v2-a-better-faster-and-more-versatile-speech-codec.html) to ONNX.

Minimal reproduction of error: https://colab.research.google.com/gist/josephrocca/8916bf2faa938ed24f89e0228bb20481/lyra-v2-soundstream-tflite-to-onnx-conversion-error-didn-t-find-op-for-builtin-opcode-conv_2d-version-6.ipynb

### Full error:
```
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-10-02 05:13:41,350 - INFO - Using tensorflow=2.8.2, onnx=1.12.0, tf2onnx=1.12.0/c60c5e
2022-10-02 05:13:41,350 - INFO - Using opset <onnx, 16>
2022-10-02 05:13:41,399 - WARNING - Error loading model into tflite interpreter: Didn't find op for builtin opcode 'CONV_2D' version '6'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?
Registration failed.

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 706, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 291, in main
    output_path=args.output)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 165, in _convert_common
    custom_op_handlers=custom_op_handlers, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tfonnx.py", line 453, in process_tf_graph
    main_g, subgraphs = graphs_from_tflite(tflite_path, input_names, output_names)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tflite_utils.py", line 153, in graphs_from_tflite
    parse_tflite_graph(tfl_graph, opcodes, model, prefix, tensor_shapes_from_interpreter)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tflite_utils.py", line 485, in parse_tflite_graph
    onnx_node = helper.make_node(optype, input_names, output_names, name=output_names[0], **attr)
IndexError: list index out of range
```

**Comment by josephrocca** [comment]
As expected, this same sort of error was solved by the tfjs-tflite project by simply updating to the latest tflite binary: 

* https://github.com/tensorflow/tfjs/issues/6885

So I'm guessing this is a fairly simple fix - just need to bump a version number somewhere?

**Comment by fatcat-z** [comment]
This error was thrown by a call to tensorflow.lite.Interpreter() method which is relative to tensorflow version. In the issue you attached, that issue was fixed by a new version released recently. So, this will be resolved once a latest tensorflow release is published.

Based on this, I think we don't have a chance to bump a new version number of tensorflow.

**Comment by josephrocca** [comment]
Ah, thanks! I should have known that tf2onnx would be using the version of TF that is installed. I upgraded the Colab's TF to 2.9.2 and that fixed this error. The latter half of the error (`list index out of range`) is still happening, so I created a separate issue: https://github.com/onnx/tensorflow-onnx/issues/2055
