### ISSUE TITLE
Pip install fails on Apple Silicon M1 Python 3.9

### ISSUE THREAD

**Issue by HadiSDev** [onnx/tensorflow-onnx#2092]
**Describe the bug**
I get this cmake error when trying to install with pip:

```
pip install -U tf2onnx
Collecting tf2onnx
  Downloading tf2onnx-1.13.0-py3-none-any.whl (442 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.3/442.3 kB 8.3 MB/s eta 0:00:00
Requirement already satisfied: requests in /Users/hadi.salameh/Library/Caches/pypoetry/virtualenvs/ssn-XfIlV6iG-py3.9/lib/python3.9/site-packages (from tf2onnx) (2.28.1)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in /Users/hadi.salameh/Library/Caches/pypoetry/virtualenvs/ssn-XfIlV6iG-py3.9/lib/python3.9/site-packages (from tf2onnx) (1.12)
Collecting onnx>=1.4.1
  Downloading onnx-1.12.0.tar.gz (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 24.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-install-rq4530yd/onnx_8e7f742fa7a749f7b5bf78604427f84b/setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

Installing it from source (git) gives the same error

**System information**
- OS Platform and Distribution: MacOs Ventura Apple M1 Pro
- TensorFlow Version: >2.9.0
- Python version: 3.9.14

**Comment by fatcat-z** [comment]
This error was thrown out by a dependency, ONNX [here](https://github.com/onnx/onnx/blob/98f6110963ee5e7226226dcc2f2e664c20de5993/setup.py#L82).

Looks like ONNX needs CMAKE to be installed on your machine. Could you please check this firstly?
