### ISSUE TITLE
Error while execution of the file

### ISSUE THREAD

**Issue by nishant2019** [onnx/tensorflow-onnx#2098]
I am getting following error. Please help me resolve it
`python -m tf2onnx.convert --tflite /home/sdr/Documents/sdr.h5 --output model.onnx

/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/runpy.py:126: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour

  warn(RuntimeWarning(msg))

2022-12-25 18:20:29,461 - INFO - Using tensorflow=2.9.2, onnx=1.13.0, tf2onnx=1.13.0/434b4a

2022-12-25 18:20:29,461 - INFO - Using opset <onnx, 13>

Traceback (most recent call last):

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/convert.py", line 706, in <module>

    main()

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/convert.py", line 269, in main

    model_proto, _ = _convert_common(

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/convert.py", line 164, in _convert_common

    g = process_tf_graph(tf_graph, const_node_values=const_node_values,

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/tfonnx.py", line 453, in process_tf_graph

    main_g, subgraphs = graphs_from_tflite(tflite_path, input_names, output_names)

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/tflite_utils.py", line 143, in graphs_from_tflite

    tflite_graphs, opcodes, model, tensor_shapes = read_tflite_model(tflite_path)

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/tflite_utils.py", line 184, in read_tflite_model

    for i in range(model.OperatorCodesLength()):

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/tf2onnx/tflite/Model.py", line 55, in OperatorCodesLength

    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/flatbuffers/table.py", line 37, in Offset

    vtable = self.Pos - self.Get(N.SOffsetTFlags, self.Pos)

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/flatbuffers/table.py", line 93, in Get

    return flags.py_type(encode.Get(flags.packer_type, self.Bytes, off))

  File "/home/sdr/miniconda3/envs/tfonnx/lib/python3.10/site-packages/flatbuffers/encode.py", line 26, in Get

    return packer_type.unpack_from(memoryview_type(buf), head)[0]

struct.error: unpack_from requires a buffer of at least 1178880141 bytes for unpacking 4 bytes at offset 1178880137 (actual buffer size is 1668256)`

**Comment by fatcat-z** [comment]
May I know how the package sys.modules come from? Looks like there is a duplicated import of tf2onnx.
