### ISSUE TITLE
onnxruntime.InferenceSession for String Tensors

### ISSUE THREAD

**Issue by jasonxcx** [onnx/tensorflow-onnx#2101]
# Ask a Question

### Question

I want to know how to check whether my onnx model is correct. My data is in dictionary with features in string or float, which I have used embeddinglookup to convert string to int tensor. I fail to use onnxruntime.InferenceSession to load onnx model since the input dtype is needed to be float or int. Can anyone help me load the onnx model and get outputs? Thank you so much!!

```bash
Metal device set to: Apple M1 Pro

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

2023-01-06 12:52:24.730929: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-06 12:52:24.731065: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Traceback (most recent call last):
  File "onnx_2_tf.py", line 36, in <module>
    sess = onnxruntime.InferenceSession('/Users/root/onnxModel1.onnx')
  File "/Users/root/miniconda3/envs/tf_to_onnx/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/root/miniconda3/envs/tf_to_onnx/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /Users/onnxModel1.onnx failed:This is an invalid model. Type Error: Type 'tensor(string)' of input parameter (area) of operator (Equal) in node (StatefulPartitionedCall/model_3/vocab_layer_9/NotEqual) is invalid.
```

**Comment by fatcat-z** [comment]
Could you please help me understand the meaning of "embeddinglookup to convert string to int tensor"?

TF2ONNX could not convert those TF data processing function to ONNX op. If you used such functions within your model, they probably could not work well which might cause the inputs of next OP is incorrect.
