### ISSUE TITLE
Cannot convert saved model that uses keras Preprocessing layer

### ISSUE THREAD

**Issue by tuanavu** [onnx/tensorflow-onnx#2222]
Conversion failed from saved model to onnx if the model use `tf.keras.layers.IntegerLookup` and `tf.keras.layers.Discretization`.

### Details
There was some issue with Bucketize ops supported in ONNX, so I am using `tf.keras.layers.IntegerLookup` and `tf.keras.layers.Discretization` to replace `tf.nn.embedding_lookup_sparse()` and `bucketize()`. However, when I tried to convert the model

````
!python -m tf2onnx.convert --saved-model ./models/tf/ --output ./models/onnx/1/model.onnx \
--extra_opset ai.onnx.contrib:1 \
--verbose
````

I got this error

```
2023-08-17 23:57:19,183 - WARNING - tf2onnx.shape_inference: Cannot infer shape for StatefulPartitionedCall/model/preprocessing/emb_layer_35/integer_lookup_35/None_Lookup/LookupTableFindV2: StatefulPartitionedCall/model/preprocessing/emb_layer_35/integer_lookup_35/None_Lookup/LookupTableFindV2:0
2023-08-17 23:57:22,413 - ERROR - tf2onnx.tfonnx: Tensorflow op [StatefulPartitionedCall/model/preprocessing/discretization/Bucketize: Bucketize] is not supported
2023-08-17 23:57:22,423 - ERROR - tf2onnx.tfonnx: Failed to convert node 'StatefulPartitionedCall/model/preprocessing/emb_layer/integer_lookup/None_Lookup/LookupTableFindV2' (fct=<bound method LookupTableFind.version_8 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableFind'>>)
            2023-08-17 23:57:23,295 - ERROR - tf2onnx.tfonnx: Tensorflow op [StatefulPartitionedCall/model/preprocessing/emb_layer_45/SparseReduceSum: SparseReduceSum] is not supported
2023-08-17 23:57:23,296 - ERROR - tf2onnx.tfonnx: Failed to convert node 'StatefulPartitionedCall/model/preprocessing/emb_layer_46/integer_lookup_46/None_Lookup/LookupTableFindV2' (fct=<bound method LookupTableFind.version_8 of <class 'tf2onnx.custom_opsets.onnx_ml.LookupTableFind'>>)
'OP=LookupTableFindV2\nName=StatefulPartitionedCall/model/preprocessing/emb_layer_46/integer_lookup_46/None_Lookup/LookupTableFindV2\nInputs:\n\tunknown:0=HashTableV2, [], 7\n\targs_0_360=Placeholder, [-1], 7\n\tFunc/StatefulPartitionedCall/input/_363:0=Const, [], 7\nOutpus:\n\tStatefulPartitionedCall/model/preprocessing/emb_layer_46/integer_lookup_46/None_Lookup/LookupTableFindV2:0=None, 7'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/custom_opsets/onnx_ml.py", line 45, in version_8
    utils.make_sure((dtype == TensorProto.INT64 and in_dtype == TensorProto.STRING) or
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Only lookup tables of type string<->int64 are currently supported.
2023-08-17 23:57:23,296 - ERROR - tf2onnx.tfonnx: Tensorflow op [StatefulPartitionedCall/model/preprocessing/emb_layer_46/integer_lookup_46/count/SparseCountSparseOutput: SparseCountSparseOutput] is not supported
2023-08-17 23:57:23,314 - ERROR - tf2onnx.tfonnx: Tensorflow op [StatefulPartitionedCall/model/preprocessing/emb_layer_46/SparseReduceSum: SparseReduceSum] is not supported
2023-08-17 23:57:23,329 - ERROR - tf2onnx.tfonnx: Unsupported ops: Counter({'Bucketize': 221, 'SparseCountSparseOutput': 47, 'SparseReduceSum': 47})
```

### System information

- Docker container: `nvcr.io/nvidia/tensorflow:22.12-tf2-py3`
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04)
- Tensorflow Version: 2.10.1
- Python version: 3.8.10
- tf2onnx: Successfully installed tf2onnx-1.14.0

**Comment by witeko** [comment]
I have the same problem

**Comment by kerocode** [comment]
I am facing the same issue, any updates

**Comment by eyalhir74** [comment]
Any idea if this was fixed somethow?

**Comment by jalola** [comment]
Hi
I did try cast_int_to_str + StringLookup to replace IntegerLookup and I was able to convert the model to ONNX

However, when I check the performance, the TF model is faster than ONNX model

This depends on model I think, my model has very a small backbone but it has a lot of preprocessing layers, that's why I think TF model can be faster than ONNX model as a whole. Of course, if only benchmarking the backbone, ONNX is faster.

If your model has big backbone, I think it can be beneficial to use ONNX.

Another option you can try is splitting the model into 2 part, 1 runs TF model, another runs ONNX model

**Comment by nvsreerag** [comment]
Iam getting the same error while trying to convert a model. Any solutions for this?
