### ISSUE TITLE
ValueError: Could not infer attribute `explicit_paddings` type from empty iterator

### ISSUE THREAD

**Issue by trung-nguyen-code** [onnx/tensorflow-onnx#2262]
**Describe the bug**

Hi, I got this error when trying to convert my tensorflow model to onnx. I tried all the opset values but no one worked. 
**Urgent**
I need this one as soon as possible, before November 8th, so please help me.
**To Reproduce**

I'm building a model to classify emotion with Convolution2D and Sequential api.
Here is link to the colab notebook.
https://colab.research.google.com/drive/1VdcubIhxcjQU79qFgqy8AObnp6dwZ59h?usp=sharing
Note that you need to upload kaggle.json file to download dataset and reproduce the resultls. Here: 
[kaggle.json](https://github.com/onnx/tensorflow-onnx/files/13194920/kaggle.json)

**Screenshots**

![Screenshot from 2023-10-28 14-43-27](https://github.com/onnx/tensorflow-onnx/assets/63198270/30e46f46-5e9b-484c-93a2-e864f61b1f12)
![Screenshot from 2023-10-28 14-43-17](https://github.com/onnx/tensorflow-onnx/assets/63198270/bdb04b79-9afe-44fd-8834-a3b9497f5fc3)

**Comment by aponte411** [comment]
I also am experiencing the same issue.

**Comment by Sawaiz8** [comment]
Getting the same error:

Traceback (most recent call last):
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/convert.py", line 273, in main
    model_proto, _ = _convert_common(
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/convert.py", line 168, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/tfonnx.py", line 459, in process_tf_graph
    main_g, subgraphs = graphs_from_tf(tf_graph, input_names, output_names, shape_override, const_node_values,
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/tfonnx.py", line 474, in graphs_from_tf
    ordered_func = resolve_functions(tf_graph)
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/tf_loader.py", line 764, in resolve_functions
    _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/tf2onnx/tf_utils.py", line 462, in tflist_to_onnx
    onnx_node = helper.make_node(node_type, input_names, output_names, name=node.name, **attr)
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/onnx/helper.py", line 164, in make_node
    node.attribute.extend(
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/onnx/helper.py", line 165, in <genexpr>
    make_attribute(key, value)
  File "/home/sawaiz/anaconda3/envs/object/lib/python3.9/site-packages/onnx/helper.py", line 876, in make_attribute
    raise ValueError(
ValueError: Could not infer attribute `explicit_paddings` type from empty iterator


**Is this a version issue?**

**Comment by hariharan-tech** [comment]
- I faced the same issue when I tried exporting the base pretrained (imagenet weights) Xception model to onnx weights format for inferencing.
- As mentioned in the Readme of this repo as tf2onnx doesn't support tensorflow version 2.14 (currently), I tried building and exporting the same simple model in tensorflow version 2.12 yet faced the same issue.
- Environment used:
   - Google collab
   - Tried TF versions 2.14 and 2.12

**Comment by lrmillennium** [comment]
same issue.  tried to export a image classification model on hugging face to onnx.  will try tensorflow.js next.

2023-10-29 21:02:04.427028: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 21:02:04.427120: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 21:02:04.427187: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 21:02:08.444768: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Framework not specified. Using tf to export to ONNX.
All model checkpoint layers were used when initializing TFViTForImageClassification.

All the layers of TFViTForImageClassification were initialized from the model checkpoint at ericrong888/logo_classifier.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFViTForImageClassification for predictions without further training.
Automatic task detection to image-classification.
/usr/local/lib/python3.10/dist-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(
Using the export variant default. Available variants are:
	- default: The default ONNX variant.
`input_shapes` argument is not supported by the Tensorflow ONNX export and will be ignored.
Using framework TensorFlow: 2.14.0
Could not search for non-variable resources. Concrete function internal representation may have changed.
pass1 convert failed for name: "tf_vi_t_for_image_classification/vit/embeddings/patch_embeddings/projection/Conv2D"
op: "Conv2D"
input: "tf_vi_t_for_image_classification/vit/embeddings/patch_embeddings/transpose"
input: "tf_vi_t_for_image_classification/vit/embeddings/patch_embeddings/projection/Conv2D/ReadVariableOp"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "dilations"
  value {
    list {
      i: 1
      i: 1
      i: 1
      i: 1
    }
  }
}
attr {
  key: "explicit_paddings"
  value {
    list {
    }
  }
}
attr {
  key: "padding"
  value {
    s: "VALID"
  }
}
attr {
  key: "strides"
  value {
    list {
      i: 1
      i: 16
      i: 16
      i: 1
    }
  }
}
attr {
  key: "use_cudnn_on_gpu"
  value {
    b: true
  }
}
, ex=Could not infer attribute `explicit_paddings` type from empty iterator
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/export/onnx.py", line 232, in run
    main_export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 486, in main_export
    _, onnx_outputs = export_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 752, in export_models
    export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 875, in export
    export_output = export_tensorflow(model, config, opset, output)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 685, in export_tensorflow
    onnx_model, _ = tf2onnx.convert.from_keras(model, input_signature, opset=opset)
  File "/usr/local/lib/python3.10/dist-packages/tf2onnx/convert.py", line 502, in from_keras
    model_proto, external_tensor_storage = _convert_common(
  File "/usr/local/lib/python3.10/dist-packages/tf2onnx/convert.py", line 168, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File "/usr/local/lib/python3.10/dist-packages/tf2onnx/tfonnx.py", line 459, in process_tf_graph
    main_g, subgraphs = graphs_from_tf(tf_graph, input_names, output_names, shape_override, const_node_values,
  File "/usr/local/lib/python3.10/dist-packages/tf2onnx/tfonnx.py", line 474, in graphs_from_tf
    ordered_func = resolve_functions(tf_graph)
  File "/usr/local/lib/python3.10/dist-packages/tf2onnx/tf_loader.py", line 764, in resolve_functions
    _, _, _, _, _, functions = tflist_to_onnx(tf_graph, {})
  File "/usr/local/lib/python3.10/dist-packages/tf2onnx/tf_utils.py", line 462, in tflist_to_onnx
    onnx_node = helper.make_node(node_type, input_names, output_names, name=node.name, **attr)
  File "/usr/local/lib/python3.10/dist-packages/onnx/helper.py", line 164, in make_node
    node.attribute.extend(
  File "/usr/local/lib/python3.10/dist-packages/onnx/helper.py", line 165, in <genexpr>
    make_attribute(key, value)
  File "/usr/local/lib/python3.10/dist-packages/onnx/helper.py", line 876, in make_attribute
    raise ValueError(
ValueError: Could not infer attribute `explicit_paddings` type from empty iterator

**Comment by fatcat-z** [comment]
Please don't use ONNX 1.15 and try a lower version.

**Comment by fatcat-z** [comment]
> * I faced the same issue when I tried exporting the base pretrained (imagenet weights) Xception model to onnx weights format for inferencing.
> * As mentioned in the Readme of this repo as tf2onnx doesn't support tensorflow version 2.14 (currently), I tried building and exporting the same simple model in tensorflow version 2.12 yet faced the same issue.
> * Environment used:
>   
>   * Google collab
>   * Tried TF versions 2.14 and 2.12


Please don't use ONNX 1.15 and try a lower version.

**Comment by felixdittrich92** [comment]
@fatcat-z Would it be possible to release a patch with the empty iterator fix for onnx 1.15 ? #2252

**Comment by trung-nguyen-code** [comment]
> > * I faced the same issue when I tried exporting the base pretrained (imagenet weights) Xception model to onnx weights format for inferencing.
> > * As mentioned in the Readme of this repo as tf2onnx doesn't support tensorflow version 2.14 (currently), I tried building and exporting the same simple model in tensorflow version 2.12 yet faced the same issue.
> > * Environment used:
> >   
> >   * Google collab
> >   * Tried TF versions 2.14 and 2.12
> 
> Please don't use ONNX 1.15 and try a lower version.

How? Please give me the command line to install a new one.

**Comment by SergheiDinu** [comment]
pip install onnx==1.14.1 worked

**Comment by SergheiDinu** [comment]
> > > * I faced the same issue when I tried exporting the base pretrained (imagenet weights) Xception model to onnx weights format for inferencing.
> > > * As mentioned in the Readme of this repo as tf2onnx doesn't support tensorflow version 2.14 (currently), I tried building and exporting the same simple model in tensorflow version 2.12 yet faced the same issue.
> > > * Environment used:
> > >   
> > >   * Google collab
> > >   * Tried TF versions 2.14 and 2.12
> > 
> > 
> > Please don't use ONNX 1.15 and try a lower version.
> 
> How? Please give me the command line to install a new one.

pip install onnx==1.14.1

**Comment by Jensssen** [comment]
Installing tf2onnx via pip will install onnx:1.15.0. You can verify that by running `pip list | grep onnx` 
In order to downgrade the version of your onnx dependency, just run `pip install onnx==1.14.1`.
With ONNX==1.14.1, it should work.

**Comment by hariharan-tech** [comment]
> > * I faced the same issue when I tried exporting the base pretrained (imagenet weights) Xception model to onnx weights format for inferencing.
> > * As mentioned in the Readme of this repo as tf2onnx doesn't support tensorflow version 2.14 (currently), I tried building and exporting the same simple model in tensorflow version 2.12 yet faced the same issue.
> > * Environment used:
> >   
> >   * Google collab
> >   * Tried TF versions 2.14 and 2.12
> 
> Please don't use ONNX 1.15 and try a lower version.

Yes, I used Tensorflow version 2.11 with tf2onnx version 1.14.0 and the export works!
Thanks!

**Comment by trung-nguyen-code** [comment]
> > > * I faced the same issue when I tried exporting the base pretrained (imagenet weights) Xception model to onnx weights format for inferencing.
> > > * As mentioned in the Readme of this repo as tf2onnx doesn't support tensorflow version 2.14 (currently), I tried building and exporting the same simple model in tensorflow version 2.12 yet faced the same issue.
> > > * Environment used:
> > >   
> > >   * Google collab
> > >   * Tried TF versions 2.14 and 2.12
> > 
> > 
> > Please don't use ONNX 1.15 and try a lower version.
> 
> Yes, I used Tensorflow version 2.11 with tf2onnx version 1.14.0 and the export works! Thanks!

It's weird , I tried : 
!pip install -U tf2onnx==1.14.0
!pip install tensorflow==2.11

But still get the same error

**Comment by trung-nguyen-code** [comment]
Thanks all! I did it!

**Comment by raulcarlomagno** [comment]
> Installing tf2onnx via pip will install onnx:1.15.0. You can verify that by running `pip list | grep onnx` In order to downgrade the version of your onnx dependency, just run `pip install onnx==1.14.1`. With ONNX==1.14.1, it should work.
it does work
![image](https://github.com/onnx/tensorflow-onnx/assets/2282315/186a27fb-536b-4d51-a73a-082cd9b46454)

**Comment by fatcat-z** [comment]
> @fatcat-z Would it be possible to release a patch with the empty iterator fix for onnx 1.15 ? #2252

The PR has been merged into code, will prepare a new patch/release to support ONNX 1.15 officially.
