### ISSUE TITLE
An error is reported when converting a ckpt file to onnx

### ISSUE THREAD

**Issue by SwordShiSan** [onnx/tensorflow-onnx#2266]
python -m tf2onnx.convert --checkpoint checkpoint/PIAFusion/IAFusion.ckpt.meta --inputs input/vi_images:0,input/ir_images:0 --outputs PIAFusion/decoder/add:0 --output checkpoint/PIAFusion/PIAFusion.onnx --opset 9

Error：
Traceback (most recent call last):
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tf2onnx/convert.py", line 710, in <module>
    main()
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tf2onnx/convert.py", line 239, in main
    graph_def, inputs, outputs = tf_loader.from_checkpoint(args.checkpoint, args.inputs, args.outputs)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 381, in from_checkpoint
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 302, in freeze_session
    graph_def = convert_variables_to_constants(sess, graph_def, output_node_names)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 330, in new_func
    return func(*args, **kwargs)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 330, in convert_variables_to_constants
    returned_variables = sess.run(variable_names)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/data6/anaconda3/envs/tensorflow_115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value PIAFusion/decoder/conv1x1/kernel/Adam
         [[{{node _retval_PIAFusion/decoder/conv1x1/kernel/Adam_0_9}}]]

Some Information：
Using python 3.7 is the same error
Version：
tensorflow                1.15.0          
tensorflow-base           1.15.0         
tensorflow-estimator      1.15.1             
tensorflow-gpu            1.15.0               
termcolor                 1.1.0              
tf2onnx                   1.15.1

**Comment by fatcat-z** [comment]
Looks like the function convert_variables_to_constants throws an exception.

Given your python version is 3.6, which is not checked by latest tf2onnx. Do you mind to try tensorflow 1.15 on a high version of Python, like 3.8, to see if this problem is gone?

**Comment by SwordShiSan** [comment]
> Looks like the function convert_variables_to_constants throws an exception.
> 
> Given your python version is 3.6, which is not checked by latest tf2onnx. Do you mind to try tensorflow 1.15 on a high version of Python, like 3.8, to see if this problem is gone?

Thanks for the answer, I used python 3.7 but it doesn't seem to be an issue with the python version.I tried modifying the tf_loader.py, around line 390，and it works.
        with tf_session() as sess:
            saver = tf_import_meta_graph(model_path, clear_devices=True)
            # Add the following line
            sess.run([tf.global_variables_initializer(),tf.local_variables_initializer()])  
            saver.restore(sess, model_path[:-5])

**Comment by fatcat-z** [comment]
By the description [here](https://www.tensorflow.org/api_docs/python/tf/compat/v1/global_variables_initializer): in TF2, variables are initialized immediately when they are created. There is no longer a need to run variable initializers before using them. It is recommended to upgrade to tf2 for more better benefits.
