### ISSUE TITLE
SparseSoftmaxCrossEntropyWithLogits support

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#229]
> ERROR:tf2onnx:pass1 convert failed for name: "SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits"
> op: "SparseSoftmaxCrossEntropyWithLogits"
> input: "dense_2/Sigmoid"
> input: "ratings:0"
> attr {
>   key: "T"
>   value {
>     type: DT_FLOAT
>   }
> }
> attr {
>   key: "Tlabels"
>   value {
>     type: DT_INT32
>   }
> }
> , ex=Value "<dtype: 'int32'>" is not valid attribute data type.
>         to_onnx FAIL Value "<dtype: 'int32'>" is not valid attribute data type. Traceback (most recent call last):
>   File "tests\run_pretrained_models.py", line 307, in run_test
>     onnx_graph = self.to_onnx(sess.graph, opset=opset, shape_override=shape_override)
>   File "tests\run_pretrained_models.py", line 174, in to_onnx
>     target=Test.target, shape_override=shape_override, output_names=self.output_names)
>   File "C:\Program Files\Python3.6\lib\site-packages\tf2onnx-0.4.0-py3.6.egg\tf2onnx\tfonnx.py", line 2402, in process_tf_graph
>     onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
>   File "C:\Program Files\Python3.6\lib\site-packages\tf2onnx-0.4.0-py3.6.egg\tf2onnx\tfonnx.py", line 153, in tensorflow_to_onnx
>     return tflist_to_onnx(graph.get_operations(), shape_override)
>   File "C:\Program Files\Python3.6\lib\site-packages\tf2onnx-0.4.0-py3.6.egg\tf2onnx\tfonnx.py", line 140, in tflist_to_onnx
>     onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
>   File "C:\Program Files\Python3.6\lib\site-packages\onnx-1.3.0-py3.6-win-amd64.egg\onnx\helper.py", line 51, in make_node
>     for key, value in sorted(kwargs.items()))
>   File "C:\Program Files\Python3.6\lib\site-packages\onnx-1.3.0-py3.6-win-amd64.egg\onnx\helper.py", line 51, in <genexpr>
>     for key, value in sorted(kwargs.items()))
>   File "C:\Program Files\Python3.6\lib\site-packages\onnx-1.3.0-py3.6-win-amd64.egg\onnx\helper.py", line 250, in make_attribute
>     'Value "{}" is not valid attribute data type.'.format(value))
> ValueError: Value "<dtype: 'int32'>" is not valid attribute data type.

issue found in real model. @zhijxu-MS  is working on this.

**Comment by pengwa** [comment]
https://github.com/onnx/tensorflow-onnx/pull/244 fixed this. Though we know sometime, the depth cannot retrieved from ctx.get_shape() correctly. While we will need refine this later.
