### ISSUE TITLE
Tensorflow 2.16 / Keras 3 support

### ISSUE THREAD

**Issue by pwuertz** [onnx/tensorflow-onnx#2329]
The switch from Keras 2 to Keras 3 in Tensorflow 2.16 apparently breaks `tf2onnx`:
```python
import tf2onnx
...
onnx_model, _ = tf2onnx.convert.from_keras(model)
# AttributeError: ... object has no attribute '_get_save_spec'
```

This is probably the same issue people are seeing with `tf.lite.TFLiteConverter` since Keras 3:
https://github.com/keras-team/keras/issues/18430

Is there an alternative route like `tf2onnx.convert.from_function` we could use as a workaround?

**Comment by MidnessX** [comment]
I've discovered that explicitly passing an input signature makes the function work again:

``` python
import tf2onnx
import keras

inputs = [
     keras.Input((128, 2), batch_size=64, dtype="float32", name="input_1"),
     keras.Input((64, 4), batch_size=64, dtype="float32", name="input_2")
]
# [...] Rest of Keras code
model = keras.Model(inputs=inputs, outputs=outputs)

model_proto, _ = tf2onnx.convert.from_keras(
    model,
    input_signature=(
        tf.TensorSpec(
            model.inputs[0].shape,
            dtype=model.inputs[0].dtype,
            name=model.inputs[0].name,
        ),
        tf.TensorSpec(
            model.inputs[1].shape,
            dtype=model.inputs[1].dtype,
            name=model.inputs[1].name,
        ),
    ),
    output_path="model.onnx",
)
```

However, I do not know how robust this workaround is.
I suggest exporting the model to the TensorFlow `saved_model` format first using `model.export("path/to/saved_model_folder")` and then using:
``` console
python -m tf2onnx.convert --saved-model "path/to/saved_model_folder" --output "path/to/model.onnx"
```
to convert it to the ONNX format.

**Comment by dmagee** [comment]
Is there any news of getting t2fonnx with keras models working on recent versions of Keras/Tensorflow? I've tried the workarounds suggested above and tf2onnx.convert.from_keras() gives me an error "Cannot convert a symbolic tf.Tensor (input_1:0) to a numpy array." and model.export() gives error "AttributeError: module 'keras._tf_keras.keras.backend' has no attribute 'set_learning_phase'." 

python 3.11 / tensorflow 2.16.1 / windows 10

**Comment by cyber-barrista** [comment]
This snippet works (at least for my use case)

```python
import keras
import tensorflow as tf
import tf2onnx

def _convert_to_onnx(source_path: str, destination_path: str):
    model = keras.models.load_model(source_path)

    input_tensor = model.layers[0]._input_tensor
    input_signature = tf.TensorSpec(
        name=input_tensor.name, shape=input_tensor.shape, dtype=input_tensor.dtype
    )
    output_name = model.layers[-1].name

    @tf.function(input_signature=[input_signature])
    def _wrapped_model(input_data):
        return {output_name: model(input_data)}

    tf2onnx.convert.from_function(
        _wrapped_model, input_signature=[input_signature], output_path=destination_path
    )
```
`source_path` points to a `.keras` file while `destination_path` points to the corresponding `.onnx` file.

**Comment by eli-osherovich** [comment]
Does it work for anyone when using JAX as the backend?

**Comment by lambda-science** [comment]
None of the tricks listed here works for me.
This issue is fairly old, we can't at all convert from Keras 3 to Onnx ?

```python
  MyoQuant-SDH-Model git:(main) ✗ uv run python -m tf2onnx.convert --saved-model "tf_saved_format" --output "model.onnx"
/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/tf2onnx/utils.py:49: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  onnx_pb.TensorProto.STRING: np.object,
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/tf2onnx/__init__.py", line 15, in <module>
    from tf2onnx import tfonnx, utils, graph, graph_builder, graph_matcher, shape_inference, schemas, convert  # pylint: disable=wrong-import-order
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/tf2onnx/tfonnx.py", line 20, in <module>
    import tf2onnx.onnx_opset  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/tf2onnx/onnx_opset/__init__.py", line 5, in <module>
    from . import (
  File "/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/tf2onnx/onnx_opset/controlflow.py", line 19, in <module>
    from tf2onnx import utils
  File "/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/tf2onnx/utils.py", line 49, in <module>
    onnx_pb.TensorProto.STRING: np.object,
                                ^^^^^^^^^
  File "/Users/cmeyer/code/MyoQuant-SDH-Model/.venv/lib/python3.12/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(__former_attrs__[attr], name=None)
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
