### ISSUE TITLE
SSD Inception v2 doesnt work?

### ISSUE THREAD

**Issue by engineer1982** [onnx/tensorflow-onnx#233]
Hi. I see in "https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml" that the ssd_inception_v2_coco was tested. But when I try to convert the pb model of this network to the onxx model, I get this error:

==================================================

Instructions for updating:
Use tf.gfile.GFile.
2018-12-11 22:50:12.996875: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2018-12-11 22:50:13.209267: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
Traceback (most recent call last):
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\site-packages\tf2onnx\convert.py", line 120, in <module>
    main()
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\site-packages\tf2onnx\convert.py", line 105, in main
    shape_override=args.shape_override)
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\site-packages\tf2onnx\tfonnx.py", line 1866, in process_tf_graph
    topological_sort(g.get_nodes())
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\site-packages\tf2onnx\tfonnx.py", line 1830, in topological_sort
    g.topological_sort(ops)
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\site-packages\tf2onnx\graph.py", line 446, in topological_sort
    _push_stack(stack, node, in_stack)
  File "C:\Users\Valeadmin\Anaconda3\envs\p36\lib\site-packages\tf2onnx\graph.py", line 411, in _push_stack
    raise ValueError('Graph has cycles.')
ValueError: Graph has cycles.

==================================================

What I am missing to replicate what you guys have done with the ssd_inception_v2_coco ?

thank you! :)

**Comment by pengwa** [comment]
@engineer1982 the model is listed in the yaml, but was disabled as a test. So officially it was not convertible for now. it takes times to evaluate the gaps and convert it as we last looked into it.

**Comment by engineer1982** [comment]
Thanks @pengwa meanwhile, do you know if its possible to convert the this ssd .pb model do a pickle file?

**Comment by engineer1982** [comment]
and if not, is there other object detection model that is convertible?

**Comment by ardorem** [comment]
I have reached to here while trying to use tf2onnx for ssd. Is there a list of working models for the link: https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml ?

It would be great if we can keep track of which are supported and which are not.

**Comment by pengwa** [comment]
@ardorem thanks for the feedback, those models marked as "disabled: true" along with a comment like "# issues with control flow" is not supported for that reason the comment described. For those not having "disable: true", they are supported, and will be tested during the PR validation .

**Comment by ardorem** [comment]
Oh I missed the "disabled" flags. Thanks for letting me know!

**Comment by engineer1982** [comment]
@pengwa what is "PR Validation"?

**Comment by guschmue** [comment]
When tests are disabled I tried to have a comment right under the test name with the reason ... I know, its not a great UI - maybe we'll find some time and have a tool stick this automagically into the README.

**Comment by pengwa** [comment]
@engineer1982 it's validation for each pull request. now it is not automatically (change owner run that locally) , but I guess it could be something we can make automatical later.

**Comment by guschmue** [comment]
This converts now.
