### ISSUE TITLE
Cannot handle dynamic shape

### ISSUE THREAD

**Issue by stakemura** [onnx/tensorflow-onnx#267]
Hi,

I cannot handle dynamic shape like the following example code.

```
import tensorflow as tf
import tf2onnx

with tf.Session() as sess:
    x = tf.placeholder(tf.float32, [1, 4, 4, 1], name="input")
    x_shape = tf.shape(x)
    x_ = tf.slice(x, [0, 1, 1, 0], [-1, x_shape[1] - 1, x_shape[2] - 1, -1])
    _ = tf.identity(x_, name="output")
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, output_names=["output:0"])
    model_proto = onnx_graph.make_model("test")
    with open("cropped.onnx", "wb") as f:
        f.write(model_proto.SerializeToString())
```

Error log

```
2019-01-08 19:29:14.454375: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-08 19:29:15.624188: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-08 19:29:15.629221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2019-01-08 19:29:15.705648: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-08 19:29:15.706086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2019-01-08 19:29:15.706794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-01-08 19:29:16.074884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-08 19:29:16.074919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2019-01-08 19:29:16.074925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y 
2019-01-08 19:29:16.074929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N 
2019-01-08 19:29:16.075250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10399 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-01-08 19:29:16.075422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10400 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
ERROR:tf2onnx:node Slice: exception get tensor value: Slice/size__12 must be Const
Traceback (most recent call last):
  File "/home/stakemura/union/falcon/tools/export_onnx.py", line 9, in <module>
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, output_names=["output:0"])
  File "/home/stakemura/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2441, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "/home/stakemura/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2307, in tensorflow_onnx_mapping
    raise ex
  File "/home/stakemura/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2298, in tensorflow_onnx_mapping
    onnx_node = func(g, node, node.name, args)
  File "/home/stakemura/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 995, in slice_op
    size = node.inputs[2].get_tensor_value()
  File "/home/stakemura/anaconda3/lib/python3.6/site-packages/tf2onnx/graph.py", line 180, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Slice/size__12 must be Const
```

**Comment by nbcsm** [comment]
Slice in opset10 now supports dynamic shape.
please give a try with onnx 1.5 and latest tf2onnx master branch.

**Comment by guschmue** [comment]
We assume that is no longer an issue.

**Comment by UndeadBlow** [comment]
I'm successfully convert graph with opeset 10 on 1.5. version but can not load it:
```
ERROR: image_tensor:0_TRT_DYNAMIC_SHAPES:58 In function importInput:
[7] Assertion failed: convert_dims(onnx_tensor_type.shape().dim(), trt_dims)
```

Why this can happen?

**Comment by jignparm** [comment]
> I'm successfully convert graph with opeset 10 on 1.5. version but can not load it:
> Why this can happen?

Does it load using OnnxRuntime python package? If yes, then most likely it's a TRT shape inference limitation.

**Comment by keivanmoazami** [comment]
I have same problem. model converted to onnx but when run inference output shape changed and add zero dimension.
![Screenshot from 2021-01-14 02-32-31](https://user-images.githubusercontent.com/6730752/104520694-cfc21280-5610-11eb-8eeb-700c5380cecc.png)
