### ISSUE TITLE
ValueError: Input 0 of node ToFloat was passed float from image_tensor:0 incompatible with expected uint8.

### ISSUE THREAD

**Issue by M1thun** [onnx/tensorflow-onnx#279]
After optimizing frozen inference graph I am getting this error while checking the results.
Please help me with this at the earliest. 

The error displayed in the terminal

$ python3 Object_detection_webcam.py
Traceback (most recent call last):
  File "/home/mithun/anaconda3/envs/tfp3.6/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node ToFloat was passed float from image_tensor:0 incompatible with expected uint8.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Object_detection_webcam.py", line 66, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/home/mithun/anaconda3/envs/tfp3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/mithun/anaconda3/envs/tfp3.6/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node ToFloat was passed float from image_tensor:0 incompatible with expected uint8.

**Comment by nbcsm** [comment]
it fails when loading tf graph before entering converter logic, 
seems something is wrong with type of the tf graph input?

is that ok to share you tf model please?
and which version of tf is used?

**Comment by M1thun** [comment]
thanks for the reply
sure not a problem. tell me where i can share it with you.

tensorflow 1.6

**Comment by nbcsm** [comment]
you can put it on your github repo or any public cloud storage.
thanks.

**Comment by M1thun** [comment]
I was able to solve this issue by changing some parameters in DetectorActivity.java to accept float model
and hence closing this issue.
Thank you!!
