### ISSUE TITLE
TFL detect app getting crashed with an error for ssd mobilenet v2 model trained for custom dataset. Please help me out 

### ISSUE THREAD

**Issue by M1thun** [onnx/tensorflow-onnx#281]
This is the error I get after app gets crashed

 
java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.
	at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:251)
	at org.tensorflow.lite.Tensor.setTo(Tensor.java:110)
	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:145)
	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
	at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:193)
	at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:247)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by simpeng** [comment]
we don't actually support model built by TFlite.

**Comment by M1thun** [comment]
Thanks for fast response ,
I tried deploying the frozen graph directly without optimizing the graph into android example(not tflite) and the app was getting crashed soon after I open it while it is working fine with my laptop webcam feed.
So for that reason I optimized the pb graph and then deploy the optimized graph into android example(not tflite) but again I reached an error mentioned below  where there is is mismatch in the input data type which I couldnt resolve and then moved to exporting tflite ssd graph and further to .tflte to deploy in TFL detect and facing the errot mentioned in my 1st comment.



After trying to get output from optimized graph from webcam I got this following error:


$ python3 Object_detection_webcam.py
Traceback (most recent call last):
  File "/home/mithun/anaconda3/envs/tfp3.6/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node ToFloat was passed float from image_tensor:0 incompatible with expected uint8.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Object_detection_webcam.py", line 66, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/home/mithun/anaconda3/envs/tfp3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/mithun/anaconda3/envs/tfp3.6/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node ToFloat was passed float from image_tensor:0 incompatible with expected uint8.

**Comment by pengwa** [comment]
too bad about the combability between different TF build.

so object detection logic is converted? I cannot believe.... anyway, this is cool.

**Comment by ramyrao** [comment]
> Voila..!! I have successfully solved this issue and hence closing the issue
> I changed some parameters in DetectorActiivity.java for TFlite to make exception for FLOAT model .
> There are some compatibility issues with T F android(not TFlite) while deploying the model. Where the datatype of input parameters has to be changed somewhere deep in codes to match with the datatype accepted model the problem for which is not yet resolved :( .

**Comment by ramyrao** [comment]
@M1thun 

I am facing the same error, can you please let me know what exactly you did to make the error go away. Will be extremely grateful to you for your reply.
