### ISSUE TITLE
ValueError: tensorflow op Switch is not supported

### ISSUE THREAD

**Issue by thefiddler** [onnx/tensorflow-onnx#291]
When trying to convert a tensorflow graph, I get the following error:

```bash
python -m tf2onnx.convert --input model.pb --inputs image:0 --outputs segmentation:0 --fold_const

using tensorflow=1.12.0, onnx=1.4.1, opset=7, tfonnx=0.3.2/aa1141
2019-01-29 10:49:15.547514: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-01-29 10:49:18.805007: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-01-29 10:49:18.976460: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-01-29 10:49:19.396431: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-01-29 10:49:23.588931: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/convert.py", line 118, in <module>
    main()
  File ~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/convert.py", line 102, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2441, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2290, in tensorflow_onnx_mapping
    raise ValueError("tensorflow op " + op + " is not supported")
ValueError: tensorflow op Switch is not supported
```

I am using tf2onnx 0.3.2, freshly installed from pip.

**Comment by nbcsm** [comment]
we have added more tf control flow support recently, but it is not published to pypi yet.
you may want to give a try with the latest master branch.

and is that possible to share the model?
it is hard to tell whether the Swtich op here is from a while loop or if/else branch.

**Comment by thefiddler** [comment]
It's from an if-else branch to avoid NaNs. Let me try with master!
