### ISSUE TITLE
ValueError: tensorflow op IsNan is not supported

### ISSUE THREAD

**Issue by thefiddler** [onnx/tensorflow-onnx#292]
As a workaround for #291, I tried to use `tf.where(tf.is_nan(x))` to avoid using `tf.cond()`. Unfortunately that also raises a not supported error.

```bash
python -m tf2onnx.convert --input model.pb --inputs image:0 --outputs segmentation:0 --fold_const

using tensorflow=1.12.0, onnx=1.4.1, opset=7, tfonnx=0.3.2/aa1141
2019-01-29 10:57:35.515393: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-01-29 10:57:39.814326: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-01-29 10:57:39.999134: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-01-29 10:57:40.422431: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-01-29 10:57:44.999310: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/convert.py", line 118, in <module>
    main()
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/convert.py", line 102, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2441, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2290, in tensorflow_onnx_mapping
    raise ValueError("tensorflow op " + op + " is not supported")
ValueError: tensorflow op IsNan is not supported
```

Edit: this is also happening with git master (`tfonnx=0.4.0/209e06`).

**Comment by nbcsm** [comment]
link https://github.com/onnx/tensorflow-onnx/issues/270

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/336 is merged to support isnan
