### ISSUE TITLE
ValueError: get tensor value: stack_Concat__28 must be Const

### ISSUE THREAD

**Issue by thefiddler** [onnx/tensorflow-onnx#293]
When trying to convert the [attached model](https://github.com/onnx/tensorflow-onnx/files/2807249/model.pb.zip), I am getting the following error:

```bash
python -m tf2onnx.convert --input sample/model.pb --inputs image:0 --outputs segmentation:0 --fold_const

using tensorflow=1.12.0, onnx=1.4.1, opset=7, tfonnx=0.4.0/209e06
2019-01-29 11:34:38.933012: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-01-29 11:34:38.949411: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-01-29 11:34:38.949649: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-01-29 11:34:38.950258: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-01-29 11:34:38.957778: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
ERROR:tf2onnx:node resize_images/ResizeBilinear: exception get tensor value: stack_Concat__28 must be Const
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/convert.py", line 119, in <module>
    main()
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/convert.py", line 102, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2506, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2349, in tensorflow_onnx_mapping
    raise ex
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 2340, in tensorflow_onnx_mapping
    onnx_node = func(g, node, node.name, args)
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 1170, in upsample_op7
    target_shape = node.inputs[1].get_tensor_value()
  File "~/.virtualenvs/onnx/lib/python3.7/site-packages/tf2onnx/graph.py", line 182, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_Concat__28 must be Const
```

The model resizes the input image to 256x256 using linear interpolation and the error seems to be linked to those two lines:
```python
        new_shape = tf.stack((h, w))
        x = tf.image.resize_images(x, new_shape, interpolation, align_corners=True)
```

**Comment by nbcsm** [comment]
thanks for reporting.

it is a known issue.
- TF ResizeBilinear is able to increase OR decrease image size, while in ONNX, there is no OP to do BOTH.
Upsample can only increase while *Pool can only decrease. when image size or target size is not a const, we don't know which op to map.

- TF ResizeBilinear accepts ```size``` as an input, while Upsample (before opset9) and Pool only accept size as attribute, which needs to be const.

we are proposing onnx change, a Resize op maybe .

**Comment by linkerzhang** [comment]
@nbcsm Resize op is available now. Is that good enough to solve the issue?

**Comment by dima85** [comment]
I have the same issue with retina net model: https://github.com/fizyr/keras-retinanet 
Would be very nice if this could be fixed.

**Comment by nbcsm** [comment]
Slice-10 is supported now.
please give a try on latest master branch with ```--opset 10```
you would need onnx 1.5 and onnxruntime 0.4 to execute the model.

**Comment by zhijxu-MS** [comment]
@dima85 tf2onnx supports slice-10 now, can it fix your issues now?

**Comment by djl11** [comment]
For additional information, I tried with the following model: [tfoptflow](https://github.com/philferriere/tfoptflow).
By using --opset 10, I was able to avoid the error.
I think this issue can therefore be closed?

**Comment by zhijxu-MS** [comment]
thanks for the info.  please feel free to reopen it if any problems.

**Comment by shravanshetty1** [comment]
I encountered this issue - fixed it by setting `--opset 12` - hope this stops you from pulling your hair out, gl

**Comment by OutSorcerer** [comment]
An alternative workaround for those who has to use older ONNX opset e.g. opset 7:

```
# TF version is 2.4.1
# model is Keras model with UpSampling2D layer

def monkey_patched_UpSampling2D_call(self, inputs):
    # Original implementation was:
    #     return backend.resize_images(
    #         inputs, self.size[0], self.size[1], self.data_format,
    #         interpolation=self.interpolation)
    return tf.image.resize(inputs, size=self.output.shape[1:3], method=self.interpolation)


tf.keras.layers.UpSampling2D.call = monkey_patched_UpSampling2D_call

tf.saved_model.save(model, "test_saved_model")

!python3 -m tf2onnx.convert --saved-model "test_saved_model" --output "test_saved_model.onnx" --opset 7
```

The produced ONNX works on NVidia Jetson TX2 (Jetpack 4.4.1, TensorRT 7.1.3.0).
