### ISSUE TITLE
TypeError: Item in ``from list'' not a string

### ISSUE THREAD

**Issue by aeftimia** [onnx/tensorflow-onnx#374]
No matter how I install (setup.py install/develop or pip install) this package, I get `TypeError: Item in ``from list'' not a string

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "tf2onnx/__init__.py", line 13, in <module>
    from tf2onnx import tfonnx, utils, graph, graph_matcher, shape_inference, schemas  # pylint: disable=wrong-import-order
  File "tf2onnx/tfonnx.py", line 24, in <module>
    from tf2onnx.function import *  # pylint: disable=wildcard-import
TypeError: Item in ``from list'' not a string
```

This seems to only affect python2 and not python3

**Comment by guschmue** [comment]
we only support python 3.5 and better.
