### ISSUE TITLE
TF 1.13.1.  test_backend.py failed 

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#381]
ERROR: test_leaky_relu (__main__.BackendTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\test_backend.py", line 741, in test_leaky_relu
    self._run_test_case([_OUTPUT], {_INPUT: x_val})
  File "tests\test_backend.py", line 95, in _run_test_case
    return self.run_test_case(feed_dict, [], output_names_with_port, **kwargs)
  File "C:\last\tensorflow-onnx\tests\backend_test_base.py", line 142, in run_test_case
    target=self.config.target, **process_args)
  File "C:\Program Files\Python3.6\lib\site-packages\tf2onnx-0.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 2477, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "C:\Program Files\Python3.6\lib\site-packages\tf2onnx-0.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 2289, in tensorflow_onnx_mapping
    raise ValueError("tensorflow op " + op + " is not supported")
ValueError: tensorflow op LeakyRelu is not supported

the original TF graph looks as below, this should be different with the one generated in older tf versions. 

![image](https://user-images.githubusercontent.com/10530022/54513894-ad6af980-4993-11e9-96e4-fc2b1e3703f9.png)

**Comment by pengwa** [comment]
@mindest  is working on the fix.

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/issues/381
