### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by ayermolo** [onnx/tensorflow-onnx#434]
Hello

I am trying to convert tiny-yolov2-voc that was created by dark flow.
If I try to convert one directly produced by darkflow it works, but if I try to convert one that went through optimize_for_inference.py I get error below. Any idea what is going on? Is optimize_for_inference.py unnecessary?

Thanks

(tfConverter) c:\projects\gitlab\darkflow\built_graph>python -m tf2onnx.convert --input tiny-yolo-voc_freeze.pb --output tiny-yolo-v2_freeze.onnx --inputs input:0 --outputs output:0 --verbose
2019-04-01 18:42:43.023046: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:tensorflow:Froze 0 variables.
INFO:tensorflow:Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
INFO:tensorflow:Converted 0 variables to const ops.
2019-04-01 18:42:43.732780: I T:\src\github\tensorflow\tensorflow\tools\graph_transforms\transform_graph.cc:318] Applying fold_batch_norms
2019-04-01 18:42:43.847819: I T:\src\github\tensorflow\tensorflow\tools\graph_transforms\transform_graph.cc:318] Applying fold_old_batch_norms
using tensorflow=1.9.0, onnx=1.4.1, opset=7, tfonnx=1.5.0/9fcb06
ERROR:tf2onnx:rewriter <function rewrite_conv2d_with_pad at 0x000001C032F34400>: exception list index out of range
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\convert.py", line 135, in <module>
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\convert.py", line 118, in main
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 2557, in process_tf_graph
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 2472, in run_rewriters
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 2463, in run_rewriters
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 2331, in rewrite_conv2d_with_pad
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 518, in conv_op
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 380, in conv_convert_inputs
  File "C:\ProgramData\Anaconda3\envs\tfConverter\lib\site-packages\tf2onnx-1.5.0-py3.6.egg\tf2onnx\tfonnx.py", line 340, in spatial_map
IndexError: list index out of range

**Comment by nbcsm** [comment]
could you share your model please? thanks.

**Comment by ayermolo** [comment]
@nbcsm Is there a shared drive or something for this project I can dump it to? It's almost 200mb, and looks like too big for github.

**Comment by nbcsm** [comment]
sorry, we don't have a shared drive...
you may use any public shared drive.

**Comment by ayermolo** [comment]
@nbcsm Trying to be compliant here with internal IT policies...
I can put it on FTP server that is externally accessible, but it requires username/password. Can email those to you directly. Would that be acceptable?
Alternative I can post steps to reproduce. Involves using darkflow to generate the model.

**Comment by nbcsm** [comment]
yes, username/password is fine.
thanks.

**Comment by ayermolo** [comment]
What is your email so I can sent it? Thanks.

**Comment by nbcsm** [comment]
guohua at microsoft dot com

**Comment by nbcsm** [comment]
@ayermolo, i got your model now.
we will take a look and get back to you later.
sorry but it may take a while, we are really busy with opset10 stuff currently...

**Comment by ayermolo** [comment]
@nbcsm No problem. Thanks for looking at it. I mentioned second issue of Transpose not being inserted properly. I think that one is a higher priority. Want me to file a separate issue here?

**Comment by nbcsm** [comment]
yes, please.

**Comment by CasiaFan** [comment]
Same issue when converting SSD-ResNet-FPN model. Here is the code while shape None error raised at `FeatureExtractor/resnet_v1_50/resnet_v1_50/conv1/Conv2D` node.

```bash
python3 -m tf2onnx.convert \
        --input=frozen_inference_model.pb \
        --output=ssd_res.onnx \
        --inputs="image_tensor:0[1,640,640,3]" \
        --outputs="detection_boxes:0,detection_classes:0,detection_scores:0,num_detections:0"\
        --opset=8 \
        --verbose
```

**Comment by guschmue** [comment]
ahh, this is ssd. There are some ops missing in onnx for ssd but onnx-1.5/opset10 that was just released does have the support we need to make this work. We are in the process of adding opset10 to the converter right now ... should be there shortly (maybe 1-2 weeks before this is solid enough to try).

**Comment by nbcsm** [comment]
@ayermolo, the list index out of range issue was already fixed in master branch.

your original graph and frozen graph can all be converted.
the command that i used:
python -m tf2onnx.convert --input yolo-voc_freeze.pb --output yolo-voc_freeze.onnx --inputs input:0[1,416,416,3] --outputs output:0 --opset 7

but then i met https://github.com/onnx/tensorflow-onnx/issues/480, it is a bug, i will fix it.

**Comment by nbcsm** [comment]
close this issue
