### ISSUE TITLE
Cann't support 3d convolution: ValueError: kernel rank must be 2* spatial

### ISSUE THREAD

**Issue by meijia85** [onnx/tensorflow-onnx#461]
3D convolution kernel rank is 5, 3D convolution kernel shape [H, W, D, inChannels, outChannels]
conv_kernel_shape and conv_dims_attr only support kernel rank 2 or 4.

**Comment by SPengLiang** [comment]
same issue

**Comment by ralovich** [comment]
Reproducer network available at https://github.com/ralovich/trt-regression
$python -m tf2onnx.convert --input model_100.pb --inputs input_1_100_100_100_1:0 --outputs inception_v3_3d_1/output/sub_1:0 --output model_100.onnx --opset 10

2019-10-29 10:40:57,751 - INFO - Using tensorflow=1.15.0, onnx=1.6.0, tf2onnx=1.5.3/7b598d
2019-10-29 10:40:57,751 - INFO - Using opset <onnx, 10>
2019-10-29 10:40:58,039 - ERROR - Failed to convert node inception_v3_3d_1/full_conv/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/full_conv/Conv/Conv3D
Inputs:
	inception_v3_3d_1/full_conv/truediv:0=Div, [1, 100, 100, 100, 1], 1
	inception_v3_3d/full_conv/Conv/conv0_weights:0=Const, [3, 3, 3, 1, 32], 1
Outpus:
	inception_v3_3d_1/full_conv/Conv/Conv3D:0=[1, 98, 98, 98, 32], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,041 - ERROR - Failed to convert node inception_v3_3d_1/full_conv/Conv_1/Conv3D
OP=Conv
Name=inception_v3_3d_1/full_conv/Conv_1/Conv3D
Inputs:
	inception_v3_3d_1/full_conv/Conv/Relu:0=Relu, [1, 98, 98, 98, 32], 1
	inception_v3_3d/full_conv/Conv_1/conv4_weights:0=Const, [3, 3, 3, 32, 192], 1
Outpus:
	inception_v3_3d_1/full_conv/Conv_1/Conv3D:0=[1, 96, 96, 96, 192], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,041 - ERROR - Tensorflow op [inception_v3_3d_1/full_conv/pool2: MaxPool3D] is not supported
2019-10-29 10:40:58,041 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/Conv/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/AvgPool3D:0=AveragePool, [1, 92, 92, 92, 192], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch_pool/Conv/branch_pool_weights:0=Const, [1, 1, 1, 192, 32], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/Conv/Conv3D:0=[1, 92, 92, 92, 32], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,042 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv/Conv3D
Inputs:
	inception_v3_3d_1/full_conv/pool2:0=MaxPool3D, [1, 94, 94, 94, 192], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch5x5/Conv/branch5x5a_weights:0=Const, [1, 1, 1, 192, 48], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv/Conv3D:0=[1, 94, 94, 94, 48], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,042 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv_1/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv_1/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv/Relu:0=Relu, [1, 94, 94, 94, 48], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch5x5/Conv_1/branch5x5b_weights:0=Const, [5, 5, 5, 48, 64], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch5x5/Conv_1/Conv3D:0=[1, 90, 90, 90, 64], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,043 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv/Conv3D
Inputs:
	inception_v3_3d_1/full_conv/pool2:0=MaxPool3D, [1, 94, 94, 94, 192], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch3x3dbl/Conv/branch3x3dbla_weights:0=Const, [1, 1, 1, 192, 64], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv/Conv3D:0=[1, 94, 94, 94, 64], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,043 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_1/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_1/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv/Relu:0=Relu, [1, 94, 94, 94, 64], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_1/branch3x3dblb_weights:0=Const, [3, 3, 3, 64, 96], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_1/Conv3D:0=[1, 92, 92, 92, 96], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,043 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_2/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_2/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_1/Relu:0=Relu, [1, 92, 92, 92, 96], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_2/branch3x3dblc_weights:0=Const, [3, 3, 3, 96, 96], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch3x3dbl/Conv_2/Conv3D:0=[1, 90, 90, 90, 96], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,043 - ERROR - Failed to convert node inception_v3_3d_1/inception_1/mixed_35x35x256a/branch1x1/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/inception_1/mixed_35x35x256a/branch1x1/Conv/Conv3D
Inputs:
	inception_v3_3d_1/full_conv/pool2:0=MaxPool3D, [1, 94, 94, 94, 192], 1
	inception_v3_3d/inception_1/mixed_35x35x256a/branch1x1/Conv/branch1x1_weights:0=Const, [1, 1, 1, 192, 64], 1
Outpus:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch1x1/Conv/Conv3D:0=[1, 94, 94, 94, 64], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,044 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch_pool/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch_pool/Conv/Conv3D
Inputs:
	inception_v3_3d_1/mixed_35x35x288_0/branch_pool/AvgPool3D:0=AveragePool, [1, 88, 88, 88, 256], 1
	inception_v3_3d/mixed_35x35x288_0/branch_pool/Conv/branch_pool_0_weights:0=Const, [1, 1, 1, 256, 32], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch_pool/Conv/Conv3D:0=[1, 88, 88, 88, 32], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,045 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/concat:0=Concat, [1, 90, 90, 90, 256], 1
	inception_v3_3d/mixed_35x35x288_0/branch5x5/Conv/branch5x5_0_weights:0=Const, [1, 1, 1, 256, 48], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv/Conv3D:0=[1, 90, 90, 90, 48], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,045 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv_1/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv_1/Conv3D
Inputs:
	inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv/Relu:0=Relu, [1, 90, 90, 90, 48], 1
	inception_v3_3d/mixed_35x35x288_0/branch5x5/Conv_1/branch5x5b_0_weights:0=Const, [5, 5, 5, 48, 64], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch5x5/Conv_1/Conv3D:0=[1, 86, 86, 86, 64], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,045 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/concat:0=Concat, [1, 90, 90, 90, 256], 1
	inception_v3_3d/mixed_35x35x288_0/branch3x3dbl/Conv/branch3x3dbl_0_weights:0=Const, [1, 1, 1, 256, 64], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv/Conv3D:0=[1, 90, 90, 90, 64], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,046 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_1/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_1/Conv3D
Inputs:
	inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv/Relu:0=Relu, [1, 90, 90, 90, 64], 1
	inception_v3_3d/mixed_35x35x288_0/branch3x3dbl/Conv_1/branch3x3dblb_0_weights:0=Const, [3, 3, 3, 64, 96], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_1/Conv3D:0=[1, 88, 88, 88, 96], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,046 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_2/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_2/Conv3D
Inputs:
	inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_1/Relu:0=Relu, [1, 88, 88, 88, 96], 1
	inception_v3_3d/mixed_35x35x288_0/branch3x3dbl/Conv_2/branch3x3dblc_0_weights:0=Const, [3, 3, 3, 96, 96], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch3x3dbl/Conv_2/Conv3D:0=[1, 86, 86, 86, 96], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,046 - ERROR - Failed to convert node inception_v3_3d_1/mixed_35x35x288_0/branch1x1/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/mixed_35x35x288_0/branch1x1/Conv/Conv3D
Inputs:
	inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/concat:0=Concat, [1, 90, 90, 90, 256], 1
	inception_v3_3d/mixed_35x35x288_0/branch1x1/Conv/branch1x1_0_weights:0=Const, [1, 1, 1, 256, 64], 1
Outpus:
	inception_v3_3d_1/mixed_35x35x288_0/branch1x1/Conv/Conv3D:0=[1, 90, 90, 90, 64], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,047 - ERROR - Failed to convert node inception_v3_3d_1/output/Conv/Conv3D
OP=Conv
Name=inception_v3_3d_1/output/Conv/Conv3D
Inputs:
	inception_v3_3d_1/mixed_35x35x288_0/concat:0=Concat, [1, 86, 86, 86, 256], 1
	inception_v3_3d/output/Conv/output_weights:0=Const, [10, 10, 10, 256, 2], 1
Outpus:
	inception_v3_3d_1/output/Conv/Conv3D:0=[1, 68, 68, 68, 2], 1
Traceback (most recent call last):
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-10-29 10:40:58,047 - ERROR - Unsupported ops: Counter({'MaxPool3D': 1})
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 575, in process_tf_graph
    raise exceptions[0]
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/home/tade/venv-tf-onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial

**Comment by xiuxin121** [comment]
i get the same issue.
the tensorflow-onnx:https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py
def conv_kernel_shape(ctx, node, input_idx, spatial=2):
kernel_shape = ctx.get_shape(node.input[input_idx])
if len(kernel_shape) != 2 * spatial:
raise ValueError("kernel rank must be 2* spatial")
kernel_shape = kernel_shape[0:spatial]
node.set_attr("kernel_shape", kernel_shape)
return kernel_shape
it is only support 2dconv????

**Comment by guschmue** [comment]
ok, got it - popular feature. We'll add this real soon.

**Comment by pribalta** [comment]
Same issue here for a 3d model. @guschmue any timeline for this feature to be available?

Part of the trace:
```
2019-11-28 08:55:31,794 - ERROR - Tensorflow op [vnet/upsample_block_1/residual_block/batch_normalization_2/batchnorm/add_1: AddV2] is not supported
2019-11-28 08:55:31,795 - ERROR - Tensorflow op [vnet/upsample_block_1/residual_block/add: AddV2] is not supported
2019-11-28 08:55:31,795 - ERROR - Tensorflow op [vnet/output_block/conv3d_transpose/conv3d_transpose: Conv3DBackpropInputV2] is not supported
2019-11-28 08:55:31,795 - ERROR - Tensorflow op [vnet/output_block/batch_normalization/batchnorm/add_1: AddV2] is not supported
2019-11-28 08:55:31,795 - ERROR - Failed to convert node vnet/output_block/conv3d/Conv3D
OP=Conv
Name=vnet/output_block/conv3d/Conv3D
Inputs:
        vnet/output_block/Relu:0=Relu, [1, 32, 32, 32, 16], 1
        vnet/conv3d_19/kernel:0=Const, [3, 3, 3, 16, 3], 1
Outpus:
        vnet/output_block/conv3d/Conv3D:0=[1, 32, 32, 32, 3], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial
2019-11-28 08:55:31,795 - ERROR - Unsupported ops: Counter({'AddV2': 50, 'Conv3DBackpropInputV2': 3})
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 575, in process_tf_graph
    raise exceptions[0]
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 204, in version_1
    kernel_shape = conv_kernel_shape(ctx, node, 1, spatial=2)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 189, in conv_kernel_shape
    raise ValueError("kernel rank must be 2* spatial")
ValueError: kernel rank must be 2* spatial

```

**Comment by xiuxin121** [comment]
any timeline for this feature to be available?
mark+1

**Comment by danperazzo** [comment]
Any updates on this feature?

**Comment by ThatAIGeek** [comment]
any updates?

**Comment by crohkohl** [comment]
Are there any updates? I looked into the code and it seems there are multiple steps to take, e.g. the whole data and kernel conversion still only assumes 2D. This will require several changes throughout `nn.py`. Further, `MaxPool3D` is also missing in order to be complete and usable.

I would look into it - did anyone already start with this or found a workaround?

**Comment by danperazzo** [comment]
Is there anyway to construct the Conv3D op from the 2D convolution op?

**Comment by crohkohl** [comment]
I do not think this would be worthwhile, because a 3D or N-D convolution should be supported.

The major hurdle is a library redesign that uses a "channel_first" or "channel_last" format in n-dimensions and not only hardcoded 2D-Dimensions. This touches many positions but would be worthwhile.

@guschmue Is there already some work started on this or a strategy defined?

**Comment by guschmue** [comment]
Sorry, we have not gotten to it. I'll try to find some time next few days.

**Comment by danperazzo** [comment]
Thanks @guschmue! However, in the meantime, is there any workaround?

**Comment by danperazzo** [comment]
Hey guys, I tried a workaround. For the moment, my model does not need 2D convolutions. Because of this, I tried to change the nn.py code so that, whenever it seemed to handle 2D convolutions, I changed to their 3D equivalents. I will upload the changed  nn.py function. I have only changed the opset under "Conv2D,Conv3D,Conv2D" and all the functions that are called by it. With this workaround I managed to create a onnx model, however, when I tried to load this model, it freezes my computer (keeps alocating memory without stop). (I only upload it as a .txt since github does not support sharing .py files). Again, thanks for the help!
[nn.txt](https://github.com/onnx/tensorflow-onnx/files/4350336/nn.txt)

**Comment by gerbenvv** [comment]
Hey, I have made a fix allowing any-dimensional convolutions to work (although it seems tensorflow only supports 1-3 dimensional convolutions. I have tested it locally for a lot of configurations, but there may be need for some test cases as I don't think 1D and 3D convolutions are tested.

The code heavily assumes two-dimensionality, for example in `Node.is_nhwc()`, which only works for the 2D case (a general check is checking if the `data_format` does not start with `NC`). I've only been able to fix some of that, but there needs to be more awareness about this I think. I have made some utility functions to make this transition easier.

**Comment by ralovich** [comment]
Could this be please reopened. In the example from https://github.com/onnx/tensorflow-onnx/issues/461#issuecomment-559401157, we can see that multiple other layers are not supported: Conv3DBackpropInputV2, AddV2.

**Comment by guschmue** [comment]
I think this issue is for Conv3D. Might be easier to just open a new issue for the 3D pooling and Conv3DBackpropInputV2.
AddV2 should be supported https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/math.py#L25 since some time.

**Comment by guschmue** [comment]
and just reading over @gerbenvv comment - yes, we should add some ut for *3D*
