### ISSUE TITLE
Problems converting Resnet50 (from ONNX to TensorRT) 

### ISSUE THREAD

**Issue by adriacabeza** [onnx/tensorflow-onnx#476]
Hi, I am trying to create a Keras to TensorRT converter for my models through tensorflow-onnx. They way it works is extracting the frozen graph of the Keras model(in this case the ResNet50 from keras.applications) and then parsing to tensorRT the ONNX model converted from it. 

Here is the line I use to convert it to ONNX (I do have tried also with opset 7 which is the one recommended in the README, and also I've done it through terminal with the command)
```python
os.system('python -m tf2onnx.convert --input {} --inputs {} --outputs {} --output {} --opset 8  --verbose'.format(tf_outfile, INPUT_NAMES, OUTPUT_NAMES, onnx_outfile))
print('ONNX model succesfully created')
```

I do get this output warnings if I run it:

```bash
using tensorflow=1.13.1, onnx=1.4.1, opset=8, tfonnx=1.4.1/1ccb27
tensorflow ops: Counter({'Const': 430, 'Switch': 318, 'FusedBatchNorm': 106, 'BiasAdd': 54, 'Conv2D': 53, 'Merge': 53, 'Relu': 49, 'Add': 16, 'Pad': 2, 'Placeholder': 1, 'Mean': 1, 'PlaceholderWithDefault': 1, 'MaxPool': 1, 'MatMul': 1, 'Softmax': 1})
tensorflow attr: Counter({'T': 655, 'dtype': 432, 'value': 430, '_class': 318, 'data_format': 214, 'epsilon': 106, 'is_training': 106, 'padding': 54, 'strides': 54, 'dilations': 53, 'use_cudnn_on_gpu': 53, 'N': 53, 'Tpaddings': 2, 'shape': 2, 'transpose_b': 1, 'keep_dims': 1, 'ksize': 1, 'Tidx': 1, 'transpose_a': 1})
onnx mapped: Counter({'Const': 429, 'FusedBatchNorm': 106, 'BiasAdd': 54, 'If': 53, 'Conv2D': 52, 'Relu': 49, 'Add': 16, 'Placeholder': 1, 'Mean': 1, 'MaxPool': 1, 'Pad': 1, 'PlaceholderWithDefault': 1, 'MatMul': 1, 'Softmax': 1})
onnx unmapped: Counter()
NON-CRITICAL error in optimizer:  ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/optimizer/__init__.py", line 33, in optimize_graph\n    graph = opt(debug=debug).optimize(graph)\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 145, in optimize\n    if self._handle_nhwc_tranpose(n):\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 271, in _handle_nhwc_tranpose\n    return op_handler(trans, p)\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 428, in _identity_handler\n    self._g.remove_node(node.name)\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 478, in remove_node\n    utils.make_sure(node_name in self._nodes_by_name, "node %s not in current graph, cannot remove", node_name)\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/utils.py", line 302, in make_sure\n    raise ValueError("make_sure failure: " + error_msg % args)\n', 'ValueError: make_sure failure: node bn_conv1/cond_Identity__10 not in current graph, cannot remove\n']
NON-CRITICAL error in optimizer:  ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 1061, in optimize_model_proto\n    model_proto = graph.make_model(onnx_model_proto.graph.doc_string,\n', "AttributeError: 'NoneType' object has no attribute 'make_model'\n"]
NON-CRITICAL, optimizers are not applied successfully
Complete successfully, the onnx model is generated at model.onnx
```

Then I use the following code to convert it to a tensorRT engine:
```python 

# It creates a TensorRt engine from an ONNX model
def fromOnnx2TensorRTEngine(onnx_file_path, engine_file_path):
        b = False
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
                builder.max_workspace_size = 1 << 30  #1GB
                builder.max_batch_size = 1
                builder.fp16_mode = True
                if not os.path.exists(onnx_file_path):
                        print('ONNX file {} not found!'.format(onnx_file_path))
                        exit(0)
                print('Loading ONNX file from path {}'.format(onnx_file_path))
                with open(onnx_file_path,'rb') as model:
                        print('Beginning ONNX file parsing')
                        b = parser.parse(model.read()) # if the parsing was completed b is true
                if b:
                        print('Completed parsing of ONNX file')
                        print('Building an engine from file {}; this may take a while'.format(onnx_file_path))
                        engine = builder.build_cuda_engine(network)
                        del parser
                        if(engine):
                                print('Completed creating Engine')
                                with open(engine_file_path,"wb") as f:
                                        f.write(engine.serialize())
                                        print('Engine saved')
                        else:
                                print('Error building engine')
                                exit(1)
                else:
                        print('Number of errors: {}'.format(parser.num_errors))
                        error = parser.get_error(0) # if it gets mnore than one error this have to be changed
                        del parser
                        desc = error.desc()
                        line = error.line()
                        code = error.code()
                        print('Description of the error: {}'.format(desc))
                        print('Line where the error occurred: {}'.format(line))
                        print('Error code: {}'.format(code))
                        print("Model was not parsed successfully")
                        exit(0)
```

But the code does not work because it is not able to parse the ONNX model, this is the error I get:

```bash 
Creating the engine from ONNX
Loading ONNX file from path model.onnx
Beginning ONNX file parsing
Number of errors: 1
Description of the error: No importer registered for op: If
Line where the error occurred: 142
Error code: UNSUPPORTED_NODE
Model was not parsed successfully
```
If I got some error regarding an implemented layer I would have tried some other stuff but since the operation it gets the error is If. I do not know what it could be the error. I've also tried to use the Python API but I do get the same error. How could I solve it (the warnings and the parsing error) ? 

Thanks in advance.

**Comment by adriacabeza** [comment]
Also I've tried to download from source tensorflow-onnx and I've gotten a different verbose output but the error still remains the same. Here it is:

```bash
2019-04-24 10:20:30,287 - INFO - tf2onnx.tfonnx: Using tensorflow=1.13.1, onnx=1.4.1, tf2onnx=1.5.0/1f8589
2019-04-24 10:20:30,287 - INFO - tf2onnx.tfonnx: Using opset <onnx, 8>
2019-04-24 10:20:32,373 - VERBOSE - tf2onnx.tfonnx: Summay Stats:
	tensorflow ops: Counter({'Const': 430, 'Switch': 318, 'FusedBatchNorm': 106, 'BiasAdd': 54, 'Conv2D': 53, 'Merge': 53, 'Relu': 49, 'Add': 16, 'Pad': 2, 'Placeholder': 1, 'Mean': 1, 'MaxPool': 1, 'Softmax': 1, 'MatMul': 1})
	tensorflow attr: Counter({'T': 655, 'dtype': 431, 'value': 430, 'data_format': 214, 'is_training': 106, 'epsilon': 106, 'padding': 54, 'strides': 54, 'N': 53, 'use_cudnn_on_gpu': 53, 'dilations': 53, 'Tpaddings': 2, 'transpose_a': 1, 'transpose_b': 1, 'keep_dims': 1, 'ksize': 1, 'Tidx': 1, 'shape': 1})
	onnx mapped: Counter({'Const': 429, 'FusedBatchNorm': 106, 'BiasAdd': 54, 'If': 53, 'Conv2D': 52, 'Relu': 49, 'Add': 16, 'Mean': 1, 'Placeholder': 1, 'MaxPool': 1, 'Softmax': 1, 'Pad': 1, 'MatMul': 1})
	onnx unmapped: Counter()
2019-04-24 10:20:32,486 - INFO - tf2onnx: 
2019-04-24 10:20:32,848 - INFO - tf2onnx.optimizer: Optimizing ONNX model
2019-04-24 10:20:32,852 - VERBOSE - tf2onnx.optimizer: Apply optimize_transpose
2019-04-24 10:20:32,936 - WARNING - tf2onnx.optimizer: Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/optimizer/__init__.py", line 44, in optimize_graph
    graph = factory().optimize(current)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/optimizer/optimizer_base.py", line 32, in optimize
    graph = self._optimize(graph)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/optimizer/transpose_optimizer.py", line 143, in _optimize
    if self._handle_nhwc_tranpose(n):
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/optimizer/transpose_optimizer.py", line 262, in _handle_nhwc_tranpose
    return op_handler(trans, p)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/optimizer/transpose_optimizer.py", line 419, in _identity_handler
    self._g.remove_node(node.name)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/graph.py", line 485, in remove_node
    utils.make_sure(node_name in self._nodes_by_name, "node %s not in current graph, cannot remove", node_name)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/utils.py", line 304, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: node bn_conv1/cond_Identity__13 not in current graph, cannot remove
2019-04-24 10:20:32,937 - VERBOSE - tf2onnx.optimizer: Apply fold_constants
2019-04-24 10:20:33,105 - VERBOSE - tf2onnx.optimizer.ConstFoldOptimizer: no change
2019-04-24 10:20:33,105 - VERBOSE - tf2onnx.optimizer: Apply merge_duplication
2019-04-24 10:20:33,679 - VERBOSE - tf2onnx.optimizer.MergeDuplicatedNodesOptimizer: Transpose -4 (320->316)
2019-04-24 10:20:33,679 - VERBOSE - tf2onnx.optimizer: Apply remove_identity
2019-04-24 10:20:33,830 - VERBOSE - tf2onnx.optimizer.IdentityOptimizer: Identity -479 (532->53)
2019-04-24 10:20:33,833 - INFO - tf2onnx.optimizer: After optimization: Transpose -4 (320->316), Identity -479 (532->53)
2019-04-24 10:20:33,919 - INFO - tf2onnx: 
2019-04-24 10:20:33,920 - INFO - tf2onnx: Successfully converted TensorFlow model model.pb to ONNX
2019-04-24 10:20:34,041 - INFO - tf2onnx: ONNX model is saved at model.onnx
ONNX model succesfully created
```

**Comment by prasanthpul** [comment]
Hi, TensorRT does not support all ONNX Ops (such as If). Have you tried running with ONNX Runtime (https://pypi.org/project/onnxruntime/)? ONNX Runtime supports all ONNX operators. The onnxruntime-gpu package has CUDA support. You can also get TensorRT acceleration since ONNX Runtime integrates with TensorRT as an optional execution provider (https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md#TensorRT)

**Comment by guschmue** [comment]
I belief the official tensorflow resnet50 should work fine. We use it here:
https://github.com/mlperf/inference/tree/master/cloud/image_classification
and the stesps to convert it to onnx are here:
https://github.com/mlperf/inference/blob/master/cloud/image_classification/tools/resnet50-to-onnx.sh

**Comment by adriacabeza** [comment]
First of all, thanks for your fast responses, appreciated 🥇 

Hi @prasanthpul, I've checked onnxruntime and it seems really cool and interesting. How does it work exactly? Since not all operations are not supported in TensorRT I do not get how it can be used the TensorRT execution provider. Are the subgraphs that are convertible transformed into TensorRT and the ones that are not implemented yet kept in onnx? How is the ONNX graph processed to be executed in the NVIDIA hardware?

Hi @guschmue, the example you posted is not working because the Zenodo link (the place where the model is located) is broken. However, I checked it out, and we are doing kinda exactly the same. 
Also, there is the difference that I am trying starting from a Keras model that is transformed to a frozen graph and not starting from a .pb file.  My problem is not the conversion, the conversion to ONNX is done correctly, is the step to TensorRT where I figure the issue of an unsupported ONNX ops in TensorRT.

Thanks in advance

**Comment by guschmue** [comment]
Got it. For resnet50 I'd expect that tensorrt has all the ops needed and naively assume keras should result in the same ops. This is the standard keras resnet50 ? We could take a look if we see something in that model that is different from the tensorflow model.

**Comment by adriacabeza** [comment]
Yes, I expected the same as you. I am using https://github.com/keras-team/keras-applications/blob/master/keras_applications/resnet50.py available with ```python
from keras.applications.resnet50 import ResNet50```. It is difficult to see which layers are the ones that gives us problems. 

As I said before here we can see the ops that are present in the tensorflow frozen graph from the Keras model (note that in this step the training nodes are removed ) and its mapped ONNX ops:
```bash
	tensorflow ops: Counter({'Const': 430, 'Switch': 318, 'FusedBatchNorm': 106, 'BiasAdd': 54, 'Conv2D': 53, 'Merge': 53, 'Relu': 49, 'Add': 16, 'Pad': 2, 'Softmax': 1, 'MatMul': 1, 'MaxPool': 1, 'Placeholder': 1, 'Mean': 1})
	tensorflow attr: Counter({'T': 655, 'dtype': 431, 'value': 430, 'data_format': 214, 'epsilon': 106, 'is_training': 106, 'padding': 54, 'strides': 54, 'use_cudnn_on_gpu': 53, 'N': 53, 'dilations': 53, 'Tpaddings': 2, 'ksize': 1, 'keep_dims': 1, 'transpose_b': 1, 'shape': 1, 'transpose_a': 1, 'Tidx': 1})
	onnx mapped: Counter({'Const': 429, 'FusedBatchNorm': 106, 'BiasAdd': 54, 'If': 53, 'Conv2D': 52, 'Relu': 49, 'Add': 16, 'Placeholder': 1, 'MatMul': 1, 'MaxPool': 1, 'Pad': 1, 'Softmax': 1, 'Mean': 1}) ```

**Comment by prasanthpul** [comment]
@adriacabeza ONNX Runtime provides optimized CPU implementations of all ONNX operators. It also has mechanism for TensorRT and others to plug in. Subgraphs that are supported by TensorRT are sent to TensorRT, they rest is handled by ONNX Runtime. This gives you combination of full ONNX support while still getting perf optimizations provided by various accelerators.

**Comment by adriacabeza** [comment]
@prasanthpul that sounds really nice :D. Really cool work! 

I guess the way it works is similar to [TensorFlow-TensorRT](https://docs.nvidia.com/deeplearning/dgx/tf-trt-user-guide/index.html). Is there any study comparing them or showing the differences of performance with ONNX Runtime + TensorRT?

**Comment by guschmue** [comment]
So for the list of ops above - TensorRT might not like the 'If' that is a result of the 'Switch' in the keras model. Not totally sure why this is in the keras model but there is little we can do on it in tf2onnx.

**Comment by adriacabeza** [comment]
That is true, thank you. I will wait for TensorRT to develop more layers. Until then, will try the ONNX runtime option and check it's performance.

**Comment by barzan-hayati** [comment]
@adriacabeza  How you convert `.onnx` file to `TensorRT` `.trt `using `onnxruntime`, `onnxruntime-gpu`or other tools?
Thanks in adnavce.
