### ISSUE TITLE
"ValueError: Graph has cycles." for another model

### ISSUE THREAD

**Issue by mkawahito** [onnx/tensorflow-onnx#513]
It is related to https://github.com/onnx/tensorflow-onnx/issues/182.

I tried to convert [kagglelstm1.pb.zip](https://github.com/onnx/tensorflow-onnx/files/3175379/kagglelstm1.pb.zip), but I got the following error. Could you take a look at this problem?

```
$ python3 -m tf2onnx.convert --opset 10 --input kagglelstm1.pb --output kagglelstm1.onnx --inputs lstm_1_input:0 --outputs dense_1/Sigmoid:0 --continue_on_error

2019-05-10 05:31:46,509 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.0/348b4d
2019-05-10 05:31:46,510 - INFO - Using opset <onnx, 10>
2019-05-10 05:31:46,686 - ERROR - rewriter <function rewrite_single_direction_lstm at 0x7f4fe2b891e0>: exception list index out of range
2019-05-10 05:31:46,688 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 29, in rewrite_single_direction_lstm\n    return r.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/unit_rnn_rewriter_base.py", line 63, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,696 - ERROR - rewriter <function rewrite_single_direction_gru at 0x7f4fe2b997b8>: exception list index out of range
2019-05-10 05:31:46,696 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 38, in rewrite_single_direction_gru\n    return r.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/unit_rnn_rewriter_base.py", line 63, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,704 - ERROR - rewriter <function rewrite_custom_rnn_cell at 0x7f4fe2b99e18>: exception list index out of range
2019-05-10 05:31:46,704 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 46, in rewrite_custom_rnn_cell\n    return  CustomRnnRewriter(g).run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/custom_rnn_rewriter.py", line 43, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,710 - ERROR - rewriter <function rewrite_generic_loop at 0x7f4fe2b99ea0>: exception list index out of range
2019-05-10 05:31:46,710 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/rnn.py", line 50, in rewrite_generic_loop\n    return LoopRewriter(g).run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter.py", line 35, in run\n    return self.run_internal()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal\n    self._check_in_read_only_mode(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode\n    self._parse_loop_variables(context)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables\n    loop_var = self._get_loop_var_from_switch(s)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/loop_rewriter_base.py", line 391, in _get_loop_var_from_switch\n    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]\n', 'IndexError: list index out of range\n']
2019-05-10 05:31:46,713 - ERROR - rewriter <function rewrite_cond at 0x7f4fe2b67488>: exception Graph has cycles.
2019-05-10 05:31:46,714 - INFO - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 650, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/cond_rewriter.py", line 321, in rewrite_cond\n    return CondRewriter(g).rewrite()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/cond_rewriter.py", line 56, in rewrite\n    return self.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/rewriter/cond_rewriter.py", line 63, in run\n    self.g.topological_sort(self.g.get_nodes())\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 775, in topological_sort\n    _push_stack(stack, node, in_stack)\n', '  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 732, in _push_stack\n    raise ValueError(\'Graph has cycles.\')\n', 'ValueError: Graph has cycles.\n']
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/convert.py", line 145, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/convert.py", line 129, in main
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 867, in make_model
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 794, in make_graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 775, in topological_sort
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/graph.py", line 732, in _push_stack
ValueError: Graph has cycles.
```

**Comment by lucienwang1009** [comment]
Current converter only supports TensorArray.stack() outside while_loop, while it seems you invoke TensorArray.read().
This usage is reasonable when you only want to get one item in the TensorArray. 
We will see if it's easy to support this case.
For now, I suggest instead of using TensorArray.read(), you can stack the TensorArray first then get the item by Gather or Slice.

**Comment by guschmue** [comment]
close this one since it is quite old and the code improved a lot since. Also under tf-2.x we use the V2 control flow which should help.
