### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by zcc720** [onnx/tensorflow-onnx#515]
**when i convert my own ssd_mobilenet net,some wrong with it,Is there any solution to this problem?**
 python -m tf2onnx.convert --input ./mobilenet_274308/frozen_inference_graph.pb  --opset 10 --inputs image_tensor:0 --outputs detection_boxes:0,detection_scores:0,detection_classes:0,num_detections:0 --output ./mobilenet_274308/mobilenet_v2_coco.onnx
2019-05-14 13:47:58,814 - INFO - Using tensorflow=1.12.0, onnx=1.5.0, tf2onnx=1.5.0/73ac94
2019-05-14 13:47:58,814 - INFO - Using opset <onnx, 10>
2019-05-14 13:48:01,426 - ERROR - loop rewrite failed, due to exception: object of type 'NoneType' has no len(), details:Traceback (most recent call last):
  File "/home/jh/tensorflow-onnx/tf2onnx/rewriter/loop_rewriter.py", line 61, in rewrite
    out_tensor_value_info.shape = utils.create_vague_shape_like(out_tensor_value_info.shape)
  File "/home/jh/tensorflow-onnx/tf2onnx/utils.py", line 394, in create_vague_shape_like
    make_sure(len(shape) >= 0, "rank should be >= 0")
TypeError: object of type 'NoneType' has no len()
2019-05-14 13:48:01,427 - ERROR - rewriter <function rewrite_generic_loop at 0x7f405f49b620>: exception rewrite failed, so just fast fail it

**Comment by nbcsm** [comment]
could you give another try using latest master branch?
tf shape inference is enhanced recently, hope it works.

if it is still not working, please share your model so we can take a look.

**Comment by zcc720** [comment]
I tried the latest version and succeeded. Thank you.

**Comment by yahuuu** [comment]
> could you give another try using latest master branch? tf shape inference is enhanced recently, hope it works.
> 
> if it is still not working, please share your model so we can take a look.

tf2onnx-1.5.3 onxx-1.4.1 tf-1.10.0 worked for me. I am from 2024, GOD.
