### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Zhitao** [onnx/tensorflow-onnx#533]
``` 
$ python3 -m tf2onnx.convert --saved-model saved_model
[saved_model.zip](https://github.com/onnx/tensorflow-onnx/files/3206630/saved_model.zip)


using tensorflow=1.8.0, onnx=1.5.0, opset=7, tfonnx=0.4.2/f9533d
2019-05-22 09:16:08.609480: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from b'saved_model/variables/variables'
INFO:tensorflow:Restoring parameters from b'saved_model/variables/variables'
INFO:tensorflow:Froze 15 variables.
INFO:tensorflow:Froze 15 variables.
Converted 15 variables to const ops.
2019-05-22 09:16:08.783867: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2019-05-22 09:16:08.788386: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
ERROR:tf2onnx:rewriter <function rewrite_custom_rnn_cell at 0x7fc75d167b70>: exception list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 143, in <module>
    main()
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 125, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2444, in process_tf_graph
    run_rewriters(g, rewriters, continue_on_error)
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2369, in run_rewriters
    raise ex
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2360, in run_rewriters
    ops = func(g, g.get_nodes())
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/rewriter/rnn.py", line 51, in rewrite_custom_rnn_cell
    return  CustomRnnRewriter(g).run()
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/rewriter/custom_rnn_rewriter.py", line 40, in run
    return self.run_internal()
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 198, in run_internal
    self._check_in_read_only_mode(context)
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 221, in _check_in_read_only_mode
    self._parse_loop_variables(context)
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 235, in _parse_loop_variables
    loop_var = self._get_loop_var_from_switch(s)
  File "/home/xxx/.local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 382, in _get_loop_var_from_switch
    ta_gather_node = [n for n in exit_consumers if is_tensor_array_gather_op(n)][0]
IndexError: list index out of range
```

**Comment by lucienwang1009** [comment]
Please see #513

**Comment by guschmue** [comment]
I assume this is no longer an issue.

**Comment by XUYUNYUN666** [comment]
> I assume this is no longer an issue.

![image](https://user-images.githubusercontent.com/38391161/71458521-0d71b480-27de-11ea-86f3-d0a7c0735842.png)
How to solve it? thank you
