### ISSUE TITLE
ValueError: get tensor value: stack_3_Concat__34 must be Const

### ISSUE THREAD

**Issue by boostf** [onnx/tensorflow-onnx#553]
When trying to convert the a deeplabv3+ (trained by quantize-aware-training) model, getting the error:
```
python3 -m tf2onnx.convert --input ./deeplab.pb \
        --inputs ImageTensor:0 \
        --outputs ArgMax:0 \
        --output ./deeplabv3p.onnx \
        --verbose  --fold_const

2019-05-30 06:34:17.348850: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-30 06:34:17.351966: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3699440000 Hz
2019-05-30 06:34:17.352555: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x45b1a20 executing computations on platform Host. Devices:
2019-05-30 06:34:17.352575: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:37: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
2019-05-30 06:34:17,635 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:37: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
2019-05-30 06:34:17,635 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
INFO:tensorflow:Froze 0 variables.
2019-05-30 06:34:17,677 - INFO - tensorflow: Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
2019-05-30 06:34:17,709 - INFO - tensorflow: Converted 0 variables to const ops.
2019-05-30 06:34:17.806684: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-05-30 06:34:17.882834: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-05-30 06:34:17.884985: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-05-30 06:34:17.890799: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-05-30 06:34:18,034 - INFO - tf2onnx.tfonnx: Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-05-30 06:34:18,034 - INFO - tf2onnx.tfonnx: Using opset <onnx, 7>
2019-05-30 06:34:18,555 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2019-05-30 06:34:18,593 - ERROR - tf2onnx.tfonnx: Failed to convert node Pad
OP=Pad
Name=Pad
Inputs:
	sub_2:0=Sub, [-1, -1, 3], 1
	stack_3_Concat__34:0=Concat, [3, 2], 6
Outpus:
	Pad:0=[-1, -1, -1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__34 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__34 must be Const
```

**Comment by zhijxu-MS** [comment]
could you try --opset 8 or --opset 9 or --opset 10?

**Comment by boostf** [comment]
error is also exists

1. if opset 8
```
Inputs:
	sub_2:0=Sub, [-1, -1, 3], 1
	stack_3_Concat__34:0=Concat, [3, 2], 6
Outpus:
	Pad:0=[-1, -1, -1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__34 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__34 must be Const
```
2 if opset 9
```
2019-05-30 08:50:37,070 - ERROR - tf2onnx.tfonnx: Failed to convert node Pad
OP=Pad
Name=Pad
Inputs:
	sub_2:0=Sub, [-1, -1, 3], 1
	stack_3_Concat__34:0=Concat, [3, 2], 6
Outpus:
	Pad:0=[-1, -1, -1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__34 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__34 must be Const
```

3. if opset 10
```
2019-05-30 08:51:26,879 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2019-05-30 08:51:26,918 - ERROR - tf2onnx.tfonnx: Failed to convert node Pad
OP=Pad
Name=Pad
Inputs:
	sub_2:0=Sub, [-1, -1, 3], 1
	stack_3_Concat__46:0=Concat, [3, 2], 6
Outpus:
	Pad:0=[-1, -1, -1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__46 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__46 must be Const
```

**Comment by zhijxu-MS** [comment]
please add --fold_const

**Comment by boostf** [comment]
i've already add --fold_const option

**Comment by zhijxu-MS** [comment]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Pad
onnx pad only supports static padding while tf pad supports dynamic padding

**Comment by zhijxu-MS** [comment]
if you are sure that the padding input is const, then please wait our tensorflow_constant_fold optimizer, or hack the code.

**Comment by samhodge** [comment]
I saw a similar issue

```
(tensorflow-1.12.0-src) kaos-new:tensorflow-onnx sam$ python -m tf2onnx.convert --input ~/kognat/models/before/deeplabv3_pascal_trainval.pb --inputs ImageTensor:0[1,513,513,3] --outputs SemanticPredictions:0 --output ~/kognat/models/before/deeplab_large.onnx --opset 10 --fold_const --inputs-as-nchw False --verbose
INFO:tensorflow:Froze 0 variables.
2019-07-02 20:53:40,218 - INFO - tensorflow: Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
2019-07-02 20:53:40,417 - INFO - tensorflow: Converted 0 variables to const ops.
2019-07-02 20:53:41.197944: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-07-02 20:53:42.746680: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-07-02 20:53:42.956730: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-07-02 20:53:43.393552: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-07-02 20:53:46,812 - INFO - tf2onnx.tfonnx: Using tensorflow=1.12.0, onnx=1.5.0, tf2onnx=1.5.0/64423c
2019-07-02 20:53:46,812 - INFO - tf2onnx.tfonnx: Using opset <onnx, 10>
2019-07-02 20:53:46,812 - INFO - tf2onnx.shape_inference: Apply shape override:
2019-07-02 20:53:46,812 - INFO - tf2onnx.shape_inference: 	Set ImageTensor:0 shape to [1, 513, 513, 3]
2019-07-02 20:53:52,205 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2019-07-02 20:53:52,327 - ERROR - tf2onnx.tfonnx: Failed to convert node Pad
OP=Pad
Name=Pad
Inputs:
	sub_2:0=Sub, [-1, -1, 3], 1
	stack_3_Concat__107:0=Concat, [3, 2], 6
Outpus:
	Pad:0=[-1, -1, -1], 1
Traceback (most recent call last):
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__107 must be Const
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/Users/sam/dev/tensorflow-onnx/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: stack_3_Concat__107 must be Const
```

**Comment by samhodge** [comment]
The values are not const in Tensorboard

The shapes appear as X,X,3

Etc so they are not const.

What can be done to make them const?

Is there any tricks that can be done using TFLite?

DeepLabv3 has been converted to TFLite and then to CoreML 

https://github.com/tf-coreml/tf-coreml/issues/147






Why not to onnx?

**Comment by samhodge** [comment]
<img width="313" alt="unknowndimensions" src="https://user-images.githubusercontent.com/86946/60561593-54fa1500-9d54-11e9-8a29-75e60584a7de.png">
Here is what I mean about the shapes

**Comment by guschmue** [comment]
Pad in opset 11 can handle dynamic inputs. Master also has better constant folding so I assume this is fixed.

**Comment by guschmue** [comment]
we assume this is fixed.
