### ISSUE TITLE
ResizeBilinear problems when convert google offical deeplab v3 models

### ISSUE THREAD

**Issue by luke-evans-liu** [onnx/tensorflow-onnx#556]
Terminal log:

**python3 -m tf2onnx.convert --input ./deeplabv3_mnv2_pascal_trainval_2018_01_29.pb --inputs ImageTensor:0 --outputs SemanticPredictions:0 --output** ./deeplabv3_mnv2_pascal_trainval_2018_01_29.onnx --fold_const
2019-05-31 16:32:57,244 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-05-31 16:32:57,244 - INFO - Using opset <onnx, 7>
2019-05-31 16:32:57,917 - ERROR - Failed to convert node ResizeBilinear
OP=Upsample
Name=ResizeBilinear
Inputs:
	ExpandDims:0=Unsqueeze, [1, -1, -1, 3], 1
	ToInt32:0=Cast, [2], 6
Outpus:
	ResizeBilinear:0=[1, -1, -1, 3], 1
Traceback (most recent call last):
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 478, in version_7
    target_shape = node.inputs[1].get_tensor_value()
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: ToInt32 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 478, in version_7
    target_shape = node.inputs[1].get_tensor_value()
  File "/home/luke/.local/lib/python3.6/site-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: ToInt32 must be Const

Somebody can help me?

**Comment by guschmue** [comment]
Hard to tell for sure without seeing the part of the graph, but:

In opset7 ResizeBilinear was mapped to [ONNX Upsample](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Upsample-7) and that specific upsample required the target size to be an attribute ... basically it must be a constant, else tf2onnx can't know what to pass in as attribute.

In opset 9 that was changed to some degree and in opset 10 it was changed some more.

If you pass ```--opset 10``` in the command line it might get over this.

**Comment by zhijxu-MS** [comment]
@luke-evans-liu  can "--opset 10" fix your problem?

**Comment by hamster3d** [comment]
I was able to successfully convert **deeplabv3** model with `--opset 11`

**Comment by shokohigol** [comment]
> I was able to successfully convert **deeplabv3** model with `--opset 11`

Cab you say tensorrt version?
