### ISSUE TITLE
Proposal: remove unused nodes before tensorflow_to_onnx(...) pass1 call; allow extending ignored_attrs

### ISSUE THREAD

**Issue by vadimkantorov** [onnx/tensorflow-onnx#578]
Dataset and iterator-related nodes often fail tf2onnx graph conversion, but they will not be used in the final exported graph anyway. So it would be nice if these errors could be skipped (at least allow to provide a custom ignored attr key list, currently it's hard-coded in `tflist_to_onnx`)

Currently the tensorflow graph is converted to onnx graph and only then graph rewrites and graph surgery happens.

In the example below `helper.make_node(node.type, input_names, output_names, name=node.name, **attr)` failed at the attr list of output shapess and attr list of data types.

Here `output_shapes`, `Toutput_types` and `output_types` are problematic.
```
pass1 convert failed for name: "import/Iterator"
op: "Iterator"
device: "/device:GPU:0"
attr {
  key: "container"
  value {
    s: ""
  }
}

attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: -1
        }
        dim {
          size: 64
        }
      }
      shape {
        dim {
          size: -1
        }
        dim {
          size: 1
        }
      }
      shape {
        dim {
          size: -1
        }
        dim {
          size: -1
        }
      }
      shape {
        dim {
          size: -1
        }
        dim {
          size: 1
        }
      }
    }
  }
}

attr {
  key: "output_types"
  value {
    list {
      type: DT_HALF
      type: DT_INT32
      type: DT_INT32
      type: DT_INT32
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}
, ex=You passed in an iterable attribute but I cannot figure out its applicable type.
Traceback (most recent call last):
  File "tfcheckpoint2pytorch.py", line 122, in <module>
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(graph, input_names=input_names, output_names=output_names, continue_on_error = True, opset = args.opset)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 708, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 123, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 110, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 251, in make_attribute
    "You passed in an iterable attribute but I cannot figure out "
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.

**Comment by vadimkantorov** [comment]
A few more breaking attrs:
```
# ValueError: Value "name: "tf_map_func_kKkn53ja0zs" is not valid attribute data type.

attr {
  key: "f"
  value {
    func {
      name: "tf_map_func_kKkn53ja0zs"
    }
  }
}
```

```
, ex=Value "name: "tf_predicate_OS9nrDc7EDA"  is not valid attribute data type.
attr {
  key: "predicate"
  value {
    func {
      name: "tf_predicate_OS9nrDc7EDA"
    }
  }
}
```

```
, ex=You passed in an iterable attribute but I cannot figure out its applicable type.

attr {
  key: "dtypes"
  value {
    list {
      type: DT_HALF
      type: DT_HALF
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
...
```

Also, not all data types are mapped, e.g. types_pb2.DT_VARIANT, types_pb2.DT_FLOAT_REF, types_pb2.DT_HALF_REF, types_pb2.DT_INT64_REF are missing in tf2onnx.utils.TF_TO_ONNX_DTYPE.

**Comment by vadimkantorov** [comment]
Also, some dtypes are not mapped (types_pb2.DT_VARIANT, types_pb2.DT_FLOAT_REF, types_pb2.DT_HALF_REF, types_pb2.DT_INT64_REF are missing in tf2onnx.utils.TF_TO_ONNX_DTYPE), which causes `dtypes[out.name] = utils.map_tf_dtype(out.dtype)` to fail.

It would be nice if `continue_on_error` applied to unmappable types and attrs.

**Comment by paulbauriegel** [comment]
@vadimkantorov Having the same problem right now when trying to convert a TF model from  [davidsandberg/facenet](https://github.com/davidsandberg/facenet)

**Comment by guschmue** [comment]
I think this was valid some time back but we have not seen this issue in a long time - guess we captured all the types needed.
