### ISSUE TITLE
ValueError: get tensor value: MultipleGridAnchorGenerator/Meshgrid_9/ExpandedShape_1/ExpandDims must be Const

### ISSUE THREAD

**Issue by Mespith** [onnx/tensorflow-onnx#605]
I get the error ValueError: get tensor value: MultipleGridAnchorGenerator/Meshgrid_9/ExpandedShape_1/ExpandDims must be Const when trying to convert my model from TF.

Python version:
3.6.5
[GCC 7.2.0] on linux
ONNX version:
1.5.0
TF2ONNX version:
1.5.1
Tensorflow version:
1.13.1

The model that I try to convert was trained using tensorflow version 1.10.0 using the pre-trained model mobilenet_v1.

```
python -m tf2onnx.convert\
    --input output_24_apr/frozen_inference_graph.pb\
    --inputs image_tensor:0[1,224,224,3]\
    --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0\
    --output model.onnx\
    --verbose
```
![image](https://user-images.githubusercontent.com/7500718/59611912-7c2dd100-911c-11e9-949e-04e0a4a17455.png)

**Comment by guschmue** [comment]
Add the option ```--opset 10 --fold_const``` to the command line. opset10 is needed because some ops needed for ssd came in with opset-10. fold_const is maybe not needed but helps us to optimize transposes.
We started a tutorial for the same here (its a draft, still come spelling errors but maybe it helps):
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb

**Comment by Mespith** [comment]
Thank you for the tips and the link to the tutorial. It certainly helped but I stumbled into a new but similar error.
```
python -m tf2onnx.convert\
    --graphdef output_24_apr/frozen_inference_graph.pb\
    --inputs image_tensor:0\
    --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0\
    --output model.onnx\
    --opset 10\
    --fold_const
```

2019-06-18 11:06:04,156 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-06-18 11:06:04,156 - INFO - Using opset <onnx, 10>
2019-06-18 11:06:06,363 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_3
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_3
Inputs:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice_3:0=Slice, None, 1
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_3_Concat__800:0=Concat, [1, 2], 6
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_3:0=[-1], 1
Traceback (most recent call last):
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_3_Concat__800 must be Const
2019-06-18 11:06:06,378 - ERROR - Failed to convert node generic_loop_Loop__56
OP=Loop
Name=generic_loop_Loop__56
Inputs:
        trip_count__54=Const, (), 7
        cond__55=Const, (), 9
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/iteration_counter:0=Const, [], 6
        Postprocessor/BatchMultiClassNonMaxSuppression/map/Const:0=Const, [], 6
Outpus:
        unused_loop_output___52=[-1], None
Outpus:
        unused_loop_output___53=[-1], None
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayStack/TensorArrayGatherV3:0=[-1, -1, -1], 1
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayStack_1/TensorArrayGatherV3:0=[-1, -1], 1
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayStack_2/TensorArrayGatherV3:0=[-1, -1], 1
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayStack_4/TensorArrayGatherV3:0=[-1], 6
Traceback (most recent call last):
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 569, in tensorflow_onnx_mapping
    m_ops, unm_ops = tensorflow_onnx_mapping(b_g, continue_on_error, ops_mapping)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_3_Concat__800 must be Const
Traceback (most recent call last):
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 569, in tensorflow_onnx_mapping
    m_ops, unm_ops = tensorflow_onnx_mapping(b_g, continue_on_error, ops_mapping)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 579, in tensorflow_onnx_mapping
    raise ex
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 574, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 392, in version_4
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jaimy/anaconda3/envs/tf2onnx/lib/python3.6/site-packages/tf2onnx/graph.py", line 239, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_3_Concat__800 must be Const

**Comment by Mespith** [comment]
I tried to follow the tutorial with the ssd_mobilenet_v1 model I used to train my model: ssd_mobilenet_v1_coco_11_06_2017. When I try to convert that model I get the error that tensorflow NonMaxSuppression is not supported. So that explains the error I'm getting I suppose. Could anybody tell me if this is going to be implemented some day?
```
!python -m tf2onnx.convert --graphdef $WORK/$MODEL/frozen_inference_graph.pb --output $WORK/$MODEL.frozen.onnx \
    --fold_const --opset 10 \
    --inputs image_tensor:0 \
    --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0  
```   

2019-06-18 12:01:22,816 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-06-18 12:01:22,816 - INFO - Using opset <onnx, 10>
2019-06-18 12:01:24,992 - WARNING - Cannot infer shape for Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/cond/zeros: Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/cond/zeros:0
Traceback (most recent call last):
  File "/home/jaimy/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jaimy/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jaimy/anaconda3/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in <module>
    main()
  File "/home/jaimy/anaconda3/lib/python3.6/site-packages/tf2onnx/convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/jaimy/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 786, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, ops_mapping)
  File "/home/jaimy/anaconda3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 552, in tensorflow_onnx_mapping
    raise ValueError("tensorflow op " + op + " is not supported")
ValueError: tensorflow op NonMaxSuppression is not supported

**Comment by guschmue** [comment]
ah, this must be generated by an older tensorflow version ... we currently have NonMaxSuppressionV2 and NonMaxSuppressionV3 implemented, but not the older NonMaxSuppression:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/tensor.py#L1156

Can you switch to the newer model here
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
?
Else we can see if we can add support for NonMaxSuppression, need to check how much work this is.

**Comment by guschmue** [comment]
I assume this is no longer an issue.
