### ISSUE TITLE
stack_Concat_2174_must be const

### ISSUE THREAD

**Issue by zarekxu** [onnx/tensorflow-onnx#659]
When I try to convert the ssd_mobilenet_v1_coco model from tensorflow format to the onnx format with this tutorial everything is fine. 

However, when we switch to the ssd_mobilenet_v2_coco model from tensorflow, I get the following errors: 

Command:
/raid/home/xzu143/tensorflow-onnx-master# python  -m tf2onnx.convert  --graphdef /raid/home/xzu143/frozen_350000/frozen_inference_graph.pb  --output /raid/home/xzu143/frozen_350000/model.onnx  --opset 10  --inputs image_tensor:0  --outputs detection_boxes:0,detection_classes:0,detection_scores:0,num_detections:0

Error Information: 
2019-07-22 17:57:37,725 - INFO - Using tensorflow=1.13.2, onnx=1.5.0, tf2onnx=1.6.0/82f805
2019-07-22 17:57:37,725 - INFO - Using opset <onnx, 10>
2019-07-22 17:57:47,911 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad
Inputs:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice:0=Slice, None, 1
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_Concat__2174:0=Concat, [2, 2], 6
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad:0=[-1, -1], 1
Traceback (most recent call last):
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/onnx_opset/nn.py", line 401, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_Concat__2174 must be Const
2019-07-22 17:57:47,934 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_3
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_3
Inputs:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice_3:0=Slice, None, 1
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_3_Concat__2203:0=Concat, [1, 2], 6
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_3:0=[-1], 1
Traceback (most recent call last):
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/onnx_opset/nn.py", line 401, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_3_Concat__2203 must be Const
2019-07-22 17:57:47,957 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1
Inputs:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice_1:0=Slice, None, 1
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_1_Concat__2232:0=Concat, [1, 2], 6
Outpus:
        Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1:0=[-1], 1
Traceback (most recent call last):
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/onnx_opset/nn.py", line 401, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_1_Concat__2232 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/tfonnx.py", line 575, in process_tf_graph
    raise exceptions[0]
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/onnx_opset/nn.py", line 401, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/raid/home/xzu143/tensorflow-onnx-master/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_Concat__2174 must be Const

I saw someone also meet a similar problem which may be caused by the dynamic padding. How I can check whether I have dynamic padding in my model since I directly downloaded from tensorflow model zoo. 

Thanks

**Comment by guschmue** [comment]
Hm, I think I tried the ssd-mobilenetv2 some time ago.
Try adding ```--fold_const``` to the command line.

**Comment by guschmue** [comment]
I assume this is no longer an issue.
