### ISSUE TITLE
tf2onnx.convert: invalid attribute data type error for op HashtableV2 - for feature columns Indicator column

### ISSUE THREAD

**Issue by VigneshRavichandran** [onnx/tensorflow-onnx#662]
2019-07-23 21:35:24,644 - ERROR - tf2onnx.tfonnx: pass1 convert failed for name: "dnn/input_from_feature_columns/input_layer/x1_indicator/x1_lookup/hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
, ex=Value "<dtype: 'string'>" is not valid attribute data type.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tf2onnx\convert.py", line 145, in <module>
    main()
  File "C:\Anaconda3\envs\py36\lib\site-packages\tf2onnx\convert.py", line 127, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tf2onnx\tfonnx.py", line 708, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tf2onnx\tfonnx.py", line 123, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tf2onnx\tfonnx.py", line 110, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "C:\Anaconda3\envs\py36\lib\site-packages\onnx\helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "C:\Anaconda3\envs\py36\lib\site-packages\google\protobuf\internal\containers.py", line 386, in extend
    for message in elem_seq:
  File "C:\Anaconda3\envs\py36\lib\site-packages\onnx\helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "C:\Anaconda3\envs\py36\lib\site-packages\onnx\helper.py", line 255, in make_attribute
    'Value "{}" is not valid attribute data type.'.format(value))
ValueError: Value "<dtype: 'string'>" is not valid attribute data type.

**Comment by guschmue** [comment]
This is a dup of the 2 issues here:
https://github.com/onnx/tensorflow-onnx/issues/469
https://github.com/onnx/tensorflow-onnx/issues/414
