### ISSUE TITLE
Unable to convert TF 1.14 models to onnx? google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by srkm009** [onnx/tensorflow-onnx#685]
TF-1.14 
Python: 3.6 
I have built the tf2onnx repositories from source successfully. 

(tf114-py36) @dl:~/Deeplearning$ python -m tf2onnx.convert  --input /home/Deeplearning/server_lab/TF_WEIGHTS/test_onnx_unet_tf114.hdf5_pb/saved_model.pb  --output test_onnx_unet_tf114.onnx --opset 9
2019-09-02 11:22:45,642 - WARNING - From /home/anaconda3/envs/tf114-py36/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/home/anaconda3/envs/tf114-py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/tf114-py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/tf114-py36/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/convert.py", line 161, in <module>
  File "/home/anaconda3/envs/tf114-py36/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/convert.py", line 116, in main
  File "/home/anaconda3/envs/tf114-py36/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/loader.py", line 62, in from_graphdef

**google.protobuf.message.DecodeError: Error parsing message**

**Comment by guschmue** [comment]
```--input``` implies a graphdef file and tensorflow tells us it is not in graphdef.
If you want to use a graphdef or checkpoint you also need to provide ```--inputs``` and ```--outputs``` arguments (I'm not sure how your command line can results in your error because https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L69 should have told that --inputs and --outputs arguments are missing).

If you want to use the saved-model format, use ```--saved-model``` with the directory instead of ```--input```.

**Comment by srkm009** [comment]
Yes, it was a miss on my part! i actually noticed it shortly after posting this issue :) 
Thanks @guschmue.
