### ISSUE TITLE
Failed to convert node feature_fusion/ResizeBilinear

### ISSUE THREAD

**Issue by fujingling** [onnx/tensorflow-onnx#694]
Hi，I have a problem when I convert tensorflow model to onnx, does onnx not support  feature_fusion opp?

- ERROR - Failed to convert node feature_fusion/ResizeBilinear
OP=Upsample
Name=feature_fusion/ResizeBilinear
Inputs:
	resnet_v1_50/block4/unit_3/bottleneck_v1/Relu:0=Relu, [-1, -1, -1, 2048], 1
	feature_fusion/ResizeBilinear/size_Concat__781:0=Concat, [2], 6
Outpus:
	feature_fusion/ResizeBilinear:0=[-1, -1, -1, 2048], 1

**Comment by guschmue** [comment]
For some reason the github email had more of the error message:
```
feature_fusion/ResizeBilinear:0=[-1, -1, -1, 2048], 1
Traceback (most recent call last):
File "/Users/fujingling/anaconda2/envs/card_dev/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
func(g, node, **kwargs)
File "/Users/fujingling/anaconda2/envs/card_dev/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 492, in version_7
target_shape = node.inputs[1].get_tensor_value()
File "/Users/fujingling/anaconda2/envs/card_dev/lib/python3.6/site-packages/tf2onnx/graph.py", line 256, in get_tensor_value
raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: feature_fusion/ResizeBilinear/size_Concat__781 must be Const
```

try to add ```--opset 10 --fold_const``` to the command line.
