### ISSUE TITLE
Failed to convert node import/conv2d_transpose

### ISSUE THREAD

**Issue by adaber** [onnx/tensorflow-onnx#699]
Hi everyone,

I have tried to save my frozen TensorFlow model to the ONNX format but I have gotten the following error:

**Failed to convert node import/conv2d_transpose
OP=ConvTranspose
Name=import/conv2d_transpose**

I assume this OP is not supported yet ? If so, when do you plan to implement it ? 

Thanks :)

**Comment by guschmue** [comment]
ConvTranspose is supported:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py#L212

Which tensorflow version is this ? Can you post the full error message ?

**Comment by adaber** [comment]
Thank you for the response, guschmu.

Operating system: Win 10
Python:                    3.6.8
Tensorflow:              1.13.1 (GPU)

The full error message:

```python
Failed to convert node import/conv2d_transpose
OP=ConvTranspose
Name=import/conv2d_transpose
Inputs:
	import/stack_Concat__359:0=Concat, [4], 6
	import/Variable_16:0=Const, [2, 2, 96, 96], 1
	import/MaxPool_3__343:0=Transpose, [-1, 30, 40, 96], 1
Outpus:
	import/conv2d_transpose:0=[-1, -1, -1, 96], 1
Traceback (most recent call last):
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\onnx_opset\nn.py", line 234, in version_1
    utils.make_sure(new_output_shape.count(-1) <= 0, "output h and w need to be known")
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: output h and w need to be known
Failed to convert node import/conv2d_transpose_1
OP=ConvTranspose
Name=import/conv2d_transpose_1
Inputs:
	import/stack_1_Concat__398:0=Concat, [4], 6
	import/Variable_24:0=Const, [2, 2, 64, 64], 1
	import/LeakyRelu_10:0=LeakyRelu, [-1, 60, 80, 64], 1
Outpus:
	import/conv2d_transpose_1:0=[-1, -1, -1, 64], 1
Traceback (most recent call last):
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\onnx_opset\nn.py", line 234, in version_1
    utils.make_sure(new_output_shape.count(-1) <= 0, "output h and w need to be known")
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: output h and w need to be known
Failed to convert node import/conv2d_transpose_2
OP=ConvTranspose
Name=import/conv2d_transpose_2
Inputs:
	import/stack_2_Concat__437:0=Concat, [4], 6
	import/Variable_32:0=Const, [2, 2, 32, 32], 1
	import/LeakyRelu_13:0=LeakyRelu, [-1, 120, 160, 32], 1
Outpus:
	import/conv2d_transpose_2:0=[-1, -1, -1, 32], 1
Traceback (most recent call last):
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\onnx_opset\nn.py", line 234, in version_1
    utils.make_sure(new_output_shape.count(-1) <= 0, "output h and w need to be known")
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: output h and w need to be known
Failed to convert node import/conv2d_transpose_3
OP=ConvTranspose
Name=import/conv2d_transpose_3
Inputs:
	import/stack_3_Concat__476:0=Concat, [4], 6
	import/Variable_40:0=Const, [2, 2, 16, 16], 1
	import/LeakyRelu_16:0=LeakyRelu, [-1, 240, 320, 16], 1
Outpus:
	import/conv2d_transpose_3:0=[-1, -1, -1, 16], 1
Traceback (most recent call last):
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\onnx_opset\nn.py", line 234, in version_1
    utils.make_sure(new_output_shape.count(-1) <= 0, "output h and w need to be known")
  File "C:\Users\im360\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: output h and w need to be known

---------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-0a70bb0076ad> in <module>
     84 
     85 # Convert to the ONNX format
---> 86 onnx_graph  = tf2onnx.tfonnx.process_tf_graph(graph, input_names=["import/Input:0"], output_names=["import/OutputSat:0"])
     87 model_proto = onnx_graph.make_model("Model")
     88 with open("./Model01.onnx", "wb") as f:

~\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\tfonnx.py in process_tf_graph(***failed resolving arguments***)
    573         logger.error("Unsupported ops: %s", unmapped_op)
    574     if exceptions and not continue_on_error:
--> 575         raise exceptions[0]
    576 
    577     # post-processing rewriters

~\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\tfonnx.py in tensorflow_onnx_mapping(g, ops_mapping)
    350 
    351         try:
--> 352             func(g, node, **kwargs)
    353             node.skip_conversion = True
    354         except Exception as ex:

~\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\onnx_opset\nn.py in version_1(cls, ctx, node, **kwargs)
    232             input_hw = [input_shape[2], input_shape[3]]
    233 
--> 234         utils.make_sure(new_output_shape.count(-1) <= 0, "output h and w need to be known")
    235         utils.make_sure(new_output_shape[0] >= input_hw[0] and new_output_shape[1] >= input_hw[1],
    236                         "output h and w cannot be smaller than input h and w.")

~\Anaconda3\envs\tensorflowGPU\lib\site-packages\tf2onnx\utils.py in make_sure(bool_val, error_msg, *args)
    288 def make_sure(bool_val, error_msg, *args):
    289     if not bool_val:
--> 290         raise ValueError("make_sure failure: " + error_msg % args)
    291 
    292 

ValueError: make_sure failure: output h and w need to be known
```python

**Comment by guschmue** [comment]
The problem is that we need to set the output shape for the ConvTranspose (or calculate some padding). For both we need to have H+W of the output shape but in your case they are unknown.
Need to think a little if we find them in a different way.

**Comment by adaber** [comment]
So, the problem is the fact that I calculate the conv2d_transpose output shape programmatically (based on the input layer's shape) ?

If that's the case then I might be able to still do the conversion if I provide the output shape layer's width and height as known numbers directly rather than compute them based on the input layer's width and height. I will definitely try to use this method (hope it works) while you figure out how to solve this limitation on your end.

**Comment by adaber** [comment]
I would just like to confirm that the converter did work when I used plain numbers to define my conv2d_transpose output shape (no computation based on the input layer's shape was used). Thank you again for your comment that helped me realize what the problem was.

I think it would still be great if you could figure out how to convert a frozen model where a conv2d_transpose output shape is calculated based on the input layer's shape.

Thanks!

**Comment by zhijxu-MS** [comment]
try to add this cli option "--extra_opset com.microsoft:1" **if onnxruntime is used**. it will use custom op "ConvTransposeWithDynamicPads" in onnxruntime.

**Comment by adaber** [comment]
Hi, zhijxu-MS

Thanks for your comment. I am not sure if I understood it completely :)

Where would you use this cli option in this example ? https://github.com/onnx/tensorflow-onnx/blob/master/examples/call_coverter_via_python.py

Thanks!

**Comment by zhijxu-MS** [comment]
the argument "extra_opset" of process_tf_graph is used to accept the option.

you could see how cli option is parsed into process_tf_graph's arg here[https://github.com/onnx/tensorflow-onnx/blob/cc9e078e80ffa53522fadc18ee940e2097d204e1/tf2onnx/convert.py#L85](url)

**Comment by adaber** [comment]
Thanks, zhijxu-MS. I'll definitely look into that.

**Comment by guschmue** [comment]
I assume this is resolved.
