### ISSUE TITLE
Cannot convert the user's tensorflow model

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#711]
**Describe the bug**
One user has a keras model which contains custom layer that we need convert using tf2onnx. But tf2onnx fails to convert it. I convert the keras model to tensorflow frozen graph and then attach this frozen graph here for you to debug.

**System information**
- Windows 10.0.17763
- Tensorflow Version: 1.14.0
- Python version: 3.6

**To Reproduce**
See attached model.
[att.zip](https://github.com/onnx/tensorflow-onnx/files/3740755/att.zip)

**Screenshots**
```python
Error
Traceback (most recent call last):
  File "E:\dev\keras-onnx\keras2onnx\ktf2onnx\tf2onnx\tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "E:\dev\keras-onnx\keras2onnx\ktf2onnx\tf2onnx\onnx_opset\tensor.py", line 1394, in version_10
    , "shape of axis {} is unknown".format(axis))
  File "E:\dev\keras-onnx\keras2onnx\ktf2onnx\tf2onnx\utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: shape of axis 0 is unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\python368\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\ProgramData\Anaconda3\envs\python368\lib\unittest\case.py", line 605, in run
    testMethod()
  File "E:\dev\keras-onnx\applications\nightly_build\test_keras_applications.py", line 383, in test_attention
    onnx_model = keras2onnx.convert_tensorflow(graph_def, **keras2onnx.build_io_names_tf2onnx(model))
  File "E:\dev\keras-onnx\keras2onnx\main.py", line 180, in convert_tensorflow
    input_names=input_names)
  File "E:\dev\keras-onnx\keras2onnx\ktf2onnx\tf2onnx\tfonnx.py", line 571, in process_tf_graph
    mapped_op, unmapped_op, exceptions = tensorflow_onnx_mapping(g, ops_mapping)
  File "E:\dev\keras-onnx\keras2onnx\ktf2onnx\tf2onnx\tfonnx.py", line 355, in tensorflow_onnx_mapping
    logger.error("Failed to convert node %s\n%s", node.name, node.summary, exc_info=1)
  File "E:\dev\keras-onnx\keras2onnx\ktf2onnx\tf2onnx\graph.py", line 172, in summary
    node = g.get_node_by_output(name)
AttributeError: 'NoneType' object has no attribute 'get_node_by_output'
```

Thank you very much!

**Comment by hanxiaotian** [comment]
I have encounterd the same problem

**Comment by sonu1-p** [comment]
I am also facing the same issue(in ReverseV2 - https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/tensor.py#L1690).  Any updates on this? 

Traceback (most recent call last):
  File "lib/python3.6/site-packages/tf2onnx/schemas.py", line 157, in infer_onnx_shape_dtype
    inferred_model = shape_inference.infer_shapes(model_proto)
  File "lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: [TypeInferenceError] Value of attribute to not specified
Traceback (most recent call last):
  File "lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 356, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "lib/python3.6/site-packages/tf2onnx/onnx_opset/tensor.py", line 1657, in version_10
    , "shape of axis {} is unknown".format(axis))
  File "lib/python3.6/site-packages/tf2onnx/utils.py", line 291, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: shape of axis 0 is unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "python3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 575, in process_tf_graph
    mapped_op, unmapped_op, exceptions = tensorflow_onnx_mapping(g, ops_mapping)
  File "lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 359, in tensorflow_onnx_mapping
    logger.error("Failed to convert node %s\n%s", node.name, node.summary, exc_info=1)
  File "/apollo/env/NeMoRt/lib/python3.6/site-packages/tf2onnx/graph.py", line 175, in summary
    node = g.get_node_by_output(name)
AttributeError: 'NoneType' object has no attribute 'get_node_by_output'

**Comment by jignparm** [comment]
@sonu1-p , the original model/issue is resolved in https://github.com/onnx/tensorflow-onnx/pull/819.

To fix this, you must use `--opset 11` (or later) on the command line.
