### ISSUE TITLE
tf2onnx.tfonnx: Failed to convert node roi_align_classifier/TopKV2

### ISSUE THREAD

**Issue by OuHangKresnik** [onnx/tensorflow-onnx#715]
**Describe the bug**
2019-10-22 19:16:12,473 - ERROR - tf2onnx.tfonnx: Failed to convert node roi_align_classifier/TopKV2
OP=TopK
Name=roi_align_classifier/TopKV2
Inputs:
	roi_align_classifier/add_2:0=Add, [600], 6
	roi_align_classifier/strided_slice_7:0=StridedSlice, [], 6
Outpus:
	roi_align_classifier/TopKV2:0=[600], 6
Outpus:
	roi_align_classifier/TopKV2:1=[600], 6

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Tensorflow Version: 1.14.1
- Python version: 2.7

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**
Successful Conversion

2019-10-22 19:16:12,473 - ERROR - tf2onnx.tfonnx: Failed to convert node roi_align_classifier/TopKV2
OP=TopK
Name=roi_align_classifier/TopKV2
Inputs:
	roi_align_classifier/add_2:0=Add, [600], 6
	roi_align_classifier/strided_slice_7:0=StridedSlice, [], 6
Outpus:
	roi_align_classifier/TopKV2:0=[600], 6
Outpus:
	roi_align_classifier/TopKV2:1=[600], 6
Traceback (most recent call last):
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/onnx_opset/tensor.py", line 878, in version_1
    k = node.inputs[1].get_tensor_value()
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: roi_align_classifier/strided_slice_7 must be Const
Traceback (most recent call last):
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/convert.py", line 162, in <module>
    main()
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 575, in process_tf_graph
    raise exceptions[0]
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/onnx_opset/tensor.py", line 878, in version_1
    k = node.inputs[1].get_tensor_value()
  File "/disk2/ouhang.oh/miniconda/envs/taso/lib/python3.6/site-packages/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: roi_align_classifier/strided_slice_7 must be Const

**Comment by OuHangKresnik** [comment]
I think it's because this stridedslice is not supported in onnx because of the limit:

                raise ValueError("StridedSlice: only strides=1 is supported")

In tensor.py

**Comment by OuHangKresnik** [comment]
Any plan to support StridedSlice with strides != 1 ?

**Comment by guschmue** [comment]
```--opset 10``` should take care of this.

**Comment by OuHangKresnik** [comment]
> `--opset 10` in the command line should take care of this.

Thank you, it works
