### ISSUE TITLE
iterable attribute application type error

### ISSUE THREAD

**Issue by dmoham1476** [onnx/tensorflow-onnx#73]
I ran tf2onnx on a resnet .pb file. The output is Reshape operator of type ndarray. I get the following error - 

Traceback (most recent call last):
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 67, in <module>
    main()
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 56, in main
    target=args.target)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 987, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 940, in tensorflow_onnx_mapping
    onnx_node = func(g, node, node.name, args)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 239, in reshape_op
    node.set_attr("shape", shape)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/graph.py", line 104, in set_attr
    self.attr[name] = helper.make_attribute(name, value)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/site-packages/onnx/helper.py", line 202, in make_attribute
    "You passed in an iterable attribute but I cannot figure out "
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.

 I printed out the shapes in the helper function and I see the ndarray is not covered in the ifcases. Kindly help resolve this issue. 

shape
<class 'numpy.int32'>
<class 'numpy.int32'>
shape
<class 'numpy.ndarray'>

**Comment by dmoham1476** [comment]
This is on a frozen resnet50 graph (.pb)

**Comment by nbcsm** [comment]
close this issue for now.
please re-open it if needed.

**Comment by baoachun** [comment]
Unfortunately, I also encountered this problem, onnx does not support the DT_STRING type?
