### ISSUE TITLE
AssertionError: output is not in graph

### ISSUE THREAD

**Issue by rkpandya** [onnx/tensorflow-onnx#739]
**Describe the bug**

  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: output is not in graph

**Urgency**
High

**System information**
- OS Platform and Distribution: Red Hat Enterprise Linux Server 7.6 (Maipo)
- Tensorflow Version: 1.12
- Python version: 3.5

**To Reproduce**
python -m tf2onnx.convert --input $frozen --inputs $input_names --outputs $output_names --output $output $@

Using this command to generate the onnx model. the $frozen variable is the path to the frozen .pb tf model. 

Tried the same using --checkpoint also, and pointing to path of .meta file and still receiving the same error.

**Expected behavior**
Expect model.onnx to be saved to output location

**Screenshots**
Entire Output of command:

$ python -m tf2onnx.convert --input $frozen --inputs $input_names --outputs $output_names --output $output $@

/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tf2onnx/convert.py", line 116, in main
    graph_def, inputs, outputs = loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tf2onnx/loader.py", line 64, in from_graphdef
    frozen_graph = freeze_session(sess, output_names=output_names)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tf2onnx/loader.py", line 37, in freeze_session
    output_names, freeze_var_names)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 232, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 174, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/cluster/home/pandyar1/Python3.5/Python-3.5.6/envTensorflow3.5/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: output is not in graph

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jignparm** [comment]
Can you do the following

* Try adding `--fold_const` to the command line (this sometimes prevents certain types of errors)
* Share a link to the model you are looking to convert
* Expand the variables in the command line pasted (e.g. $input_names), so it's clear what argument values are being used.

**Comment by rkpandya** [comment]
Thank you! Here's the variable inputs:

frozen="/path/to/model.pb"
input_names=X:0 
output_names=output:0
output="/path/to/save/model.onnx"

command: python -m tf2onnx.convert --input $frozen --inputs $input_names --outputs $output_names --output $output --fold_const $@

I added the flag --fold_const, still see the same error.

The model I am trying to convert is based on the Gppgle's DeepLabV3+ for semantic segmentation, developed by a colleague using transfer learning. (https://github.com/tensorflow/models/tree/master/research/deeplab)

**Comment by guschmue** [comment]
Yes. I think this might be fixable with opset-11. We'll look at it.

```
python tf2onnx/convert.py  --input ~/download/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb  --inputs ImageTensor:0 --outputs SemanticPredictions:0 --opset 11 --fold_const 
```
gives me:
```
OP=Pad
Name=Pad
Inputs:
        sub_2:0=Sub, [-1, -1, 3], 1
        stack_3_Concat__91:0=Concat, [3, 2], 6
Outpus:
        Pad:0=[-1, -1, -1], 1
Traceback (most recent call last):
  File "/home/gs/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/gs/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 451, in version_11
    pads = node.inputs[1].get_tensor_value()
```

**Comment by jignparm** [comment]
@rkpandya , @guschmue,  for the `Pad` error message above, looks like the `Pad` op was not handling dynamic padding values correctly (for opset 11). The fix  is in PR #748 .

Using the pretrained  deeplab model from [here](https://github.com/gustavz/realtime_segmenation/blob/master/models/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb), the following command works successfully (n.b. there's a shape inference warning for now, which you can ignore).

```
python -m tf2onnx.convert --input frozen_inference_graph.pb --inputs ImageTensor:0 --outputs SemanticPredictions:0 --opset 11 --fold_const --output deeplab.onnx
```

The accuracy comparison with original TF model also passes.

```
2019-11-23 02:28:41,545 - INFO - Optimizing ONNX model
2019-11-23 02:28:47,244 - INFO - After optimization: Add -55 (70->15), Cast -3 (19->16), Const -228 (368->140), Gather +1 (0->1), Identity -88 (88->0), Reshape -17 (18->1), Squeeze -4 (10->6), Transpose -123 (178->55), Unsqueeze -8 (14->6)
2019-11-23 02:28:47,277 - INFO - To_ONNX, OK
2019-11-23 02:28:47,288 - INFO - Created d:\tmp\pre-trained\deeplabv3.onnx
2019-11-23 02:28:47,867 - INFO - Model saved to C:\Users\localadmin\AppData\Local\Temp\2\tmplka6k8he\run_pretrained\deeplabv3.onnx
2019-11-23 02:30:07,759 - INFO - Run_ONNX OK
2019-11-23 02:30:07,760 - INFO - Results: OK
2019-11-23 02:30:07,767 - INFO - ===================================
2019-11-23 02:30:07,767 - INFO - RESULT: 0 failed of 1, backend=onnxruntime
```

However, @rkpandya can you paste the location of the deeplab model you are using (not the training source code)? There are multiple deeplab models, and the one I used (similar to @guschmue 's model) may not be identical to the model you are using.

**Comment by rkpandya** [comment]
Thanks for looking into this! I tried the above command, but the output stops after all the warnings, hangs up right here.

The model I am trying to convert is http://download.tensorflow.org/models/deeplab_cityscapes_xception71_trainvalfine_2018_09_08.tar.gz

![Capture](https://user-images.githubusercontent.com/131262/69570668-3c51fc00-0f8e-11ea-85ef-304cf5654e4f.PNG)

**Comment by jignparm** [comment]
@rkpandya, sorry for delayed reply. 

It looks like TF has error in loading the frozen model that you mentioned (goes into an infinite loop), which is why the conversion is hanging.

 I'm using TF 1.14.   Are you able to load the model at all using TF (outside of the TF2ONNX convertor)?

### Command
```bash
python -m tf2onnx.convert --input ./frozen_inference_graph.pb --inputs ImageTensor:0[1,100,100, 3] --outputs SemanticPredictions:0 --opset 11 --fold_const --output frozen_inference_graph.onnx -vvvv
```

### Log
```
INFO:tensorflow:Froze 0 variables.
2019-12-02 23:26:05,578 - INFO - tensorflow: Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
2019-12-02 23:26:06,123 - INFO - tensorflow: Converted 0 variables to const ops.
2019-12-02 23:26:06,386 - INFO - tf2onnx: inputs: ['ImageTensor:0']
2019-12-02 23:26:06,386 - INFO - tf2onnx: outputs: ['SemanticPredictions:0']
2019-12-02 23:26:07.717581: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-12-02 23:26:10.614722: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-12-02 23:26:10.956924: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-12-02 23:26:11.734855: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-12-02 23:26:12.338655: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv1_pointwise/BatchNorm/beta/read/_101__cf__101 to be preserved.
2019-12-02 23:26:12.339111: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv1_pointwise/BatchNorm/gamma/read/_102__cf__102 to be preserved.
2019-12-02 23:26:12.339380: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv1_pointwise/BatchNorm/moving_mean/read/_103__cf__103 to be preserved.
2019-12-02 23:26:12.339941: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv1_pointwise/BatchNorm/moving_variance/read/_104__cf__104 to be preserved.
2019-12-02 23:26:12.340274: W tensorflow/tools/graph_transforms/transform_utils.cc:448] Generator function didn't preserve needed nodes, copying old replacements back in instead.
2019-12-02 23:26:12.341434: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv2_pointwise/BatchNorm/beta/read/_111__cf__111 to be preserved.
2019-12-02 23:26:12.341694: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv2_pointwise/BatchNorm/gamma/read/_112__cf__112 to be preserved.
2019-12-02 23:26:12.342041: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv2_pointwise/BatchNorm/moving_mean/read/_113__cf__113 to be preserved.
2019-12-02 23:26:12.342413: W tensorflow/tools/graph_transforms/transform_utils.cc:441] Expected xception_71/entry_flow/block1/unit_1/xception_module/separable_conv2_pointwise/BatchNorm/moving_variance/read/_114__cf__114 to be preserved.
2019-12-02 23:26:12.342767: W tensorflow/tools/graph_transforms/transform_utils.cc:448] Generator function didn't preserve needed nodes, copying old replacements back in instead.
```

**Comment by guschmue** [comment]
We know about this one and will use a different mechanism with once we support tf-2.0. 
I'm close with the tf-2.0 support, give me a few days before I'll send a PR.

**Comment by rkpandya** [comment]
I am using TF 1.12, and able to load the model and use it.

**Comment by rkpandya** [comment]
Hello, I tried the same conversion now with the latest tensorflow-gpu 2.0 and the latest tf2onnx version 1.5.5. Still see the conversion going into an infinite loop. 

Here's the command I am using: 
output="/path/to/model.onnx"
output_names=output:0                      
input_names=X:0
frozen="/path/to/DeepLabV3_V3.pb"

python -m tf2onnx.convert --input $frozen --inputs ImageTensor:0 --outputs SemanticPredictions:0 --opset 11 --fold_const --output $output

**Comment by jignparm** [comment]
@rkpandya -- I was able to convert successfully using both TF1.14 as well as TF2.1. See the log below. However, I was using the master branch of TF2ONNX -- could you try cloning this repo and using the master branch?

###log
```
$./convert.bat
...
$ cat convert.bat
python -m tf2onnx.convert --input frozen_inference_graph.pb --inputs ImageTensor:0 --outputs SemanticPredictions:0 --opset 11 --fold_const --output deeplab.onnx

2020-03-21 03:44:44,397 - INFO - Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.6.0/82f805
2020-03-21 03:44:44,397 - INFO - Using opset <onnx, 11>
2020-03-21 03:44:45,598 - INFO - Optimizing ONNX model
2020-03-21 03:44:51,076 - INFO - After optimization: Add -55 (70->15), Cast -5 (19->14), Const -233 (370->137), Identity -88 (88->0), Reshape -17 (18->1), Squeeze -4 (10->6), Transpose -123 (178->55), Unsqueeze -8 (14->6)
2020-03-21 03:44:51,116 - INFO -
2020-03-21 03:44:51,116 - INFO - Successfully converted TensorFlow model frozen_inference_graph.pb to ONNX
2020-03-21 03:44:51,127 - INFO - ONNX model is saved at deeplab.onnx
```

**Comment by rkpandya** [comment]
So basically install from source, run the install command and then make the call right? Sorry for my ignorance, I am new to this

**Comment by jignparm** [comment]
The steps below should work.

* uninstall tf2onnx package from your python distribution.
* "git clone <repository>" to  get source locally
* set environment variable PYTHONPATH=<root of local clone>
* Run the convertor as before

**Comment by jinfagang** [comment]
convert.py: error: unrecognized arguments: --fold_const
