### ISSUE TITLE
tensorflow VariableV2 not supported

### ISSUE THREAD

**Issue by dmoham1476** [onnx/tensorflow-onnx#74]
Hi I ran tf2onnx on a vgg_19.pb file and got this error
Traceback (most recent call last):
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 67, in <module>
    main()
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 56, in main
    target=args.target)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 987, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 929, in tensorflow_onnx_mapping
    raise ValueError("tensorflow op " + op + " is not supported")
ValueError: tensorflow op VariableV2 is not supported

**Comment by guschmue** [comment]
we need a frozen graph as input and the all variables should have been converted to a constant.
Sometimes not all variables can be converted when freezing the graph. If you can send me a pointer to vgg_19.pb I can take a look at the model.
onnx itself has no notion of variables ... that is why we need the frozen graph.
