### ISSUE TITLE
KeyError: tf.float32_ref

### ISSUE THREAD

**Issue by I-CANT-CODE** [onnx/tensorflow-onnx#740]
Hi I am getting this issue when running the command:

python3 -m tf2onnx.convert  --input my_model.pb --inputs X:0 --outputs summaries/up_convolution_out/activations:0 --output model.onnx --verbose

ISSUE:

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2019-11-15 12:17:48,167 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:58: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

2019-11-15 12:17:48,167 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:58: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:59: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-11-15 12:17:48,167 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:59: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-11-15 12:17:48.168165: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-11-15 12:17:48.168185: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-11-15 12:17:48.168212: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (henry): /proc/driver/nvidia/version does not exist
2019-11-15 12:17:48.168424: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-15 12:17:48.193263: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3506260000 Hz
2019-11-15 12:17:48.194114: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5dd2b10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-11-15 12:17:48.194157: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:60: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

2019-11-15 12:17:48,198 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:60: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:61: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2019-11-15 12:17:48,198 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:61: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:29: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

2019-11-15 12:18:00,114 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:29: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:37: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
2019-11-15 12:18:05,845 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tf2onnx/loader.py:37: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2019-11-15 12:18:05,845 - WARNING - tensorflow: From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 0 variables.
2019-11-15 12:18:06,795 - INFO - tensorflow: Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
2019-11-15 12:18:06,801 - INFO - tensorflow: Converted 0 variables to const ops.
2019-11-15 12:18:07,370 - WARNING - tf2onnx.loader: inputs [X:0] is not in frozen graph, delete them
2019-11-15 12:18:07,755 - INFO - tf2onnx: inputs: []
2019-11-15 12:18:07,756 - INFO - tf2onnx: outputs: ['summaries/up_convolution_out/activations:0']
2019-11-15 12:18:07.810142: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-11-15 12:18:07.817513: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-11-15 12:18:07,883 - INFO - tf2onnx.tfonnx: Using tensorflow=1.15.0, onnx=1.6.0, tf2onnx=1.5.3/7b598d
2019-11-15 12:18:07,883 - INFO - tf2onnx.tfonnx: Using opset <onnx, 7>
2019-11-15 12:18:07,884 - WARNING - tf2onnx.shape_inference: Shape of placeholder dropout_probability is unknown, treated it as a scalar
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 493, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 122, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/tfonnx.py", line 66, in tflist_to_onnx
    dtypes[out.name] = utils.map_tf_dtype(out.dtype)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx/utils.py", line 191, in map_tf_dtype
    dtype = TF_TO_ONNX_DTYPE[dtype]
KeyError: tf.float32_ref

**Comment by guschmue** [comment]
One of the first things tf2onnx does is freezing the graph, aka all variables become constant. This is needed for onnx since it is a inference graph and there are no variables.
The type tf.float32_ref is a variable so there must be something in the model that can't be make constant. An example would be if you have the keep_prob of a dropout come from a placeholder.

**Comment by I-CANT-CODE** [comment]
I see, and is there a way to remove these variables and keep the graph the
same?

**Comment by guschmue** [comment]
we see this issue from time to time but its relatively rare. In most cases where is a way around it but it requires a close look at the model.

**Comment by I-CANT-CODE** [comment]
If it helps, This is the model I am using:

https://github.com/jakeret/tf_unet

**Comment by I-CANT-CODE** [comment]
is there any way to potentially change the code for instantiation of the model to not include any variables, and then load in the pb with just the nodes that exist in that version of the graph, and then resave it?

**Comment by guschmue** [comment]
In https://github.com/jakeret/tf_unet/blob/master/tf_unet/unet.py#L196 try this:
```
-        self.keep_prob = tf.placeholder(tf.float32, name="dropout_probability")  # dropout (keep probability)
+        self.keep_prob = tf.placeholder_with_default(1.0, shape=(), name="dropout_probability")  # dropout (keep probability
```
and run:
```
 python -m tf2onnx.convert  --checkpoint ~/download/tf_unet/demo/unet_trained/model.ckpt.meta  --inputs x:0,y:0 --outputs results/pixel_wise_softmax/truediv:0 --opset 11 --fold_const  --output /tmp/t.onnx 
```
This will fail because of unknown dims that we need to calculate the shapes for ConvTranspose
```
  File "/home/gs/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 259, in version_11
    cls.version_1(ctx, node, **kwargs)
  File "/home/gs/tensorflow-onnx/tf2onnx/onnx_opset/nn.py", line 239, in version_1
    utils.make_sure(new_output_shape.count(-1) <= 0, "output h and w need to be known")
  File "/home/gs/tensorflow-onnx/tf2onnx/utils.py", line 291, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: output h and w need to be known
```
You can work around this by a fix HW on input x:
```
python -m tf2onnx.convert  --checkpoint ~/download/tf_unet/demo/unet_trained/model.ckpt.meta  --inputs x:0[1,572,572,1],y:0 --outputs results/pixel_wise_softmax/truediv:0 --opset 11 --fold_const  --output t.onnx
```

Not sure if we can come up with a fix for the unknown dims issue.

**Comment by I-CANT-CODE** [comment]
still having an issue:

tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

so what I did was:

1. i trained the network using the original code in tf_unet
2. saved the model
3. altered the code as such:

-        self.keep_prob = tf.placeholder(tf.float32, name="dropout_probability")  # dropout (keep probability)
+        self.keep_prob = tf.placeholder_with_default(1.0, shape=(), name="dropout_probability")  # dropout (keep probability

then run the command you instructed using the fixed input size.

**Comment by guschmue** [comment]
yeah, you need to retrain the model with this.
I'm sure you can also rewrite the graph and remove this placeholder but that is a little more work.

**Comment by I-CANT-CODE** [comment]
AH! ok so I got it to work!!! thank you!
