### ISSUE TITLE
error in tf2onnx on inception graph

### ISSUE THREAD

**Issue by dmoham1476** [onnx/tensorflow-onnx#75]
Hi

I ran tf2onnx on inception graph and got this error
Traceback (most recent call last):
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 67, in <module>
    main()
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 56, in main
    target=args.target)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 987, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 940, in tensorflow_onnx_mapping
    onnx_node = func(g, node, node.name, args)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 580, in concat_op
    axis = axis_node.get_tensor_value()
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/graph.py", line 120, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: mixed3a_pool_reduce must be Const

**Comment by guschmue** [comment]
In tensorflow concat looks like:
    # T output = ConcatV2(T values, Tidx axis, @int N, @type Tidx)
in onnx it is:
    # T concat_result = Concat(T inputs, @INT axis)

Basically the axis in onnx is a attribute where in tensorflow it is dynamic. The converter complains because if it is not a constant we can not create the axis attribute.
No easy way out of this.

Was this a frozen graph ?

**Comment by dmoham1476** [comment]
I understand. I got the .pb file from the tensorflow models page - https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models.

I checking to make sure if these were frozen graphs else if I can generate frozen graphs.

**Comment by guschmue** [comment]
I think those are just checkpoints for vga ... there is some export.py script in the slim directory to create the frozen graph.

**Comment by dmoham1476** [comment]
I generated a frozen inception_v3 graph from the ckpt file that I downloaded on the models download page. I reran tf2onnx and I now see the same issue that I filed on resnet - https://github.com/onnx/tensorflow-onnx/issues/73

shape
<class 'numpy.int32'>
<class 'numpy.int32'>
shape
<class 'numpy.ndarray'>
Traceback (most recent call last):
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 67, in <module>
    main()
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 56, in main
    target=args.target)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 988, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 941, in tensorflow_onnx_mapping
    onnx_node = func(g, node, node.name, args)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/tfonnx.py", line 240, in reshape_op
    node.set_attr("shape", shape)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/graph.py", line 104, in set_attr
    self.attr[name] = helper.make_attribute(name, value)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/site-packages/onnx/helper.py", line 202, in make_attribute
    "You passed in an iterable attribute but I cannot figure out "
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.
(onnx_env) dmohan@sj1mach1:/nfs/cadv11/dmohan/projects/tensorflow-onnx$ Attributes
Attributes: command not found
(onnx_env) dmohan@sj1mach1:/nfs/cadv11/dmohan/projects/tensorflow-onnx$
(onnx_env) dmohan@sj1mach1:/nfs/cadv11/dmohan/projects/tensorflow-onnx$ python -m tf2onnx.convert    --input /nfs/cadv11/dmohan/projects/frozen_tf_graphs/frozen_inception_v3.pb --inputs=input --outputs=InceptionV3/Predictions/Reshape_1  --output /nfs/cadv11/dmohan/projects/tensorflow-onnx/frozen_inception_v3.onnx --verbose

**Comment by guschmue** [comment]
Hm, slim inception_v3 is part of the tests we run frequently and passes:
https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml#L61
Just tried this manual and its fine for me:
python -m tf2onnx.convert --input \tmp\pre-trained\inception_v3_2016_08_28_frozen.pb\inception_v3_2016_08_28_frozen.pb --inputs=input --outputs=InceptionV3/Predictions/Reshape_1 --output t.pb

**Comment by dmoham1476** [comment]
I ran the tests and generated the frozen model using run_pretrained_models. The same command for me generates this error - Traceback (most recent call last):
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 116, in <module>
    main()
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/convert.py", line 108, in main
    optimize=not args.continue_on_error)
  File "/nfs/cadv11/dmohan/projects/tensorflow-onnx/tf2onnx/graph.py", line 398, in make_model
    v = helper.make_tensor_value_info(name, dtype, self.get_shape(name))
  File "/nfs/cadv11/dmohan/projects/Downloads/yes/envs/onnx_env/lib/python3.6/site-packages/onnx/helper.py", line 253, in make_tensor_value_info
    for d in shape:
TypeError: 'NoneType' object is not iterable

I see that when the run kicks off, it is using onnx 1.1.2. However the onnx install page uses 1.2.1 and I installed onnx 1.2.1. When I run tests, it is using 1.2.2. 
Could this be a versioning issue? 

Also, when we run testing, how can we dump the .onnx files? I enabled debug mode, I see that only has a print graph option, but no dump onnx graph.

**Comment by snehabhapkar10** [comment]
@dmoham1476 How the error got solved ? Was it a onnx version problem ? I am using onnx 1.6 still it is giving the same issue.

**Comment by guschmue** [comment]
You'll need ```--opset 10``` for sure.

**Comment by Exlsunshine** [comment]
> You'll need `--opset 10` for sure.

I'm facing the same error, and I have tried opset=10, but still got the same error...
onnx 1.6.0
onnxruntime 1.0.0
tf2onnx 1.5.3

**Comment by guschmue** [comment]
which model? Inception-v3 should be working since it is part of our tests:
https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml#L114

**Comment by Exlsunshine** [comment]
> which model? Inception-v3 should be working since it is part of our tests:
> https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml#L114

I am not using the inception, but my own model, it complains `ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.` Have no idea how to fix this.

**Comment by woaixiaojiaa** [comment]
@guschmue hello, in recently, i have also met ValueError: You passed in an iterable attribute but I cannot figure out its applicable type, has any tips? ,thx

**Comment by guschmue** [comment]
Can you add the full error message with stack trace?

**Comment by GitOP** [comment]
Here is the full error: "ValueError: You passed in an iterable attribute but I cannot figure out its applicable type." stack trace attached.
[stack-trace.txt](https://github.com/onnx/tensorflow-onnx/files/5656010/stack-trace.txt)

**Comment by guschmue** [comment]
Hm, your stack trace says:
```
----> 8 onnx_model = convert_sparkml(pipelineModel, 'Pyspark model', initial_types, spark_session = spark )
```
Does not look like tf2onnx issue.
