### ISSUE TITLE
tensorrt5.1.5 sample load yolov3.onnx encounters a problem

### ISSUE THREAD

**Issue by xiaoga501** [onnx/tensorflow-onnx#752]
I have tried to use the tf2onnx convert yolov3.pb -> yolov3.onnx. (https://github.com/onnx/tensorflow-onnx)The yolov3 tensorflow model comes from https://github.com/YunYang1994/tensorflow-yolov3/blob/master/freeze_graph.py#L23.
following jignparm's method2 and use this command: `python tests/run_pretrained_models.py --backend onnxruntime --config mypretrained.yaml --onnx-file /home/xiaoga/pre-trained --fold_const -v`
It seems to generate yolov3.onnx:

```
2019-12-12 10:14:15,616 - INFO - run_pretrained: To_ONNX, OK
2019-12-12 10:14:15,914 - INFO - run_pretrained: Created /home/xiaoga/pre-trained/yolov3.onnx
2019-12-12 10:14:16,184 - INFO - run_pretrained: Model saved to /tmp/tmphwporkg5/run_pretrained/yolov3.onnx
2019-12-12 10:14:16,674 - INFO - run_pretrained: Run_ONNX OK
2019-12-12 10:14:16,687 - ERROR - run_pretrained: Results
Traceback (most recent call last):
  File "tests/run_pretrained_models.py", line 283, in run_test
    np.testing.assert_allclose(tf_res, onnx_res, rtol=self.rtol, atol=self.atol)
  File "/home/xiaoga/anaconda3/envs/mypy35/lib/python3.5/site-packages/numpy/testing/_private/utils.py", line 1515, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/xiaoga/anaconda3/envs/mypy35/lib/python3.5/site-packages/numpy/testing/_private/utils.py", line 841, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.01, atol=1e-06

Mismatch: 0.00704%
Max absolute difference: 1.0280139e+36
Max relative difference: 1.
 x: array([[[[[8.000000e+00, 8.000000e+00, 1.566263e-36, ...,
           1.000000e+00, 9.869913e-01, 1.000000e+00],
          [8.000000e+00, 8.000000e+00, 0.000000e+00, ...,...
 y: array([[[[[8.000000e+00, 8.000000e+00, 1.566263e-36, ...,
           1.000000e+00, 9.869853e-01, 1.000000e+00],
          [8.000000e+00, 8.000000e+00, 0.000000e+00, ...,...
2019-12-12 10:14:16,714 - INFO - run_pretrained: ===================================
2019-12-12 10:14:16,714 - INFO - run_pretrained: RESULT: 1 failed of 1, backend=onnxruntime
```

But when I modified the tensorrt mnist_onnx_sample to parse the yolov3.onnx, encounter the problem below:

```
(mypy35) xiaoga@xiaoga-Lenovo:~/到 TensorRT-5.1.5.0 的链接/bin$ ./sample_onnx_mnist
&&&& RUNNING TensorRT.sample_onnx_mnist # ./sample_onnx_mnist
----------------------------------------------------------------
Input filename: ../../../data/mnist/yolov3.onnx
ONNX IR version: 0.0.4
Opset version: 7
Producer name: tf2onnx
Producer version: 1.5.3
Domain:
Model version: 0
Doc string:
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
While parsing node number 151 [Slice]:
ERROR: builtin_op_importers.cpp:2041 In function importSlice:
[8] Assertion failed: std::find(axes.begin(), axes.end(), BATCH_DIM) == axes.end()
[E] Failure while parsing ONNX file
&&&& FAILED TensorRT.sample_onnx_mnist # ./sample_onnx_mnist
sample_onnx_mnist: sampleOnnxMNIST.cpp:212: int main(int, char**): Assertion `trtModelStream != nullptr' failed.
已放弃 (核心已转储)

```
Please give some advice and thanns a lot!

**Comment by jignparm** [comment]
@xiaoga501 , the TensorRT MNIST example seems to be using quite an old parser. Is there a way to update the TensorRT parser so that it supports  opset 7 (and hence newer ONNX IR version as well)? 

The yolov3.onnx model is generated at opset=7, and is able to run/score using  OnnxRuntime, so the model  is generated correctly. You can control the opset version that the model is generated with (e.g. using  `--opset 11` with stamp model at opset 11),  but going older than opset 7 is not recommended. 

Updating TensorRT to support opset=7 should solve this particular issue.

**Comment by guschmue** [comment]
Basically the onnx version used by tensorrt seems older and the propper fix is there. 
When we write the onnx file, the onnx library will set the IR version that onnx is build with. 
For onnx-1.4 and onnx-1.5 that is 4.
So maybe as a hack you could try to install onnx-1.3 and re-create the onnx file. We are not testing the converter with that version but with a little luck this will work.

**Comment by ou525** [comment]
@xiaoga501 Does the conversion succeed?

**Comment by guschmue** [comment]
I assume this is resolved.
