### ISSUE TITLE
"perm can't be dynamic in ONNX" even with --fold_const

### ISSUE THREAD

**Issue by chriselion** [onnx/tensorflow-onnx#760]
**Describe the bug**
Similar to the issues reported in https://github.com/onnx/tensorflow-onnx/issues/693 and https://github.com/onnx/tensorflow-onnx/issues/650, I'm getting `ValueError: make_sure failure: perm can't be dynamic in ONNX` when trying to convert a frozen graph that uses `tf.nn.dynamic_rnn()`. Unlike those, the error doesn't go away when using `--fold_const` on the commandline.

**Urgency**
Medium. I'm trying to convert https://github.com/Unity-Technologies/ml-agents to export to ONNX, since we want that to be the standard format we use for inference instead of our current "bespoke" format. This bug blocks adoption of ONNX, but there's no specific deadline for that.

**System information**
- macOS Mojave 10.14.6
- Tensorflow Version: 1.14
- Python version: 3.7.3
onnx==1.6.0
tf2onnx==1.5.3

**To Reproduce**
[graph_rnn.pb.zip](https://github.com/onnx/tensorflow-onnx/files/3985551/graph_rnn.pb.zip)
Unzip the attached graph and run 
``` console
> python -m tf2onnx.convert --graphdef graph_rnn.pb --inputs=action_masks:0,vector_observation:0 --outputs=action:0,action_probs:0,recurrent_out:0 --output out.onnx --fold_const --verbose --debug
```
(github wouldn't let me attach a .pb file)

This produces the following output (removing tensorflow deprecation warnings):
```
INFO:tensorflow:Froze 0 variables.
2019-12-19 15:45:08,010 - INFO - tensorflow: Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
2019-12-19 15:45:08,015 - INFO - tensorflow: Converted 0 variables to const ops.
2019-12-19 15:45:08,021 - INFO - tf2onnx: inputs: ['vector_observation:0', 'action_masks:0']
2019-12-19 15:45:08,022 - INFO - tf2onnx: outputs: ['action:0', 'action_probs:0', 'recurrent_out:0']
2019-12-19 15:45:08.037816: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2019-12-19 15:45:08.050151: E tensorflow/tools/graph_transforms/transform_graph.cc:332] fold_constants: Ignoring error You must feed a value for placeholder tensor 'recurrent_in' with dtype float and shape [?,4]
	 [[{{node recurrent_in}}]]
2019-12-19 15:45:08.051517: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying remove_attribute
2019-12-19 15:45:08.053464: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_batch_norms
2019-12-19 15:45:08.058315: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_old_batch_norms
2019-12-19 15:45:08,112 - INFO - tf2onnx.tfonnx: Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.5.3/7b598d
2019-12-19 15:45:08,112 - INFO - tf2onnx.tfonnx: Using opset <onnx, 7>
2019-12-19 15:45:08,112 - WARNING - tf2onnx.shape_inference: Shape of placeholder sequence_length is unknown, treated it as a scalar
2019-12-19 15:45:08,332 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2019-12-19 15:45:08,346 - ERROR - tf2onnx.tfonnx: Failed to convert node lstm/rnn/transpose
OP=Transpose
Name=lstm/rnn/transpose
Inputs:
	Reshape:0=Reshape, [-1, -1, 9], 1
	lstm/rnn/concat__39:0=Cast, [3], 6
Outpus:
	lstm/rnn/transpose:0=[-1, -1, 9], 1
Traceback (most recent call last):
  File "/Users/chris.elion/code/ml-agents/venv/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/Users/chris.elion/code/ml-agents/venv/lib/python3.7/site-packages/tf2onnx/onnx_opset/tensor.py", line 201, in version_1
    utils.make_sure(False, "perm can't be dynamic in ONNX")
  File "/Users/chris.elion/code/ml-agents/venv/lib/python3.7/site-packages/tf2onnx/utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: perm can't be dynamic in ONNX
```
(and similar for `lstm/rnn/transpose_1`)

**Expected behavior**
The frozen graph is converted with no errors.

**Screenshots**
See logs above.

**Additional context**
The code that produces the graph is fairly involved, but I can try to narrow down a repro if you prefer that over the serialized file. The actual code that adds the lstm cells is here
https://github.com/Unity-Technologies/ml-agents/blob/dfe9c11518f1de73f36bf85c36477372481e1598/ml-agents/mlagents/trainers/models.py#L568-L575

Thanks!
-Chris

Side note: one of the links from https://github.com/onnx/tensorflow-onnx/blob/master/examples/rnn_tips.md goes to https://github.com/onnx/tensorflow-onnx/blob/master/examples/tests/test_custom_rnncell.py, but that's a dead link.

**Comment by jignparm** [comment]
@chriselion, the error message is slightly misleading. The original error is higher up in the log output, which indicates that one of the required inputs was not listed. This should be halting condition (needs to be updated).

The model has 5 inputs, and if you provide them all on the command line parameters, the conversion works successfully. See the full command below.

### Convert the model
```
python -m tf2onnx.convert --graphdef graph_rnn.pb --inputs=action_masks:0,vector_observation:0,recurrent_in:0,prev_action:0,sequence_length:0 --outputs=action:0,action_probs:0,recurrent_out:0 --output out.onnx --fold_const --verbose --debug

```

### Run and compare TF and ONNX model

The outputs of running the TF model and ONNX model matches as well. To run the onnx model, ensure that OnnxRuntime is installed ( `pip install onnxruntime` )

```
python tests/run_pretrained_models.py --backend onnxruntime --opset 11 --config mypretrained.yaml --onnx-file . --fold_const   -v
```
### Contents of mypretrained.yaml
(N.B. the "get_ones" function is not part of the master branch , only for testing this model. It generates an int32 array of ones, of the shape required by the input shape)
```
modelschriseilion:
  disabled: false
  model: D:\modelschriselion\graph_rnn.pb
  input_get: get_ones
  inputs:
    "action_masks:0": [1,5]
    "vector_observation:0": [1,108]
    "recurrent_in:0": [1,4]
    "prev_action:0": [1,1]
    "sequence_length:0": []

  outputs:
    - action:0
    - action_probs:0
    - recurrent_out:0
```

### Run Log
```
2019-12-19 22:28:35,639 - INFO - run_pretrained: To_ONNX, OK 
2019-12-19 22:28:35,641 - INFO - run_pretrained: Created .\modelschriseilion.onnx   
2019-12-19 22:28:36,223 - INFO - run_pretrained: Model saved to C:\Users\localadmin\AppData\Local\Temp\2\tmpb4l4yvd6\run_pretrained\mode lschriseilion.onnx
...
...
2019-12-19 22:28:36,652 - INFO - run_pretrained: Run_ONNX OK  
2019-12-19 22:28:36,653 - INFO - run_pretrained: Results: OK   
2019-12-19 22:28:36,660 - INFO - run_pretrained: ===================================                                                   
2019-12-19 22:28:36,661 - INFO - run_pretrained: RESULT: 0 failed of 1, backend=onnxruntime
```

**Comment by chriselion** [comment]
Hi @jignparm,
Thanks for the quick reply. You're correct that I was missing some inputs; I fixed this in my export process and now things are looking good!
