### ISSUE TITLE
error of convert a bisegnet model 

### ISSUE THREAD

**Issue by jhx2002** [onnx/tensorflow-onnx#762]
Error log : 

```
: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
2019-12-28 06:41:32,462 - INFO - tf2onnx.tfonnx: Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.5.3/7b598d
2019-12-28 06:41:32,463 - INFO - tf2onnx.tfonnx: Using opset <onnx, 7>
2019-12-28 06:41:32,463 - WARNING - tf2onnx.shape_inference: Shape of placeholder ImageTensor is unknown, treated it as a scalar
2019-12-28 06:41:34,026 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2019-12-28 06:41:34,257 - ERROR - tf2onnx.tfonnx: Tensorflow op [DecodeRaw: DecodeRaw] is not supported
2019-12-28 06:41:34,503 - ERROR - tf2onnx.tfonnx: Failed to convert node ResizeBilinear_1
OP=Upsample
Name=ResizeBilinear_1
Inputs:
	conv2d_35/Conv2D__232:0=Transpose, [1, 64, 128, 19], 1
	ResizeBilinear_1/size_Concat__110:0=Concat, [2], 6
Outpus:
	ResizeBilinear_1:0=[1, -1, -1, 19], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 492, in version_7
    target_shape = node.inputs[1].get_tensor_value()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: ResizeBilinear_1/size_Concat__110 must be Const
2019-12-28 06:41:34,506 - ERROR - tf2onnx.tfonnx: Unsupported ops: Counter({'DecodeRaw': 1})
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 575, in process_tf_graph
    raise exceptions[0]
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 352, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 492, in version_7
    target_shape = node.inputs[1].get_tensor_value()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 256, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: ResizeBilinear_1/size_Concat__110 must be Const

```

**Comment by guschmue** [comment]
I guess we currently don't support DecodeRaw. Need to take a look if there is an onnx equivalent.

**Comment by jignparm** [comment]
DecodeRaw is doing data wrangling (e.g. litte_endian, out_type etc.). 

There's no equivalent ONNX op, but it seems like that type of data wrangling should be done outside of the model. Otherwise ONNX would need to support all disk/network IO operations as well, which seems impractical.

**Comment by guschmue** [comment]
closing - nothing we can do in tf2onnx without onnx support.
