### ISSUE TITLE
error when I convert frozen model（pb） to onnx

### ISSUE THREAD

**Issue by liupengkd** [onnx/tensorflow-onnx#764]
**Describe the bug**
when I convert frozen model to onnx，An error occurred：
Traceback (most recent call last):
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 321, in version_1
    _ = GraphBuilder(ctx).make_slice(kwargs, name=node.name)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/graph_builder.py", line 40, in make_slice
    starts = self.convert_to_attribute(kwargs.pop("starts"))
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/graph_builder.py", line 106, in convert_to_attribute
    res = const_node.get_tensor_value(as_list=True)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/graph.py", line 260, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
**ValueError: get tensor value: Slice/begin_Concat__233 must be Const**

**During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "/home/liupeng/anaconda3/envs/tf2onnx/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liupeng/anaconda3/envs/tf2onnx/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/tfonnx.py", line 573, in process_tf_graph
    mapped_op, unmapped_op, exceptions = tensorflow_onnx_mapping(g, ops_mapping)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/tfonnx.py", line 357, in tensorflow_onnx_mapping
    logger.error("Failed to convert node %s\n%s", node.name, node.summary, exc_info=1)
  File "/home/liupeng/cplus_tensorrt_retinaface/models/config-uff/tensorflow-onnx/tf2onnx/graph.py", line 175, in summary
    node = g.get_node_by_output(name)
**AttributeError: 'NoneType' object has no attribute 'get_node_by_output'**

**System information**
- OS Platform and Distribution ：Linux Ubuntu 16.04:
- Tensorflow Version:1.9
- Python version:3.5

**Comment by jignparm** [comment]
Please provide a link to the model and the command line parameters you are using to convert the model.

**Comment by jignparm** [comment]
Closing out due to non-response.
