### ISSUE TITLE
when i use it to convert yoloV3

### ISSUE THREAD

**Issue by chuqnzhao** [onnx/tensorflow-onnx#772]
2020-01-15 23:12:21.114076: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Froze 0 variables.
2020-01-15 23:12:21,880 - INFO - tensorflow: Froze 0 variables.
Converted 0 variables to const ops.
2020-01-15 23:12:21,912 - INFO - tf2onnx: inputs: ['input/input_data:0']
2020-01-15 23:12:21,915 - INFO - tf2onnx: outputs: ['pred_sbbox/concat_2:0', 'pred_sbbox/concat_2:0', 'pred_lbbox/concat_2:0']
2020-01-15 23:12:22.322401: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2020-01-15 23:12:22.646328: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
2020-01-15 23:12:23,420 - INFO - tf2onnx.tfonnx: Using tensorflow=1.5.0, onnx=1.6.0, tf2onnx=1.6.0/0aa0e8
2020-01-15 23:12:23,420 - INFO - tf2onnx.tfonnx: Using opset <onnx, 8>
2020-01-15 23:12:23,421 - WARNING - tf2onnx.shape_inference: Shape of placeholder input/input_data is unknown, treated it as a scalar
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 4 but is rank 0 for 'darknet/conv0/Conv2D' (op: 'Conv2D') with input shapes: [], [3,3,3,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 163, in <module>
    main()
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 147, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 486, in process_tf_graph
    tf_graph = infer_shape(tf_graph, shape_override)
  File "/home/onnx/tensorflow-onnx/tf2onnx/shape_inference.py", line 33, in infer_shape
    tf_graph = infer_shape_for_graph(tf_graph)
  File "/home/onnx/tensorflow-onnx/tf2onnx/shape_inference.py", line 96, in infer_shape_for_graph
    tf_graph = reload_tf_graph(tf_graph)
  File "/home/onnx/tensorflow-onnx/tf2onnx/shape_inference.py", line 73, in reload_tf_graph
    tf.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 664, in import_graph_def
    ops.set_shapes_for_outputs(op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 4 but is rank 0 for 'darknet/conv0/Conv2D' (op: 'Conv2D') with input shapes: [], [3,3,3,32].

How can I fix this problem, thank you!

**Comment by chuqnzhao** [comment]
How can I fix this problem, thank you!

**Comment by jignparm** [comment]
The issue is closed (i assume using -fold_const resolved it). Otherwise see the link below for the fix.

https://github.com/onnx/tensorflow-onnx/issues/729

**Comment by chuqnzhao** [comment]
> The issue is closed (i assume using -fold_const resolved it). Otherwise see the link below for the fix.
> 
> #729

hi ,thanks for your reply,I tried to modify with bug729, but the error message was the same.

**the information**
python3 -m tf2onnx.convert --input yolov3_pb_demo/yolov3_coco.pb --inputs input/input_data:0[1,416,416,3]    --outputs pred_sbbox/concat_2:0,pred_sbbox/concat_2:0,pred_lbbox/concat_2:0   --output yolov3_pb_demo/model.onnx   --verbose --fold_const --opset 11


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
----------------------------------------------
['input/input_data:0'] {'input/input_data:0': [1, 416, 416, 3]}
2020-01-16 19:12:58.082257: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Froze 0 variables.
2020-01-16 19:13:00,021 - INFO - tensorflow: Froze 0 variables.
Converted 0 variables to const ops.
2020-01-16 19:13:00,055 - INFO - tf2onnx: inputs: ['input/input_data:0']
2020-01-16 19:13:00,058 - INFO - tf2onnx: outputs: ['pred_sbbox/concat_2:0', 'pred_sbbox/concat_2:0', 'pred_lbbox/concat_2:0']
2020-01-16 19:13:00.447580: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_constants
2020-01-16 19:13:00.580845: E tensorflow/tools/graph_transforms/transform_graph.cc:279] fold_constants: Ignoring error NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: pred_sbbox/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_INT32, Truncate=false](pred_sbbox/Tile_2). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
2020-01-16 19:13:00.691039: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying remove_attribute
2020-01-16 19:13:00.700611: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2020-01-16 19:13:00.722805: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
2020-01-16 19:13:01,446 - INFO - tf2onnx.tfonnx: Using tensorflow=1.5.0, onnx=1.6.0, tf2onnx=1.6.0/0aa0e8
2020-01-16 19:13:01,447 - INFO - tf2onnx.tfonnx: Using opset <onnx, 11>
2020-01-16 19:13:01,447 - INFO - tf2onnx.shape_inference: Apply shape override:
2020-01-16 19:13:01,448 - INFO - tf2onnx.shape_inference:       Set input/input_data:0 shape to [1, 416, 416, 3]
2020-01-16 19:13:03,363 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2020-01-16 19:13:05,425 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_lbbox/strided_slice_7
OP=StridedSlice
Name=pred_lbbox/strided_slice_7
Inputs:
        pred_lbbox/range_1:0=Range, [-1], 6
        pred_lbbox/strided_slice_7/stack:0=Const, [2], 6
        pred_lbbox/strided_slice_7/stack_1:0=Const, [2], 6
        pred_lbbox/strided_slice_7/stack_2:0=Const, [2], 6
Outpus:
        pred_lbbox/strided_slice_7:0=[1, -1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,448 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_lbbox/strided_slice_6
OP=StridedSlice
Name=pred_lbbox/strided_slice_6
Inputs:
        pred_lbbox/range:0=Range, [-1], 6
        pred_lbbox/strided_slice_6/stack:0=Const, [2], 6
        pred_lbbox/strided_slice_6/stack_1:0=Const, [2], 6
        pred_lbbox/strided_slice_6/stack_2:0=Const, [2], 6
Outpus:
        pred_lbbox/strided_slice_6:0=[-1, 1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,452 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_lbbox/strided_slice_8
OP=StridedSlice
Name=pred_lbbox/strided_slice_8
Inputs:
        pred_lbbox/Tile_1:0=Tile, [-1, -1], 6
        pred_lbbox/strided_slice_8/stack:0=Const, [3], 6
        pred_lbbox/strided_slice_8/stack_1:0=Const, [3], 6
        pred_lbbox/strided_slice_8/stack_2:0=Const, [3], 6
Outpus:
        pred_lbbox/strided_slice_8:0=[-1, -1, 1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,459 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_lbbox/strided_slice_9
OP=StridedSlice
Name=pred_lbbox/strided_slice_9
Inputs:
        pred_lbbox/Tile:0=Tile, [-1, -1], 6
        pred_lbbox/strided_slice_9/stack:0=Const, [3], 6
        pred_lbbox/strided_slice_9/stack_1:0=Const, [3], 6
        pred_lbbox/strided_slice_9/stack_2:0=Const, [3], 6
Outpus:
        pred_lbbox/strided_slice_9:0=[-1, -1, 1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,463 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_lbbox/strided_slice_10
OP=StridedSlice
Name=pred_lbbox/strided_slice_10
Inputs:
        pred_lbbox/concat:0=Concat, [-1, -1, 2], 6
        pred_lbbox/strided_slice_10/stack:0=Const, [5], 6
        pred_lbbox/strided_slice_10/stack_1:0=Const, [5], 6
        pred_lbbox/strided_slice_10/stack_2:0=Const, [5], 6
Outpus:
        pred_lbbox/strided_slice_10:0=[1, -1, -1, 1, 2], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,684 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_sbbox/strided_slice_7
OP=StridedSlice
Name=pred_sbbox/strided_slice_7
Inputs:
        pred_sbbox/range_1:0=Range, [-1], 6
        pred_sbbox/strided_slice_7/stack:0=Const, [2], 6
        pred_sbbox/strided_slice_7/stack_1:0=Const, [2], 6
        pred_sbbox/strided_slice_7/stack_2:0=Const, [2], 6
Outpus:
        pred_sbbox/strided_slice_7:0=[1, -1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,687 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_sbbox/strided_slice_6
OP=StridedSlice
Name=pred_sbbox/strided_slice_6
Inputs:
        pred_sbbox/range:0=Range, [-1], 6
        pred_sbbox/strided_slice_6/stack:0=Const, [2], 6
        pred_sbbox/strided_slice_6/stack_1:0=Const, [2], 6
        pred_sbbox/strided_slice_6/stack_2:0=Const, [2], 6
Outpus:
        pred_sbbox/strided_slice_6:0=[-1, 1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,691 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_sbbox/strided_slice_8
OP=StridedSlice
Name=pred_sbbox/strided_slice_8
Inputs:
        pred_sbbox/Tile_1:0=Tile, [-1, -1], 6
        pred_sbbox/strided_slice_8/stack:0=Const, [3], 6
        pred_sbbox/strided_slice_8/stack_1:0=Const, [3], 6
        pred_sbbox/strided_slice_8/stack_2:0=Const, [3], 6
Outpus:
        pred_sbbox/strided_slice_8:0=[-1, -1, 1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,698 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_sbbox/strided_slice_9
OP=StridedSlice
Name=pred_sbbox/strided_slice_9
Inputs:
        pred_sbbox/Tile:0=Tile, [-1, -1], 6
        pred_sbbox/strided_slice_9/stack:0=Const, [3], 6
        pred_sbbox/strided_slice_9/stack_1:0=Const, [3], 6
        pred_sbbox/strided_slice_9/stack_2:0=Const, [3], 6
Outpus:
        pred_sbbox/strided_slice_9:0=[-1, -1, 1], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
2020-01-16 19:13:05,702 - ERROR - tf2onnx.tfonnx: Failed to convert node pred_sbbox/strided_slice_10
OP=StridedSlice
Name=pred_sbbox/strided_slice_10
Inputs:
        pred_sbbox/concat:0=Concat, [-1, -1, 2], 6
        pred_sbbox/strided_slice_10/stack:0=Const, [5], 6
        pred_sbbox/strided_slice_10/stack_1:0=Const, [5], 6
        pred_sbbox/strided_slice_10/stack_2:0=Const, [5], 6
Outpus:
        pred_sbbox/strided_slice_10:0=[1, -1, -1, 1, 2], 6
Traceback (most recent call last):
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 163, in <module>
    main()
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 147, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 577, in process_tf_graph
    raise exceptions[0]
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/onnx/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported

**Comment by chuqnzhao** [comment]
> The issue is closed (i assume using -fold_const resolved it). Otherwise see the link below for the fix.
> 
> #729
**the command**

python3 -m tf2onnx.convert --input yolov3_pb_demo/yolov3_coco.pb --inputs input/input_data:0[1,416,416,3] --outputs pred_sbbox/concat_2:0,pred_sbbox/concat_2:0,pred_lbbox/concat_2:0 --output yolov3_pb_demo/model.onnx --verbose --fold_const --opset 11

**Comment by jignparm** [comment]
What is the  source of this model (paste exact link if possible?)
