### ISSUE TITLE
Support tf.keras.layers.CudnnGRU

### ISSUE THREAD

**Issue by THULiusj** [onnx/tensorflow-onnx#787]
**Describe the bug**
I have a model using tf.keras.layers.CudnnGRU op. I try to transform the TF model to onnx, and it reports error:
2019-12-25 17:37:20,725 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter1/ReverseV2: ReverseV2] is not supported
2019-12-25 17:37:20,741 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter1/CudnnRNN_1: CudnnRNN] is not supported
2019-12-25 17:37:20,741 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter1/ReverseV2_1: ReverseV2] is not supported
2019-12-25 17:37:20,746 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter1/CudnnRNN: CudnnRNN] is not supported
2019-12-25 17:37:20,774 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter2/CudnnRNN: CudnnRNN] is not supported
2019-12-25 17:37:20,774 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter2/ReverseV2: ReverseV2] is not supported
2019-12-25 17:37:20,774 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter2/CudnnRNN_1: CudnnRNN] is not supported
2019-12-25 17:37:20,775 - ERROR - Tensorflow op [resnet_ada/adapter/general/rnn_adapter2/ReverseV2_1: ReverseV2] is not supported

**Urgency**
I want to publish the model to production but blocked by this issue. I also communicated with Nvidia contact. And they replied that this op should be supported by tf2onnx first.

**System information**
- Tensorflow Version: 1.13+
- Python version: 3.5+

**Expected behavior**
tf2onnx supports tf.keras.layers.CudnnGRU to be transformed to onnx

**Comment by guschmue** [comment]
ReverseV2 is supported if you use ```--opset 11```. 
CudnnRNN we don't support right now. Let me check if we can add this.

**Comment by THULiusj** [comment]
@guschmue Hi, how about the status of CudnnRNN?

**Comment by guschmue** [comment]
have not gotten to it yet.

**Comment by RandySheriffH** [comment]
Adding support now, will share PR with ready.

**Comment by THULiusj** [comment]
@RandySheriffH , good news! waiting for the PR!

**Comment by RandySheriffH** [comment]
Would u mind share me your frozen graph please?

**Comment by THULiusj** [comment]
@RandySheriffH I can, but how to share it? It's a saved model about 10M.

**Comment by RandySheriffH** [comment]
like the one shared in:
https://github.com/onnx/tensorflow-onnx/issues/683
would be great if also paste your command for conversion please.

**Comment by THULiusj** [comment]
@RandySheriffH , saved model and frozen graph are saved here(recommend using saved model): 
 https://drive.google.com/open?id=1aQM1ts45BnjTFUA9PWAxu7hgJTTge2-6.  command: python -m tf2onnx.convert --saved-model cudnngru --inputs embedding_input:0 --outputs dense/Sigmoid:0 --output cudnngru.onnx --opset11

**Comment by RandySheriffH** [comment]
https://github.com/RandySheriffH/tensorflow-onnx/tree/rashuai/CudnnGRU
Here is a candidate fix - testing is still ongoing but please feel free to play with it.

**Comment by THULiusj** [comment]
@RandySheriffH Hi, I've tried to install from source of your branch, it converts sucessfully but still reports error: 
2020-03-02 04:48:35,814 - WARNING - Cannot infer shape for bidirectional/CudnnRNN: bidirectional/CudnnRNN:3
2020-03-02 04:48:35,814 - WARNING - Cannot infer shape for bidirectional/CudnnRNN_1: bidirectional/CudnnRNN_1:3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/tfonnx.py", line 356, in tensorflow_onnx_mapping
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/onnx_opset/tensor.py", line 1659, in version_10
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/utils.py", line 291, in make_sure
ValueError: make_sure failure: ReverseSequence batch size for axis 1 is unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/convert.py", line 161, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/convert.py", line 145, in main
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/tfonnx.py", line 575, in process_tf_graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/tfonnx.py", line 359, in tensorflow_onnx_mapping
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/graph.py", line 175, in summary
AttributeError: 'NoneType' object has no attribute 'get_node_by_output'

I'm not sure if the onnx is correct now?

**Comment by RandySheriffH** [comment]
I see - your model requires another fix on reverse op which is also approaching ready. Let me do the test then.

**Comment by RandySheriffH** [comment]
@THULiusj : Branch updated with additional fix and tested, mind to try again on your side?

**Comment by THULiusj** [comment]
@RandySheriffH Thanks, I've verified, it works. 
But there's a warning: "WARNING - Cannot infer shape for bidirectional/CudnnRNN: bidirectional/CudnnRNN:3
2020-03-03 14:07:35,593 - WARNING - Cannot infer shape for bidirectional/CudnnRNN_1: bidirectional/CudnnRNN_1:3"

Does this warning matter?

**Comment by RandySheriffH** [comment]
Never mind, they are just trivial warnings.
