### ISSUE TITLE
Error converting bidirectional GRU

### ISSUE THREAD

**Issue by chinhuang007** [onnx/tensorflow-onnx#802]
We tried to convert a tf model with bidirectional GRU in the env:

Ubuntu 18.04
Tensorflow: 1.13.1
Python: 3.6.8
ONNX: 1.5.0

Command:
python -m tf2onnx.convert --saved-model ./saved_model --output test_model.onnx --opset 10 --fold_const

Got the following error:
2020-02-12 23:26:51,241 - ERROR - rewriter <function rewrite_single_direction_lstm at 0x7efed32110d0>: exception list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/tfonnx.py", line 569, in process_tf_graph
    run_rewriters(g, rewriters, continue_on_error)
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/tfonnx.py", line 436, in run_rewriters
    raise ex
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/tfonnx.py", line 427, in run_rewriters
    ops = func(g, g.get_nodes())
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/rnn.py", line 29, in rewrite_single_direction_lstm
    return r.run()
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/lstm_rewriter.py", line 43, in run
    return super(LSTMUnitRewriter, self).run()
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/unit_rnn_rewriter_base.py", line 62, in run
    return self.run_internal()
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/loop_rewriter_base.py", line 207, in run_internal
    self._check_in_read_only_mode(context)
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/loop_rewriter_base.py", line 230, in _check_in_read_only_mode
    self._parse_loop_variables(context)
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/loop_rewriter_base.py", line 244, in _parse_loop_variables
    loop_var = self._get_loop_var_from_switch(s)
  File "/home/chinhuang/tensorflow-onnx/tf2onnx/rewriter/loop_rewriter_base.py", line 393, in _get_loop_var_from_switch
    ta_gather_node = [n for n in exit_consumers if is_tf_tensor_array_gather_op(n)][0]
IndexError: list index out of range

I don't know the exact rewriter logic. Can we check the length of the list `[n for n in exit_consumers if is_tf_tensor_array_gather_op(n)]` before we assign the gather node?

**Comment by jignparm** [comment]
@chinhuang007, can you share the model which produces this error? The rewriters try to pattern-match a sequence of operators in the TF graph, so that they can be rewritten as a collection of ONNX operators.

**Comment by jignparm** [comment]
Closing this due to non-response. Please reopen if needed.
