### ISSUE TITLE
i use it to convert mobilenet

### ISSUE THREAD

**Issue by chuqnzhao** [onnx/tensorflow-onnx#806]
Model name-> mobilenet_v1
Model source-> https://github.com/chuqnzhao/mobilenet_V1.git

##Cmd line
```
 python3 -m tf2onnx.convert --input resnet/model.pb --inputs prefetch_queue/fifo_queue:0 --outputs MobilenetV1/Logits/SpatialSqueeze:0 --output resnet/model.onnx --verbose --fold_const --custom-ops FIFOQueueV2
```
##log
```
python3 -m tf2onnx.convert --input resnet/modelmobile.pb --inputs prefetch_queue/fifo_queue:0 --outputs MobilenetV1/Logits/SpatialSqueeze:0 --output resnet/model.onnx --verbose --fold_const
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
['prefetch_queue/fifo_queue:0'] None
2020-02-17 17:52:26.482261: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Froze 0 variables.
2020-02-17 17:52:26,602 - INFO - tensorflow: Froze 0 variables.
Converted 0 variables to const ops.
2020-02-17 17:52:26,612 - INFO - tf2onnx: inputs: ['prefetch_queue/fifo_queue:0']
2020-02-17 17:52:26,613 - INFO - tf2onnx: outputs: ['MobilenetV1/Logits/SpatialSqueeze:0']
2020-02-17 17:52:26.648628: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_constants
2020-02-17 17:52:26.702629: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying remove_attribute
2020-02-17 17:52:26.704203: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2020-02-17 17:52:26.706877: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 163, in <module>
    main()
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 133, in main
    graph_def = tf_optimize(inputs, outputs, graph_def, args.fold_const)
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 404, in tf_optimize
    graph_def = TransformGraph(graph_def, inputs, outputs, transforms)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/tools/graph_transforms/__init__.py", line 51, in TransformGraph
    transforms_string, status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Beta input to batch norm has bad shape: [32]
```
I encountered this error when converting the mobilenet model. Is there any way to solve it? I have shared the model file with you and look forward to your reply.

**Comment by jignparm** [comment]
Thanks for including a link to the model. 

The error is coming from TF optimization (surprisingly). One option is to not do that level of TF optimization, by removing it from here --> https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tfonnx.py#L400

Will review it shortly.

**Comment by chuqnzhao** [comment]
> Thanks for including a link to the model.
> 
> The error is coming from TF optimization (surprisingly). One option is to not do that level of TF optimization, by removing it from here --> https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tfonnx.py#L400
> 
> Will review it shortly.


##cmd line
```python3 -m tf2onnx.convert --input resnet/modelmobile.pb --inputs prefetch_queue/fifo_queue:0 --outputs MobilenetV1/Logits/SpatialSqueeze:0 --output resnet/model.onnx --verbose --fold_const --opset 10  
```
##log     
```
['prefetch_queue/fifo_queue:0'] None
2020-02-17 22:27:03.532746: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Froze 0 variables.
2020-02-17 22:27:03,645 - INFO - tensorflow: Froze 0 variables.
Converted 0 variables to const ops.
2020-02-17 22:27:03,654 - INFO - tf2onnx: inputs: ['prefetch_queue/fifo_queue:0']
2020-02-17 22:27:03,655 - INFO - tf2onnx: outputs: ['MobilenetV1/Logits/SpatialSqueeze:0']
2020-02-17 22:27:03.685413: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_constants
2020-02-17 22:27:03.724735: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying remove_attribute
2020-02-17 22:27:03.725999: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2020-02-17 22:27:03,787 - INFO - tf2onnx.tfonnx: Using tensorflow=1.5.0, onnx=1.6.0, tf2onnx=1.6.0/f4b13b
2020-02-17 22:27:03,787 - INFO - tf2onnx.tfonnx: Using opset <onnx, 10>
2020-02-17 22:27:03,790 - WARNING - tf2onnx.shape_inference: two shapes not possible to broadcast, [None, None, None, None], [64, 1, 1, 1024]
2020-02-17 22:27:03,791 - WARNING - tf2onnx.shape_inference: two shapes not possible to broadcast, [None, None, None, None], [64, 1, 1, 1024]
2020-02-17 22:27:03,801 - ERROR - tf2onnx.tfonnx: pass1 convert failed for name: "fifo_queue_Dequeue"
op: "QueueDequeueV2"
input: "prefetch_queue/fifo_queue"
attr {
  key: "component_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_FLOAT
    }
  }
}
attr {
  key: "timeout_ms"
  value {
    i: -1
  }
}
, ex=You passed in an iterable attribute but I cannot figure out its applicable type.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 163, in <module>
    main()
  File "/home/onnx/tensorflow-onnx/tf2onnx/convert.py", line 147, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 497, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 124, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "/home/onnx/tensorflow-onnx/tf2onnx/tfonnx.py", line 111, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python3.6/dist-packages/onnx/helper.py", line 269, in make_attribute
    "You passed in an iterable attribute but I cannot figure out "
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type.
```
Note to the corresponding code, But I have encountered the above problems. How to solve them? Thanks!

**Comment by jignparm** [comment]
The problem seems to be the first node of type `FIFOQueueV2`. The model doesn't have any inputs according to summarize_graph.exe. How is this model supposed to work without any inputs?


```
$ /d/bin/summarize_graph.exe --in_graph=model.pb
No inputs spotted.
No variables spotted.
Found 1 possible outputs: (name=MobilenetV1/Logits/SpatialSqueeze, op=Squeeze)
Found 3217233 (3.22M) const parameters, 0 (0) variable parameters, and 0 control_edges
84 nodes assigned to device '/job:worker/task:0/device:CPU:0'152 nodes assigned to device '/job:worker/task:0/device:GPU:0'Op types used: 141 Const, 83 Identity, 27 FusedBatchNorm, 27 Relu6, 15 Conv2D, 13 DepthwiseConv2dNative, 2 Add, 2 Mul, 1 AvgPool, 1 BiasAdd, 1 FIFOQueueV2, 1 Floor, 1 QueueDequeueV2, 1 RandomUniform, 1 RealDiv, 1 Squeeze, 1 Sub
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=model.pb --show_flops --input_layer= --input_layer_type= --input_layer_shape= --output_layer=MobilenetV1/Logits/SpatialSqueeze


```

**Comment by guschmue** [comment]
We would not know QueueDequeueV2 and there is onnx equivalent for it. For tf.data we fixed this by making the iterator a placeholder. Maybe we could do the same thing here. @RandySheriffH  - could you take a look ?

**Comment by chuqnzhao** [comment]
> We would not know QueueDequeueV2 and there is onnx equivalent for it. For tf.data we fixed this by making the iterator a placeholder. Maybe we could do the same thing here. @RandySheriffH - could you take a look ?

Thanks for your reply. I will try.

**Comment by guschmue** [comment]
The change for tf.data was here:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/controlflow.py#L375

**Comment by RandySheriffH** [comment]
@chuqnzhao :
The PR replace fifoqueue with placeholders.
To try with the change, remember to override shapes like:
python -m tf2onnx.convert --input resnet/modelmobile.pb --inputs **"fifo_queue_Dequeue:0[64,224,224,3],fifo_queue_Dequeue:1[64,10]**" --outputs MobilenetV1/Logits/SpatialSqueeze:0 --output resnet/model.onnx --verbose --fold_const

**Comment by RandySheriffH** [comment]
Closing the issue - please follow above advice to convert your model.

**Comment by alex96295** [comment]
@RandySheriffH Could you please have a look at the issue I have opened two days ago? It is related to this problem, I think
