### ISSUE TITLE
Support for tf.math.add_n

### ISSUE THREAD

**Issue by jusonn** [onnx/tensorflow-onnx#817]
tensorflow-onnx now support `tf.math.add` and `tf.math.add_n` in https://github.com/onnx/tensorflow-onnx/blob/master/support_status.md

However, when I convert AddN, an error occurs

```
node lambda/AddN of type AddN cannot be converted, fall back to tf2onnx
Traceback (most recent call last):
  File "build_model.py", line 66, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/main.py", line 60, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 794, in parse_graph
    graph, keras_node_dict, topo, top_level, output_names)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 595, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 335, in _on_parsing_tf_subgraph
    raise RuntimeError("Some tensorflow operation doesn't support, stop converting.")
RuntimeError: Some tensorflow operation doesn't support, stop converting.
```

It looks like AddN is not supported bute there's am implementation of it in https://github.com/onnx/tensorflow-onnx/blob/ed3a41d91146116ab789b285be4fe86d56cc5004/tf2onnx/onnx_opset/reduction.py

**Comment by guschmue** [comment]
This issue should be filed under keras2onnx. keras2onnx is using tf2onnx but they don't use our releases and instead take a source copy which makes it hard for us provide support.
tf2onnx itself does support tf.math.add_n: https://github.com/onnx/tensorflow-onnx/blob/master/tests/test_backend.py#L1597
