### ISSUE TITLE
Not able to convert official tensorflow model

### ISSUE THREAD

**Issue by SanthoshSandi** [onnx/tensorflow-onnx#862]
**Describe the bug**
Tried using the official tensorflow models for creating a replica of the classification model, using the latest git repository. Not able to convert the final trained checkpoint to onnx, due to version mismatch error. Model trained using the latest tensorflow version. 

**Urgency**
This issue is a critical one, as this serves as the base for any image classification algorithm as such.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Tensorflow Version: 1.15.0 (latest nightly)
- Python version: 3.6

**To Reproduce**
Describe steps/code to reproduce the behavior:
1) Train the model using the training script available in [here](https://github.com/tensorflow/models/tree/master/research/slim). 
2) Export the trained model for inference using the reference code snippets mentioned in the above ReadME.md file.
3) Try converting ONNX using the following code.
`python -m tf2onnx.convert --graphdef frozen_mobilenetv2.pb --output sample_classification.onnx --fold_const  --opset 10 --inputs input:0 --outputs MobilenetV2/Predictions/Reshape_1:0`

**Expected behavior**
Model should get converted without any issues

**Logs**

WARNING:tensorflow:From /home/santhosh/.local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-03-28 13:43:47,248 - WARNING - From /home/santhosh/.local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-03-28 13:43:47.364023: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
Traceback (most recent call last):
  File "/home/santhosh/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node MobilenetV2/Conv/BatchNorm/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/santhosh/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/santhosh/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/santhosh/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/santhosh/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 116, in main
    graph_def, inputs, outputs = loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/santhosh/.local/lib/python3.6/site-packages/tf2onnx/loader.py", line 63, in from_graphdef
    tf.import_graph_def(graph_def, name='')
  File "/home/santhosh/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/santhosh/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/santhosh/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node MobilenetV2/Conv/BatchNorm/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.)

**Comment by jignparm** [comment]
> (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.)

This error seems to indicate there's a mismatch between the TF version used to load the graphdef file. Try TF 2.0 or 2.1 instead of 1.15.

In case that doesn't work, can you upload/attach the  specific model you are using, instead of providing a link to a generic model training script?

**Comment by guschmue** [comment]
If I parse the error correctly it reads as:
the importer found an attribute exponential_avg_factor on the FusedBatchNormV3 op but that attribute is not defined on that op:
https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/fused-batch-norm-v3

But I'm not sure how you can get here.
Do you use the same version of tensorflow with tf2onnx that was used to train it ?
And can you load the model with tensorflow itself?

**Comment by HarryVancao** [comment]
Any update on this? did TF 2.0 or 2.1 work out?

**Comment by guschmue** [comment]
I think I saw a similar issue - as far I can remember I saw this once with graphdef and it went away when using saved-model. Might be some tf issue.
Have not noticed something with tf-2.2rc3.

**Comment by HarryVancao** [comment]
Thanks for the update. I also think it is a tf issue. But I do see a similar problem in a saved-model

**Comment by guschmue** [comment]
just tried on tf-2.2.0 and it was happy.

**Comment by codethief** [comment]
I'm experiencing the same issue with ssd_mobilenet_v2_mnasfpn_coco from the [TF *v1* model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md). (For details see below.) Given that the model is meant for TF v1 and it's not working on v1 I suggest we re-open this issue?

**Details:**

I'm trying to convert the given model to ONNX using TensorFlow 1.15.3 and [tf2onnx](https://github.com/onnx/tensorflow-onnx) 1.8.2:

```
$ python3 -m tf2onnx.convert --input frozen_inference_graph.pb --output model.onnx --opset 11
```

As in the OP's case, it doesn't even get to the converting step but already fails at loading the frozen graph using TF:

```
Traceback (most recent call last):
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tf2onnx/convert.py", line 221, in <module>
    main()
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tf2onnx/convert.py", line 148, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 200, in from_graphdef
    tf.import_graph_def(graph_def, name='')
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

**Comment by robertlugg** [comment]
I'm posting this in a couple of github issues:  It seems that that option was introduced in TF 2.2.  Likely model was created using 2.2+, saved, and then attempted to use in < 2.2
