### ISSUE TITLE
Models with simple input / output names are not supported

### ISSUE THREAD

**Issue by ongun-kanat** [onnx/tensorflow-onnx#872]
**Describe the bug**
When trying to export a simple linear TF model tf2onnx raises an exception since variable names are not in the format  "`name:0`" . It seems to be a hardcoded assumption in various places in the tf2onnx library. 

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 Conda environment
- Tensorflow Version: 1.15
- Python version: 3.6
- tf2onnx version: 1.5.3 (conda-forge)

**To Reproduce**
The bug can be reproduced with a simple script:

```python3
import tensorflow as tf
import pathlib
import google.protobuf as pb
import google.protobuf.json_format

graph = tf.Graph()

# Design a linear equation
with graph.as_default():
    x = tf.placeholder(tf.dtypes.float32, name="x", shape=(3, 8))
    A_value = np.random.randint(low=0, high=5, size=(5, 3)).astype(np.single)
    A = tf.constant(A_value, name="A", dtype=tf.dtypes.float32)
    y = tf.matmul(A, x, name="y")

graph_def = graph.as_graph_def()

graph_file = pathlib.Path(__file__).resolve().parent / "linear_equation_model.pb"
with tf.gfile.GFile(str(graph_file), "wb") as out:
    out.write(graph_def.SerializeToString())

# JSON
graph_file_txt = pathlib.Path(__file__).resolve().parent / "linear_equation_model.json"
with open(str(graph_file_txt), "w") as out:
    out.write(pb.json_format.MessageToJson(graph_def))
```
The json output for the GraphDef is:

```json
{
  "node": [
    {
      "name": "x",
      "op": "Placeholder",
      "attr": {
        "dtype": {
          "type": "DT_FLOAT"
        },
        "shape": {
          "shape": {
            "dim": [
              {
                "size": "3"
              },
              {
                "size": "8"
              }
            ]
          }
        }
      }
    },
    {
      "name": "A",
      "op": "Const",
      "attr": {
        "value": {
          "tensor": {
            "dtype": "DT_FLOAT",
            "tensorShape": {
              "dim": [
                {
                  "size": "5"
                },
                {
                  "size": "3"
                }
              ]
            },
            "tensorContent": "AACAQAAAgD8AAIA/AAAAAAAAQEAAAIBAAACAPwAAQEAAAAAAAAAAQAAAQEAAAABAAACAQAAAAAAAAAAA"
          }
        },
        "dtype": {
          "type": "DT_FLOAT"
        }
      }
    },
    {
      "name": "y",
      "op": "MatMul",
      "input": [
        "A",
        "x"
      ],
      "attr": {
        "T": {
          "type": "DT_FLOAT"
        },
        "transpose_a": {
          "b": false
        },
        "transpose_b": {
          "b": false
        }
      }
    }
  ],
  "versions": {
    "producer": 134
  }
}
```

Then I execute:
```
python3 -m tf2onnx.convert --graphdef linear_equation_model.pb --inputs "x" --outputs "y"
```
Note that the names are not in "name:0" format. The JSON shows that they are indeed "x" and "y"

This causes an exception in  loader.py:26
```
Traceback (most recent call last):
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/convert.py", line 116, in main
    graph_def, inputs, outputs = loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/loader.py", line 64, in from_graphdef
    frozen_graph = freeze_session(sess, output_names=output_names)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/loader.py", line 26, in freeze_session
    output_names = [i.split(':')[:-1][0] for i in output_names]
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/loader.py", line 26, in <listcomp>
    output_names = [i.split(':')[:-1][0] for i in output_names]
IndexError: list index out of range
```
It can be fixed by modifying loader.py:26 to

```python3
output_names = [i.split(':')[-1][0] for i in output_names]
```

but it creates yet another error:

```
Failed to convert: inputs/outputs specified do not exist, make sure your passedin format: input/output_node_name:port_id. Problematical inputs/outputs are: {'y', 'x'} 

Traceback (most recent call last):
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/ongun/miniconda3/envs/tf115/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 511, in process_tf_graph
    raise ValueError("Inputs/Outputs Not Found")
ValueError: Inputs/Outputs Not Found
```

Further investigation of `tf2onnx.py` shows that `def tflist_to_onnx(node_list, shape_override):` has also similar assumptions.

**Expected behavior**
Variables without "`:#`" in their name should also work.

**Comment by jignparm** [comment]
@ongun-kanat, I'm sure you are aware already, but just to make it explicit, the model above converts if you specify the port number of 'x' as shown in the log below.

The main question is, should 'tf2onnx' assume  port ':0'   of the inputs if the user does not specify the port on the command line? The downside is the user confusion: should inputs be node names, or port IDs? Currently it's always port IDs -- if we make the change requested, it's sometimes port IDs, and sometimes node names.



```
$python -m tf2onnx.convert --graphdef linear_equation_model.pb --inputs x:0 --outputs y:0 --output model.onnx

2020-07-11 20:19:00,198 - INFO - Using tensorflow=1.14.0, onnx=1.7.0, tf2onnx=1.7.0/aafc83
2020-07-11 20:19:00,198 - INFO - Using opset <onnx, 11>
2020-07-11 20:19:00,204 - INFO - Optimizing ONNX model
2020-07-11 20:19:00,211 - INFO - After optimization: Identity -1 (1->0)
2020-07-11 20:19:00,211 - INFO -
2020-07-11 20:19:00,211 - INFO - Successfully converted TensorFlow model linear_equation_model.pb to ONNX
2020-07-11 20:19:00,213 - INFO - ONNX model is saved at model.onnx

```

**Comment by guschmue** [comment]
We want to avoid that sometimes the node name will work and sometimes the tensor name - its always going to be the tensor name.
