### ISSUE TITLE
Optimizers are failing

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/tensorflow-onnx#885]
**Describe the bug**
Graph optimization is failing due to issue in deepcopy().
When we are taking a copy of current object into a new object using deepcopy(), I am getting ReferenceError: weakly-referenced object no longer exists

Log (below is for remove_back_to_back, similar failure for other 6 optimizers as well):
2020-04-15 00:50:35,200 - VERBOSE - tf2onnx.optimizer: Apply remove_back_to_back
2020-04-15 00:50:35,216 - WARNING - tf2onnx.optimizer: Failed to apply remove_back_to_back
Traceback (most recent call last):
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/lib/python3.6/site-packages/tf2onnx/optimizer/__init__.py", line 50, in optimize_graph
    current = copy.deepcopy(graph)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 183, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 283, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 183, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 283, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 183, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 283, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/bnandano/debug/env/NeMoRt-ONNXTools-1.0/runtime/python3.6/lib/python3.6/copy.py", line 170, in deepcopy
    reductor = getattr(x, "__reduce_ex__", None)
ReferenceError: weakly-referenced object no longer exists 

**Urgency**
I got a workaround for time-being by using the new try except block like:
logger.verbose("Apply %s", name)
                try:
                    current = copy.deepcopy(graph)
                except Exception:
                    logger.verbose("Failed to do deepcopy")
                    current = graph
                opt = factory()
                graph = opt.optimize(current) or graph
But not sure this will work for all, as there is a chance of corruption of original graph.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux 2
- Tensorflow Version: 1.14
- Python version: 3.6
- ONNX: 1.7

**To Reproduce**
Describe steps/code to reproduce the behavior:
I might not able to share the model. Basically it a model with some Conv and LSTM nodes.

**Expected behavior**
Deepcopy should have worked without throwing ReferenceError: weakly-referenced object no longer exists

**Comment by jignparm** [comment]
@buddhapuneeth, what version of tf2onnx are you using (master branch, or one of the released Python packages)?

Is there a another similar model that you can share to reproduce this error (since you are not able to share the original model)?

**Comment by buddhapuneeth** [comment]
@jignparm yes I thought of providing you any sample model for you to reproduce. But unable to reproduce with any other model. I can understand it will be difficult to fix without the model.
I am using r1.5 branch not the mainline. ONNX is from rel-1.7.0 branch.

**Comment by jignparm** [comment]
Can you try the master branch to see if you still have the issue?

•	pip install git+https://github.com/onnx/tensorflow-onnx

**Comment by guschmue** [comment]
This is the same issue as https://github.com/onnx/tensorflow-onnx/issues/886. We are trying to reproduce this but have not been able to with similar environment and model.

**Comment by jignparm** [comment]
@buddhapuneeth,  PR #972 should resolve this issue. Let me know if you see any errors. It took a while before we got a model to reproduce the error systematically -- hopefully this resolves it finally.

**Comment by buddhapuneeth** [comment]
verified. working fine.
@jignparm Thank you!

**Comment by jignparm** [comment]
Great. Thanks for verifying @buddhapuneeth
