### ISSUE TITLE
ResizeNearestNeighbor's 2nd input is assumed to be Const 

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#89]
If it's not a const, conversion will fail. 

This is found when I am working on convert style2paints go_head inference model. 

```
-------------------- start handling style2paints_head.pb ----------------------------
change working directory to /home/pengwa/community/tensorflow
------ summarize the frozen graph, to get the inputs and outputs name
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/tmp/frozen/style2paints_head.pb
Found 5 possible inputs: (name=Placeholder, type=float(1), shape=[?,1]) (name=Placeholder_1, type=float(1), shape=[?,?,?,1]) (name=Placeholder_2, type=float(1), shape=[?,?,?,3]) (name=Placeholder_3, type=float(1), shape=[?,?,?,4]) (name=Placeholder_4, type=float(1), shape=[?,?,?,3])
No variables spotted.
Found 1 possible outputs: (name=strided_slice_20, op=StridedSlice)
Found 187414779 (187.41M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 954 Const, 640 Identity, 446 Mul, 318 Add, 238 Conv2D, 228 Relu, 151 Sub, 150 BiasAdd, 136 Rsqrt, 48 MatMul, 36 ConcatV2, 24 Mean, 24 Reshape, 18 StridedSlice, 14 AvgPool, 11 Shape, 10 MaxPool, 10 ResizeNearestNeighbor, 6 RealDiv, 5 Placeholder, 2 Pad, 1 ClipByValue, 1 ResizeBilinear
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/tmp/frozen/style2paints_head.pb --show_flops --input_layer=Placeholder,Placeholder_1,Placeholder_2,Placeholder_3,Placeholder_4 --input_layer_type=float,float,float,float,float --input_layer_shape=-1,1:-1,-1,-1,1:-1,-1,-1,3:-1,-1,-1,4:-1,-1,-1,3 --output_layer=strided_slice_20
------ update the inputs and outputs name to format like input_name:index
python3 /home/pengwa/community/learning/onnx/update_name_with_index.py Placeholder,Placeholder_1,Placeholder_2,Placeholder_3,Placeholder_4
updated input names is Placeholder:0,Placeholder_1:0,Placeholder_2:0,Placeholder_3:0,Placeholder_4:0, output names is strided_slice_20:0
------ start convertion, tensorflow usage require caller program must not in tensorflow root folder, so switch to current user directory with cd
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
using tensorflow=1.8.0, onnx=1.2.2
2018-07-26 13:25:24.639220: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2018-07-26 13:25:26.395159: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
2018-07-26 13:25:37.818018: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-26 13:25:38.069259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 40a8:00:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-07-26 13:25:38.258768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 1 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 5ee9:00:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-07-26 13:25:38.451087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 2 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 7cf5:00:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-07-26 13:25:38.654067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 3 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: c2da:00:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-07-26 13:25:38.654247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1, 2, 3
2018-07-26 13:25:39.723172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-26 13:25:39.723246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 2 3
2018-07-26 13:25:39.723262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N N N N
2018-07-26 13:25:39.723281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   N N N N
2018-07-26 13:25:39.723299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 2:   N N N N
2018-07-26 13:25:39.723317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 3:   N N N N
2018-07-26 13:25:39.724189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10755 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 40a8:00:00.0, compute capability: 3.7)
2018-07-26 13:25:39.818390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10755 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: 5ee9:00:00.0, compute capability: 3.7)
2018-07-26 13:25:40.053652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10755 MB memory) -> physical GPU (device: 2, name: Tesla K80, pci bus id: 7cf5:00:00.0, compute capability: 3.7)
2018-07-26 13:25:40.301944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10755 MB memory) -> physical GPU (device: 3, name: Tesla K80, pci bus id: c2da:00:00.0, compute capability: 3.7)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/convert.py", line 116, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/convert.py", line 104, in main
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/tfonnx.py", line 1396, in process_tf_graph
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/tfonnx.py", line 1325, in tensorflow_onnx_mapping
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/tfonnx.py", line 1317, in tensorflow_onnx_mapping
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/tfonnx.py", line 850, in upsample_op7
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-0.0.2.0-py3.5.egg/tf2onnx/graph.py", line 150, in get_tensor_value
ValueError: get tensor value: model_1_4/up_sampling2d_8/mul must be Const
python3 -m tf2onnx.convert --input /tmp/frozen/style2paints_head.pb --inputs Placeholder:0,Placeholder_1:0,Placeholder_2:0,Placeholder_3:0,Placeholder_4:0 --outputs strided_slice_20:0 --output style2paints_head.pb.onnx --verbose --continue_on_error
generated onnx is located/home/pengwa/style2paints_head.pb.onnx
------ switch back to original directory: /home/pengwa/community/learning/onnx

```

The sub graph looks like:
```

node {
  name: "model_1_4/up_sampling2d_8/Shape"
  op: "Shape"
  input: "model_1_4/activation_39/Relu"
  device: "/device:GPU:0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "out_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "model_1_4/up_sampling2d_8/strided_slice/stack"
  op: "Const"
  device: "/device:GPU:0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}

node {
  name: "model_1_4/up_sampling2d_8/strided_slice/stack_1"
  op: "Const"
  device: "/device:GPU:0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "model_1_4/up_sampling2d_8/strided_slice/stack_2"
  op: "Const"
  device: "/device:GPU:0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}

node {
  name: "model_1_4/up_sampling2d_8/strided_slice"
  op: "StridedSlice"
  input: "model_1_4/up_sampling2d_8/Shape"
  input: "model_1_4/up_sampling2d_8/strided_slice/stack"
  input: "model_1_4/up_sampling2d_8/strided_slice/stack_1"
  input: "model_1_4/up_sampling2d_8/strided_slice/stack_2"
  device: "/device:GPU:0"
  attr {
    key: "Index"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "begin_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "ellipsis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "end_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "new_axis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "shrink_axis_mask"
    value {
      i: 0
    }
  }
}


node {
  name: "model_1_4/up_sampling2d_8/Const"
  op: "Const"
  device: "/device:GPU:0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\002\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "model_1_4/up_sampling2d_8/mul"
  op: "Mul"
  input: "model_1_4/up_sampling2d_8/strided_slice"
  input: "model_1_4/up_sampling2d_8/Const"
  device: "/device:GPU:0"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "model_1_4/up_sampling2d_8/ResizeNearestNeighbor"
  op: "ResizeNearestNeighbor"
  input: "model_1_4/activation_39/Relu"
  input: "model_1_4/up_sampling2d_8/mul"
  device: "/device:GPU:0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "align_corners"
    value {
      b: false
    }
  }
}

```

**Comment by pengwa** [comment]
Since corresponding op Upsample require the "scales : list of floats (required)" as an attribute to control the  scale to expand output_dimention. 

So I think we need figure out a way to get the value of "model_1_4/up_sampling2d_8/mul", either by using some possible existing fold technique (i'll investigate) or we need do extra calculation ( I am not whether we have similar requirement before).

**Comment by pengwa** [comment]
I think we don't have good approach handling this case, until ONNX Upsample can make the scales be an input, instead of being an attribute.

**Comment by guschmue** [comment]
Yes, it is a unlucky choice by onnx to have those attributes instead of inputs. @linkerzhang, maybe this can be fixed in the future ?

**Comment by guschmue** [comment]
hanging this on https://github.com/onnx/tensorflow-onnx/issues/151 
that is the needed change that comes in once we add opset 9 support.

**Comment by edurenye** [comment]
#151 Was fixed, and the error still appears.

**Comment by guschmue** [comment]
it was fixed for opset-9 but there are cases where const is required. opset-11 should not need const anymore.
