### ISSUE TITLE
load saved model error

### ISSUE THREAD

**Issue by intgogo** [onnx/tensorflow-onnx#892]
UnboundLocalError: local variable 'concrete_func' referenced before assignment

https://github.com/onnx/tensorflow-onnx/blob/212e119788cfaeeddde6c52646d8b9812febcf13/tf2onnx/tf_loader.py#L212

https://github.com/onnx/tensorflow-onnx/blob/212e119788cfaeeddde6c52646d8b9812febcf13/tf2onnx/tf_loader.py#L229

**Comment by jignparm** [comment]
Maybe there are no any signatures  present in the model? Is the model you are using a public model, or a custom one?

**Comment by intgogo** [comment]
> Maybe there are no any signatures present in the model? Is the model you are using a public model, or a custom one?

Yes,I don't know what signature is.I find `signature_def ` in argparse but I don't know how to use it.

I downloaded the model, but I am newbie to tensorflow. The model contains a  pb and pbtxt files.

**Comment by guschmue** [comment]
What is the output of
```
saved_model_cli show --all --dir YOUR_MODEL
```
?

**Comment by intgogo** [comment]
> What is the output of
> 
> ```
> saved_model_cli show --all --dir YOUR_MODEL
> ```
> 
> ?

```
[root@localhost lilw]# python -m tensorflow.python.tools.saved_model_cli show --all --dir /root/lilw/smartai/main/data/angle
2020-04-24 11:28:17.014012: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /root/shiyu/sydp-linux-1.0.6:/usr/local/cuda/lib64:/usr/local/lib64:/usr/local/lib:/root/shiyu/sydp-linux-1.0.6:/usr/local/cuda/lib64:/usr/local/lib64:/usr/local/lib:
2020-04-24 11:28:17.014159: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /root/shiyu/sydp-linux-1.0.6:/usr/local/cuda/lib64:/usr/local/lib64:/usr/local/lib:/root/shiyu/sydp-linux-1.0.6:/usr/local/cuda/lib64:/usr/local/lib64:/usr/local/lib:
2020-04-24 11:28:17.014178: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

MetaGraphDef with tag-set: '' contains the following SignatureDefs:
Traceback (most recent call last):
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 994, in <module>
    sys.exit(main())
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 990, in main
    args.func(args)
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 691, in show
    _show_all(args.dir)
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 278, in _show_all
    signature_def_map = get_signature_def_map(saved_model_dir, tag_set)
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 323, in get_signature_def_map
    meta_graph = saved_model_utils.get_meta_graph_def(saved_model_dir, tag_set)
  File "/root/lilw/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow_core/python/tools/saved_model_utils.py", line 120, in get_meta_graph_def
    ' could not be found in SavedModel')
RuntimeError: MetaGraphDef associated with tag-set  could not be found in SavedModel
```
But the problem is that I can use this model to inference successfully.

**Comment by jignparm** [comment]
That's odd that `saved_model_cli` is failing.

I saw a similar error with another model, and was able to work around it using an empty signature. Could you append an empty signature using something like `signatures.append('')`  above line 222 in tf_loader.py? If that works, we can update the logic to check for empty as well (although it might be  rare occurrence).

Did you have a link to the model for debugging, in case the empty signature does not work?

**Comment by intgogo** [comment]
link: https://pan.baidu.com/s/1zo2jqkYdBZ8aPIMxQy15yw 
code: ytbu

I tested adding `signatures.append('')` ,but still error.

**Comment by jignparm** [comment]
The link requires the YunDetectService, so I cannot access ( login id/pwd required for downloader)

Can you  upload to a location like git lfs (e.g. https://help.github.com/en/github/managing-large-files/installing-git-large-file-storage)
