### ISSUE TITLE
A Bug is occur when I try to transfer tf2.1'pb to onnx

### ISSUE THREAD

**Issue by jiaozhentian** [onnx/tensorflow-onnx#899]
**Describe the bug**
I had my model frozen by tf2.1, and it worked well in inference not only by tf2.1, but also in tf-serving. I am trying to use tf2onnx to generate a onnx model, while the wired error occurred and I can not trace or fix it.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04.2
- Tensorflow Version: Tensorflow 2.1
- Python version: Python3.6

**To Reproduce**
Describe steps/code to reproduce the behavior: Just use the command line as below:
python -m tf2onnx.convert --opset 10 --fold_const --saved-model ./export_model2/ --output ./onnx_model/model.onnx

**Additional context**
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_utils.py", line 60, in tf_to_onnx_tensor
    np_data = np_data.astype(np.str).astype(np.object)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 169, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 153, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 389, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes, _ = tensorflow_to_onnx(tf_graph, shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_utils.py", line 225, in tensorflow_to_onnx
    return tflist_to_onnx(graph, shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_utils.py", line 197, in tflist_to_onnx
    onnx_tensor = tf_to_onnx_tensor(get_tf_node_attr(node, a), name=port_name(node.name))
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_utils.py", line 62, in tf_to_onnx_tensor
    raise RuntimeError("Not support type: {}".format(type(np_data.flat[0])))
RuntimeError: Not support type: <class 'bytes'>

**Comment by jignparm** [comment]
Is this a public model (and can you share the link)? It's likely a UTF string encoding issue .

**Comment by jiaozhentian** [comment]
> Is this a public model (and can you share the link)? It's likely a UTF string encoding issue .

Well, actually this model is exported by myself, and trained by the EfficientNet, which is used automl's code. The model can not convert neither by the official code nor mine, and I prefer do not to modify the sorce code.

**Comment by jignparm** [comment]
Please have a look at #922. Apparently another model showed a similar error. Does this fix work for your model?

**Comment by guschmue** [comment]
Also efficientnet&co should work in general and we have some notebook with an example here:
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/efficientnet-lite.ipynb

**Comment by guschmue** [comment]
we assume this is fixed.
