### ISSUE TITLE
MobilenetV2. Transpose optimizer fail : list index out of range

### ISSUE THREAD

**Issue by anoushsepehri** [onnx/tensorflow-onnx#973]
**Describe the bug**
When trying to optimize an SSD-MobilenetV2, the network fails to optimize. The error thread can be seen below:

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetson Nano: Jetpack 4.4
- Tensorflow Version: 2.1.0
- Python version: 3.6

python3 -m tf2onnx.convert --saved-model saved_model2 --opset 11 --output mobilenetv2.onnx
2020-06-15 12:14:12.021503: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:From /home/anoush/.local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-06-15 12:14:19,451 - WARNING - From /home/anoush/.local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-06-15 12:14:19.487066: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-06-15 12:14:19.493127: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.493273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
2020-06-15 12:14:19.493342: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
2020-06-15 12:14:19.523316: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-06-15 12:14:19.540454: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-06-15 12:14:19.582085: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-06-15 12:14:19.601861: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-06-15 12:14:19.620986: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-06-15 12:14:19.621555: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-06-15 12:14:19.621832: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.622093: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.622182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-06-15 12:14:19.649569: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
2020-06-15 12:14:19.650256: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x13882310 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-15 12:14:19.650324: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
2020-06-15 12:14:19.726864: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.727358: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x139ee850 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-15 12:14:19.727431: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2020-06-15 12:14:19.727828: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.727957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
2020-06-15 12:14:19.728080: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
2020-06-15 12:14:19.728169: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-06-15 12:14:19.728237: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-06-15 12:14:19.728300: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-06-15 12:14:19.728363: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-06-15 12:14:19.728423: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-06-15 12:14:19.728487: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-06-15 12:14:19.728672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.728945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:19.729047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-06-15 12:14:19.729125: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
2020-06-15 12:14:22.306261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-15 12:14:22.306372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186] 0
2020-06-15 12:14:22.306413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0: N
2020-06-15 12:14:22.306955: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:22.307264: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:22.307479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 130 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
2020-06-15 12:14:52.676885: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:52.677041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
2020-06-15 12:14:52.677132: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
2020-06-15 12:14:52.677227: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-06-15 12:14:52.677285: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-06-15 12:14:52.677329: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-06-15 12:14:52.677375: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-06-15 12:14:52.677418: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-06-15 12:14:52.677468: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-06-15 12:14:52.677659: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:52.677859: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:52.677933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-06-15 12:14:52.678037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-15 12:14:52.678067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186] 0
2020-06-15 12:14:52.678091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0: N
2020-06-15 12:14:52.678300: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:52.678518: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-06-15 12:14:52.678637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 130 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
2020-06-15 12:14:52,679 - INFO - Using tensorflow=1.15.2, onnx=1.7.0, tf2onnx=1.7.0/b73231
2020-06-15 12:14:52,679 - INFO - Using opset <onnx, 11>
2020-06-15 12:15:10,350 - INFO - folding node type=Pack, name=Preprocessor/stack_1
2020-06-15 12:15:10,380 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast
2020-06-15 12:15:10,407 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_1
2020-06-15 12:15:10,433 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_2
2020-06-15 12:15:10,458 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_3
2020-06-15 12:15:10,484 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_4
2020-06-15 12:15:10,510 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_5
2020-06-15 12:15:10,536 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_6
2020-06-15 12:15:10,562 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_7
2020-06-15 12:15:10,588 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_8
2020-06-15 12:15:10,614 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_9
2020-06-15 12:15:10,641 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_10
2020-06-15 12:15:10,667 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_11
2020-06-15 12:15:10,694 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_12
2020-06-15 12:15:10,721 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_13
2020-06-15 12:15:10,750 - INFO - folding node type=Sqrt, name=MultipleGridAnchorGenerator/Sqrt
2020-06-15 12:15:10,776 - INFO - folding node type=Mul, name=MultipleGridAnchorGenerator/mul_15
2020-06-15 12:15:10,803 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range
2020-06-15 12:15:10,830 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_14
2020-06-15 12:15:10,856 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_1
2020-06-15 12:15:10,882 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_15
2020-06-15 12:15:10,910 - INFO - folding node type=Sqrt, name=MultipleGridAnchorGenerator/Sqrt_1
2020-06-15 12:15:10,936 - INFO - folding node type=Mul, name=MultipleGridAnchorGenerator/mul_23
2020-06-15 12:15:10,963 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_2
2020-06-15 12:15:10,990 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_16
2020-06-15 12:15:11,017 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_3
2020-06-15 12:15:11,044 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_17
2020-06-15 12:15:11,074 - INFO - folding node type=Sqrt, name=MultipleGridAnchorGenerator/Sqrt_2
2020-06-15 12:15:11,101 - INFO - folding node type=Mul, name=MultipleGridAnchorGenerator/mul_31
2020-06-15 12:15:11,127 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_4
2020-06-15 12:15:11,154 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_18
2020-06-15 12:15:11,181 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_5
2020-06-15 12:15:11,207 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_19
2020-06-15 12:15:11,235 - INFO - folding node type=Sqrt, name=MultipleGridAnchorGenerator/Sqrt_3
2020-06-15 12:15:11,261 - INFO - folding node type=Mul, name=MultipleGridAnchorGenerator/mul_39
2020-06-15 12:15:11,288 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_6
2020-06-15 12:15:11,315 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_20
2020-06-15 12:15:11,343 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_7
2020-06-15 12:15:11,370 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_21
2020-06-15 12:15:11,398 - INFO - folding node type=Sqrt, name=MultipleGridAnchorGenerator/Sqrt_4
2020-06-15 12:15:11,425 - INFO - folding node type=Mul, name=MultipleGridAnchorGenerator/mul_47
2020-06-15 12:15:11,451 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_8
2020-06-15 12:15:11,478 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_22
2020-06-15 12:15:11,504 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_9
2020-06-15 12:15:11,531 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_23
2020-06-15 12:15:11,559 - INFO - folding node type=Sqrt, name=MultipleGridAnchorGenerator/Sqrt_5
2020-06-15 12:15:11,586 - INFO - folding node type=Mul, name=MultipleGridAnchorGenerator/mul_55
2020-06-15 12:15:11,613 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_10
2020-06-15 12:15:11,641 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_24
2020-06-15 12:15:11,668 - INFO - folding node type=Range, name=MultipleGridAnchorGenerator/range_11
2020-06-15 12:15:11,694 - INFO - folding node type=Cast, name=MultipleGridAnchorGenerator/Cast_25
2020-06-15 12:15:11,725 - INFO - folding node type=Cast, name=Postprocessor/Cast_1
2020-06-15 12:15:11,751 - INFO - folding node type=Cast, name=Postprocessor/Cast_2
2020-06-15 12:15:11,777 - INFO - folding node type=Cast, name=Postprocessor/Cast_3
2020-06-15 12:15:11,804 - INFO - folding node type=Mul, name=Postprocessor/BatchMultiClassNonMaxSuppression/mul
2020-06-15 12:15:11,831 - INFO - folding node type=Add, name=Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/add_1
2020-06-15 12:15:11,859 - INFO - folding node type=Add, name=Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/add_3
2020-06-15 12:15:11,886 - INFO - folding node type=ConcatV2, name=Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Concatenate/concat_5
2020-06-15 12:15:58,268 - INFO - Optimizing ONNX model
2020-06-15 12:22:33,970 - WARNING - Failed to apply optimize_transpose
Traceback (most recent call last):
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/init.py", line 52, in optimize_graph
graph = opt.optimize(current) or graph
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
graph = self._optimize(graph)
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 135, in _optimize
return self._apply_optimization(graph, self._optimize_at_current_graph_level)
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
graph = optimize_func(graph)
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 168, in _optimize_at_current_graph_level
self.post_optimize_action()
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 105, in post_optimize_action
if (is_nchw_transpose(op) and (input_shape[3] == 1 or (input_shape[1:3] == [1, 1])))
IndexError: list index out of range
2020-06-15 12:23:18,525 - WARNING - Failed to apply optimize_transpose
Traceback (most recent call last):
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/init.py", line 52, in optimize_graph
graph = opt.optimize(current) or graph
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
graph = self._optimize(graph)
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 135, in _optimize
return self._apply_optimization(graph, self._optimize_at_current_graph_level)
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
graph = optimize_func(graph)
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 168, in _optimize_at_current_graph_level
self.post_optimize_action()
File "/home/anoush/.local/lib/python3.6/site-packages/tf2onnx/optimizer/transpose_optimizer.py", line 105, in post_optimize_action
if (is_nchw_transpose(op) and (input_shape[3] == 1 or (input_shape[1:3] == [1, 1])))
IndexError: list index out of range
2020-06-15 12:23:31,817 - INFO - After optimization: Add -140 (197->57), BatchNormalization -57 (64->7), Cast -256 (335->79), Concat -19 (91->72), Const -1152 (1420->268), Div -5 (34->29), Equal -70 (81->11), Expand -41 (49->8), Identity -120 (120->0), Min -1 (8->7), Mul -83 (146->63), Range -1 (4->3), Reshape -56 (135->79), Shape -1 (15->14), Slice -42 (114->72), Squeeze -10 (58->48), Transpose -289 (311->22), Unsqueeze -55 (118->63)
2020-06-15 12:23:32,574 - INFO -
2020-06-15 12:23:32,575 - INFO - Successfully converted TensorFlow model saved_model2 to ONNX
2020-06-15 12:23:32,882 - INFO - ONNX model is saved at mobilenetv2.onnx

**Comment by jignparm** [comment]
@anoushsepehri , this is fixed by #974.
