### ISSUE TITLE
Issues converting UNET model to ONNX

### ISSUE THREAD

**Issue by anoushsepehri** [onnx/tensorflow-onnx#976]
**Describe the bug**
When I try to convert a UNET model trainined using Tensorflow 2.1.0 to ONNX, I get the following error:

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-06-17 20:10:12,913 - WARNING - From /usr/local/lib/python3.6/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from Conv1_1/kernel:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 169, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 142, in main
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from Conv1_1/kernel:0 incompatible with expected resource.

**Urgency**
Very urgent

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetson Nano with Jetpack 4.4
- Tensorflow Version: 1.15.0
- Python version: 3.6.9

**To Reproduce**
python -m tf2onnx.convert --opset 11  --saved-model saved_model_dir --output unet.onnx

**Comment by guschmue** [comment]
uh, this fails inside tensorflow itself. 
Is it possible to share the unet graph so we can take a look at it?

**Comment by anoushsepehri** [comment]
@guschmue 

I can send you a zip file of the saved model to your email or through some other private message.

Please share with me your email and I will do it asap.

Thanks

**Comment by jignparm** [comment]
@anoushsepehri, you can forward the model (or a link to it) to my ID @microsoft.com.

FYI, the operator `StatefulPartitionedCall` is not  supported yet. Although there's some experimental capability for Keras models (using the `--keras` option),  which sometimes include `StatefulPartitionedCall` ops.

What is the source of them model -- was it fine-tuned/trained locally, or just downloaded?

Also, are you able to load the TF model successfully (outside of tf2onnx)? If yes, it would be helpful to share the code snippet you are using to load the model into a session and score it.

**Comment by anoushsepehri** [comment]
@jignparm 

The model uses a pre trained mobilenetv2 as a feature extractor that was downloaded through tensorflow keras library. The upsample portion was written and trained from scratch using tensorflow keras API.

**Comment by jignparm** [comment]
@anoushsepehri , since it's a TF 2.x model, you need to run with TF 2.x for the conversion to succeed.  

Using TF 1.x  gives the error message you mentioned above. The converter should probably just halt if it detects that the model is TF 2.x but the TF version is 1.x, since it's unlikely to succeed. 

Upgrading TF version should fix the error you are seeing.

### Run log 
```
$python -m tf2onnx.convert --saved-model fibre_segmentation --output converted.onnx


2020-06-18 07:23:01,964 - INFO - Using tensorflow=2.2.0, onnx=1.7.0, tf2onnx=1.7.0/aafc83
2020-06-18 07:23:01,964 - INFO - Using opset <onnx, 12>
2020-06-18 07:23:08,883 - INFO - Optimizing ONNX model
2020-06-18 07:23:18,034 - INFO - After optimization: BatchNormalization -44 (54->10), Cast -4 (14->10), Const -391 (547->156), Gather +10 (0->10), Identity -5 (5->0), Reshape -21 (21->0), Squeeze -5 (15->10), Transpose -206 (241->35), Unsqueeze -10 (20->10)
2020-06-18 07:23:18,115 - INFO -
2020-06-18 07:23:18,116 - INFO - Successfully converted TensorFlow model fibre_segmentation to ONNX
2020-06-18 07:23:18,190 - INFO - ONNX model is saved at converted.onnx

```
