### ISSUE TITLE
Error when converting albert model

### ISSUE THREAD

**Issue by prabhat00155** [onnx/tensorflow-onnx#982]
**Describe the bug**
Error when converting albert (https://tfhub.dev/tensorflow/lite-model/albert_lite_base/squadv1/1) model to ONNX.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Darwin Kernel Version 19.5.0
- Tensorflow Version: 1.15.2
- Python version: 3.6.8
- Others:
onnx==1.6.0
tf2onnx==1.7.0
**To Reproduce**
Describe steps/code to reproduce the behavior:
```
python -m tf2onnx.convert --saved-model tf2/albert/ --output albert.onnx

20-06-22 19:55:03,859 - WARNING - From /Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/convert.py", line 169, in <module>
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/convert.py", line 130, in main
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/tf_loader.py", line 244, in from_saved_model
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/tf_loader.py", line 184, in _from_saved_model_v1
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 349, in load_graph
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 327, in get_meta_graph_def_from_tags
    "\navailable_tags: " + str(available_tags))
RuntimeError: MetaGraphDef associated with tags 'serve' could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [{'train'}, set()]

```

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jignparm** [comment]
Some of the saved_models don't have the 'serve' tag. Looks like this is one of them. Will try to get a comprehensive fix in a few hours that can convert this model, as well as a few other TFHub models.

BTW TFHub contains a few different formats -- saved_model, tflite and coral. The fix would only work for saved_model formats (not tflite or coral).

**Comment by guschmue** [comment]
just add a --tags option. Kind of rare but legal.

**Comment by jignparm** [comment]
I don't see --tags option any more, although it was probably there earlier.

Also, I noticed some of the TFHub models (not this one) have defined functions outside of the 'serving_default' signature, so at least a couple  of changes are required to the saved_model loading logic to get the other TFHub models to work successfully.

Will update on this shortly.

**Comment by guschmue** [comment]
I meant ***implement*** ```--tag```

**Comment by jignparm** [comment]
@prabhat00155 , PR #984 should fix the issue for the TF2.x albert model conversion.

```python
$ python -m tf2onnx.convert --saved-model .  --signature_def mlm --output converted.onnx
...
2020-06-24 12:30:04,391 - INFO - Using tensorflow=2.2.0, onnx=1.7.0, tf2onnx=1.7.0/aafc83
2020-06-24 12:30:04,391 - INFO - Using opset <onnx, 11>
2020-06-24 12:30:33,839 - INFO - Optimizing ONNX model
2020-06-24 12:30:52,057 - INFO - After optimization: Cast -74 (177->103), Concat -24 (76->52), Const -1436 (1494->58), Identity -33 (33->0), Shape -48 (87->39), Slice -72 (151->79), Squeeze -147 (150->3), Transpose -13 (73->60), Unsqueeze -285 (287->2)
2020-06-24 12:30:52,260 - INFO -
2020-06-24 12:30:52,261 - INFO - Successfully converted TensorFlow model . to ONNX
2020-06-24 12:30:52,415 - INFO - ONNX model is saved at converted.onnx
```

**Comment by jignparm** [comment]
Closing out this issue for now -- if OnnxRuntime cannot support INT64 in the future, may need to add this patch into master as well., but a better location would be ORT.
