### ISSUE TITLE
Error when converting mobilebert model

### ISSUE THREAD

**Issue by prabhat00155** [onnx/tensorflow-onnx#983]
**Describe the bug**
I get error when converting mobile bert model (https://storage.googleapis.com/cloud-tpu-checkpoints/mobilebert/uncased_L-24_H-128_B-512_A-4_F-4_OPT.tar.gz) to ONNX.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Darwin Kernel Version 19.5.0
- Tensorflow Version: 1.15.2
- Python version: 3.6.8
- Others:
onnx==1.6.0
tf2onnx==1.7.0

**To Reproduce**
```
python -m tf2onnx.convert --checkpoint mobilebert/mobilebert_variables.ckpt.data-00000-of-00001  --output bert.onnx --inputs input_ids:0,input_mask:0,segment_ids:0 --outputs start_logits:0,end_logits:0

WARNING:tensorflow:From /Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-06-22 20:07:13,018 - WARNING - From /Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/convert.py", line 169, in <module>
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/convert.py", line 126, in main
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tf2onnx-1.7.0-py3.6.egg/tf2onnx/tf_loader.py", line 167, in from_checkpoint
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1467, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/Users/prroy/Documents/MachineLearning/onnx_projects/onnxrt_env/lib/python3.6/site-packages/tensorflow_core/python/framework/meta_graph.py", line 647, in read_meta_graph_file
    text_format.Merge(file_content.decode("utf-8"), meta_graph_def)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 0: invalid start byte
(onnxrt_env) prroy-Mac:bert prroy$ 
```

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jignparm** [comment]
@prabhat00155 , 

I don't see the .meta file in this model. Is that available somewhere? I believe it's needed.

```
$ ll mobilebert/
total 143238
-rw-r--r-- 1 localadmin 197121       560 Apr  9 23:01 bert_config.json
-rw-r--r-- 1 localadmin 197121       315 Apr  9 23:01 checkpoint
-rw-r--r-- 1 localadmin 197121 146390264 Apr  9 23:02 mobilebert_variables.ckpt.data-00000-of-00001
-rw-r--r-- 1 localadmin 197121     47002 Apr  9 23:02 mobilebert_variables.ckpt.index
-rw-r--r-- 1 localadmin 197121    231508 Apr  9 23:02 vocab.txt

```

**Comment by guschmue** [comment]
This is just the checkpoint after pre-training. 
https://github.com/google-research/google-research/tree/master/mobilebert has a saved-model fine tuned for squad. 
@prabhat00155 , I assume we want to use this one ?

**Comment by jignparm** [comment]
The floating point saved_model, listed on the page mentioned above  (i.e. at [mobilebert_squad_savedmodels ](https://storage.googleapis.com/cloud-tpu-checkpoints/mobilebert/mobilebert_squad_savedmodels.tar.gz)) converts to Onnx fine.

The other quantized model, in the same tar archive, requires a missing `FakeQuantWithMinMaxVars` operator, so this won't run in OnnxRuntime. The floating point model should be fine however.


```
$ python -m tf2onnx.convert --saved-model float --output mobilebert.float.onnx --tag serve

2020-06-29 19:39:58,261 - INFO - Using tensorflow=2.2.0, onnx=1.7.0, tf2onnx=1.7.0/aafc83
2020-06-29 19:39:58,261 - INFO - Using opset <onnx, 11>
2020-06-29 19:40:19,179 - INFO - Optimizing ONNX model
2020-06-29 19:43:11,124 - INFO - After optimization: Add -23 (412->389), Cast -728 (729->1), Const -946 (2053->1107), Identity -6 (6->0), Mul -23 (242->219), Reshape -74 (728->654), Transpose -27 (124->97), Unsqueeze -23 (25->2)
2020-06-29 19:43:11,612 - INFO -
2020-06-29 19:43:11,612 - INFO - Successfully converted TensorFlow model float to ONNX
2020-06-29 19:43:11,963 - INFO - ONNX model is saved at mobilebert.float.onnx
```

**Comment by guschmue** [comment]
For the quantitized model - FakeQuantWithMinMaxVars  comes from Qat and we will add support for this here https://github.com/onnx/tensorflow-onnx/issues/965.

**Comment by prabhat00155** [comment]
Yes, the model conversion works with the latest master(`tag` needed), and I was able to run the converted model with onnxruntime.

**Comment by guschmue** [comment]
This should work on tf2onnx-1.6.2 as well as --tag serve was the default there. I belief the problem was that we used the phase2 pre-trained checkpoint and not the fine tuned model.
