### ISSUE TITLE
Error when converting TensorFlow model to onnx

### ISSUE THREAD

**Issue by AkhilJ99** [onnx/tensorflow-onnx#985]
**Describe the bug**

Got this error when trying to convert my model to tensorflow

`2020-06-26 11:53:25,420 - WARNING - '--tag' not specified for saved_model. Using empty tag [[]]
Traceback (most recent call last):
  File "/home/akhil/anaconda3/envs/TDL/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/akhil/anaconda3/envs/TDL/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/akhil/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 171, in <module>
    main()
  File "/home/akhil/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 131, in main
    graph_def, inputs, outputs = tf_loader.from_saved_model(
  File "/home/akhil/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 274, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names, tag, signatures, concrete_function)
  File "/home/akhil/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py", line 233, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
  File "/home/akhil/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 578, in load
    return load_internal(export_dir, tags)
  File "/home/akhil/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 613, in load_internal
    root = load_v1_in_v2.load(export_dir, tags)
  File "/home/akhil/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 263, in load
    return loader.load(tags=tags)
  File "/home/akhil/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 188, in load
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "/home/akhil/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load_v1_in_v2.py", line 83, in get_meta_graph_def_from_tags
    return super(_EagerSavedModelLoader, self).get_meta_graph_def_from_tags(
  File "/home/akhil/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 353, in get_meta_graph_def_from_tags
    raise RuntimeError(
RuntimeError: MetaGraphDef associated with tags  could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [{'serve'}]
`

**The code used to generate the pbfile is here**

`import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import matplotlib.pyplot as plt

X_train = np.random.randn(50,1)

#print(X_train)
Y_train = X_train*2 + 25

lr = 0.02
epochs = 1500

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

size_input = 1
size_output = 1
size_hidden1 = 2
size_hidden2 = 6
size_hidden3 = 18

def model() :
    Wh1 = tf.Variable(tf.random_normal([size_input,size_hidden1]), name = "Wh1")
    bh1 = tf.Variable(tf.random_normal([1,size_hidden1]),name = "bh1")

    Wh2 = tf.Variable(tf.random_normal([size_hidden1,size_hidden2]),name = "Wh2")
    bh2 = tf.Variable(tf.random_normal([1,size_hidden2]),name = "bh1")

    Wh3 = tf.Variable(tf.random_normal([size_hidden2,size_hidden3]),name = "Wh3")
    bh3 = tf.Variable(tf.random_normal([1,size_hidden3]),name = "bh3")

    Wy = tf.Variable(tf.random_normal([size_hidden3,size_output]),name = "Wy")
    by = tf.Variable(tf.random_normal([1,size_hidden3]),name = "by")

    a1 = tf.matmul(X,Wh1) + bh1
    lh1 = tf.nn.relu(a1)

    a2 = tf.matmul(lh1,Wh2) + bh2
    lh2 = tf.nn.relu(a2)

    a3 = tf.matmul(lh2,Wh3) + bh3
    lh3 = tf.nn.relu(a3)

    pred = tf.matmul(lh3,Wy) + by
    return pred

pred = model()
loss = tf.reduce_sum(tf.pow((Y-pred),2.0))/(2.0*len(X_train))

opt = tf.train.GradientDescentOptimizer(learning_rate=lr).minimize(loss)

globalgraph = 1
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())

    for i in range(epochs) :
        count = 0
        while count <49 :
            sess.run(opt,feed_dict={X:X_train,Y:Y_train})
            count = count + 1
        if i%1000 == 0 :
            print("Loss :",loss.eval({X:X_train, Y:Y_train}))
    X_test = X_test = [[1.0],[2.0],[3.0],[4.0],[5.0],[6.0]]
    print(sess.run(pred, feed_dict={X:X_test}))
    tf.saved_model.simple_save(sess,"./model", inputs = {"X":tf.convert_to_tensor(X_train)}, outputs = {"Y":tf.convert_to_tensor(Y_train)} )
`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Tensorflow Version: 2.2.0
- Python version: 3.8.3

**To Reproduce**
Just run the above code and then run this command python -m tf2onnx.convert --saved-model model  --output model.onnx
(the model is saved in the model directory)

**Screenshots**
Error message
![err](https://user-images.githubusercontent.com/32807730/85828010-0899b780-b7a5-11ea-8c01-90b94eeb83c1.png)

**Comment by jignparm** [comment]
@AkhilJ99 , from the log, it looks like your model contains the 'serve' tag. You will need to specify `--tag serve` on the command line to specify that tag for conversion purposes, as the model may contain multiple tags. 

This is a recent change, where the default value for tag is a null/None value if user does not specify.

**Comment by guschmue** [comment]
we assume this is resolved.
