### ISSUE TITLE
IndexError with EfficientNet

### ISSUE THREAD

**Issue by yutkin** [onnx/tensorflow-onnx#996]
Trying to convert official [EfficientNet](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b3.tar.gz), but fail with `IndexError`:
```
python3 -m tf2onnx.convert --checkpoint=model.ckpt.meta --output efficientnet-b3.onnx --inputs 0:sub --outputs logits
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-07-06 08:31:22,637 - WARNING - From /usr/local/lib/python3.6/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 169, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 126, in main
    graph_def, inputs, outputs = tf_loader.from_checkpoint(args.checkpoint, args.inputs, args.outputs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_loader.py", line 171, in from_checkpoint
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_loader.py", line 113, in freeze_session
    output_node_names = [i.split(':')[:-1][0] for i in output_names]
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tf_loader.py", line 113, in <listcomp>
    output_node_names = [i.split(':')[:-1][0] for i in output_names]
IndexError: list index out of range
```

Package versions:
```
pip3 list
Package              Version
-------------------- ---------------
absl-py              0.9.0
asn1crypto           0.24.0
astor                0.8.1
certifi              2020.6.20
chardet              3.0.4
cryptography         2.1.4
gast                 0.2.2
google-pasta         0.2.0
grpcio               1.30.0
h5py                 2.10.0
idna                 2.6
importlib-metadata   1.7.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
keyring              10.6.0
keyrings.alt         3.0
Markdown             3.2.2
numpy                1.19.0
onnx                 1.7.0
onnxruntime          1.3.0
opt-einsum           3.2.1
pip                  20.1.1
protobuf             3.12.2
pycrypto             2.6.1
pygobject            3.26.1
python-apt           1.6.5+ubuntu0.3
pyxdg                0.25
requests             2.24.0
SecretStorage        2.3.1
setuptools           49.1.0
six                  1.11.0
tensorboard          1.15.0
tensorflow           1.15.3
tensorflow-estimator 1.15.1
termcolor            1.1.0
tf2onnx              1.6.2
typing-extensions    3.7.4.2
urllib3              1.25.9
Werkzeug             1.0.1
wheel                0.34.2
wrapt                1.12.1
zipp                 3.1.0
```

**Comment by jignparm** [comment]
Some of the parameters on your command line look odd. For example the `=` after --checkpoint shouldn't be there, the --inputs name seems malformed, and the --outputs name seems to be missing a port.  Have a look at the EfficientNet tutorial below. Does that work for your model?

https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/efficientnet-edge.ipynb

**Comment by yutkin** [comment]
All works fine after converting to saved_model format using https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/export_model.py. Thank you!
